[ClassVersion("1.0.0.0"), FriendlyName("AADNamedLocationPolicy")]
class MSFT_AADNamedLocationPolicy : OMI_BaseResource
{
    [Write, Description("Specifies the Odata Type of a Named Location object in Azure Active Directory"), ValueMap{"#microsoft.graph.countryNamedLocation","#microsoft.graph.ipNamedLocation","#microsoft.graph.compliantNetworkNamedLocation"}, Values{"#microsoft.graph.countryNamedLocation","#microsoft.graph.ipNamedLocation","#microsoft.graph.compliantNetworkNamedLocation"}] string OdataType;
    [Write, Description("Specifies the ID of a Named Location in Azure Active Directory.")] String Id;
    [Key, Description("Specifies the Display Name of a Named Location in Azure Active Directory")] string DisplayName;
    [Write, Description("Specifies the IP ranges of the Named Location in Azure Active Directory")] String IpRanges[];
    [Write, Description("Specifies the isTrusted value for the Named Location (IP ranges only) in Azure Active Directory")] Boolean IsTrusted;
    [Write, Description("Specifies the countries and regions for the Named Location in Azure Active Directory")] String CountriesAndRegions[];
    [Write, Description("Determines what method is used to decide which country the user is located in. Possible values are clientIpAddress(default) and authenticatorAppGps."), ValueMap{"clientIpAddress","authenticatorAppGps"}, Values{"clientIpAddress","authenticatorAppGps"}] String CountryLookupMethod;
    [Write, Description("Specifies the includeUnknownCountriesAndRegions value for the Named Location in Azure Active Directory")] Boolean IncludeUnknownCountriesAndRegions;
    [Write, Description("Specify if the Azure AD Named Location should exist or not."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Write, Description("Credentials for the Microsoft Graph delegated permissions."), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Id of the Azure Active Directory tenant used for authentication.")] String TenantId;
    [Write, Description("Secret of the Azure Active Directory application to authenticate with."), EmbeddedInstance("MSFT_Credential")] String ApplicationSecret;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Managed ID being used for authentication.")] Boolean ManagedIdentity;
    [Write, Description("Access token used for authentication.")] String AccessTokens[];

};
