[ClassVersion("1.0.0.0"), FriendlyName("EXOGroupSettings")]
class MSFT_EXOGroupSettings : OMI_BaseResource
{
    [Key, Description("The DisplayName parameter specifies the name of the Microsoft 365 Group. The display name is visible in the Exchange admin center, address lists, and Outlook. The maximum length is 64 characters.")] string DisplayName;
    [Write, Description("The unique Id of the group")] string Id;
    [Write, Description("The AcceptMessagesOnlyFromSendersOrMembers parameter specifies who is allowed to send messages to this recipient. Messages from other senders are rejected.")] string AcceptMessagesOnlyFromSendersOrMembers[];
    [Write, Description("Private"), ValueMap{"Public","Private"}, Values{"Public","Private"}] string AccessType;
    [Write, Description("The AlwaysSubscribeMembersToCalendarEvents switch controls the default subscription settings of new members that are added to the Microsoft 365 Group. Changing this setting doesn't affect existing group members.")] boolean AlwaysSubscribeMembersToCalendarEvents;
    [Write, Description("The AlwaysSubscribeMembersToCalendarEvents switch controls the default subscription settings of new members that are added to the Microsoft 365 Group. Changing this setting doesn't affect existing group members.")] string AuditLogAgeLimit;
    [Write, Description("The AutoSubscribeNewMembers switch specifies whether to automatically subscribe new members that are added to the Microsoft 365 Group to conversations and calendar events. Only users that are added to the group after you enable this setting are automatically subscribed to the group.")] boolean AutoSubscribeNewMembers;
    [Write, Description("The CalendarMemberReadOnly parameter specifies whether to set read-only Calendar permissions to the Microsoft 365 Group for members of the group.")] boolean CalendarMemberReadOnly;
    [Write, Description("The CalendarMemberReadOnly switch specifies whether to set read-only Calendar permissions to the Microsoft 365 Group for members of the group.")] string Classification;
    [Write, Description("The CalendarMemberReadOnly switch specifies whether to set read-only Calendar permissions to the Microsoft 365 Group for members of the group.")] boolean ConnectorsEnabled;
    [Write, Description("This parameter specifies a value for the CustomAttribute1 property on the recipient. You can use this property to store custom information about the recipient, and to identify the recipient in filters. The maximum length is 1024 characters.")] string CustomAttribute1;
    [Write, Description("This parameter specifies a value for the CustomAttribute2 property on the recipient. You can use this property to store custom information about the recipient, and to identify the recipient in filters. The maximum length is 1024 characters.")] string CustomAttribute2;
    [Write, Description("This parameter specifies a value for the CustomAttribute3 property on the recipient. You can use this property to store custom information about the recipient, and to identify the recipient in filters. The maximum length is 1024 characters.")] string CustomAttribute3;
    [Write, Description("This parameter specifies a value for the CustomAttribute4 property on the recipient. You can use this property to store custom information about the recipient, and to identify the recipient in filters. The maximum length is 1024 characters.")] string CustomAttribute4;
    [Write, Description("This parameter specifies a value for the CustomAttribute5 property on the recipient. You can use this property to store custom information about the recipient, and to identify the recipient in filters. The maximum length is 1024 characters.")] string CustomAttribute5;
    [Write, Description("This parameter specifies a value for the CustomAttribute6 property on the recipient. You can use this property to store custom information about the recipient, and to identify the recipient in filters. The maximum length is 1024 characters.")] string CustomAttribute6;
    [Write, Description("This parameter specifies a value for the CustomAttribute7 property on the recipient. You can use this property to store custom information about the recipient, and to identify the recipient in filters. The maximum length is 1024 characters.")] string CustomAttribute7;
    [Write, Description("This parameter specifies a value for the CustomAttribute8 property on the recipient. You can use this property to store custom information about the recipient, and to identify the recipient in filters. The maximum length is 1024 characters.")] string CustomAttribute8;
    [Write, Description("This parameter specifies a value for the CustomAttribute9 property on the recipient. You can use this property to store custom information about the recipient, and to identify the recipient in filters. The maximum length is 1024 characters.")] string CustomAttribute9;
    [Write, Description("This parameter specifies a value for the CustomAttribute10 property on the recipient. You can use this property to store custom information about the recipient, and to identify the recipient in filters. The maximum length is 1024 characters.")] string CustomAttribute10;
    [Write, Description("This parameter specifies a value for the CustomAttribute11 property on the recipient. You can use this property to store custom information about the recipient, and to identify the recipient in filters. The maximum length is 1024 characters.")] string CustomAttribute11;
    [Write, Description("This parameter specifies a value for the CustomAttribute12 property on the recipient. You can use this property to store custom information about the recipient, and to identify the recipient in filters. The maximum length is 1024 characters.")] string CustomAttribute12;
    [Write, Description("This parameter specifies a value for the CustomAttribute13 property on the recipient. You can use this property to store custom information about the recipient, and to identify the recipient in filters. The maximum length is 1024 characters.")] string CustomAttribute13;
    [Write, Description("This parameter specifies a value for the CustomAttribute14 property on the recipient. You can use this property to store custom information about the recipient, and to identify the recipient in filters. The maximum length is 1024 characters.")] string CustomAttribute14;
    [Write, Description("This parameter specifies a value for the CustomAttribute15 property on the recipient. You can use this property to store custom information about the recipient, and to identify the recipient in filters. The maximum length is 1024 characters.")] string CustomAttribute15;
    [Write, Description("The DataEncryptionPolicy parameter specifies the data encryption policy that's applied to the Microsoft 365 Group. ")] string DataEncryptionPolicy;
    [Write, Description("The EmailAddresses parameter specifies all the email addresses (proxy addresses) for the recipient, including the primary SMTP address.")] string EmailAddresses[];
    [Write, Description("This parameter specifies a value for the ExtensionCustomAttribute1 property on the recipient. You can use this property to store custom information about the recipient, and to identify the recipient in filters. You can specify up to 1300 values separated by commas.")] string ExtensionCustomAttribute1;
    [Write, Description("This parameter specifies a value for the ExtensionCustomAttribute2 property on the recipient. You can use this property to store custom information about the recipient, and to identify the recipient in filters. You can specify up to 1300 values separated by commas.")] string ExtensionCustomAttribute2;
    [Write, Description("This parameter specifies a value for the ExtensionCustomAttribute3 property on the recipient. You can use this property to store custom information about the recipient, and to identify the recipient in filters. You can specify up to 1300 values separated by commas.")] string ExtensionCustomAttribute3;
    [Write, Description("This parameter specifies a value for the ExtensionCustomAttribute4 property on the recipient. You can use this property to store custom information about the recipient, and to identify the recipient in filters. You can specify up to 1300 values separated by commas.")] string ExtensionCustomAttribute4;
    [Write, Description("This parameter specifies a value for the ExtensionCustomAttribute5 property on the recipient. You can use this property to store custom information about the recipient, and to identify the recipient in filters. You can specify up to 1300 values separated by commas.")] string ExtensionCustomAttribute5;
    [Write, Description("The GrantSendOnBehalfTo parameter specifies who can send on behalf of this Microsoft 365 Group.")] string GrantSendOnBehalfTo[];
    [Write, Description("The GrantSendOnBehalfTo parameter specifies who can send on behalf of this Microsoft 365 Group.")] boolean HiddenFromAddressListsEnabled;
    [Write, Description("The HiddenFromExchangeClientsEnabled switch specifies whether the Microsoft 365 Group is hidden from Outlook clients connected to Microsoft 365.")] boolean HiddenFromExchangeClientsEnabled;
    [Write, Description("The InformationBarrierMode parameter specifies the information barrier mode for the Microsoft 365 Group."), ValueMap{"Explicit","Implicit","Open","OwnerModerated"}, Values{"Explicit","Implicit","Open","OwnerModerated"}] string InformationBarrierMode;
    [Write, Description("This parameter specifies whether or not members are allow to edit content.")] boolean IsMemberAllowedToEditContent;
    [Write, Description("The Language parameter specifies language preference for the Microsoft 365 Group.")] string Language;
    [Write, Description("The MailboxRegion parameter specifies the preferred data location (PDL) for the Microsoft 365 Group in multi-geo environments.")] string MailboxRegion;
    [Write, Description("The MailTip parameter specifies the custom MailTip text for this recipient. The MailTip is shown to senders when they start drafting an email message to this recipient. ")] string MailTip;
    [Write, Description("The MailTipTranslations parameter specifies additional languages for the custom MailTip text that's defined by the MailTip parameter.")] string MailTipTranslations;
    [Write, Description("The MaxReceiveSize parameter specifies the maximum size of an email message that can be sent to this group. Messages that exceed the maximum size are rejected by the group.")] string MaxReceiveSize;
    [Write, Description("The MaxSendSize parameter specifies the maximum size of an email message that can be sent by this group.")] string MaxSendSize;
    [Write, Description("The ModeratedBy parameter specifies one or more moderators for this recipient. A moderator approves messages sent to the recipient before the messages are delivered. A moderator must be a mailbox, mail user, or mail contact in your organization. You can use any value that uniquely identifies the moderator. ")] string ModeratedBy[];
    [Write, Description("The ModerationEnabled parameter specifies whether moderation is enabled for this recipient.")] boolean ModerationEnabled;
    [Write, Description("The Notes parameter specifies the description of the Microsoft 365 Group. If the value contains spaces, enclose the value in quotation marks.")] string Notes;
    [Write, Description("The PrimarySmtpAddress parameter specifies the primary return email address that's used for the recipient. You can't use the EmailAddresses and PrimarySmtpAddress parameters in the same command.")] string PrimarySmtpAddress;
    [Write, Description("The RejectMessagesFromSendersOrMembers parameter specifies who isn't allowed to send messages to this recipient. Messages from these senders are rejected.")] string RejectMessagesFromSendersOrMembers[];
    [Write, Description("The RequireSenderAuthenticationEnabled parameter specifies whether to accept messages only from authenticated (internal) senders. ")] boolean RequireSenderAuthenticationEnabled;
    [Write, Description("The SensitivityLabelId parameter specifies the GUID value of the sensitivity label that's assigned to the Microsoft 365 Group.")] string SensitivityLabelId;
    [Write, Description("The SubscriptionEnabled switch specifies whether the group owners can enable subscription to conversations and calendar events on the groups they own. ")] boolean SubscriptionEnabled;
    [Write, Description("The UnifiedGroupWelcomeMessageEnabled switch specifies whether to enable or disable sending system-generated welcome messages to users who are added as members to the Microsoft 365 Group.")] boolean UnifiedGroupWelcomeMessageEnabled;
    [Write, Description("Credentials of the Exchange Admin"), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Id of the Azure Active Directory tenant used for authentication.")] String TenantId;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Username can be made up to anything but password will be used for CertificatePassword"), EmbeddedInstance("MSFT_Credential")] String CertificatePassword;
    [Write, Description("Path to certificate used in service principal usually a PFX file.")] String CertificatePath;
    [Write, Description("Managed ID being used for authentication.")] Boolean ManagedIdentity;
};
