[ClassVersion("1.0.0.0"), FriendlyName("AADTokenIssuancePolicy")]
class MSFT_AADTokenIssuancePolicy : OMI_BaseResource
{
    [Key, Description("Display name for this policy. Required.")] String DisplayName;
    [Write, Description("Unique identifier for this policy. Read-only.")] String Id;
    [Write, Description("The token-issuance policy can only be applied to service principals and can't be set globally for the organization.")] Boolean IsOrganizationDefault;
    [Write, Description("Description for this policy.")] String Description;
    [Write, Description("A string collection containing a JSON string that defines the rules and settings for this policy. See below for more details about the JSON schema for this property. Required.")] String Definition[];

    [Write, Description("Present ensures the instance exists, absent ensures it is removed."), ValueMap{"Absent","Present"}, Values{"Absent","Present"}] string Ensure;
    [Write, Description("Credentials of the workload's Admin"), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Id of the Azure Active Directory tenant used for authentication.")] String TenantId;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Managed ID being used for authentication.")] Boolean ManagedIdentity;
    [Write, Description("Access token used for authentication.")] String AccessTokens[];
};
