[ClassVersion("1.0.0.0"), FriendlyName("TeamsUpgradePolicy")]
class MSFT_TeamsUpgradePolicy : OMI_BaseResource
{
    [Key, Description("Identity of the Teams Upgrade Policy.")] String Identity;
    [Write, Description("If true, users with this policy see a notification in their Skype for Business client indicating that Teams is coming soon.")] Boolean NotifySfbUsers;
    [Write, Description("Description of what the Teams Upgrade Policy is about.")] String Description;
    [Write, Description("Present ensures the Team Upgrade Policy exists, absent ensures it is removed"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Required, Description("Credentials of the SharePoint Global Admin"), EmbeddedInstance("MSFT_Credential")] String GlobalAdminAccount;
};

