[ClassVersion("1.0.0.0"), FriendlyName("EXODkimSigningConfig")]
class MSFT_EXODkimSigningConfig : OMI_BaseResource
{
    [Key, Description("The Identity parameter specifies the DKIM signing policy that you want to modify.  This should be the FQDN. ")] String Identity;
    [Write, Description("The AdminDisplayName parameter specifies a description for the policy.")] String AdminDisplayName;
    [Write, Description("The BodyCanonicalization parameter specifies the canonicalization algorithm that's used to create and verify the message body part of the DKIM signature. This value effectively controls the sensitivity of DKIM to changes to the message body in transit. Valid values are 'Simple' or 'Relaxed'.  'Relaxed' is the default."), ValueMap{"Simple","Relaxed"}, Values{"Simple","Relaxed"}] String BodyCanonicalization;
    [Write, Description("The HeaderCanonicalization parameter specifies the canonicalization algorithm that's used to create and verify the message header part of the DKIM signature. This value effectively controls the sensitivity of DKIM to changes to the message headers in transit. Valid values are 'Simple' or 'Relaxed'.  'Relaxed' is the default."), ValueMap{"Simple","Relaxed"}, Values{"Simple","Relaxed"}] String HeaderCanonicalization;
    [Write, Description("The KeySize parameter specifies the size in bits of the public key that's used in the DKIM signing policy. The only available value is 1024."),ValueMap{"1024"}, Values{"1024"}] Uint16 KeySize;
    [Write, Description("The Enabled parameter specifies whether the DKIM Signing Configuration is enabled or disabled. Default is $true.")] Boolean Enabled;
    [Write, Description("Specifies if this Client Access Rule should exist."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Required, Description("Credentials of the Exchange Global Admin"), EmbeddedInstance("MSFT_Credential")] String GlobalAdminAccount;
};
