[ClassVersion("1.0.0.0"), FriendlyName("EXOMailboxSettings")]
class MSFT_EXOMailboxSettings : OMI_BaseResource
{
    [Key, Description("The display name of the Shared Mailbox")] string DisplayName;
    [Write, Description("Associated retention policy.")] string RetentionPolicy;
    [Write, Description("Associated address book policy.")] string AddressBookPolicy;
    [Write, Description("Associated role assignment policy.")] string RoleAssignmentPolicy;
    [Write, Description("Associated sharing policy.")] string SharingPolicy;
    [Write, Description("The name of the Time Zone to assign to the mailbox")] string TimeZone;
    [Write, Description("The code of the Locale to assign to the mailbox")] string Locale;
    [Write, Description("Present ensures the Mailbox Settings are applied"), ValueMap{"Present"}, Values{"Present"}] string Ensure;
    [Write, Description("Credentials of the Exchange Global Admin"), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Id of the Azure Active Directory tenant used for authentication.")] String TenantId;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Username can be made up to anything but password will be used for CertificatePassword"), EmbeddedInstance("MSFT_Credential")] String CertificatePassword;
    [Write, Description("Path to certificate used in service principal usually a PFX file.")] String CertificatePath;
    [Write, Description("Managed ID being used for authentication.")] Boolean ManagedIdentity;
    [Write, Description("Access token used for authentication.")] String AccessTokens[];
};

