[ClassVersion("1.0.0.0"), FriendlyName("EXOMailboxSettings")]
class MSFT_EXOMailboxSettings : OMI_BaseResource
{
    [Key, Description("The display name of the Shared Mailbox")] string DisplayName;
    [Write, Description("The name of the Time Zone to assign to the mailbox")] string TimeZone;
    [Write, Description("The code of the Locale to assign to the mailbox")] string Locale;
    [Write, Description("Present ensures the Mailbox Settings are applied"), ValueMap{"Present"}, Values{"Present"}] string Ensure;
    [Required, Description("Credentials of the SharePoint Global Admin"), EmbeddedInstance("MSFT_Credential")] string GlobalAdminAccount;
};

