[ClassVersion("1.0.0.0")]
class MSFT_AADCertificateBasedApplicationConfigurationTrustedCertificateAuthority
{
    [Write, Description("The certificate data in base64 encoded format.")] String Certificate;
    [Write, Description("Indicates if the certificate is a root authority.")] Boolean IsRootAuthority;
    [Write, Description("The issuer of the certificate.")] String Issuer;
    [Write, Description("The subject key identifier of the issuer.")] String IssuerSubjectKeyIdentifier;
};

[ClassVersion("1.0.0.0"), FriendlyName("AADCertificateBasedApplicationConfiguration")]
class MSFT_AADCertificateBasedApplicationConfiguration : OMI_BaseResource
{
    [Key, Description("Display name for the configuration.")] String DisplayName;
    [Write, Description("The unique identifier for the configuration.")] String Id;
    [Write, Description("Description for the configuration.")] String Description;
    [Write, Description("Collection of trusted certificate authorities."), EmbeddedInstance("MSFT_AADCertificateBasedApplicationConfigurationTrustedCertificateAuthority")] String TrustedCertificateAuthorities[];

    [Write, Description("Present ensures the instance exists, absent ensures it is removed."), ValueMap{"Absent","Present"}, Values{"Absent","Present"}] String Ensure;
    [Write, Description("Credentials of the workload's Admin"), EmbeddedInstance("MSFT_Credential")] String Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Id of the Azure Active Directory tenant used for authentication.")] String TenantId;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Managed ID being used for authentication.")] Boolean ManagedIdentity;
    [Write, Description("Access token used for authentication.")] String AccessTokens[];
};
