[ClassVersion("1.0.0.0"), FriendlyName("MicrosoftPlaceDesk")]
class MSFT_MicrosoftPlaceDesk : OMI_BaseResource
{
    [Key, Description("The unique identifier for the desk.")] String Identity;
    [Write, Description("The display name of the desk.")] String DisplayName;
    [Write, Description("The physical address of the desk.")] String Address;
    [Write, Description("The city where the desk is located.")] String City;
    [Write, Description("The state or province where the desk is located.")] String State;
    [Write, Description("The country or region where the desk is located.")] String CountryOrRegion;
    [Write, Description("The postal code of the desk.")] String PostalCode;
    [Write, Description("The phone number for the desk.")] String Phone;
    [Write, Description("The geographic coordinates of the desk.")] String GeoCoordinates;
    [Write, Description("The building identifier where the desk is located.")] String BuildingId;
    [Write, Description("The floor number where the desk is located.")] String Floor;
    [Write, Description("The floor label where the desk is located.")] String FloorLabel;
    [Write, Description("The label for the desk.")] String Label;
    [Write, Description("Indicates if the desk is wheelchair accessible.")] Boolean IsWheelChairAccessible;
    [Write, Description("Additional features or tags for the desk.")] String Tags[];
    [Write, Description("Specify if the desk should exist or not."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Write, Description("Credentials of the Microsoft Graph delegated permissions."), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Id of the Azure Active Directory tenant used for authentication.")] String TenantId;
    [Write, Description("Secret of the Azure Active Directory application to authenticate with."), EmbeddedInstance("MSFT_Credential")] String ApplicationSecret;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Managed ID being used for authentication.")] Boolean ManagedIdentity;
    [Write, Description("Access token used for authentication.")] String AccessTokens[];
};