[ClassVersion("1.0.0.0")]
class MSFT_DeviceManagementConfigurationPolicyAssignments
{
    [Write, Description("The type of the target assignment."), ValueMap{"#microsoft.graph.groupAssignmentTarget","#microsoft.graph.allLicensedUsersAssignmentTarget","#microsoft.graph.allDevicesAssignmentTarget","#microsoft.graph.exclusionGroupAssignmentTarget","#microsoft.graph.configurationManagerCollectionAssignmentTarget"}, Values{"#microsoft.graph.groupAssignmentTarget","#microsoft.graph.allLicensedUsersAssignmentTarget","#microsoft.graph.allDevicesAssignmentTarget","#microsoft.graph.exclusionGroupAssignmentTarget","#microsoft.graph.configurationManagerCollectionAssignmentTarget"}] String dataType;
    [Write, Description("The type of filter of the target assignment i.e. Exclude or Include. Possible values are:none, include, exclude."), ValueMap{"none","include","exclude"}, Values{"none","include","exclude"}] String deviceAndAppManagementAssignmentFilterType;
    [Write, Description("The Id of the filter for the target assignment.")] String deviceAndAppManagementAssignmentFilterId;
    [Write, Description("The group Id that is the target of the assignment.")] String groupId;
    [Write, Description("The group Display Name that is the target of the assignment.")] String groupDisplayName;
    [Write, Description("The collection Id that is the target of the assignment.(ConfigMgr)")] String collectionId;
};

[ClassVersion("1.0.0.0"), FriendlyName("IntuneDeviceCompliancePolicyAndroid")]
class MSFT_IntuneDeviceCompliancePolicyAndroid : OMI_BaseResource
{
    [Key, Description("Display name of the Android device compliance policy.")] String DisplayName;
    [Write, Description("Description of the Android device compliance policy.")] String Description;
    [Write, Description("Assignments of the Intune Policy."), EmbeddedInstance("MSFT_DeviceManagementConfigurationPolicyAssignments")] String Assignments[];
    [Write, Description("PasswordRequired of the Android device compliance policy.")] Boolean PasswordRequired;
    [Write, Description("PasswordMinimumLength of the Android device compliance policy.")] Uint32 PasswordMinimumLength;
    [Write, Description("PasswordRequiredType of the Android device compliance policy."), ValueMap{"deviceDefault", "alphabetic", "alphanumeric", "alphanumericWithSymbols", "lowSecurityBiometric", "numeric", "numericComplex", "any"}, Values{"deviceDefault", "alphabetic", "alphanumeric", "alphanumericWithSymbols", "lowSecurityBiometric", "numeric", "numericComplex", "any"}] String PasswordRequiredType;
    [Write, Description("RequiredPasswordComplexity of the Android device compliance policy."), ValueMap{"none", "low", "medium", "high"}, Values{"none", "low", "medium", "high"}] String RequiredPasswordComplexity;
    [Write, Description("PasswordMinutesOfInactivityBeforeLock of the Android device compliance policy.")] Uint32 PasswordMinutesOfInactivityBeforeLock;
    [Write, Description("PasswordExpirationDays of the Android device compliance policy.")] Uint32 PasswordExpirationDays;
    [Write, Description("PasswordPreviousPasswordBlockCount of the Android device compliance policy.")] Uint32 PasswordPreviousPasswordBlockCount;
    [Write, Description("PasswordSignInFailureCountBeforeFactoryReset of the Android device compliance policy.")] Uint32 PasswordSignInFailureCountBeforeFactoryReset;
    [Write, Description("SecurityPreventInstallAppsFromUnknownSources of the Android device compliance policy.")] Boolean SecurityPreventInstallAppsFromUnknownSources;
    [Write, Description("SecurityDisableUsbDebugging of the Android device compliance policy.")] Boolean SecurityDisableUsbDebugging;
    [Write, Description("SecurityRequireVerifyApps of the Android device compliance policy.")] Boolean SecurityRequireVerifyApps;
    [Write, Description("DeviceThreatProtectionEnabled of the Android device compliance policy.")] Boolean DeviceThreatProtectionEnabled;
    [Write, Description("DeviceThreatProtectionRequiredSecurityLevel of the Android device compliance policy."), ValueMap{"unavailable", "secured", "low", "medium", "high", "notSet"}, Values{"unavailable", "secured", "low", "medium", "high", "notSet"}] String DeviceThreatProtectionRequiredSecurityLevel;
    [Write, Description("AdvancedThreatProtectionRequiredSecurityLevel of the Android device compliance policy."), ValueMap{"unavailable", "secured", "low", "medium", "high", "notSet"}, Values{"unavailable", "secured", "low", "medium", "high", "notSet"}] String AdvancedThreatProtectionRequiredSecurityLevel;
    [Write, Description("SecurityBlockJailbrokenDevices of the Android device compliance policy.")] Boolean SecurityBlockJailbrokenDevices;
    [Write, Description("SecurityBlockDeviceAdministratorManagedDevices of the Android device compliance policy.")] Boolean SecurityBlockDeviceAdministratorManagedDevices;
    [Write, Description("OsMinimumVersion of the Android device compliance policy.")] String OsMinimumVersion;
    [Write, Description("OsMaximumVersion of the Android device compliance policy.")] String OsMaximumVersion;
    [Write, Description("MinAndroidSecurityPatchLevel of the Android device compliance policy.")] String MinAndroidSecurityPatchLevel;
    [Write, Description("StorageRequireEncryption of the Android device compliance policy.")] Boolean StorageRequireEncryption;
    [Write, Description("SecurityRequireSafetyNetAttestationBasicIntegrity of the Android device compliance policy.")] Boolean SecurityRequireSafetyNetAttestationBasicIntegrity;
    [Write, Description("SecurityRequireSafetyNetAttestationCertifiedDevice of the Android device compliance policy.")] Boolean SecurityRequireSafetyNetAttestationCertifiedDevice;
    [Write, Description("SecurityRequireGooglePlayServices of the Android device compliance policy.")] Boolean SecurityRequireGooglePlayServices;
    [Write, Description("SecurityRequireUpToDateSecurityProviders of the Android device compliance policy.")] Boolean SecurityRequireUpToDateSecurityProviders;
    [Write, Description("SecurityRequireCompanyPortalAppIntegrity of the Android device compliance policy.")] Boolean SecurityRequireCompanyPortalAppIntegrity;
    [Write, Description("ConditionStatementId of the Android device compliance policy.")] String ConditionStatementId;
    [Write, Description("RestrictedApps of the Android device compliance policy.")] String RestrictedApps;
    [Write, Description("RoleScopeTagIds of the Android device compliance policy.")] String RoleScopeTagIds;
    [Write, Description("Present ensures the policy exists, absent ensures it is removed."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] string Ensure;
    [Write, Description("Credentials of the Intune Admin"), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Id of the Azure Active Directory tenant used for authentication.")] String TenantId;
    [Write, Description("Secret of the Azure Active Directory tenant used for authentication."), EmbeddedInstance("MSFT_Credential")] String ApplicationSecret;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Managed ID being used for authentication.")] Boolean ManagedIdentity;
    [Write, Description("Access token used for authentication.")] String AccessTokens[];
};
