[ClassVersion("1.0.0.0"), FriendlyName("IntuneDeviceCompliancePolicyAndroid")]
class MSFT_IntuneDeviceCompliancePolicyAndroid : OMI_BaseResource
{
    [Key, Description("Display name of the Android device compliance policy.")] String DisplayName;
    [Write, Description("Description of the Android device compliance policy.")] String Description;
    [Write, Description("PasswordRequired of the Android device compliance policy.")] Boolean PasswordRequired;
    [Write, Description("PasswordMinimumLength of the Android device compliance policy.")] Uint32 PasswordMinimumLength;
    [Write, Description("PasswordRequiredType of the Android device compliance policy."), ValueMap{"deviceDefault", "alphabetic", "alphanumeric", "alphanumericWithSymbols", "lowSecurityBiometric", "numeric", "numericComplex", "any"}, Values{"deviceDefault", "alphabetic", "alphanumeric", "alphanumericWithSymbols", "lowSecurityBiometric", "numeric", "numericComplex", "any"}] String PasswordRequiredType;
    [Write, Description("RequiredPasswordComplexity of the Android device compliance policy."), ValueMap{"none", "low", "medium", "high"}, Values{"none", "low", "medium", "high"}] String RequiredPasswordComplexity;
    [Write, Description("PasswordMinutesOfInactivityBeforeLock of the Android device compliance policy.")] Uint32 PasswordMinutesOfInactivityBeforeLock;
    [Write, Description("PasswordExpirationDays of the Android device compliance policy.")] Uint32 passwordExpirationDays;
    [Write, Description("PasswordPreviousPasswordBlockCount of the Android device compliance policy.")] Uint32 passwordPreviousPasswordBlockCount;
    [Write, Description("PasswordSignInFailureCountBeforeFactoryReset of the Android device compliance policy.")] Uint32 passwordSignInFailureCountBeforeFactoryReset;
    [Write, Description("SecurityPreventInstallAppsFromUnknownSources of the Android device compliance policy.")] Boolean securityPreventInstallAppsFromUnknownSources;
    [Write, Description("SecurityDisableUsbDebugging of the Android device compliance policy.")] Boolean securityDisableUsbDebugging;
    [Write, Description("SecurityRequireVerifyApps of the Android device compliance policy.")] Boolean securityRequireVerifyApps;
    [Write, Description("DeviceThreatProtectionEnabled of the Android device compliance policy.")] Boolean deviceThreatProtectionEnabled;
    [Write, Description("DeviceThreatProtectionRequiredSecurityLevel of the Android device compliance policy."), ValueMap{"unavailable", "secured", "low", "medium", "high", "notSet"}, Values{"unavailable", "secured", "low", "medium", "high", "notSet"}] String DeviceThreatProtectionRequiredSecurityLevel;
    [Write, Description("AdvancedThreatProtectionRequiredSecurityLevel of the Android device compliance policy."), ValueMap{"unavailable", "secured", "low", "medium", "high", "notSet"}, Values{"unavailable", "secured", "low", "medium", "high", "notSet"}] String advancedThreatProtectionRequiredSecurityLevel;
    [Write, Description("SecurityBlockJailbrokenDevices of the Android device compliance policy.")] Boolean securityBlockJailbrokenDevices;
    [Write, Description("SecurityBlockDeviceAdministratorManagedDevices of the Android device compliance policy.")] Boolean securityBlockDeviceAdministratorManagedDevices;
    [Write, Description("OSMinimumVersion of the Android device compliance policy.")] String osMinimumVersion;
    [Write, Description("OSMaximumVersion of the Android device compliance policy.")] String osMaximumVersion;
    [Write, Description("MinAndroidSecurityPatchLevel of the Android device compliance policy.")] String minAndroidSecurityPatchLevel;
    [Write, Description("StorageRequireEncryption of the Android device compliance policy.")] Boolean storageRequireEncryption;
    [Write, Description("SecurityRequireSafetyNetAttestationBasicIntegrity of the Android device compliance policy.")] Boolean securityRequireSafetyNetAttestationBasicIntegrity;
    [Write, Description("SecurityRequireSafetyNetAttestationCertifiedDevice of the Android device compliance policy.")] Boolean securityRequireSafetyNetAttestationCertifiedDevice;
    [Write, Description("SecurityRequireGooglePlayServices of the Android device compliance policy.")] Boolean securityRequireGooglePlayServices;
    [Write, Description("SecurityRequireUpToDateSecurityProviders of the Android device compliance policy.")] Boolean securityRequireUpToDateSecurityProviders;
    [Write, Description("SecurityRequireCompanyPortalAppIntegrity of the Android device compliance policy.")] Boolean securityRequireCompanyPortalAppIntegrity;
    [Write, Description("ConditionStatementId of the Android device compliance policy.")] String conditionStatementId;
    [Write, Description("RestrictedApps of the Android device compliance policy.")] String restrictedApps;
    [Write, Description("RoleScopeTagIds of the Android device compliance policy.")] String roleScopeTagIds;
    [Write, Description("Present ensures the policy exists, absent ensures it is removed."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] string Ensure;
    [Required, Description("Credentials of the Intune Admin"), EmbeddedInstance("MSFT_Credential")] String GlobalAdminAccount;
};
