[ClassVersion("1.0.0.0"), FriendlyName("TeamsTeam")]
class MSFT_TeamsTeam : OMI_BaseResource
{
    [Key, Description("Display Name of the Team")] string DisplayName;
    [Write, Description("Description of Team.")] string Description;
    [Write, Description("Team group ID, only used to target a Team when duplicated display names occurs.")] string GroupID;
    [Write, Description("MailNickName of O365 Group associated with Team")] string MailNickName;
    [Write, Description("Owners of the Team")] string Owner[];
    [Write, Description("Visibility of the Team"),ValueMap{"Public","Private"},Values{"Public","Private"}] String Visibility;
    [Write, Description("Allow add or remove apps from the Team.")] Boolean AllowAddRemoveApps;
    [Write, Description("Allow giphy in Team.")] Boolean AllowGiphy;
    [Write, Description("Giphy content rating of the Team."),ValueMap{"Strict","Moderate"}, Values{"Strict","Moderate"}] string GiphyContentRating;
    [Write, Description("Allow stickers and mimes in the Team.")] Boolean AllowStickersAndMemes;
    [Write, Description("Allow custom memes in Team.")] Boolean AllowCustomMemes;
    [Write, Description("Allow members to edit messages within Team.")] Boolean AllowUserEditMessages;
    [Write, Description("Allow members to delete messages within Team.")] Boolean AllowUserDeleteMessages;
    [Write, Description("Allow owners to delete messages within Team.")] Boolean AllowOwnerDeleteMessages;
    [Write, Description("Allow members to delete channels within Team.")] Boolean AllowDeleteChannels;
    [Write, Description("Allow members to manage connectors within Team.")] Boolean AllowCreateUpdateRemoveConnectors;
    [Write, Description("Allow members to manage tabs within Team.")] Boolean AllowCreateUpdateRemoveTabs;
    [Write, Description("Allow mentions in Team.")] Boolean AllowTeamMentions;
    [Write, Description("Allow channel mention in Team.")] Boolean AllowChannelMentions;
    [Write, Description("Allow guests to create and update channels in Team.")] Boolean AllowGuestCreateUpdateChannels;
    [Write, Description("Allow guests to delete channel in Team.")] Boolean AllowGuestDeleteChannels;
    [Write, Description("Allow members to create and update channels within Team.")] Boolean AllowCreateUpdateChannels;
    [Write, Description("Present ensures the Team exists, absent ensures it is removed."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Write, Description("Credentials of the SharePoint Global Admin"), EmbeddedInstance("MSFT_Credential")] String GlobalAdminAccount;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Id of the Azure Active Directory tenant used for authentication.")] String TenantId;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
};

