[ClassVersion("1.0.0.0"), FriendlyName("TeamsUserCallingSettings")]
class MSFT_TeamsUserCallingSettings : OMI_BaseResource
{
    [Key, Description("The Identity of the user to set call forwarding, simultaneous ringing and call group settings for. Can be specified using the ObjectId or the SIP address.")] String Identity;
    [Write, Description("The group notification override that will be set on the specified user. The supported values are Ring, Mute and Banner."), ValueMap{"Ring","Mute","Banner"}, Values{"Ring","Mute","Banner"}] String GroupNotificationOverride;
    [Write, Description("The order in which to call members of the Call Group. The supported values are Simultaneous and InOrder.")] String CallGroupOrder;
    [Write, Description("The members of the Call Group. You need to always specify the full set of members as the parameter value. What you set here will overwrite the current call group membership.")] String CallGroupTargets[];
    [Write, Description("This parameter controls whether forwarding for unasnwered calls is enabled or not.")] Boolean IsUnansweredEnabled;
    [Write, Description("The time the call will ring the user before it is forwarded to the unanswered target. The supported format is hh:mm:ss and the delay range needs to be between 10 and 60 seconds in 10 seconds increments, i.e. 00:00:10, 00:00:20, 00:00:30, 00:00:40, 00:00:50 and 00:01:00. The default value is 20 seconds.")] String UnansweredDelay;
    [Write, Description("The unanswered target. Supported type of values are ObjectId, SIP address and phone number. For phone numbers we support the following types of formats: E.164 (+12065551234 or +1206555000;ext=1234) or non-E.164 like 1234.")] String UnansweredTarget;
    [Write, Description("The unanswered target type. Supported values are Voicemail, SingleTarget, MyDelegates and Group."), ValueMap{"Group","MyDelegates","SingleTarget","Voicemail"}, Values{"Group","MyDelegates","SingleTarget","Voicemail"}] String UnansweredTargetType;
    [Write, Description("This parameter controls whether forwarding is enabled or not.")] Boolean IsForwardingEnabled;
    [Write, Description("The type of forwarding to set. Supported values are Immediate and Simultaneous"),ValueMap{"Immediate","Simultaneous"}, Values{"Immediate","Simultaneous"}] String ForwardingType;
    [Write, Description("The forwarding target type. Supported values are Voicemail, SingleTarget, MyDelegates and Group. Voicemail is only supported for Immediate forwarding."), ValueMap{"Group","MyDelegates","SingleTarget","Voicemail"}, Values{"Group","MyDelegates","SingleTarget","Voicemail"}] String ForwardingTargetType;
    [Write, Description("The forwarding target. Supported types of values are ObjectId's, SIP addresses and phone numbers. For phone numbers we support the following types of formats: E.164 (+12065551234 or +1206555000;ext=1234) or non-E.164 like 1234.")] String ForwardingTarget;
    [Write, Description("Present ensures the policy exists, absent ensures it is removed."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Write, Description("Credentials of the Teams Global Admin."), EmbeddedInstance("MSFT_Credential")] String Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Name of the Azure Active Directory tenant used for authentication. Format contoso.onmicrosoft.com")] String TenantId;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Managed ID being used for authentication.")] Boolean ManagedIdentity;
};
