[ClassVersion("1.0.0.0"), FriendlyName("TeamsCallParkPolicy")]
class MSFT_TeamsCallParkPolicy : OMI_BaseResource
{
    [Key, Description("A unique identifier for the policy - this will be used to retrieve the policy later on to assign it to specific users.")] String Identity;
    [Write, Description("If set to true, customers will be able to leverage the call park feature to place calls on hold and then decide how the call should be handled - transferred to another department, retrieved using the same phone, or retrieved using a different phone.")] Boolean AllowCallPark;
    [Write, Description("Description of the Teams Call Park Policy.")] String Description;
    [Write, Description("Specify the number of seconds to wait before ringing the parker when the parked call hasn't been picked up. Value can be from 120 to 1800 (seconds).")] UInt64 ParkTimeoutSeconds;
    [Write, Description("Specify the maximum value that a rendered pickup code can take. Value can be from 10 to 9999. Note: PickupRangeStart must be smaller than PickupRangeEnd.")] UInt64 PickupRangeEnd;
    [Write, Description("Specify the minimum value that a rendered pickup code can take. Value can be from 10 to 9999.")] UInt64 PickupRangeStart;
    [Write, Description("Present ensures the instance exists, absent ensures it is removed."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] string Ensure;
    [Write, Description("Credentials of the workload's Admin"), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Id of the Azure Active Directory tenant used for authentication.")] String TenantId;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Managed ID being used for authentication.")] Boolean ManagedIdentity;
    [Write, Description("Access token used for authentication.")] String AccessTokens[];
};
