[ClassVersion("1.0.0.0"), FriendlyName("TeamsChannel")]
class MSFT_TeamsChannel : OMI_BaseResource
{
    [Key, Description("Current channel name")] string DisplayName;
    [Key, Description("Name of the team the Channel belongs to")] string TeamName;
    [Write, Description("Used to update current channel name")] string NewDisplayName;
    [Write, Description("Channel description")] string Description;
    [Write, Description("Specifies the visibility of the Channel. Standard for public channel and Private for private channels."), ValueMap{"Standard","Private"}, Values{"Standard","Private"}] String MembershipType;
    [Write, Description("Present ensures the Team channel exists, absent ensures it is removed"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Required, Description("Credentials of the SharePoint Global Admin"), EmbeddedInstance("MSFT_Credential")] String GlobalAdminAccount;
};

