[ClassVersion("1.0.0.0"), FriendlyName("EXOSweepRule")]
class MSFT_EXOSweepRule : OMI_BaseResource
{
    [Key, Description("The Name parameter specifies the name of the Sweep rule. If the value contains spaces, enclose the value in quotation marks.")] String Name;
    [Write, Description("The Provider parameter specifies the provider for the Sweep rule. If the value contains spaces, enclose the value in quotation marks. For Sweep rules that you create in Outlook on the web, the default value is Exchange16.")] String Provider;
    [Write, Description("The DestinationFolder parameter specifies an action for the Sweep rule that moves messages to the specified folder.")] String DestinationFolder;
    [Write, Description("The Enabled parameter specifies whether the Sweep rule is enabled or disabled.")] Boolean Enabled;
    [Write, Description("The KeepForDays parameter specifies an action for the Sweep rule that specifies the number of days to keep messages that match the conditions of the rule. After the number of days have passed, the messages are moved to the location that's specified by the DestinationFolder parameter (by default, the Deleted Items folder). You can't use this parameter with the KeepLatest parameter and the Sweep rule must contain a KeepForDays or KeepLatest parameter value.")] UInt32 KeepForDays;
    [Write, Description("The KeepLatest parameter specifies an action for the Sweep rule that specifies the number of messages to keep that match the conditions of the rule. After the number of messages is exceeded, the oldest messages are moved to the location that's specified by the DestinationFolder parameter (by default, the Deleted Items folder). You can't use this parameter with the KeepForDays parameter and the Sweep rule must contain a KeepForDays or KeepLatest parameter value.")] UInt32 KeepLatest;
    [Write, Description("The Mailbox parameter specifies the mailbox where you want to create the Sweep rule. You can use any value that uniquely identifies the mailbox.")] String Mailbox;
    [Write, Description("The SenderName parameter specifies a condition for the Sweep rule that looks for the specified sender in messages. For internal senders, you can use any value that uniquely identifies the sender.")] String SenderName;
    [Write, Description("The SourceFolder parameter specifies a condition for the Sweep rule that looks for messages in the specified folder.")] String SourceFolder;
    [Write, Description("The SystemCategory parameter specifies a condition for the sweep rule that looks for messages with the specified system category. System categories are available to all mailboxes in the organization.")] String SystemCategory;
    [Write, Description("Specify if this rule should exist or not."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Write, Description("Credentials of the workload's Admin"), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Id of the Azure Active Directory tenant used for authentication.")] String TenantId;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Managed ID being used for authentication.")] Boolean ManagedIdentity;
    [Write, Description("Access token used for authentication.")] String AccessTokens[];
};
