[ClassVersion("1.0.0.0"), FriendlyName("M365DSCGraphAPIRuleEvaluation")]
class MSFT_M365DSCGraphAPIRuleEvaluation : OMI_BaseResource
{
    [Key, Description("Url of the REST Endpoint.")] String APIUrl;
    [Key, Description("Specify the rules to evaluate.")] String RuleDefinition;
    [Write, Description("Name of the parent property of the response, which contains the instances. Default is 'value'.")] String InstancesProperty;
    [Write, Description("For logging purposes only. This represents the unique identifier of instances returned by the Graph API call.")] String InstanceIdentifier;
    [Write, Description("Custom display name for the rule. This will show up in the logs on drift detection.")] String RuleName;
    [Write, Description("Query to check how many instances exist, using PowerShell format")] String AfterRuleCountQuery;
    [Write, Description("Credentials of the Azure Active Directory Admin"), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Id of the Azure Active Directory tenant used for authentication.")] String TenantId;
    [Write, Description("Secret of the Azure Active Directory application to authenticate with."), EmbeddedInstance("MSFT_Credential")] String ApplicationSecret;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Username can be made up to anything but password will be used for CertificatePassword"), EmbeddedInstance("MSFT_Credential")] String CertificatePassword;
    [Write, Description("Path to certificate used in service principal usually a PFX file.")] String CertificatePath;
    [Write, Description("Managed ID being used for authentication.")] Boolean ManagedIdentity;
    [Write, Description("Access token used for authentication.")] String AccessTokens[];
};
