[ClassVersion("1.0.0.0"), FriendlyName("EXOMailbox")]
class MSFT_EXOMailbox : OMI_BaseResource
{
    [Key, Description("The Identity parameter specifies the Mailbox that you want to modify.")] String Identity;
    [Write, Description("Mailbox cannot be created/removed in O365.  This must be set to 'Present'"), ValueMap{"Present"}, Values{"Present"}] String Ensure;
    [Write, Description("The Alias parameter specifies the Exchange alias (also known as the mail nickname) for the recipient.")] String Alias;
    [Write, Description("The EmailAddresses parameter specifies all the email addresses (proxy addresses) for the Mailbox")] string EmailAddresses[];
    [Write, Description("The DisplayName parameter specifies the display name of the mailbox.")] String DisplayName;
    [Write, Description("")] String DistinguishedName;
    [Write, Description("")] String ExchangeVersion;
    [Write, Description("")] String ExternalDirectoryObjectId;
    [Write, Description("")] String Guid;
    [Write, Description("")] String Id;
    [Write, Description("")] String Name;
    [Write, Description("")] String OrganizationId;
    [Write, Description("")] String PrimarySmtpAddress;
    [Write, Description("")] String RecipientType;
    [Write, Description("")] String RecipientTypeDetails;
    [Write, Description("")] String UserPrincipalName;
    [Write, Description("The AddressBookPolicy parameter specifies the address book policy that's applied to the mailbox. ")] String AddressBookPolicy;
    [Write, Description("")] String AddressListMembership;
    [Write, Description("")] String GeneratedOfflineAddressBooks;
    [Write, Description("The HiddenFromAddressListsEnabled parameter specifies whether this recipient is visible in address lists. ")] String HiddenFromAddressListsEnabled;
    [Write, Description("")] String OfflineAddressBook;

    [Write, Description("The ArchiveDatabase parameter specifies the Exchange database that contains the archive that's associated with this mailbox.")] String ArchiveDatabase;
    [Write, Description("The ArchiveDomain parameter specifies the domain in the cloud-based service where the archive that's associated with this mailbox exists.")] String ArchiveDomain;
    [Write, Description("")] String ArchiveGuid;
    [Write, Description("The ArchiveName parameter specifies the name of the archive mailbox. This is the name displayed to users in Outlook on the web (formerly known as Outlook Web App).")] String ArchiveName;
    [Write, Description("The ArchiveQuota parameter specifies the maximum size for the user's archive mailbox. If the archive mailbox reaches or exceeds this size, it no longer accepts messages.")] String ArchiveQuota;
    [Write, Description("")] String ArchiveRelease;
    [Write, Description("")] String ArchiveState;
    [Write, Description("")] String ArchiveStatus;
    [Write, Description("The ArchiveWarningQuota parameter specifies the warning threshold for the size of the user's archive mailbox. If the archive mailbox reaches or exceeds this size, the user receives a descriptive warning message.")] String ArchiveWarningQuota;
    [Write, Description("")] String AutoExpandingArchiveEnabled;
    [Write, Description("")] String DisabledArchiveDatabase;
    [Write, Description("")] String DisabledArchiveGuid;
    [Write, Description("")] String JournalArchiveAddress;

    [Write, Description("The AuditAdmin parameter specifies the mailbox operations to log for administrators as part of mailbox audit logging.")] String AuditAdmin;
    [Write, Description("The AuditDelegate parameter specifies the mailbox operations to log for delegate users as part of mailbox audit logging")] String AuditDelegate;
    [Write, Description("The AuditEnabled parameter specifies whether to enable or disable mailbox audit logging for the mailbox.")] String AuditEnabled;
    [Write, Description("The AuditLogAgeLimit parameter specifies the maximum age of audit log entries for the mailbox. Log entries older than the specified value are removed. The default value is 90 days.")] String AuditLogAgeLimit;
    [Write, Description("The AuditOwner parameter specifies the mailbox operations to log for mailbox owners as part of mailbox audit logging.")] String AuditOwner;
    [Write, Description("The DefaultAuditSet parameter specifies whether to revert the mailbox operations that are logged in the mailbox audit log back to the set of default operations for the specified logon type")] String DefaultAuditSet;

    [Write, Description("This parameter specifies a value for the CustomAttribute1 property on the recipient. You can use this property to store custom information about the recipient, and to identify the recipient in filters.")] String CustomAttribute1;
    [Write, Description("This parameter specifies a value for the CustomAttribute2 property on the recipient. You can use this property to store custom information about the recipient, and to identify the recipient in filters.")] String CustomAttribute2;
    [Write, Description("This parameter specifies a value for the CustomAttribute3 property on the recipient. You can use this property to store custom information about the recipient, and to identify the recipient in filters.")] String CustomAttribute3;
    [Write, Description("This parameter specifies a value for the CustomAttribute4 property on the recipient. You can use this property to store custom information about the recipient, and to identify the recipient in filters.")] String CustomAttribute4;
    [Write, Description("This parameter specifies a value for the CustomAttribute5 property on the recipient. You can use this property to store custom information about the recipient, and to identify the recipient in filters.")] String CustomAttribute5;
    [Write, Description("This parameter specifies a value for the CustomAttribute6 property on the recipient. You can use this property to store custom information about the recipient, and to identify the recipient in filters.")] String CustomAttribute6;
    [Write, Description("This parameter specifies a value for the CustomAttribute7 property on the recipient. You can use this property to store custom information about the recipient, and to identify the recipient in filters.")] String CustomAttribute7;
    [Write, Description("This parameter specifies a value for the CustomAttribute8 property on the recipient. You can use this property to store custom information about the recipient, and to identify the recipient in filters.")] String CustomAttribute8;
    [Write, Description("This parameter specifies a value for the CustomAttribute9 property on the recipient. You can use this property to store custom information about the recipient, and to identify the recipient in filters.")] String CustomAttribute9;
    [Write, Description("This parameter specifies a value for the CustomAttribute10 property on the recipient. You can use this property to store custom information about the recipient, and to identify the recipient in filters.")] String CustomAttribute10;
    [Write, Description("This parameter specifies a value for the CustomAttribute11 property on the recipient. You can use this property to store custom information about the recipient, and to identify the recipient in filters.")] String CustomAttribute11;
    [Write, Description("This parameter specifies a value for the CustomAttribute12 property on the recipient. You can use this property to store custom information about the recipient, and to identify the recipient in filters.")] String CustomAttribute12;
    [Write, Description("This parameter specifies a value for the CustomAttribute13 property on the recipient. You can use this property to store custom information about the recipient, and to identify the recipient in filters.")] String CustomAttribute13;
    [Write, Description("This parameter specifies a value for the CustomAttribute14 property on the recipient. You can use this property to store custom information about the recipient, and to identify the recipient in filters.")] String CustomAttribute14;
    [Write, Description("This parameter specifies a value for the CustomAttribute15 property on the recipient. You can use this property to store custom information about the recipient, and to identify the recipient in filters.")] String CustomAttribute15;
    [Write, Description("This parameter specifies a value for the ExtensionCustomAttribute1 property on the recipient. You can use this property to store custom information about the recipient, and to identify the recipient in filters.")] String ExtensionCustomAttribute1;
    [Write, Description("This parameter specifies a value for the ExtensionCustomAttribute2 property on the recipient. You can use this property to store custom information about the recipient, and to identify the recipient in filters.")] String ExtensionCustomAttribute2;
    [Write, Description("This parameter specifies a value for the ExtensionCustomAttribute3 property on the recipient. You can use this property to store custom information about the recipient, and to identify the recipient in filters.")] String ExtensionCustomAttribute3;
    [Write, Description("This parameter specifies a value for the ExtensionCustomAttribute4 property on the recipient. You can use this property to store custom information about the recipient, and to identify the recipient in filters.")] String ExtensionCustomAttribute4;
    [Write, Description("This parameter specifies a value for the ExtensionCustomAttribute5 property on the recipient. You can use this property to store custom information about the recipient, and to identify the recipient in filters.")] String ExtensionCustomAttribute5;

    [Write, Description("The AcceptMessagesOnlyFrom parameter specifies who is allowed to send messages to this recipient. Messages from other senders are rejected.")] String AcceptMessagesOnlyFrom;
    [Write, Description("The AcceptMessagesOnlyFromDLMembers parameter specifies who is allowed to send messages to this recipient. Messages from other senders are rejected.")] String AcceptMessagesOnlyFromDLMembers;
    [Write, Description("The AcceptMessagesOnlyFromSendersOrMembers parameter specifies who is allowed to send messages to this recipient. Messages from other senders are rejected.")] String AcceptMessagesOnlyFromSendersOrMembers;
    [Write, Description("The DeliverToMailboxAndForward parameter specifies the message delivery behavior when a forwarding address is specified by the ForwardingAddress or ForwardingSmtpAddress parameters.")] String DeliverToMailboxAndForward;
    [Write, Description("The DowngradeHighPriorityMessagesEnabled parameter specifies whether to prevent the mailbox from sending high priority messages to an X.400 mail system. ")] String DowngradeHighPriorityMessagesEnabled;
    [Write, Description("The ForwardingAddress parameter specifies a forwarding address in your organization for messages that are sent to this mailbox.")] String ForwardingAddress;
    [Write, Description("The ForwardingSmtpAddress parameter specifies a forwarding SMTP address for messages that are sent to this mailbox. Typically, you use this parameter to specify external email addresses that aren't validated.")] String ForwardingSmtpAddress;
    [Write, Description("The GrantSendOnBehalfTo parameter specifies who can send on behalf of this mailbox.")] String GrantSendOnBehalfTo;
    [Write, Description("")] String MaxBlockedSenders;
    [Write, Description("")] String MaxReceiveSize;
    [Write, Description("")] String MaxSafeSenders;
    [Write, Description("")] String MaxSendSize;
    [Write, Description("")] String MessageCopyForSendOnBehalfEnabled;
    [Write, Description("")] String MessageCopyForSentAsEnabled;
    [Write, Description("")] String MessageRecallProcessingEnabled;
    [Write, Description("")] String MessageTrackingReadStatusEnabled;
    [Write, Description("")] String RecipientLimits;
    [Write, Description("")] String RejectMessagesFrom;
    [Write, Description("")] String RejectMessagesFromDLMembers;
    [Write, Description("")] String RejectMessagesFromSendersOrMembers;
    [Write, Description("")] String RulesQuota;

    [Write, Description("")] String ComplianceTagHoldApplied;
    [Write, Description("")] String DelayHoldApplied;
    [Write, Description("")] String InPlaceHolds;
    [Write, Description("")] String InactiveMailboxRetireTime;
    [Write, Description("")] String LitigationHoldDate;
    [Write, Description("")] String LitigationHoldDuration;
    [Write, Description("")] String LitigationHoldEnabled;
    [Write, Description("")] String LitigationHoldOwner;
    [Write, Description("The BypassModerationFromSendersOrMembers parameter specifies who is allowed to send messages to this moderated recipient without approval from a moderator.")] String BypassModerationFromSendersOrMembers;
    [Write, Description("")] String ModeratedBy;
    [Write, Description("")] String ModerationEnabled;
    [Write, Description("")] String SendModerationNotifications;
    [Write, Description("")] String MailboxMoveBatchName;
    [Write, Description("")] String MailboxMoveFlags;
    [Write, Description("")] String MailboxMoveRemoteHostName;
    [Write, Description("")] String MailboxMoveSourceMDB;
    [Write, Description("")] String MailboxMoveStatus;
    [Write, Description("")] String MailboxMoveTargetMDB;
    [Write, Description("The DataEncryptionPolicy parameter specifies the data encryption policy that's applied to the mailbox. ")] String DataEncryptionPolicy;
    [Write, Description("The EmailAddressPolicyEnabled parameter specifies whether to apply email address policies to this recipient.")] String EmailAddressPolicyEnabled;
    [Write, Description("")] String ManagedFolderMailboxPolicy;
    [Write, Description("")] String PoliciesExcluded;
    [Write, Description("")] String PoliciesIncluded;
    [Write, Description("")] String RemoteAccountPolicy;
    [Write, Description("")] String RetentionPolicy;
    [Write, Description("")] String RetentionUrl;
    [Write, Description("")] String RoleAssignmentPolicy;
    [Write, Description("")] String SharingPolicy;
    [Write, Description("")] String ThrottlingPolicy;
    [Write, Description("The DefaultPublicFolderMailbox parameter assigns a specific public folder mailbox to the user. ")] String DefaultPublicFolderMailbox;
    [Write, Description("")] String EffectivePublicFolderMailbox;
    [Write, Description("")] String IsExcludedFromServingHierarchy;
    [Write, Description("")] String IsHierarchyReady;
    [Write, Description("")] String IsHierarchySyncEnabled;
    [Write, Description("")] String IsRootPublicFolderMailbox;
    [Write, Description("The CalendarLoggingQuota parameter specifies the maximum size of the log in the Recoverable Items folder of the mailbox that stores changes to calendar items. ")] String CalendarLoggingQuota;
    [Write, Description("")] String IssueWarningQuota;
    [Write, Description("")] String ProhibitSendQuota;
    [Write, Description("")] String ProhibitSendReceiveQuota;
    [Write, Description("")] String RecoverableItemsQuota;
    [Write, Description("")] String RecoverableItemsWarningQuota;
    [Write, Description("")] String UseDatabaseQuotaDefaults;
    [Write, Description("")] String IsResource;
    [Write, Description("")] String ResourceCapacity;
    [Write, Description("")] String ResourceCustom;
    [Write, Description("")] String ResourceType;
    [Write, Description("")] String RoomMailboxAccountEnabled;
    [Write, Description("The EndDateForRetentionHold parameter specifies the end date for retention hold for messaging records management (MRM). ")] String EndDateForRetentionHold;
    [Write, Description("")] String OrphanSoftDeleteTrackingTime;
    [Write, Description("")] String RetainDeletedItemsFor;
    [Write, Description("")] String RetainDeletedItemsUntilBackup;
    [Write, Description("")] String RetentionComment;
    [Write, Description("")] String RetentionHoldEnabled;
    [Write, Description("")] String SingleItemRecoveryEnabled;
    [Write, Description("")] String StartDateForRetentionHold;
    [Write, Description("")] String UseDatabaseRetentionDefaults;
    [Write, Description("The AntispamBypassEnabled parameter specifies whether to skip anti-spam processing on the mailbox.")] String AntispamBypassEnabled;
    [Write, Description("")] String SCLDeleteEnabled;
    [Write, Description("")] String SCLDeleteThreshold;
    [Write, Description("")] String SCLJunkEnabled;
    [Write, Description("")] String SCLJunkThreshold;
    [Write, Description("")] String SCLQuarantineEnabled;
    [Write, Description("")] String SCLQuarantineThreshold;
    [Write, Description("")] String SCLRejectEnabled;
    [Write, Description("")] String SCLRejectThreshold;
    [Write, Description("")] String IncludeInGarbageCollection;
    [Write, Description("")] String IsInactiveMailbox;
    [Write, Description("")] String IsSoftDeletedByDisable;
    [Write, Description("")] String IsSoftDeletedByRemove;
    [Write, Description("")] String WhenSoftDeleted;
    [Write, Description("")] String ArchiveDatabaseGuid;
    [Write, Description("")] String DatabaseGuid;
    [Write, Description("")] String ExchangeGuid;

    [Write, Description("Credentials of the Exchange Global Admin"), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Id of the Azure Active Directory tenant used for authentication.")] String TenantId;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Username can be made up to anything but password will be used for CertificatePassword"), EmbeddedInstance("MSFT_Credential")] String CertificatePassword;
    [Write, Description("Path to certificate used in service principal usually a PFX file.")] String CertificatePath;
    [Write, Description("Managed ID being used for authentication.")] Boolean ManagedIdentity;
};
