[ClassVersion("1.0.0")]
Class MSFT_SPOThemePaletteProperty
{
    [Write, Description("Name of the property.")] String Property;
    [Write, Description("Color value in Hexadecimal.")] String Value;
};

[ClassVersion("1.0.0.0"), FriendlyName("SPOTheme")]
class MSFT_SPOTheme : OMI_BaseResource
{
    [Key, Description("The name of the theme, which appears in the theme picker UI and is also used by administrators and developers to refer to the theme in PowerShell cmdlets or calls to the SharePoint REST API.")] String Name;
    [Write, Description("This value should be false for light themes and true for dark themes; it controls whether SharePoint uses dark or light theme colors to render text on colored backgrounds.")] boolean IsInverted;
    [Write, Description("Specifies the color scheme which composes your theme."),EmbeddedInstance("MSFT_SPOThemePaletteProperty")] String Palette[];
    [Write, Description("Only accepted value is 'Present'."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Required, Description("Credentials of the SharePoint Global Admin"), EmbeddedInstance("MSFT_Credential")] string GlobalAdminAccount;
};
