[ClassVersion("1.0.0")]
class MSFT_MicrosoftGraphIdentity
{
    [Write, Description("Identity of direcory-object. For users, specify a UserPrincipalName. For Groups and SPNs, specify DisplayName")] String Identity;
    [Write, Description("Specify User, Group or ServicePrincipal to interpret the Identity")] String Type;
};
[ClassVersion("1.0.0")]
class MSFT_MicrosoftGraphScopedRoleMembership
{
    [Write, Description("Name of the Azure AD Role that is assigned")] String RoleName;
    [Write, Description("Member that is assigned the scoped role"), EmbeddedInstance("MSFT_MicrosoftGraphIdentity")] String RoleMemberInfo;
};
/* Extensions not incorporated in initial version
[ClassVersion("1.0.0")]
class MSFT_MicrosoftGraphOpenExtension
{
    [Write, Description("See https://docs.microsoft.com/en-us/graph/extensibility-overview#open-extensions")] String Id;
    [Write, Description("Optional list of properties and their values"), EmbeddedInstance("MSFT_KeyValuePair")] String Properties[];
};
*/

[ClassVersion("1.0.0.0"), FriendlyName("AADAdministrativeUnit")]
class MSFT_AADAdministrativeUnit : OMI_BaseResource
{
    [Write, Description("Object-Id of the Administrative Unit")] String Id;
    [Write, Description("Description of the Administrative Unit")] String Description;
    [Write, Description("DisplayName of the Administrative Unit")] String DisplayName;
    [Write, Description("Visibility of the Administrative Unit. Specify HiddenMembership if members of the AU are hidden")] String Visibility;
    [Write, Description("Specify membership type. Possible values are Assigned and Dynamic if the AU-preview has been activated. Otherwise do not use")] String MembershipType;
    [Write, Description("Specify membership rule. Requires that MembershipType is set to Dynamic AND the AU-preview has been activated. Otherwise, do not use")] String MembershipRule;
    [Write, Description("Specify dynamic membership-rule processing-state. Valid values are 'On' and 'Paused'. Requires that MembershipType is set to Dynamic AND the AU-preview has been activated. Otherwise, do not use")] String MembershipRuleProcessingState;
    [Write, Description("Specify members. Only specify if MembershipType is set to Static"), EmbeddedInstance("MSFT_MicrosoftGraphIdentity")] String Members[];
    [Write, Description(""), EmbeddedInstance("MSFT_MicrosoftGraphScopedRoleMembership")] String ScopedRoleMembers[];
//   [Write, Description("Extensions. See https://docs.microsoft.com/en-us/graph/extensibility-overview#open-extensions"), EmbeddedInstance("MSFT_MicrosoftGraphOpenExtension")] String Extensions[];


    [Write, Description("Present ensures the Administrative Unit exists, absent ensures it is removed."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] string Ensure;
    [Write, Description("Credentials of the Intune Admin"), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Id of the Azure Active Directory tenant used for authentication.")] String TenantId;
    [Write, Description("Secret of the Azure Active Directory application to authenticate with."), EmbeddedInstance("MSFT_Credential")] String ApplicationSecret;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Managed ID being used for authentication.")] Boolean ManagedIdentity;
};
