[ClassVersion("1.0.0")]
class MSFT_SentinelAlertRuleEventGroupSettings
{
    [Write, Description("")] String aggregationKind;
};

[ClassVersion("1.0.0")]
class MSFT_SentinelAlertRuleCustomDetails
{
    [Write, Description("")] String DetailKey;
    [Write, Description("")] String DetailValue;
};

[ClassVersion("1.0.0")]
class MSFT_SentinelAlertRuleEntityMapping
{
    [Write, Description("")] String entityType;
    [Write, Description(""), EmbeddedInstance("MSFT_SentinelAlertRuleEntityMappingFieldMapping")] String fieldMappings[];
};

[ClassVersion("1.0.0")]
class MSFT_SentinelAlertRuleEntityMappingFieldMapping
{
    [Write, Description("")] String columnName;
    [Write, Description("")] String  identifier;
};

[ClassVersion("1.0.0")]
class MSFT_SentinelAlertRuleAlertDetailsOverride
{
    [Write, Description("")] String alertDescriptionFormat;
    [Write, Description("")] String alertDisplayNameFormat;
    [Write, Description("")] String alertColumnName;
    [Write, Description("")] String alertTacticsColumnName;
    [Write, Description(""), EmbeddedInstance("MSFT_SentinelAlertRuleAlertDetailsOverrideAlertDynamicProperty")] String alertDynamicProperties;
};

[ClassVersion("1.0.0")]
class MSFT_SentinelAlertRuleAlertDetailsOverrideAlertDynamicProperty
{
    [Write, Description("")] String alertProperty;
    [Write, Description("")] String alertPropertyValue;
};

[ClassVersion("1.0.0")]
class MSFT_SentinelAlertRuleIncidentConfiguration
{
    [Write, Description("")] Boolean createIncident;
    [Write, Description(""), EmbeddedInstance("MSFT_SentinelAlertRuleIncidentConfigurationGroupingConfiguration")] String groupingConfiguration;
};

[ClassVersion("1.0.0")]
class MSFT_SentinelAlertRuleIncidentConfigurationGroupingConfiguration
{
    [Write, Description("")] Boolean enabled;
    [Write, Description(""), EmbeddedInstance("MSFT_SentinelAlertRuleIncidentConfigurationGroupingConfigurationAlertDetail")] groupByAlertDetails[];
    [Write, Description("")] String groupByCustomDetails[];
    [Write, Description("")] String groupByEntities[];
    [Write, Description("")] String lookbackDuration;
    [Write, Description("")] String matchingMethod;
    [Write, Description("")] Boolean reopenClosedIncident;
};

[ClassVersion("1.0.0")]
class MSFT_SentinelAlertRuleIncidentConfigurationGroupingConfigurationAlertDetail
{
    [Write, Description("")] String DisplayName;
    [Write, Description("")] String Severity;
};

[ClassVersion("1.0.0.0"), FriendlyName("ResourceName")]
class MSFT_ResourceName : OMI_BaseResource
{
    [Key, Description("The display name of the indicator")] String DisplayName;
    [Write, Description("The name of the resource group. The name is case insensitive.")] String SubscriptionId;
    [Write, Description("The name of the resource group. The name is case insensitive.")] String ResourceGroupName;
    [Write, Description("The name of the workspace.")] String WorkspaceName;
    [Write, Description("The unique id of the indicator.")] String Id;
    [Write, Description("The name of the workspace.")] String Description;
    [Write, Description("")] String ProductFilter;
    [Write, Description("")] Boolean Enabled;
    [Write, Description("")] String Severity;
    [Write, Description("")] String Tactics[];
    [Write, Description("")] String Techniques[];
    [Write, Description("")] String Query;
    [Write, Description("")] String QueryFrequency;
    [Write, Description("")] String QueryPeriod;
    [Write, Description("")] String TriggerOperator;
    [Write, Description("")] UInt32 TriggerThreshold;
    [Write, Description("")] String SuppressionDuration;
    [Write, Description("")] String SuppresionEnabled;
    [Write, Description("")] String AlertRuleTemplateName;
    [Write, Description("")] String DisplayNamesExcludeFilter[];
    [Write, Description("")] String DisplayNamesFilter[];
    [Write, Description("")] String SeveritiesFilter[];
    [Write, Description(""), EmbeddedInstance("MSFT_SentinelAlertRuleEventGroupSettings")] String EventGroupSettings;
    [Write, Description(""), EmbeddedInstance("MSFT_SentinelAlertRuleCustomDetails")] String CustomDetails;
    [Write, Description(""), EmbeddedInstance("MSFT_SentinelAlertRuleEntityMapping")] String EntityMappings[];
    [Write, Description(""), EmbeddedInstance("MSFT_SentinelAlertRuleAlertDetailsOverride")] String AlertDetailsOverride;
    [Write, Description(""), EmbeddedInstance("MSFT_SentinelAlertRuleIncidentConfiguration")] String IncidentConfiguration;

    [Write, Description("Present ensures the instance exists, absent ensures it is removed."), ValueMap{"Absent","Present"}, Values{"Absent","Present"}] string Ensure;
    [Write, Description("Credentials of the workload's Admin"), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Id of the Azure Active Directory tenant used for authentication.")] String TenantId;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Managed ID being used for authentication.")] Boolean ManagedIdentity;
    [Write, Description("Access token used for authentication.")] String AccessTokens[];
};
