[ClassVersion("1.0.0.0"), FriendlyName("IntuneRoleDefinition")]
class MSFT_IntuneRoleDefinition : OMI_BaseResource
{
    [Write, Description("The unique idenfier for an entity. Read-only.")] String Id;
    [Write, Description("Description of the Role definition.")] String Description;
    [Key, Description("Display Name of the Role definition.")] String DisplayName;
    [Write, Description("Type of Role. Set to True if it is built-in, or set to False if it is a custom role definition.")] Boolean IsBuiltIn;
    [Write, Description("List of allowed resource actions")] String allowedResourceActions[];
    [Write, Description("List of not allowed resource actions")] String notAllowedResourceActions[];
    [Write, Description("Id of the Scope Tags to assign")] String roleScopeTagIds[];
    [Write, Description("Present ensures the Role exists, absent ensures it is removed."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] string Ensure;
    [Write, Description("Credentials of the Intune Admin"), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Id of the Azure Active Directory tenant used for authentication.")] String TenantId;
    [Write, Description("Secret of the Azure Active Directory tenant used for authentication."), EmbeddedInstance("MSFT_Credential")] String ApplicationSecret;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Managed ID being used for authentication.")] Boolean ManagedIdentity;
    [Write, Description("Access token used for authentication.")] String AccessTokens[];
};
