[ClassVersion("1.0.0.0"), FriendlyName("ADOSecurityPolicy")]
class MSFT_ADOSecurityPolicy : OMI_BaseResource
{
    [Key, Description("The name of the Azure DevOPS Organization.")] String OrganizationName;
    [Write, Description("Controls the external guest access.")] Boolean DisallowAadGuestUserAccess;
    [Write, Description("Controls the Third-party application access via OAuth.")] Boolean DisallowOAuthAuthentication;
    [Write, Description("Controls SSH Authentication.")] Boolean DisallowSecureShell;
    [Write, Description("Controls Log Audit Events.")] Boolean LogAuditEvents;
    [Write, Description("Controls the Allow public projects setting.")] Boolean AllowAnonymousAccess;
    [Write, Description("Controls the Additional protections when using public package registries setting.")] Boolean ArtifactsExternalPackageProtectionToken;
    [Write, Description("Controls the Enable IP Conditional Access policy validation setting.")] Boolean EnforceAADConditionalAccess;
    [Write, Description("Controls the Allow team and project administrators to invite new user setting.")] Boolean AllowTeamAdminsInvitationsAccessToken;
    [Write, Description("Controls the Request access setting.")] Boolean AllowRequestAccessToken;
    [Write, Description("Credentials of the workload's Admin"), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Id of the Azure Active Directory tenant used for authentication.")] String TenantId;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Managed ID being used for authentication.")] Boolean ManagedIdentity;
    [Write, Description("Access token used for authentication.")] String AccessTokens[];
};
