[ClassVersion("1.0.0.0"), FriendlyName("IntuneDeviceConfigurationPolicyiOS")]
class MSFT_IntuneDeviceConfigurationPolicyiOS : OMI_BaseResource
{
    [Key, Description("Display name of the device configuration policy for iOS.")] String DisplayName;
    [Write, Description("Description of the device configuration policy for iOS.")] String Description;
    [Write, Description("N/A")] Boolean AccountBlockModification;
    [Write, Description("N/A")] Boolean ActivationLockAllowWhenSupervised;
    [Write, Description("N/A")] Boolean AirDropBlocked;
    [Write, Description("N/A")] Boolean AirDropForceUnmanagedDropTarget;
    [Write, Description("N/A")] Boolean AirPlayForcePairingPasswordForOutgoingRequests;
    [Write, Description("N/A")] Boolean AppleWatchBlockPairing;
    [Write, Description("N/A")] Boolean AppleWatchForceWristDetection;
    [Write, Description("N/A")] Boolean AppleNewsBlocked;
    [Write, Description("N/A")] String AppsVisibilityList[];
    [Write, Description("N/A")] String AppsVisibilityListType;
    [Write, Description("N/A")] Boolean AppStoreBlockAutomaticDownloads;
    [Write, Description("N/A")] Boolean AppStoreBlocked;
    [Write, Description("N/A")] Boolean AppStoreBlockInAppPurchases;
    [Write, Description("N/A")] Boolean AppStoreBlockUIAppInstallation;
    [Write, Description("N/A")] Boolean AppStoreRequirePassword;
    [Write, Description("N/A")] Boolean BluetoothBlockModification;
    [Write, Description("N/A")] Boolean CameraBlocked;
    [Write, Description("N/A")] Boolean CellularBlockDataRoaming;
    [Write, Description("N/A")] Boolean CellularBlockGlobalBackgroundFetchWhileRoaming;
    [Write, Description("N/A")] Boolean CellularBlockPerAppDataModification;
    [Write, Description("N/A")] Boolean CellularBlockVoiceRoaming;
    [Write, Description("N/A")] Boolean CertificatesBlockUntrustedTlsCertificates;
    [Write, Description("N/A")] Boolean ClassroomAppBlockRemoteScreenObservation;
    [Write, Description("N/A")] String CompliantAppsList[];
    [Write, Description("N/A")] String CompliantAppListType;
    [Write, Description("N/A")] Boolean ConfigurationProfileBlockChanges;
    [Write, Description("N/A")] Boolean DefinitionLookupBlocked;
    [Write, Description("N/A")] Boolean DeviceBlockEnableRestrictions;
    [Write, Description("N/A")] Boolean DeviceBlockEraseContentAndSettings;
    [Write, Description("N/A")] Boolean DeviceBlockNameModification;
    [Write, Description("N/A")] Boolean DiagnosticDataBlockSubmission;
    [Write, Description("N/A")] Boolean DiagnosticDataBlockSubmissionModification;
    [Write, Description("N/A")] Boolean DocumentsBlockManagedDocumentsInUnmanagedApps;
    [Write, Description("N/A")] Boolean DocumentsBlockUnmanagedDocumentsInManagedApps;
    [Write, Description("N/A")] String EmailInDomainSuffixes[];
    [Write, Description("N/A")] Boolean EnterpriseAppBlockTrust;
    [Write, Description("N/A")] Boolean EnterpriseAppBlockTrustModification;
    [Write, Description("N/A")] Boolean FaceTimeBlocked;
    [Write, Description("N/A")] Boolean FindMyFriendsBlocked;
    [Write, Description("N/A")] Boolean GamingBlockGameCenterFriends;
    [Write, Description("N/A")] Boolean GamingBlockMultiplayer;
    [Write, Description("N/A")] Boolean GameCenterBlocked;
    [Write, Description("N/A")] Boolean HostPairingBlocked;
    [Write, Description("N/A")] Boolean iBooksStoreBlocked;
    [Write, Description("N/A")] Boolean iBooksStoreBlockErotica;
    [Write, Description("N/A")] Boolean iCloudBlockActivityContinuation;
    [Write, Description("N/A")] Boolean iCloudBlockBackup;
    [Write, Description("N/A")] Boolean iCloudBlockDocumentSync;
    [Write, Description("N/A")] Boolean iCloudBlockManagedAppsSync;
    [Write, Description("N/A")] Boolean iCloudBlockPhotoLibrary;
    [Write, Description("N/A")] Boolean iCloudBlockPhotoStreamSync;
    [Write, Description("N/A")] Boolean iCloudBlockSharedPhotoStream;
    [Write, Description("N/A")] Boolean iCloudRequireEncryptedBackup;
    [Write, Description("N/A")] Boolean iTunesBlockExplicitContent;
    [Write, Description("N/A")] Boolean iTunesBlockMusicService;
    [Write, Description("N/A")] Boolean iTunesBlockRadio;
    [Write, Description("N/A")] Boolean KeyboardBlockAutoCorrect;
    [Write, Description("N/A")] Boolean KeyboardBlockPredictive;
    [Write, Description("N/A")] Boolean KeyboardBlockShortcuts;
    [Write, Description("N/A")] Boolean KeyboardBlockSpellCheck;
    [Write, Description("N/A")] Boolean KioskModeAllowAssistiveSpeak;
    [Write, Description("N/A")] Boolean KioskModeAllowAssistiveTouchSettings;
    [Write, Description("N/A")] Boolean KioskModeAllowAutoLock;
    [Write, Description("N/A")] Boolean KioskModeAllowColorInversionSettings;
    [Write, Description("N/A")] Boolean KioskModeAllowRingerSwitch;
    [Write, Description("N/A")] Boolean KioskModeAllowScreenRotation;
    [Write, Description("N/A")] Boolean KioskModeAllowSleepButton;
    [Write, Description("N/A")] Boolean KioskModeAllowTouchscreen;
    [Write, Description("N/A")] Boolean KioskModeAllowVoiceOverSettings;
    [Write, Description("N/A")] Boolean KioskModeAllowVolumeButtons;
    [Write, Description("N/A")] Boolean KioskModeAllowZoomSettings;
    [Write, Description("N/A")] Boolean KioskModeAppStoreUrl;
    [Write, Description("N/A")] Boolean KioskModeRequireAssistiveTouch;
    [Write, Description("N/A")] Boolean KioskModeRequireColorInversion;
    [Write, Description("N/A")] Boolean KioskModeRequireMonoAudio;
    [Write, Description("N/A")] Boolean KioskModeRequireVoiceOver;
    [Write, Description("N/A")] Boolean KioskModeRequireZoom;
    [Write, Description("N/A")] Boolean KioskModeManagedAppId;
    [Write, Description("N/A")] Boolean LockScreenBlockControlCenter;
    [Write, Description("N/A")] Boolean LockScreenBlockNotificationView;
    [Write, Description("N/A")] Boolean LockScreenBlockPassbook;
    [Write, Description("N/A")] Boolean LockScreenBlockTodayView;
    [Write, Description("N/A")] String MediaContentRatingAustralia;
    [Write, Description("N/A")] String MediaContentRatingCanada;
    [Write, Description("N/A")] String MediaContentRatingFrance;
    [Write, Description("N/A")] String MediaContentRatingGermany;
    [Write, Description("N/A")] String MediaContentRatingIreland;
    [Write, Description("N/A")] String MediaContentRatingJapan;
    [Write, Description("N/A")] String MediaContentRatingNewZealand;
    [Write, Description("N/A")] String MediaContentRatingUnitedKingdom;
    [Write, Description("N/A")] String MediaContentRatingUnitedStates;
    [Write, Description("N/A")] String MediaContentRatingApps;
    [Write, Description("N/A")] Boolean messagesBlocked;
    [Write, Description("N/A")] Boolean NotificationsBlockSettingsModification;
    [Write, Description("N/A")] Boolean PasscodeBlockFingerprintUnlock;
    [Write, Description("N/A")] Boolean PasscodeBlockModification;
    [Write, Description("N/A")] Boolean PasscodeBlockSimple;
    [Write, Description("N/A")] String PasscodeExpirationDays;
    [Write, Description("N/A")] UInt32 PasscodeMinimumLength;
    [Write, Description("N/A")] String PasscodeMinutesOfInactivityBeforeLock;
    [Write, Description("N/A")] String PasscodeMinutesOfInactivityBeforeScreenTimeout;
    [Write, Description("N/A")] String PasscodeMinimumCharacterSetCount;
    [Write, Description("N/A")] String PasscodePreviousPasscodeBlockCount;
    [Write, Description("N/A")] String PasscodeSignInFailureCountBeforeWipe;
    [Write, Description("N/A")] String PasscodeRequiredType;
    [Write, Description("N/A")] Boolean PasscodeRequired;
    [Write, Description("N/A")] Boolean PodcastsBlocked;
    [Write, Description("N/A")] Boolean SafariBlockAutofill;
    [Write, Description("N/A")] Boolean SafariBlockJavaScript;
    [Write, Description("N/A")] Boolean SafariBlockPopups;
    [Write, Description("N/A")] Boolean SafariBlocked;
    [Write, Description("N/A")] String SafariCookieSettings;
    [Write, Description("N/A")] String SafariManagedDomains[];
    [Write, Description("N/A")] String SafariPasswordAutoFillDomains[];
    [Write, Description("N/A")] Boolean SafariRequireFraudWarning;
    [Write, Description("N/A")] Boolean ScreenCaptureBlocked;
    [Write, Description("N/A")] Boolean SiriBlocked;
    [Write, Description("N/A")] Boolean SiriBlockedWhenLocked;
    [Write, Description("N/A")] Boolean SiriBlockUserGeneratedContent;
    [Write, Description("N/A")] Boolean SiriRequireProfanityFilter;
    [Write, Description("N/A")] Boolean SpotlightBlockInternetResults;
    [Write, Description("N/A")] Boolean VoiceDialingBlocked;
    [Write, Description("N/A")] Boolean WallpaperBlockModification;
    [Write, Description("Present ensures the policy exists, absent ensures it is removed."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] string Ensure;
    [Required, Description("Credentials of the Intune Admin"), EmbeddedInstance("MSFT_Credential")] String GlobalAdminAccount;
};
