[ClassVersion("1.0.0.0"), FriendlyName("SPOHubSite")]
class MSFT_SPOHubSite : OMI_BaseResource
{
    [Key, Description("The URL of the site collection")] string Url;
    [Write, Description("The title of the hub site")] string Title;
    [Write, Description("The description of the hub site")] string Description;
    [Write, Description("The url to the logo of the hub site")] string LogoUrl;
    [Write, Description("Does the hub site require approval to join")] boolean RequiresJoinApproval;
    [Write, Description("The users or mail-enabled security groups which are allowed to associate their site with a hub site")] string AllowedToJoin[];
    [Write, Description("The guid of the site design to link to the hub site")] string SiteDesignId;
    [Write, Description("Present ensures the site collection is registered as hub site, absent ensures it is unregistered"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] string Ensure;
    [Required, Description("Credentials of the SharePoint Global Admin"), EmbeddedInstance("MSFT_Credential")] string GlobalAdminAccount;
};

