FROM mcr.microsoft.com/dotnet/sdk:10.0-resolute

WORKDIR /DSC

SHELL ["bash", "-c"]

RUN apt-get update && apt-get install -y \
    build-essential \
    libssl-dev \
    zlib1g-dev \
    libbz2-dev \
    libreadline-dev \
    libsqlite3-dev \
    llvm \
    libncurses5-dev \
    libncursesw5-dev \
    xz-utils \
    tk-dev \
    libffi-dev \
    liblzma-dev \
    python3-openssl \
    && rm -rf /var/lib/apt/lists/*

# Install Python3.11
RUN curl https://pyenv.run | bash
ENV PATH="/root/.pyenv/bin:/root/.pyenv/shims:${PATH}"
RUN pyenv install "3.11.9"

RUN wget -q https://github.com/microsoft/omi/releases/download/v1.9.1-0/omi-1.9.1-0.ssl_300.ulinux.s.x64.deb && \
    dpkg -i ./omi-1.9.1-0.ssl_300.ulinux.s.x64.deb && \
    rm ./omi-1.9.1-0.ssl_300.ulinux.s.x64.deb && \
    cp /opt/omi/lib/libmi.so /usr/share/powershell/.store/powershell.linux.x64/7.6.2/powershell.linux.x64/7.6.2/tools/net10.0/any/runtimes/linux-x64/native/

RUN wget -q https://github.com/microsoft/PowerShell-DSC-for-Linux/releases/download/v1.2.4-0/dsc-1.2.4-0.ssl_110.x64.deb && \
    dpkg -i ./dsc-1.2.4-0.ssl_110.x64.deb && \
    rm ./dsc-1.2.4-0.ssl_110.x64.deb

RUN mv /etc/opt/omi/conf/dsc/configuration/baseregistration /etc/opt/omi/conf/dsc/configuration/BaseRegistration && \
    mv /etc/opt/omi/conf/dsc/configuration/BaseRegistration/baseresource.schema.mof /etc/opt/omi/conf/dsc/configuration/BaseRegistration/BaseResource.schema.mof

COPY . .

RUN pwsh -Command ./Utilities/Install-M365DSCAndDependencies.ps1 -IsSDK

ENTRYPOINT ["pwsh", "-NoLogo"]
