FROM mcr.microsoft.com/dotnet/sdk:10.0-windowsservercore-ltsc2025

WORKDIR /DSC

SHELL ["cmd", "/S", "/C"]

COPY . .
COPY ./Modules/Microsoft365DSC/Microsoft365DSC.psd1 /DSC/Microsoft365DSC.psd1

RUN powershell -Command .\Utilities\Install-M365DSCAndDependencies.ps1 -IsSDK

ENTRYPOINT ["pwsh", "-NoLogo"]
