FROM mcr.microsoft.com/dotnet/sdk:10.0-windowsservercore-ltsc2025

WORKDIR /DSC

SHELL ["powershell", "-NoLogo"]

COPY . .

RUN $null = Install-PackageProvider -Name "NuGet" -Force
RUN $null = Install-Module -Name "Microsoft.PowerShell.PSResourceGet" -Repository "PSGallery" -Scope "AllUsers" -Force -SkipPublisherCheck
RUN $null = Install-PSResource -Name "Pester" -Repository "PSGallery" -Scope "AllUsers" -SkipDependencyCheck -TrustRepository -AcceptLicense
RUN $null = Install-PSResource -Name "M365DSC.PSDesiredStateConfiguration" -Repository "PSGallery" -Scope "AllUsers" -SkipDependencyCheck -TrustRepository -AcceptLicense

RUN .\Utilities\Install-M365DSCAndDependencies.ps1 -IsSDK

ENTRYPOINT ["pwsh", "-NoLogo"]
