[ClassVersion("1.0.0.0"), FriendlyName("SPOSiteDesign")]
class MSFT_SPOSiteDesign : OMI_BaseResource
{
    [Key, Description("The title of the site design.")] string Title;
    [Write, Description("The names of the site design scripts.")] string SiteScriptNames[];
    [Write, Description("Web template to which the site design is applied to when invoked."), ValueMap{"CommunicationSite","TeamSite"}, Values{"CommunicationSite","TeamSite"}] string WebTemplate;
    [Write, Description("Description of site design.")] string Description;
    [Write, Description("Is site design applied by default to web templates.")] Boolean IsDefault;
    [Write, Description("Site design alternate preview image text.")] string PreviewImageAltText;
    [Write, Description("Site design preview image url.")] string PreviewImageUrl;
    [Write, Description("Site design version number.")] uint32 Version;
    [Write, Description("Used to add or remove site design."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Required, Description("Credentials of the Office365 Tenant Admin."), EmbeddedInstance("MSFT_Credential")] string GlobalAdminAccount;
};

