[ClassVersion("1.0.0.0"), FriendlyName("SPOSiteDesign")]
class MSFT_SPOSiteDesign : OMI_BaseResource
{
    [Key, Description("The title of the site design.")] string Title;
    [Write, Description("The names of the site design scripts.")] string SiteScriptNames[];
    [Write, Description("Web template to which the site design is applied to when invoked."), ValueMap{"CommunicationSite","TeamSite", "GrouplessTeamSite"}, Values{"CommunicationSite","TeamSite", "GrouplessTeamSite"}] string WebTemplate;
    [Write, Description("Description of site design.")] string Description;
    [Write, Description("Is site design applied by default to web templates.")] Boolean IsDefault;
    [Write, Description("Site design alternate preview image text.")] string PreviewImageAltText;
    [Write, Description("Site design preview image url.")] string PreviewImageUrl;
    [Write, Description("Site design version number.")] uint32 Version;
    [Write, Description("Used to add or remove site design."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Write, Description("Credentials of the Office365 Tenant Admin."), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Secret of the Azure Active Directory application to authenticate with."), EmbeddedInstance("MSFT_Credential")] String ApplicationSecret;
    [Write, Description("Name of the Azure Active Directory tenant used for authentication. Format contoso.onmicrosoft.com")] String TenantId;
    [Write, Description("Username can be made up to anything but password will be used for certificatePassword"), EmbeddedInstance("MSFT_Credential")] String CertificatePassword;
    [Write, Description("Path to certificate used in service principal usually a PFX file.")] String CertificatePath;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Managed ID being used for authentication.")] Boolean ManagedIdentity;
    [Write, Description("Access token used for authentication.")] String AccessTokens[];
};
