[ClassVersion("1.0.0.0"), FriendlyName("PPTenantSettings")]
class MSFT_PPTenantSettings : OMI_BaseResource
{
    [Key, Description("Should be set to yes"),ValueMap{"Yes"},Values{"Yes"}] string IsSingleInstance;
    [Write, Description("When using Copilot in Power Apps, allow users to submit feedback to Microsoft. Default value is false.")] Boolean DisableCopilotFeedback;
    [Write, Description("TBD")] Boolean DisableMakerMatch;
    [Write, Description("TBD")] Boolean DisableUnusedLicenseAssignment;
    [Write, Description("Allow people to use AI to generate an app based on an image. Default value is false.")] Boolean DisableCreateFromImage;
    [Write, Description("Gets or sets a value indicating whether non-admin users in the tenant can share connections with everyone. Default value is false.")] Boolean DisableConnectionSharingWithEveryone;
    [Write, Description("TBD")] Boolean AllowNewOrgChannelDefault;
    [Write, Description("Disables cloud flows copilot in Power Automate.

It doesn't control the ability to add AI-related connectors or actions in the flow designer. For example, the Skills connector or AI Builder creates text with a GPT action. Default value is false.")] Boolean DisableCopilot;
    [Write, Description("Disables the copilot-enhanced help feature within Power Automate to enhance answers on product documentation through Bing Search. Default value is false.")] Boolean DisableCopilotWithBing;
    [Write, Description("Disables the weekly admin digest email for Managed Environments. Default value is false.")] Boolean DisableAdminDigest;
    [Write, Description("Ignore the Teams group-preferred data location when provisioning a Teams environment. Default value is false.")] Boolean DisablePreferredDataLocationForTeamsEnvironment;
    [Write, Description("Restrict all developer environments to be created by tenant admins, Power Platform admins, or Dynamics 365 service admins. Default is false.")] Boolean DisableDeveloperEnvironmentCreationByNonAdminUsers;
    [Write, Description("TBD")] Boolean EnvironmentRoutingAllMakers;
    [Write, Description("Enables the Default Environment routing feature that creates personal, developer environments for new makers. Default value is false.")] Boolean EnableDefaultEnvironmentRouting;
    [Write, Description("When this setting is true, admins can view and manage desktop flow action groups in DLP policies in the Power Platform admin center. Default value is false.")] String EnableDesktopFlowDataPolicyManagement;
    [Write, Description("Allow users to collect telemetry data about their app in Azure Application Insights. Setting this to False blocks the transmission of this data.")] Boolean EnableCanvasAppInsights;
    [Write, Description("Allow people to create a canvas app based on a Figma file. Default value is false.")] Boolean DisableCreateFromFigma;

    [Write, Description("This is a legacy setting that is no longer used by the platform. Default value is false.")] Boolean DisableBillingPolicyCreationByNonAdminUsers;
    [Write, Description("This setting isn't currently used by the platform but might be used in the future.")] UInt32 StorageCapacityConsumptionWarningThreshold;
    [Write, Description("Ability to allow tenant, Power Platform, or Dynamics 365 admins to grant permissions to an environment administrator to view the Capacity summary tab. Default value is false.")] Boolean EnableTenantCapacityReportForEnvironmentAdmins;
    [Write, Description("Ability to allow tenant, Power Platform, or Dynamics 365 admins to grant permissions to an environment administrator to view the tenant-scoped license reports. Default value is false.")] Boolean EnableTenantLicensingReportForEnvironmentAdmins;
    [Write, Description("Ability to use unallocated AI Builder credits in environments without allocated credits. Default value is true.")] Boolean DisableUseOfUnassignedAIBuilderCredits;
    [Write, Description("TBD")] String EnableGenerativeAIFeaturesForSiteUsers;
    [Write, Description("TBD")] String EnableExternalAuthenticationProvidersInPowerPages;
    [Write, Description("This setting isn't currently used by the platform but might be used in the future.")] Boolean DisableChampionsInvitationReachout;
    [Write, Description("This setting isn't currently used by the platform but might be used in the future.")] Boolean DisableSkillsMatchInvitationReachout;
    [Write, Description("This setting isn't currently used by the platform but might be used in the future.")] Boolean EnableOpenAiBotPublishing;
    [Write, Description("TBD")] Boolean DisableAiPrompts;
    [Write, Description("When using Copilot in Power Apps, allow users to share their prompts, questions, and requests with Microsoft. Default value is true.")] Boolean DisableCopilotFeedbackMetadata;

    [Write, Description("Ability to allow Microsoft to read Power Automate Copilot AI feature customer data (inputs and outputs) and provide improved models. Default value is false.")] Boolean EnableModelDataSharing;
    [Write, Description("Ability to disable data logging and remove all data logged for Power Automate Copilot AI feature customer data (inputs and outputs). Default value is false.")] Boolean DisableDataLogging;
    [Write, Description("This setting is reserved for future use. No enforcement is driven by this setting at the current time.")] String PowerCatalogAudienceSetting;
    [Write, Description("TBD")] Boolean EnableDeleteDisabledUserinAllEnvironments;
    [Write, Description("TBD")] Boolean DisableHelpSupportCopilot;
    [Write, Description("TBD")] Boolean DisableSurveyScreenshots;
    [Write, Description("This is a legacy setting that is no longer used by the platform. Default value is false.")] boolean WalkMeOptOut;
    [Write, Description("TBD")] boolean useSupportBingSearchByAllUsers;
    [Write, Description("Ability to disable re-surveying users who left prior feedback via NPS prompts in Power Platform. Default value is false.")] boolean DisableNPSCommentsReachout;
    [Write, Description("Ability to disable the newsletter sendout feature. Default value is false.")] boolean DisableNewsletterSendout;
    [Write, Description("Restrict all environments to be created by tenant admins, Power Platform admins, or Dynamics 365 service admins. Default value is false.")] boolean DisableEnvironmentCreationByNonAdminUsers;
    [Write, Description("Restrict all portals to be created by tenant admins, Power Platform admins, or Dynamics 365 service admins. Default value is false.")] boolean DisablePortalsCreationByNonAdminUsers;
    [Write, Description("Ability to disable all NPS survey feedback prompts in Power Platform. Default value is false.")] boolean DisableSurveyFeedback;
    [Write, Description("Restrict all trial environments to be created by tenant admins, Power Platform admins, or Dynamics 365 service admins. Default value is false.")] boolean DisableTrialEnvironmentCreationByNonAdminUsers;
    [Write, Description("Ability to disable capacity allocation by environment administrators. Default value is false.")] boolean DisableCapacityAllocationByEnvironmentAdmins;
    [Write, Description("Allows users, who already have access to the Help + Support page in Power Platform admin center, to see support requests created by other users in the tenant. Default value is True, which means this feature is turned off by default.")] boolean DisableSupportTicketsVisibleByAllUsers;
    [Write, Description("When this setting is true, users in the environment can see a message that indicates Microsoft Learn and documentation search categories have been turned off by the administrator. Default value is false.")] boolean DisableDocsSearch;
    [Write, Description("When this setting is true, users in the environment can see a message that indicates community and blog search categories have been turned off by the administrator. Default value is false.")] boolean DisableCommunitySearch;
    [Write, Description("When this setting is true, users in the environment can see a message that indicates video search categories have been turned off by the administrator. Default value is false.")] boolean DisableBingVideoSearch;
    [Write, Description("	Ability to turn off the Share with Everyone capability for nonadmin users in all Power Apps. Default value is true.")] boolean DisableShareWithEveryone;
    [Write, Description("When set to true this will enable the ability for guests in your tenant to create Power Platform resources.")] boolean EnableGuestsToMake;
    [Write, Description("Maximum value setting for the number of users in a security group used to share an app built using Power Apps on Microsoft Teams. Default value is 10000 but can be increased or decreased, as required.")] uint32 ShareWithColleaguesUserLimit;
    [Write, Description("Credentials of the Power Platform Admin"), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Id of the Azure Active Directory tenant used for authentication.")] String TenantId;
    [Write, Description("Secret of the Azure Active Directory tenant used for authentication."), EmbeddedInstance("MSFT_Credential")] String ApplicationSecret;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
};
