[ClassVersion("1.0.0.0"), FriendlyName("PPTenantSettings")]
class MSFT_PPTenantSettings : OMI_BaseResource
{
    [Key, Description("Should be set to yes"),ValueMap{"Yes"},Values{"Yes"}] string IsSingleInstance;
    [Write, Description("TBD")] Boolean DisableCopilotFeedback;
    [Write, Description("TBD")] Boolean DisableMakerMatch;
    [Write, Description("TBD")] Boolean DisableUnusedLicenseAssignment;
    [Write, Description("TBD")] Boolean DisableCreateFromImage;
    [Write, Description("TBD")] Boolean DisableConnectionSharingWithEveryone;
    [Write, Description("TBD")] Boolean AllowNewOrgChannelDefault;
    [Write, Description("TBD")] Boolean DisableCopilot;
    [Write, Description("TBD")] Boolean DisableCopilotWithBing;
    [Write, Description("TBD")] Boolean DisableAdminDigest;
    [Write, Description("TBD")] Boolean DisablePreferredDataLocationForTeamsEnvironment;
    [Write, Description("TBD")] Boolean DisableDeveloperEnvironmentCreationByNonAdminUsers;
    [Write, Description("TBD")] Boolean EnvironmentRoutingAllMakers;
    [Write, Description("TBD")] Boolean EnableDefaultEnvironmentRouting;
    [Write, Description("TBD")] String EnableDesktopFlowDataPolicyManagement;
    [Write, Description("TBD")] Boolean EnableCanvasAppInsights;
    [Write, Description("TBD")] Boolean DisableCreateFromFigma;

    [Write, Description("TBD")] Boolean DisableBillingPolicyCreationByNonAdminUsers;
    [Write, Description("TBD")] UInt32 StorageCapacityConsumptionWarningThreshold;
    [Write, Description("TBD")] Boolean EnableTenantCapacityReportForEnvironmentAdmins;
    [Write, Description("TBD")] Boolean EnableTenantLicensingReportForEnvironmentAdmins;
    [Write, Description("TBD")] Boolean DisableUseOfUnassignedAIBuilderCredits;
    [Write, Description("TBD")] String EnableGenerativeAIFeaturesForSiteUsers;
    [Write, Description("TBD")] String EnableExternalAuthenticationProvidersInPowerPages;
    [Write, Description("TBD")] Boolean DisableChampionsInvitationReachout;
    [Write, Description("TBD")] Boolean DisableSkillsMatchInvitationReachout;
    [Write, Description("TBD")] Boolean EnableOpenAiBotPublishing;
    [Write, Description("TBD")] Boolean DisableAiPrompts;
    [Write, Description("TBD")] Boolean DisableCopilotFeedbackMetadata;

    [Write, Description("TBD")] Boolean EnableModelDataSharing;
    [Write, Description("TBD")] Boolean DisableDataLogging;
    [Write, Description("TBD")] String PowerCatalogAudienceSetting;
    [Write, Description("TBD")] Boolean EnableDeleteDisabledUserinAllEnvironments;
    [Write, Description("TBD")] Boolean DisableHelpSupportCopilot;
    [Write, Description("TBD")] Boolean DisableSurveyScreenshots;
    [Write, Description("When set to true this will disable the Walk Me guidance.")] boolean WalkMeOptOut;
    [Write, Description("When set to true this will disable the NPS Comments Reachout.")] boolean DisableNPSCommentsReachout;
    [Write, Description("When set to true this will disable the monthly newsletters.")] boolean DisableNewsletterSendout;
    [Write, Description("When set to true this will disable production environment creation by non-admin users.")] boolean DisableEnvironmentCreationByNonAdminUsers;
    [Write, Description("When set to true this will disable portal creation by non-admin users.")] boolean DisablePortalsCreationByNonAdminUsers;
    [Write, Description("When set to true this will disable survey feedback that sometimes pops up on top of an app.")] boolean DisableSurveyFeedback;
    [Write, Description("When set to true this will disable trial environment creation by non-admin users.")] boolean DisableTrialEnvironmentCreationByNonAdminUsers;
    [Write, Description("When set to true this will disable capacity allocation by environment admins.")] boolean DisableCapacityAllocationByEnvironmentAdmins;
    [Write, Description("When set to true this will disable support tickets to be visible by all users.")] boolean DisableSupportTicketsVisibleByAllUsers;
    [Write, Description("When set to true this will disable docs search in the Office 365 Suite navigation bar.")] boolean DisableDocsSearch;
    [Write, Description("When set to true this will disable community search in the Office 365 Suite navigation bar.")] boolean DisableCommunitySearch;
    [Write, Description("When set to true this will disable Bing video search in the Office 365 Suite navigation bar.")] boolean DisableBingVideoSearch;
    [Write, Description("When set to true this will disable the ability to share apps with the whole tenant.")] boolean DisableShareWithEveryone;
    [Write, Description("When set to true this will enable the ability for guests in your tenant to create Power Platform resources.")] boolean EnableGuestsToMake;
    [Write, Description("The amount of people an app can be shared with in Dataverse for Teams (maximum is 10,000).")] uint32 ShareWithColleaguesUserLimit;
    [Write, Description("Credentials of the Power Platform Admin"), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Id of the Azure Active Directory tenant used for authentication.")] String TenantId;
    [Write, Description("Secret of the Azure Active Directory tenant used for authentication."), EmbeddedInstance("MSFT_Credential")] String ApplicationSecret;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
};
