[ClassVersion("1.0.0")]
class MSFT_ADOPermission
{
    [Write, Description("")] String NamespaceId;
    [Write, Description("")] String DisplayName;
    [Write, Description("")] UInt32 Bit;
    [Write, Description("")] String Token;
};

[ClassVersion("1.0.0.0"), FriendlyName("ADOPermissionGroupSettings")]
class MSFT_ADOPermissionGroupSettings : OMI_BaseResource
{
    [Key, Description("")] String GroupName;
    [Write, Description("")] String OrganizationName;
    [Write, Description("")] String Descriptor;
    [Write, Description(""), EmbeddedInstance("MSFT_ADOPermission")] string AllowPermissions[];
    [Write, Description(""), EmbeddedInstance("MSFT_ADOPermission")] string DenyPermissions[];

    [Write, Description("Credentials of the workload's Admin"), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Id of the Azure Active Directory tenant used for authentication.")] String TenantId;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Managed ID being used for authentication.")] Boolean ManagedIdentity;
    [Write, Description("Access token used for authentication.")] String AccessTokens[];
};
