[ClassVersion("1.0.0.0"), FriendlyName("TeamsGuestMessagingConfiguration")]
class MSFT_TeamsGuestMessagingConfiguration : OMI_BaseResource
{
    [Key, Description("The only valid input is Global - the tenant wide configuration"), ValueMap{"Global"}, Values{"Global"}] string Identity;
    [Write, Description("Determines if a user is allowed to edit their own messages.")] Boolean AllowUserEditMessage;
    [Write, Description("Determines if a user is allowed to delete their own messages.")] Boolean AllowUserDeleteMessage;
    [Write, Description("Determines if a user is allowed to chat.")] Boolean AllowUserChat;
    [Write, Description("Turn this setting on to allow users to permanently delete their one-on-one chat, group chat, and meeting chat as participants (this deletes the chat only for them, not other users in the chat).")] Boolean AllowUserDeleteChat;
    [Write, Description("Determines Giphy content restrictions. Default value is Moderate, other options are Strict and NoRestriction."), ValueMap{"Moderate","Strict","NoRestriction"}, Values{"Moderate","Strict","NoRestriction"}] String GiphyRatingType;
    [Write, Description("Determines if memes are available for use.")] Boolean AllowMemes;
    [Write, Description("Determines if stickers are available for use.")] Boolean AllowStickers;
    [Write, Description("Determines if Giphy are available for use.")] Boolean AllowGiphy;
    [Write, Description("Determines if Immersive Reader is enabled.")] Boolean AllowImmersiveReader;
    [Write, Description("Credentials of the Teams Admin"), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Name of the Azure Active Directory tenant used for authentication. Format contoso.onmicrosoft.com")] String TenantId;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Managed ID being used for authentication.")] Boolean ManagedIdentity;
    [Write, Description("Access token used for authentication.")] String AccessTokens[];
};
