[ClassVersion("1.0.0.0"), FriendlyName("IntuneDeviceConfigurationPolicyWindows")]
class MSFT_IntuneDeviceConfigurationPolicyWindows : OMI_BaseResource
{
    [Key, Description("Display name of the device configuration policy for Windows 10.")] String description; 
    [Write, Description("Description of the device configuration policy for Windows 10.")] String displayName; 
    [Write, Description("N/A")] String enterpriseCloudPrintDiscoveryEndPoint; 
    [Write, Description("N/A")] String enterpriseCloudPrintOAuthAuthority; 
    [Write, Description("N/A")] String enterpriseCloudPrintOAuthClientIdentifier; 
    [Write, Description("N/A")] String enterpriseCloudPrintResourceIdentifier; 
    [Write, Description("N/A")] String enterpriseCloudPrintDiscoveryMaxLimit; 
    [Write, Description("N/A")] String enterpriseCloudPrintMopriaDiscoveryResourceIdentifier; 
    [Write, Description("N/A")] Boolean searchBlockDiacritics; 
    [Write, Description("N/A")] Boolean searchDisableAutoLanguageDetection; 
    [Write, Description("N/A")] Boolean searchDisableIndexingEncryptedItems; 
    [Write, Description("N/A")] Boolean searchEnableRemoteQueries; 
    [Write, Description("N/A")] String searchDisableIndexerBackoff; 
    [Write, Description("N/A")] Boolean searchDisableIndexingRemovableDrive; 
    [Write, Description("N/A")] String searchEnableAutomaticIndexSizeManangement; 
    [Write, Description("N/A")] Boolean diagnosticsDataSubmissionMode; 
    [Write, Description("N/A")] Boolean oneDriveDisableFileSync; 
    [Write, Description("N/A")] Boolean smartScreenEnableAppInstallControl; 
    [Write, Description("N/A")] String personalizationDesktopImageUrl; 
    [Write, Description("N/A")] String personalizationLockScreenImageUrl; 
    [Write, Description("N/A")] String bluetoothAllowedServices; 
    [Write, Description("N/A")] Boolean bluetoothBlockAdvertising; 
    [Write, Description("N/A")] Boolean bluetoothBlockDiscoverableMode; 
    [Write, Description("N/A")] Boolean bluetoothBlockPrePairing; 
    [Write, Description("N/A")] Boolean edgeBlockAutofill; 
    [Write, Description("N/A")] String edgeBlocked; 
    [Write, Description("N/A")] Boolean edgeCookiePolicy; 
    [Write, Description("N/A")] Boolean edgeBlockDeveloperTools; 
    [Write, Description("N/A")] Boolean edgeBlockSendingDoNotTrackHeader; 
    [Write, Description("N/A")] Boolean edgeBlockExtensions; 
    [Write, Description("N/A")] Boolean edgeBlockInPrivateBrowsing; 
    [Write, Description("N/A")] Boolean edgeBlockJavaScript; 
    [Write, Description("N/A")] Boolean edgeBlockPasswordManager; 
    [Write, Description("N/A")] Boolean edgeBlockAddressBarDropdown; 
    [Write, Description("N/A")] Boolean edgeBlockCompatibilityList; 
    [Write, Description("N/A")] Boolean edgeClearBrowsingDataOnExit; 
    [Write, Description("N/A")] Boolean edgeAllowStartPagesModification; 
    [Write, Description("N/A")] Boolean edgeDisableFirstRunPage; 
    [Write, Description("N/A")] Boolean edgeBlockLiveTileDataCollection; 
    [Write, Description("N/A")] Boolean edgeSyncFavoritesWithInternetExplorer; 
    [Write, Description("N/A")] Boolean cellularBlockDataWhenRoaming; 
    [Write, Description("N/A")] Boolean cellularBlockVpn; 
    [Write, Description("N/A")] Boolean cellularBlockVpnWhenRoaming; 
    [Write, Description("N/A")] Boolean defenderRequireRealTimeMonitoring; 
    [Write, Description("N/A")] Boolean defenderRequireBehaviorMonitoring; 
    [Write, Description("N/A")] Boolean defenderRequireNetworkInspectionSystem; 
    [Write, Description("N/A")] Boolean defenderScanDownloads; 
    [Write, Description("N/A")] Boolean defenderScanScriptsLoadedInInternetExplorer; 
    [Write, Description("N/A")] Boolean defenderBlockEndUserAccess; 
    [Write, Description("N/A")] Uint64 defenderSignatureUpdateIntervalInHours; 
    [Write, Description("N/A")] String defenderMonitorFileActivity; 
    [Write, Description("N/A")] Uint64 defenderDaysBeforeDeletingQuarantinedMalware; 
    [Write, Description("N/A")] Uint64 defenderScanMaxCpu; 
    [Write, Description("N/A")] Boolean defenderScanArchiveFiles; 
    [Write, Description("N/A")] Boolean defenderScanIncomingMail; 
    [Write, Description("N/A")] Boolean defenderScanRemovableDrivesDuringFullScan; 
    [Write, Description("N/A")] Boolean defenderScanMappedNetworkDrivesDuringFullScan; 
    [Write, Description("N/A")] Boolean defenderScanNetworkFiles; 
    [Write, Description("N/A")] Boolean defenderRequireCloudProtection; 
    [Write, Description("N/A")] String defenderCloudBlockLevel; 
    [Write, Description("N/A")] String defenderPromptForSampleSubmission; 
    [Write, Description("N/A")] String defenderScheduledQuickScanTime; 
    [Write, Description("N/A")] String defenderScanType; 
    [Write, Description("N/A")] String defenderSystemScanSchedule; 
    [Write, Description("N/A")] String defenderScheduledScanTime; 
    [Write, Description("N/A")] String defenderDetectedMalwareActions; 
    [Write, Description("N/A")] String defenderFileExtensionsToExclude; 
    [Write, Description("N/A")] String defenderFilesAndFoldersToExclude; 
    [Write, Description("N/A")] Boolean defenderProcessesToExclude; 
    [Write, Description("N/A")] Boolean lockScreenAllowTimeoutConfiguration; 
    [Write, Description("N/A")] Boolean lockScreenBlockActionCenterNotifications; 
    [Write, Description("N/A")] Boolean lockScreenBlockCortana; 
    [Write, Description("N/A")] Boolean lockScreenBlockToastNotifications; 
    [Write, Description("N/A")] Uint64 lockScreenTimeoutInSeconds; 
    [Write, Description("N/A")] Boolean passwordBlockSimple; 
    [Write, Description("N/A")] Uint64 passwordExpirationDays; 
    [Write, Description("N/A")] Uint64 passwordMinimumLength; 
    [Write, Description("N/A")] Uint64 passwordMinutesOfInactivityBeforeScreenTimeout; 
    [Write, Description("N/A")] Uint64 passwordMinimumCharacterSetCount; 
    [Write, Description("N/A")] Uint64 passwordPreviousPasswordBlockCount; 
    [Write, Description("N/A")] Boolean passwordRequired; 
    [Write, Description("N/A")] Boolean passwordRequireWhenResumeFromIdleState; 
    [Write, Description("N/A")] String passwordRequiredType; 
    [Write, Description("N/A")] Uint64 passwordSignInFailureCountBeforeFactoryReset; 
    [Write, Description("N/A")] String privacyAdvertisingId; 
    [Write, Description("N/A")] Boolean privacyAutoAcceptPairingAndConsentPrompts; 
    [Write, Description("N/A")] Boolean privacyBlockInputPersonalization; 
    [Write, Description("N/A")] Boolean startBlockUnpinningAppsFromTaskbar; 
    [Write, Description("N/A")] Boolean startMenuAppListVisibility; 
    [Write, Description("N/A")] Boolean startMenuHideChangeAccountSettings; 
    [Write, Description("N/A")] Boolean startMenuHideFrequentlyUsedApps; 
    [Write, Description("N/A")] Boolean startMenuHideHibernate; 
    [Write, Description("N/A")] Boolean startMenuHideLock; 
    [Write, Description("N/A")] Boolean startMenuHidePowerButton; 
    [Write, Description("N/A")] Boolean startMenuHideRecentJumpLists; 
    [Write, Description("N/A")] Boolean startMenuHideRecentlyAddedApps; 
    [Write, Description("N/A")] Boolean startMenuHideRestartOptions; 
    [Write, Description("N/A")] Boolean startMenuHideShutDown; 
    [Write, Description("N/A")] Boolean startMenuHideSignOut; 
    [Write, Description("N/A")] Boolean startMenuHideSleep; 
    [Write, Description("N/A")] Boolean startMenuHideSwitchAccount; 
    [Write, Description("N/A")] Boolean startMenuHideUserTile; 
    [Write, Description("N/A")] Boolean startMenuLayoutEdgeAssetsXml; 
    [Write, Description("N/A")] Boolean startMenuLayoutXml; 
    [Write, Description("N/A")] String startMenuMode; 
    [Write, Description("N/A")] String startMenuPinnedFolderDocuments; 
    [Write, Description("N/A")] String startMenuPinnedFolderDownloads; 
    [Write, Description("N/A")] String startMenuPinnedFolderFileExplorer; 
    [Write, Description("N/A")] String startMenuPinnedFolderHomeGroup; 
    [Write, Description("N/A")] String startMenuPinnedFolderMusic; 
    [Write, Description("N/A")] String startMenuPinnedFolderNetwork; 
    [Write, Description("N/A")] String startMenuPinnedFolderPersonalFolder; 
    [Write, Description("N/A")] String startMenuPinnedFolderPictures; 
    [Write, Description("N/A")] String startMenuPinnedFolderSettings; 
    [Write, Description("N/A")] String startMenuPinnedFolderVideos; 
    [Write, Description("N/A")] Boolean settingsBlockSettingsApp; 
    [Write, Description("N/A")] Boolean settingsBlockSystemPage; 
    [Write, Description("N/A")] Boolean settingsBlockDevicesPage; 
    [Write, Description("N/A")] Boolean settingsBlockNetworkInternetPage; 
    [Write, Description("N/A")] Boolean settingsBlockPersonalizationPage; 
    [Write, Description("N/A")] Boolean settingsBlockAccountsPage; 
    [Write, Description("N/A")] Boolean settingsBlockTimeLanguagePage; 
    [Write, Description("N/A")] Boolean settingsBlockEaseOfAccessPage; 
    [Write, Description("N/A")] Boolean settingsBlockPrivacyPage; 
    [Write, Description("N/A")] Boolean settingsBlockUpdateSecurityPage; 
    [Write, Description("N/A")] Boolean settingsBlockAppsPage; 
    [Write, Description("N/A")] Boolean settingsBlockGamingPage; 
    [Write, Description("N/A")] Boolean windowsSpotlightBlockConsumerSpecificFeatures; 
    [Write, Description("N/A")] Boolean windowsSpotlightBlocked; 
    [Write, Description("N/A")] Boolean windowsSpotlightBlockOnActionCenter; 
    [Write, Description("N/A")] Boolean windowsSpotlightBlockTailoredExperiences;
    [Write, Description("Present ensures the site collection exists, absent ensures it is removed"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] string Ensure;
    [Write, Description("Credentials of the SharePoint Global Admin"), EmbeddedInstance("MSFT_Credential")] string GlobalAdminAccount;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Name of the Azure Active Directory tenant used for authentication. Format contoso.onmicrosoft.com")] String TenantId;
    [Write, Description("Username can be made up to anything but password will be used for certificatePassword"), EmbeddedInstance("MSFT_Credential")] String CertificatePassword;
    [Write, Description("Path to certificate used in service principal usually a PFX file.")] String CertificatePath;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
};
