
[ClassVersion("1.0.0.0"), FriendlyName("IntuneDeviceCleanupRuleV2")]
class MSFT_IntuneDeviceCleanupRuleV2 : OMI_BaseResource
{
    [Write, Description("Indicates the description for the device clean up rule.")] String Description;
    [Write, Description("Indicates the managed device platform for which the admin wants to create the device clean up rule. Possible values are: all, androidAOSP, androidDeviceAdministrator, androidDedicatedAndFullyManagedCorporateOwnedWorkProfile, chromeOS, androidPersonallyOwnedWorkProfile, ios, macOS, windows, windowsHolographic, unknownFutureValue, visionOS, tvOS."), ValueMap{"all","androidAOSP","androidDeviceAdministrator","androidDedicatedAndFullyManagedCorporateOwnedWorkProfile","chromeOS","androidPersonallyOwnedWorkProfile","ios","macOS","windows","windowsHolographic","unknownFutureValue","visionOS","tvOS"}, Values{"all","androidAOSP","androidDeviceAdministrator","androidDedicatedAndFullyManagedCorporateOwnedWorkProfile","chromeOS","androidPersonallyOwnedWorkProfile","ios","macOS","windows","windowsHolographic","unknownFutureValue","visionOS","tvOS"}] String DeviceCleanupRulePlatformType;
    [Write, Description("Indicates the number of days when the device has not contacted Intune. Valid values 0 to 2147483647")] UInt32 DeviceInactivityBeforeRetirementInDays;
    [Key, Description("Indicates the display name of the device cleanup rule.")] String DisplayName;
    [Write, Description("The unique identifier for an entity. Read-only.")] String Id;
    [Write, Description("Present ensures the policy exists, absent ensures it is removed."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] string Ensure;
    [Write, Description("Credentials of the Admin"), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Id of the Azure Active Directory tenant used for authentication.")] String TenantId;
    [Write, Description("Secret of the Azure Active Directory tenant used for authentication."), EmbeddedInstance("MSFT_Credential")] String ApplicationSecret;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Managed ID being used for authentication.")] Boolean ManagedIdentity;
    [Write, Description("Access token used for authentication.")] String AccessTokens[];
};
