[ClassVersion("1.0.0")]
class MSFT_SCLabelSetting
{
    [Write, Description("Advanced settings key.")] String Key;
    [Write, Description("Advanced settings value.")] String Value[];
};
[ClassVersion("1.0.0")]
class MSFT_SCLabelLocaleSettings
{
    [Write, Description("Name of the Local key.")] String localeKey;
    [Write, Description("The locale settings display names."),EmbeddedInstance("MSFT_SCLabelSetting")] String Settings[];
};
[ClassVersion("1.0.0.0"), FriendlyName("SCSensitivityLabel")]
class MSFT_SCSensitivityLabel : OMI_BaseResource
{
    [Key, Description("The Name parameter specifies the unique name for the sensitivity label. The maximum length is 64 characters. If the value contains spaces, enclose the value in quotation marks.")] String Name;
    [Write, Description("Specify if this rule should exist or not."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Write, Description("The Comment parameter specifies an optional comment.")] String Comment;
    [Write, Description("The AdvancedSettings parameter enables client-specific features and capabilities on the sensitivity label. The settings that you configure with this parameter only affect apps that are designed for the setting."),EmbeddedInstance("MSFT_SCLabelSetting")] String AdvancedSettings[];
    [Write, Description("The DisplayName parameter specifies the display name for the sensitivity label. The display name appears in the Microsoft Office and is used by Outlook users to select the appropriate sensitivity label before they send a message.")] String DisplayName;
    [Write, Description("The LocaleSettings parameter specifies one or more localized label name or label Tooltips in different languages. Regions include all region codes supported in Office Client applications."),EmbeddedInstance("MSFT_SCLabelLocaleSettings")] String LocaleSettings[];
    [Write, Description("The ParentId parameter specifies the parent label that you want this label to be under (a sublabel). You can use any value that uniquely identifies the parent sensitivity label for example name.")] String ParentId;
    [Write, Description("The Priority parameter specifies a priority value for the sensitivity label that determines the order of label processing. A lower integer value indicates a highter priority.")] uint32 Priority;
    [Write, Description("The ToolTip parameter specifies the default tooltip and sensitivity label description that's seen by users. It the value contains spaces, enclose the value in quotation marks.")] String Tooltip;
    [Write, Description("The disabled parameter specifies whether to enable or disable the sensitivity label.")] Boolean Disabled;
    [Write, Description("The ApplyContentMarkingFooterAlignment parameter specifies the footer alignment."), ValueMap{"Left","Center","Right"}, Values{"Left","Center","Right"}] String ApplyContentMarkingFooterAlignment;
    [Write, Description("The disabled parameter specifies whether to enable or disable the sensitivity label.")] Boolean ApplyContentMarkingFooterEnabled;
    [Write, Description("The ApplyContentMarkingFooterFontColor parameter specifies the color of the footer text. This parameter accepts a hexadecimal color code value in the format #xxxxxx. The default value is #000000.")] String ApplyContentMarkingFooterFontColor;
    [Write, Description("The ApplyContentMarkingFooterFontName parameter specifies the font of the footer text. If the value contains spaces, enclose the value in quotation marks.")] String ApplyContentMarkingFooterFontName;
    [Write, Description("The ApplyContentMarkingFooterFontSize parameter specifies the font size (in points) of the footer text.")] SInt32 ApplyContentMarkingFooterFontSize;
    [Write, Description("The ApplyContentMarkingFooterMargin parameter specifies the size (in points) of the footer margin.")] SInt32 ApplyContentMarkingFooterMargin;
    [Write, Description("The ApplyContentMarkingFooterText parameter specifies the footer text. If the value contains spaces, enclose the value in quotation marks.")] String ApplyContentMarkingFooterText;
    [Write, Description("The ApplyContentMarkingFooterAlignment parameter specifies the header alignment."), ValueMap{"Left","Center","Right"}, Values{"Left","Center","Right"}] String ApplyContentMarkingHeaderAlignment;
    [Write, Description("The ApplyContentMarkingHeaderEnabled parameter enables or disables the Apply Content Marking Header action for the label.")] Boolean ApplyContentMarkingHeaderEnabled;
    [Write, Description("The ApplyContentMarkingFooterFontColor parameter specifies the color of the header text. This parameter accepts a hexadecimal color code value in the format #xxxxxx. The default value is #000000.")] String ApplyContentMarkingHeaderFontColor;
    [Write, Description("The ApplyContentMarkingFooterFontName parameter specifies the font of the header text. If the value contains spaces, enclose the value in quotation marks.")] String ApplyContentMarkingHeaderFontName;
    [Write, Description("The ApplyContentMarkingFooterFontSize parameter specifies the font size (in points) of the header text.")] SInt32 ApplyContentMarkingHeaderFontSize;
    [Write, Description("The ApplyContentMarkingFooterMargin parameter specifies the size (in points) of the header margin.")] SInt32 ApplyContentMarkingHeaderMargin;
    [Write, Description("The ApplyContentMarkingFooterText parameter specifies the header text. If the value contains spaces, enclose the value in quotation marks.")] String ApplyContentMarkingHeaderText;
    [Write, Description("The ApplyWaterMarkingEnabled parameter enables or disables the Apply Watermarking Header action for the label.")] Boolean ApplyWaterMarkingEnabled;
    [Write, Description("The ApplyWaterMarkingFontColor parameter specifies the color of the watermark text. This parameter accepts a hexadecimal color code value in the format #xxxxxx.")] String ApplyWaterMarkingFontColor;
    [Write, Description("The ApplyWaterMarkingFontName parameter specifies the font of the watermark text. If the value contains spaces, enclose the value in quotation marks.")] String ApplyWaterMarkingFontName;
    [Write, Description("The ApplyWaterMarkingFontSize parameter specifies the font size (in points) of the watermark text.")] SInt32 ApplyWaterMarkingFontSize;
    [Write, Description("The ApplyContentMarkingFooterAlignment parameter specifies the header alignment."), ValueMap{"Horizontal","Diagonal"}, Values{"Horizontal","Diagonal"}] String ApplyWaterMarkingLayout;
    [Write, Description("The ApplyWaterMarkingText parameter specifies the watermark text. If the value contains spaces, enclose the value in quotation marks.")] String ApplyWaterMarkingText;
    [Write, Description("The EncryptionAipTemplateScopes parameter specifies that the label is still published and usable in the AIP classic client.")] String EncryptionAipTemplateScopes;
    [Write, Description("The EncryptionContentExpiredOnDateInDaysOrNever parameter specifies when the encrypted content expires. Valid values are integer or never.")] String EncryptionContentExpiredOnDateInDaysOrNever;
    [Write, Description("The EncryptionDoNotForward parameter specifies whether the Do Not Forward template is applied.")] Boolean EncryptionDoNotForward;
    [Write, Description("The EncryptionEnabled parameter specifies whether encryption in enabled.")] Boolean EncryptionEnabled;
    [Write, Description("The EncryptionOfflineAccessDays parameter specifies the number of days that offline access is allowed.")] SInt32 EncryptionOfflineAccessDays;
    [Write, Description("The EncryptionPromptUser parameter specifies whether to set the label with user defined permission in Word, Excel, and PowerPoint.")] Boolean EncryptionPromptUser;
    [Write, Description("The EncryptionProtectionType parameter specifies the protection type for encryption."), ValueMap{"Template","RemoveProtection","UserDefined"}, Values{"Template","RemoveProtection","UserDefined"}] String EncryptionProtectionType;
    [Write, Description("The EncryptionRightsDefinitions parameter specifies the rights users have when accessing protected. This parameter uses the syntax Identity1:Rights1,Rights2;Identity2:Rights3,Rights4. For example, john@contoso.com:VIEW,EDIT;microsoft.com:VIEW.")] String EncryptionRightsDefinitions;
    [Write, Description("The EncryptionRightsUrl parameter specifies the URL for hold your own key (HYOK) protection.")] String EncryptionRightsUrl;
    [Write, Description("The SiteAndGroupProtectionAllowAccessToGuestUsers parameter enables or disables access to guest users.")] Boolean SiteAndGroupProtectionAllowAccessToGuestUsers;
    [Write, Description("The SiteAndGroupProtectionAllowEmailFromGuestUsers parameter enables or disables email from guest users.")] Boolean SiteAndGroupProtectionAllowEmailFromGuestUsers;
    [Write, Description("The SiteAndGroupProtectionAllowFullAccess parameter enables or disables full access.")] Boolean SiteAndGroupProtectionAllowFullAccess;
    [Write, Description("The SiteAndGroupProtectionAllowLimitedAccess parameter enables or disables limited access.")] Boolean SiteAndGroupProtectionAllowLimitedAccess;
    [Write, Description("The SiteAndGroupProtectionBlockAccess parameter blocks access.")] Boolean SiteAndGroupProtectionBlockAccess;
    [Write, Description("The SiteAndGroupProtectionEnabled parameter enables or disables the Site and Group Protection action for the labels.")] Boolean SiteAndGroupProtectionEnabled;
    [Write, Description("The SiteAndGroupProtectionPrivacy parameter specifies the privacy level for the label."), ValueMap{"Public","Private"}, Values{"Public","Private"}] String SiteAndGroupProtectionPrivacy;
    [Required, Description("Credentials of the Exchange Global Admin"), EmbeddedInstance("MSFT_Credential")] String GlobalAdminAccount;
};
