[ClassVersion("1.0.0.0"), FriendlyName("SCDeviceConditionalAccessRule")]
class MSFT_SCDeviceConditionalAccessRule : OMI_BaseResource
{
    [Key, Description("")] String Name;
    [Write, Description("")] String Policy;
    [Write, Description("")] String TargetGroups[];
    [Write, Description("")] String AccountName;
    [Write, Description("")] String AccountUserName;
    [Write, Description("")] Boolean AllowAppStore;
    [Write, Description("")] Boolean AllowAssistantWhileLocked;
    [Write, Description("")] Boolean AllowConvenienceLogon;
    [Write, Description("")] Boolean AllowDiagnosticSubmission;
    [Write, Description("")] Boolean AllowiCloudBackup;
    [Write, Description("")] Boolean AllowiCloudDocSync;
    [Write, Description("")] Boolean AllowiCloudPhotoSync;
    [Write, Description("")] Boolean AllowJailbroken;
    [Write, Description("")] Boolean AllowPassbookWhileLocked;
    [Write, Description("")] Boolean AllowScreenshot;
    [Write, Description("")] Boolean AllowSimplePassword;
    [Write, Description("")] Boolean AllowVideoConferencing;
    [Write, Description("")] Boolean AllowVoiceAssistant;
    [Write, Description("")] Boolean AllowVoiceDialing;
    [Write, Description("")] UInt32 AntiVirusSignatureStatus;
    [Write, Description("")] UInt32 AntiVirusStatus;
    [Write, Description("")] String AppsRating;
    [Write, Description("")] String AutoUpdateStatus;
    [Write, Description("")] Boolean BluetoothEnabled;
    [Write, Description("")] Boolean CameraEnabled;
    [Write, Description("")] String EmailAddress;
    [Write, Description("")] Boolean EnableRemovableStorage;
    [Write, Description("")] String ExchangeActiveSyncHost;
    [Write, Description("")] Boolean FirewallStatus;
    [Write, Description("")] Boolean ForceAppStorePassword;
    [Write, Description("")] Boolean ForceEncryptedBackup;
    [Write, Description("")] UInt32 MaxPasswordAttemptsBeforeWipe;
    [Write, Description("")] UInt32 MaxPasswordGracePeriod;
    [Write, Description("")] String MoviesRating;
    [Write, Description("")] UInt32 PasswordComplexity;
    [Write, Description("")] UInt32 PasswordExpirationDays;
    [Write, Description("")] UInt32 PasswordHistoryCount;
    [Write, Description("")] UInt32 PasswordMinComplexChars;
    [Write, Description("")] UInt32 PasswordMinimumLength;
    [Write, Description("")] UInt32 PasswordQuality;
    [Write, Description("")] Boolean PasswordRequired;
    [Write, Description("")] String PasswordTimeout;
    [Write, Description("")] Boolean PhoneMemoryEncrypted;
    [Write, Description("")] String RegionRatings;
    [Write, Description("")] Boolean RequireEmailProfile;
    [Write, Description("")] Boolean SmartScreenEnabled;
    [Write, Description("")] Boolean SystemSecurityTLS;
    [Write, Description("")] String TVShowsRating;
    [Write, Description("")] String UserAccountControlStatus;
    [Write, Description("")] Boolean WLANEnabled;
    [Write, Description("")] String WorkFoldersSyncUrl;

    [Write, Description("Present ensures the instance exists, absent ensures it is removed."), ValueMap{"Present"}, Values{"Present"}] string Ensure;
    [Write, Description("Credentials of the workload's Admin"), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Id of the Azure Active Directory tenant used for authentication.")] String TenantId;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Managed ID being used for authentication.")] Boolean ManagedIdentity;
    [Write, Description("Access token used for authentication.")] String AccessTokens[];
};
