[ClassVersion("1.0.0.0"), FriendlyName("TeamsClientConfiguration")]
class MSFT_TeamsClientConfiguration : OMI_BaseResource
{
    [Key, Description("The only valid input is Global - the tenant wide configuration"), ValueMap{"Global"}, Values{"Global"}] string Identity;
    [Write, Description("Designates whether users are able to leverage Box as a third party storage solution in Microsoft Teams. If $true, users will be able to add Box in the client and interact with the files stored there.")] boolean AllowBox;
    [Write, Description("Designates whether users are able to leverage DropBox as a third party storage solution in Microsoft Teams. If $true, users will be able to add DropBox in the client and interact with the files stored there.")] boolean AllowDropBox;
    [Write, Description("When set to $true, mail hooks are enabled, and users can post messages to a channel by sending an email to the email address of Teams channel.")] boolean AllowEmailIntoChannel;
    [Write, Description("Designates whether users are able to leverage GoogleDrive as a third party storage solution in Microsoft Teams. If $true, users will be able to add Google Drive in the client and interact with the files stored there.")] boolean AllowGoogleDrive;
    [Write, Description("Designates whether or not guest users in your organization will have access to the Teams client. If $true, guests in your tenant will be able to access the Teams client. Note that this setting has a core dependency on Guest Access being enabled in your Office 365 tenant.")] boolean AllowGuestUser;
    [Write, Description("When set to $true, users will be able to see the organizational chart icon other users' contact cards, and when clicked, this icon will display the detailed organizational chart.")] boolean AllowOrganizationTab;
    [Write, Description("Surface Hub uses a device account to provide email and collaboration services (IM, video, voice). This device account is used as the originating identity (the from party) when sending email, IM, and placing calls. As this account is not coming from an individual, identifiable user, it is deemed anonymous because it originated from the Surface Hub's device account. If set to $true, these device accounts will be able to send chat messages in Skype for Business Online (does not apply to Microsoft Teams).")] boolean AllowResourceAccountSendMessage;
    [Write, Description("If set to $true, the Exchange address book policy (ABP) will be used to provide customized view of the global address book for each user. This is only a virtual separation and not a legal separation.")] boolean AllowScopedPeopleSearchandAccess;
    [Write, Description("Designates whether users are able to leverage ShareFile as a third party storage solution in Microsoft Teams. If $true, users will be able to add ShareFile in the client and interact with the files stored there.")] boolean AllowShareFile;
    [Write, Description("When set to $true, Teams conversations automatically show up in Skype for Business for users that aren't enabled for Teams.")] boolean AllowSkypeBusinessInterop;
    [Write, Description("Designates whether users are able to leverage Egnyte as a third party storage solution in Microsoft Teams. If $true, users will be able to add Egnyte in the client and interact with the files stored there.")] boolean AllowEgnyte;
    [Write, Description("This setting applies only to Skype for Business Online (not Microsoft Teams) and defines whether the user must provide a secondary form of authentication to access the meeting content from a resource device account. Meeting content is defined as files that are shared to the Content Bin - files that have been attached to the meeting."), ValueMap{"NotRequired", "RequiredOutsideScheduleMeeting", "AlwaysRequired"}, Values{"NotRequired", "RequiredOutsideScheduleMeeting", "AlwaysRequired"}] string ContentPin;
    [Write, Description("Require a secondary form of authentication to access meeting content."), ValueMap{"NoAccess", "PartialAccess", "FullAccess"}, Values{"NoAccess", "PartialAccess", "FullAccess"}] string ResourceAccountContentAccess;
    [Write, Description("Senders domains can be further restricted to ensure that only allowed SMTP domains can send emails to the Teams channels. This is a comma-separated string of the domains you'd like to allow to send emails to Teams channels.")] string RestrictedSenderList[];
    [Required, Description("Credentials of the SharePoint Global Admin"), EmbeddedInstance("MSFT_Credential")] String GlobalAdminAccount;
};

