[ClassVersion("1.0.0")]
class MSFT_FabricDelegatedFrom
{
    [Write, Description("The setting is delegated from a capacity.")] String Capacity;
    [Write, Description("The setting is delegated from a domain.")] String Domain;
    [Write, Description("The setting is delegated from a tenant.")] String Tenant;
};

[ClassVersion("1.0.0")]
class MSFT_FabricTenantSettingProperty
{
    [Write, Description("The name of the property.")] String name;
    [Write, Description("The type of the property.")] String type;
    [Write, Description("The value of the property.")] String value;
};

[ClassVersion("1.0.0")]
class MSFT_FabricTenantSetting
{
    [Write, Description("Indicates if the tenant setting is enabled for a security group. 0 - The tenant setting is enabled for the entire organization.")] Boolean canSpecifySecurityGroups;
    [Write, Description("Indicates whether the tenant setting can be delegated to a workspace admin. False - Workspace admin cannot override the tenant setting.")] Boolean delegateToWorkspace;
    [Write, Description("Tenant setting delegated from tenant, capacity or domain."), EmbeddedInstance("MSFT_FabricDelegatedFrom")] string delegatedFrom;
    [Write, Description("The name of the tenant setting.")] String settingName;
    [Write, Description("The status of the tenant setting.")] Boolean enabled;
    [Write, Description("Tenant setting group name.")] String tenantSettingGroup;
    [Write, Description("The title of the tenant setting.")] String title;
    [Write, Description("Tenant setting properties."), EmbeddedInstance("MSFT_FabricTenantSettingProperty")] String properties[];
    [Write, Description("A list of excluded security groups.")] String excludedSecurityGroups[];
    [Write, Description("A list of enabled security groups.")] String enabledSecurityGroups[];
};

[ClassVersion("1.0.0.0"), FriendlyName("FabricAdminTenantSettings")]
class MSFT_FabricAdminTenantSettings : OMI_BaseResource
{
    [Key, Description("Specifies the resource is a single instance, the value must be 'Yes'."), ValueMap{"Yes"}, Values{"Yes"}] String IsSingleInstance;
    [Write, Description("Microsoft Entra single sign-on for data gateway"), EmbeddedInstance("MSFT_FabricTenantSetting")] string AADSSOForGateway;
    [Write, Description("Enhance admin APIs responses with detailed metadata"), EmbeddedInstance("MSFT_FabricTenantSetting")] string AdminApisIncludeDetailedMetadata;
    [Write, Description("Enhance admin APIs responses with DAX and mashup expressions"), EmbeddedInstance("MSFT_FabricTenantSetting")] string AdminApisIncludeExpressions;
    [Write, Description("Show a custom message before publishing reports"), EmbeddedInstance("MSFT_FabricTenantSetting")] string AdminCustomDisclaimer;
    [Write, Description("Users can create and share AI skill item types (preview)"), EmbeddedInstance("MSFT_FabricTenantSetting")] string AISkillArtifactTenantSwitch;
    [Write, Description("Azure Private Link"), EmbeddedInstance("MSFT_FabricTenantSetting")] string AllowAccessOverPrivateLinks;
    [Write, Description("AppSource Custom Visuals SSO"), EmbeddedInstance("MSFT_FabricTenantSetting")] string AllowCVAuthenticationTenant;
    [Write, Description("Allow access to the browser's local storage"), EmbeddedInstance("MSFT_FabricTenantSetting")] string AllowCVLocalStorageV2Tenant;
    [Write, Description("Allow downloads from custom visuals"), EmbeddedInstance("MSFT_FabricTenantSetting")] string AllowCVToExportDataToFileTenant;
    [Write, Description("Endorse master data (preview)"), EmbeddedInstance("MSFT_FabricTenantSetting")] string AllowEndorsementMasterDataSwitch;
    [Write, Description("Users can accept external data shares (preview)"), EmbeddedInstance("MSFT_FabricTenantSetting")] string AllowExternalDataSharingReceiverSwitch;
    [Write, Description("External data sharing (preview)"), EmbeddedInstance("MSFT_FabricTenantSetting")] string AllowExternalDataSharingSwitch;
    [Write, Description("Users can try Microsoft Fabric paid features"), EmbeddedInstance("MSFT_FabricTenantSetting")] string AllowFreeTrial;
    [Write, Description("Users can see guest users in lists of suggested people"), EmbeddedInstance("MSFT_FabricTenantSetting")] string AllowGuestLookup;
    [Write, Description("Guest users can access Microsoft Fabric"), EmbeddedInstance("MSFT_FabricTenantSetting")] string AllowGuestUserToAccessSharedContent;
    [Write, Description("Allow DirectQuery connections to Power BI semantic models"), EmbeddedInstance("MSFT_FabricTenantSetting")] string AllowPowerBIASDQOnTenant;
    [Write, Description("Data sent to Azure OpenAI can be processed outside your capacity's geographic region, compliance boundary, or national cloud instance"), EmbeddedInstance("MSFT_FabricTenantSetting")] string AllowSendAOAIDataToOtherRegions;
    [Write, Description("Allow user data to leave their geography"), EmbeddedInstance("MSFT_FabricTenantSetting")] string AllowSendNLToDaxDataToOtherRegions;
    [Write, Description("Allow service principals to create and use profiles"), EmbeddedInstance("MSFT_FabricTenantSetting")] string AllowServicePrincipalsCreateAndUseProfiles;
    [Write, Description("Service principals can access read-only admin APIs"), EmbeddedInstance("MSFT_FabricTenantSetting")] string AllowServicePrincipalsUseReadAdminAPIs;
    [Write, Description("Push apps to end users"), EmbeddedInstance("MSFT_FabricTenantSetting")] string AppPush;
    [Write, Description("Use global search for Power BI"), EmbeddedInstance("MSFT_FabricTenantSetting")] string ArtifactSearchTenant;
    [Write, Description("Microsoft can store query text to aid in support investigations"), EmbeddedInstance("MSFT_FabricTenantSetting")] string ASCollectQueryTextTelemetryTenantSwitch;
    [Write, Description("Enable granular access control for all data connections"), EmbeddedInstance("MSFT_FabricTenantSetting")] string ASShareableCloudConnectionBindingSecurityModeTenant;
    [Write, Description("Semantic models can export data to OneLake (preview)"), EmbeddedInstance("MSFT_FabricTenantSetting")] string ASWritethruContinuousExportTenantSwitch;
    [Write, Description("Users can store semantic model tables in OneLake (preview)"), EmbeddedInstance("MSFT_FabricTenantSetting")] string ASWritethruTenantSwitch;
    [Write, Description("Install Power BI app for Microsoft Teams automatically"), EmbeddedInstance("MSFT_FabricTenantSetting")] string AutoInstallPowerBIAppInTeamsTenant;
    [Write, Description("Show entry points for insights (preview)"), EmbeddedInstance("MSFT_FabricTenantSetting")] string AutomatedInsightsEntryPoints;
    [Write, Description("Receive notifications for top insights (preview)"), EmbeddedInstance("MSFT_FabricTenantSetting")] string AutomatedInsightsTenant;
    [Write, Description("Use Azure Maps visual"), EmbeddedInstance("MSFT_FabricTenantSetting")] string AzureMap;
    [Write, Description("Map and filled map visuals"), EmbeddedInstance("MSFT_FabricTenantSetting")] string BingMap;
    [Write, Description("Block Public Internet Access"), EmbeddedInstance("MSFT_FabricTenantSetting")] string BlockAccessFromPublicNetworks;
    [Write, Description("Block republish and disable package refresh"), EmbeddedInstance("MSFT_FabricTenantSetting")] string BlockAutoDiscoverAndPackageRefresh;
    [Write, Description("Restrict content with protected labels from being shared via link with everyone in your organization"), EmbeddedInstance("MSFT_FabricTenantSetting")] string BlockProtectedLabelSharingToEntireOrg;
    [Write, Description("Block ResourceKey Authentication"), EmbeddedInstance("MSFT_FabricTenantSetting")] string BlockResourceKeyAuthentication;
    [Write, Description("Create and use Gen1 dataflows"), EmbeddedInstance("MSFT_FabricTenantSetting")] string CDSAManagement;
    [Write, Description("Add and use certified visuals only (block uncertified)"), EmbeddedInstance("MSFT_FabricTenantSetting")] string CertifiedCustomVisualsTenant;
    [Write, Description("Certification"), EmbeddedInstance("MSFT_FabricTenantSetting")] string CertifyDatasets;
    [Write, Description("Define workspace retention period"), EmbeddedInstance("MSFT_FabricTenantSetting")] string ConfigureFolderRetentionPeriod;
    [Write, Description("Create workspaces"), EmbeddedInstance("MSFT_FabricTenantSetting")] string CreateAppWorkspaces;
    [Write, Description("Allow visuals created using the Power BI SDK"), EmbeddedInstance("MSFT_FabricTenantSetting")] string CustomVisualsTenant;
    [Write, Description("Create Datamarts (preview)"), EmbeddedInstance("MSFT_FabricTenantSetting")] string DatamartTenant;
    [Write, Description("Semantic Model Execute Queries REST API"), EmbeddedInstance("MSFT_FabricTenantSetting")] string DatasetExecuteQueries;
    [Write, Description("Publish template apps"), EmbeddedInstance("MSFT_FabricTenantSetting")] string DevelopServiceApps;
    [Write, Description("Discover content"), EmbeddedInstance("MSFT_FabricTenantSetting")] string DiscoverDatasetsConsumption;
    [Write, Description("Make certified content discoverable "), EmbeddedInstance("MSFT_FabricTenantSetting")] string DiscoverDatasetsSettingsCertified;
    [Write, Description("Make promoted content discoverable"), EmbeddedInstance("MSFT_FabricTenantSetting")] string DiscoverDatasetsSettingsPromoted;
    [Write, Description("Dremio SSO"), EmbeddedInstance("MSFT_FabricTenantSetting")] string DremioSSO;
    [Write, Description("Apply sensitivity labels from data sources to their data in Power BI"), EmbeddedInstance("MSFT_FabricTenantSetting")] string EimInformationProtectionDataSourceInheritanceSetting;
    [Write, Description("Automatically apply sensitivity labels to downstream content"), EmbeddedInstance("MSFT_FabricTenantSetting")] string EimInformationProtectionDownstreamInheritanceSetting;
    [Write, Description("Allow users to apply sensitivity labels for content"), EmbeddedInstance("MSFT_FabricTenantSetting")] string EimInformationProtectionEdit;
    [Write, Description("Increase the number of users who can edit and republish encrypted PBIX files (preview)"), EmbeddedInstance("MSFT_FabricTenantSetting")] string EimInformationProtectionLessElevated;
    [Write, Description("Allow workspace admins to override automatically applied sensitivity labels"), EmbeddedInstance("MSFT_FabricTenantSetting")] string EimInformationProtectionWorkspaceAdminsOverrideAutomaticLabelsSetting;
    [Write, Description("Guest users can browse and access Fabric content"), EmbeddedInstance("MSFT_FabricTenantSetting")] string ElevatedGuestsTenant;
    [Write, Description("Receive email notifications for service outages or incidents"), EmbeddedInstance("MSFT_FabricTenantSetting")] string EmailSecurityGroupsOnOutage;
    [Write, Description("Guest users can set up and subscribe to email subscriptions"), EmbeddedInstance("MSFT_FabricTenantSetting")] string EmailSubscriptionsToB2BUsers;
    [Write, Description("Users can send email subscriptions to guest users"), EmbeddedInstance("MSFT_FabricTenantSetting")] string EmailSubscriptionsToExternalUsers;
    [Write, Description("Users can set up email subscriptions"), EmbeddedInstance("MSFT_FabricTenantSetting")] string EmailSubscriptionTenant;
    [Write, Description("Embed content in apps"), EmbeddedInstance("MSFT_FabricTenantSetting")] string Embedding;
    [Write, Description("Users can use Copilot and other features powered by Azure OpenAI"), EmbeddedInstance("MSFT_FabricTenantSetting")] string EnableAOAI;
    [Write, Description("Allow specific users to turn on external data sharing"), EmbeddedInstance("MSFT_FabricTenantSetting")] string EnableDatasetInPlaceSharing;
    [Write, Description("Allow connections to featured tables"), EmbeddedInstance("MSFT_FabricTenantSetting")] string EnableExcelYellowIntegration;
    [Write, Description("Users can create and use data workflows (preview)"), EmbeddedInstance("MSFT_FabricTenantSetting")] string EnableFabricAirflow;
    [Write, Description("Allow quick measure suggestions (preview)"), EmbeddedInstance("MSFT_FabricTenantSetting")] string EnableNLToDax;
    [Write, Description("Allow tenant and domain admins to override workspace assignments (preview)"), EmbeddedInstance("MSFT_FabricTenantSetting")] string EnableReassignDataDomainSwitch;
    [Write, Description("Use ArcGIS Maps for Power BI"), EmbeddedInstance("MSFT_FabricTenantSetting")] string EsriVisual;
    [Write, Description("Help Power BI optimize your experience"), EmbeddedInstance("MSFT_FabricTenantSetting")] string ExpFlightingTenant;
    [Write, Description("Download reports"), EmbeddedInstance("MSFT_FabricTenantSetting")] string ExportReport;
    [Write, Description("Export to .csv"), EmbeddedInstance("MSFT_FabricTenantSetting")] string ExportToCsv;
    [Write, Description("Export to Excel"), EmbeddedInstance("MSFT_FabricTenantSetting")] string ExportToExcelSetting;
    [Write, Description("Export reports as image files"), EmbeddedInstance("MSFT_FabricTenantSetting")] string ExportToImage;
    [Write, Description("Export reports as MHTML documents"), EmbeddedInstance("MSFT_FabricTenantSetting")] string ExportToMHTML;
    [Write, Description("Export reports as PowerPoint presentations or PDF documents"), EmbeddedInstance("MSFT_FabricTenantSetting")] string ExportToPowerPoint;
    [Write, Description("Export reports as Word documents"), EmbeddedInstance("MSFT_FabricTenantSetting")] string ExportToWord;
    [Write, Description("Export reports as XML documents"), EmbeddedInstance("MSFT_FabricTenantSetting")] string ExportToXML;
    [Write, Description("Copy and paste visuals"), EmbeddedInstance("MSFT_FabricTenantSetting")] string ExportVisualImageTenant;
    [Write, Description("Guest users can work with shared semantic models in their own tenants"), EmbeddedInstance("MSFT_FabricTenantSetting")] string ExternalDatasetSharingTenant;
    [Write, Description("Users can invite guest users to collaborate through item sharing and permissions"), EmbeddedInstance("MSFT_FabricTenantSetting")] string ExternalSharingV2;
    [Write, Description("Capacity admins and contributors can add and remove additional workloads"), EmbeddedInstance("MSFT_FabricTenantSetting")] string FabricAddPartnerWorkload;
    [Write, Description("Product Feedback"), EmbeddedInstance("MSFT_FabricTenantSetting")] string FabricFeedbackTenantSwitch;
    [Write, Description("Users can create Fabric items"), EmbeddedInstance("MSFT_FabricTenantSetting")] string FabricGAWorkloads;
    [Write, Description("Capacity admins can develop additional workloads"), EmbeddedInstance("MSFT_FabricTenantSetting")] string FabricThirdPartyWorkloads;
    [Write, Description("Users can sync workspace items with GitHub repositories "), EmbeddedInstance("MSFT_FabricTenantSetting")] string GitHubTenantSettings;
    [Write, Description("Users can export items to Git repositories in other geographical locations (preview)"), EmbeddedInstance("MSFT_FabricTenantSetting")] string GitIntegrationCrossGeoTenantSwitch;
    [Write, Description("Users can export workspace items with applied sensitivity labels to Git repositories (preview)"), EmbeddedInstance("MSFT_FabricTenantSetting")] string GitIntegrationSensitivityLabelsTenantSwitch;
    [Write, Description("Users can synchronize workspace items with their Git repositories (preview)"), EmbeddedInstance("MSFT_FabricTenantSetting")] string GitIntegrationTenantSwitch;
    [Write, Description("Google BigQuery SSO"), EmbeddedInstance("MSFT_FabricTenantSetting")] string GoogleBigQuerySSO;
    [Write, Description("API for GraphQL (preview)"), EmbeddedInstance("MSFT_FabricTenantSetting")] string GraphQLTenant;
    [Write, Description("Healthcare data solutions (preview)"), EmbeddedInstance("MSFT_FabricTenantSetting")] string HealthcareSolutionsTenantSwitch;
    [Write, Description("Install template apps not listed in AppSource"), EmbeddedInstance("MSFT_FabricTenantSetting")] string InstallNonvalidatedTemplateApps;
    [Write, Description("Install template apps"), EmbeddedInstance("MSFT_FabricTenantSetting")] string InstallServiceApps;
    [Write, Description("Users can create Real-Time Dashboards (preview)"), EmbeddedInstance("MSFT_FabricTenantSetting")] string KustoDashboardTenantSwitch;
    [Write, Description("Users can work with semantic models in Excel using a live connection"), EmbeddedInstance("MSFT_FabricTenantSetting")] string LiveConnection;
    [Write, Description("Azure Log Analytics connections for workspace administrators"), EmbeddedInstance("MSFT_FabricTenantSetting")] string LogAnalyticsAttachForWorkspaceAdmins;
    [Write, Description("Users can see Microsoft Fabric metadata in Microsoft 365"), EmbeddedInstance("MSFT_FabricTenantSetting")] string M365DataSharing;
    [Write, Description("Database Mirroring (preview)"), EmbeddedInstance("MSFT_FabricTenantSetting")] string Mirroring;
    [Write, Description("Semantic model owners can choose to automatically update semantic models from files imported from OneDrive or SharePoint"), EmbeddedInstance("MSFT_FabricTenantSetting")] string ODSPRefreshEnforcementTenantAllowAutomaticUpdate;
    [Write, Description("Users can share links to Power BI files stored in OneDrive and SharePoint through Power BI Desktop (preview)"), EmbeddedInstance("MSFT_FabricTenantSetting")] string OneDriveSharePointAllowSharingTenantSetting;
    [Write, Description("Users can view Power BI files saved in OneDrive and SharePoint (preview)"), EmbeddedInstance("MSFT_FabricTenantSetting")] string OneDriveSharePointViewerIntegrationTenantSettingV2;
    [Write, Description("Users can sync data in OneLake with the OneLake File Explorer app"), EmbeddedInstance("MSFT_FabricTenantSetting")] string OneLakeFileExplorer;
    [Write, Description("Users can access data stored in OneLake with apps external to Fabric"), EmbeddedInstance("MSFT_FabricTenantSetting")] string OneLakeForThirdParty;
    [Write, Description("Allow XMLA endpoints and Analyze in Excel with on-premises semantic models"), EmbeddedInstance("MSFT_FabricTenantSetting")] string OnPremAnalyzeInExcel;
    [Write, Description("Create and use Metrics"), EmbeddedInstance("MSFT_FabricTenantSetting")] string PowerBIGoalsTenant;
    [Write, Description("Power Platform Solutions Integration (preview)"), EmbeddedInstance("MSFT_FabricTenantSetting")] string PowerPlatformSolutionsIntegrationTenant;
    [Write, Description("Print dashboards and reports"), EmbeddedInstance("MSFT_FabricTenantSetting")] string Printing;
    [Write, Description("Featured content"), EmbeddedInstance("MSFT_FabricTenantSetting")] string PromoteContent;
    [Write, Description("Publish apps to the entire organization"), EmbeddedInstance("MSFT_FabricTenantSetting")] string PublishContentPack;
    [Write, Description("Publish to web"), EmbeddedInstance("MSFT_FabricTenantSetting")] string PublishToWeb;
    [Write, Description("Review questions"), EmbeddedInstance("MSFT_FabricTenantSetting")] string QnaFeedbackLoop;
    [Write, Description("Synonym sharing"), EmbeddedInstance("MSFT_FabricTenantSetting")] string QnaLsdlSharing;
    [Write, Description("Scale out queries for large semantic models"), EmbeddedInstance("MSFT_FabricTenantSetting")] string QueryScaleOutTenant;
    [Write, Description("Redshift SSO"), EmbeddedInstance("MSFT_FabricTenantSetting")] string RedshiftSSO;
    [Write, Description("Block users from reassigning personal workspaces (My Workspace)"), EmbeddedInstance("MSFT_FabricTenantSetting")] string RestrictMyFolderCapacity;
    [Write, Description("Retail data solutions (preview) "), EmbeddedInstance("MSFT_FabricTenantSetting")] string RetailSolutionsTenantSwitch;
    [Write, Description("Interact with and share R and Python visuals"), EmbeddedInstance("MSFT_FabricTenantSetting")] string RScriptVisual;
    [Write, Description("Service principals can use Fabric APIs"), EmbeddedInstance("MSFT_FabricTenantSetting")] string ServicePrincipalAccess;
    [Write, Description("Allow shareable links to grant access to everyone in your organization"), EmbeddedInstance("MSFT_FabricTenantSetting")] string ShareLinkToEntireOrg;
    [Write, Description("Enable Microsoft Teams integration"), EmbeddedInstance("MSFT_FabricTenantSetting")] string ShareToTeamsTenant;
    [Write, Description("Snowflake SSO"), EmbeddedInstance("MSFT_FabricTenantSetting")] string SnowflakeSSO;
    [Write, Description("Enable Power BI add-in for PowerPoint"), EmbeddedInstance("MSFT_FabricTenantSetting")] string StorytellingTenant;
    [Write, Description("Sustainability solutions (preview)"), EmbeddedInstance("MSFT_FabricTenantSetting")] string SustainabilitySolutionsTenantSwitch;
    [Write, Description("Create template organizational apps"), EmbeddedInstance("MSFT_FabricTenantSetting")] string TemplatePublish;
    [Write, Description("Publish Get Help information"), EmbeddedInstance("MSFT_FabricTenantSetting")] string TenantSettingPublishGetHelpInfo;
    [Write, Description("Data Activator (preview)"), EmbeddedInstance("MSFT_FabricTenantSetting")] string TridentPrivatePreview;
    [Write, Description("Usage metrics for content creators"), EmbeddedInstance("MSFT_FabricTenantSetting")] string UsageMetrics;
    [Write, Description("Per-user data in usage metrics for content creators"), EmbeddedInstance("MSFT_FabricTenantSetting")] string UsageMetricsTrackUserLevelInfo;
    [Write, Description("Use semantic models across workspaces"), EmbeddedInstance("MSFT_FabricTenantSetting")] string UseDatasetsAcrossWorkspaces;
    [Write, Description("Integration with SharePoint and Microsoft Lists"), EmbeddedInstance("MSFT_FabricTenantSetting")] string VisualizeListInPowerBI;
    [Write, Description("Web content on dashboard tiles"), EmbeddedInstance("MSFT_FabricTenantSetting")] string WebContentTilesTenant;
    [Write, Description("Users can edit data models in the Power BI service (preview)"), EmbeddedInstance("MSFT_FabricTenantSetting")] string WebModelingTenantSwitch;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Secret of the Azure Active Directory application to authenticate with."), EmbeddedInstance("MSFT_Credential")] String ApplicationSecret;
    [Write, Description("Id of the Azure Active Directory tenant used for authentication.")] String TenantId;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Access token used for authentication.")] String AccessTokens[];
};
