[ClassVersion("1.0.0.0"), FriendlyName("O365OrgSettings")]
class MSFT_O365OrgSettings : OMI_BaseResource
{
    [Key, Description("Specifies the resource is a single instance, the value must be 'Yes'"), ValueMap{"Yes"}, Values{"Yes"}] String IsSingleInstance;
    [Write, Description("Allow people in your organization to start trial subscriptions for apps and services that support trials. Admins manage licenses for these trials in the same way as other licenses in your organization. Only admins can upgrade these trials to paid subscriptions, so they won’t affect your billing.")] Boolean AppsAndServicesIsAppAndServicesTrialEnabled;
    [Write, Description("Allow people in your organization to access the Office Store using their work account. The Office Store provides access to apps that aren't curated or managed by Microsoft.")] Boolean AppsAndServicesIsOfficeStoreEnabled;
    [Write, Description("Allow Cortana in windows 10 (version 1909 and earlier), and the Cortana app on iOS and Android, to access Microsoft-hosted data on behalf of people in your organization.")] Boolean CortanaEnabled;
    [Write, Description("Automatically block any internal surveys that request confidential information. Admins will be notified in the Message Center when a survey is blocked.")] Boolean DynamicsCustomerVoiceIsInOrgFormsPhishingScanEnabled;
    [Write, Description("Capture the first and last names of respondents in your organization that complete a survey. You can still change this for individual surveys.")] Boolean DynamicsCustomerVoiceIsRecordIdentityByDefaultEnabled;
    [Write, Description("Capture the first and last names of respondents in your organization that complete a survey. You can still change this for individual surveys.")] Boolean DynamicsCustomerVoiceIsRestrictedSurveyAccessEnabled;
    [Write, Description("Allow YouTube and Bing.")] Boolean FormsIsBingImageSearchEnabled;
    [Write, Description("External Sharing - Send a link to the form and collect responses.")] Boolean FormsIsExternalSendFormEnabled;
    [Write, Description("External Sharing - Share to collaborate on the form layout and structure.")] Boolean FormsIsExternalShareCollaborationEnabled;
    [Write, Description("External Sharing - Share form result summary.")] Boolean FormsIsExternalShareResultEnabled;
    [Write, Description("External Sharing - Share the form as a template that can be duplicated.")] Boolean FormsIsExternalShareTemplateEnabled;
    [Write, Description("Phishing protection.")] Boolean FormsIsInOrgFormsPhishingScanEnabled;
    [Write, Description("Record names of people in your org.")] Boolean FormsIsRecordIdentityByDefaultEnabled;
    [Write, Description("Let users open files stored in third-party storage services in Microsoft 365 on the Web.")] Boolean M365WebEnableUsersToOpenFilesFrom3PStorage;
    [Write, Description("Specifies whether or not to let people in your organization receive Briefing email from Microsoft Viva.")] Boolean MicrosoftVivaBriefingEmail;
    [Write, Description("Specifies whether or not to allow users to have access to use the Viva Insights web experience.")] Boolean VivaInsightsWebExperience;
    [Write, Description("Specifies whether or not to allow users to have access to use the Viva Insights digest email feature.")] Boolean VivaInsightsDigestEmail;
    [Write, Description("Specifies whether or not to allow users to have access to use the Viva Insights Outlook add-in and inline suggestions.")] Boolean VivaInsightsOutlookAddInAndInlineSuggestions;
    [Write, Description("Specifies whether or not to allow users to have access to use the Viva Insights schedule send suggestions feature.")] Boolean VivaInsightsScheduleSendSuggestions;
    [Write, Description("Allow Planner users to publish their plans and assigned tasks to Outlook or other calendars through iCalendar feeds.")] Boolean PlannerAllowCalendarSharing;
    [Write, Description("To Do - Allow external users to join.")] Boolean ToDoIsExternalJoinEnabled;
    [Write, Description("To Do - Allow sharing with external users.")] Boolean ToDoIsExternalShareEnabled;
    [Write, Description("To Do - Allow your users to receive push notifications.")] Boolean ToDoIsPushNotificationEnabled;
    [Write, Description("Controls whether or not the Admin Center reports will conceale user, group and site names.")] Boolean AdminCenterReportDisplayConcealedNames;
    [Write, Description("Defines how often you want your users to get feature updates for Microsoft 365 apps installed on devices running Windows"), ValueMap{"current","monthlyEnterprise","semiAnnual"}, Values{"current","monthlyEnterprise","semiAnnual"}] String InstallationOptionsUpdateChannel;
    [Write, Description("Defines the apps users can install on Windows and mobile devices."), ValueMap{"isVisioEnabled","isSkypeForBusinessEnabled","isProjectEnabled","isMicrosoft365AppsEnabled"}, Values{"isVisioEnabled","isSkypeForBusinessEnabled","isProjectEnabled","isMicrosoft365AppsEnabled"}] String InstallationOptionsAppsForWindows[];
    [Write, Description("Defines the apps users can install on Mac devices."), ValueMap{"isSkypeForBusinessEnabled","isMicrosoft365AppsEnabled"}, Values{"isSkypeForBusinessEnabled","isMicrosoft365AppsEnabled"}] String InstallationOptionsAppsForMac[];
    [Write, Description("Credentials of the Global Admin"), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Id of the Azure Active Directory tenant used for authentication.")] String TenantId;
    [Write, Description("Secret of the Azure Active Directory tenant used for authentication."), EmbeddedInstance("MSFT_Credential")] String ApplicationSecret;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Managed ID being used for authentication.")] Boolean ManagedIdentity;
    [Write, Description("Access token used for authentication.")] String AccessTokens[];
};
