[ClassVersion("1.0.0.0"), FriendlyName("EXOM365DataAtRestEncryptionPolicy")]
class MSFT_EXOM365DataAtRestEncryptionPolicy : OMI_BaseResource
{
    [Key, Description("The Identity parameter specifies the data-at-rest encryption policy that you want to modify.")] String Identity;
    [Write, Description("The Name parameter specifies a unique name for the Microsoft 365 data-at-rest encryption policy.")] String Name;
    [Write, Description("The Description parameter specifies an optional description for the policy.")] String Description;
    [Write, Description("The Enabled parameter specifies whether the policy is enabled or disabled. ")] Boolean Enabled;
    [Write, Description("The AzureKeyIDs parameter specifies the URL of the encryption key in the Azure Key Vault that's used for encryption.")] String AzureKeyIDs[];
    [Write, Description("Present ensures the instance exists, absent ensures it is removed."), ValueMap{"Absent","Present"}, Values{"Absent","Present"}] string Ensure;
    [Write, Description("Credentials of the workload's Admin"), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Id of the Azure Active Directory tenant used for authentication.")] String TenantId;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Managed ID being used for authentication.")] Boolean ManagedIdentity;
    [Write, Description("Access token used for authentication.")] String AccessTokens[];
};
