[ClassVersion("1.0.0.0"), FriendlyName("TeamsMeetingConfiguration")]
class MSFT_TeamsMeetingConfiguration : OMI_BaseResource
{
    [Key, Description("The only valid input is Global - the tenant wide configuration"), ValueMap{"Global"}, Values{"Global"}] string Identity;
    [Write, Description("URL to a logo image. This would be included in the meeting invite. Please ensure this URL is publicly accessible for invites that go beyond your federation boundaries.")] String LogoURL;
    [Write, Description("URL to a website containing legal information and meeting disclaimers. This would be included in the meeting invite. Please ensure this URL is publicly accessible for invites that go beyond your federation boundaries.")] String LegalURL;
    [Write, Description("URL to a website where users can obtain assistance on joining the meeting.This would be included in the meeting invite. Please ensure this URL is publicly accessible for invites that go beyond your federation boundaries.")] String HelpURL;
    [Write, Description("Text to be used on custom meeting invitations.")] String CustomFooterText;
    [Write, Description("Determines whether anonymous users are blocked from joining meetings in the tenant. Set this to TRUE to block anonymous users from joining. Set this to FALSE to allow anonymous users to join meetings.")] Boolean DisableAnonymousJoin;
    [Write, Description("Determines whether Quality of Service Marking for real-time media (audio, video, screen/app sharing) is enabled in the tenant. Set this to TRUE to enable and FALSE to disable.")] Boolean EnableQoS;
    [Write, Description("Determines the starting port number for client audio. Minimum allowed value: 1024 Maximum allowed value: 65535 Default value: 50000.")] UInt32 ClientAudioPort;
    [Write, Description("Determines the total number of ports available for client audio. Default value is 20.")] UInt32 ClientAudioPortRange;
    [Write, Description("Determines the starting port number for client video. Minimum allowed value: 1024 Maximum allowed value: 65535 Default value: 50020.")] UInt32 ClientVideoPort;
    [Write, Description("Determines the total number of ports available for client video. Default value is 20.")] UInt32 ClientVideoPortRange;
    [Write, Description("Determines the starting port number for client screen sharing or application sharing. Minimum allowed value: 1024 Maximum allowed value: 65535 Default value: 50040.")] UInt32 ClientAppSharingPort;
    [Write, Description("Determines whether custom media port and range selections need to be enforced. When set to True, clients will use the specified port range for media traffic. When set to False (the default value) for any available port (from port 1024 through port 65535) will be used to accommodate media traffic.")] Boolean ClientMediaPortRangeEnabled;
    [Write, Description("Determines the total number of ports available for client sharing or application sharing. Default value is 20.")] UInt32 ClientAppSharingPortRange;
    [Write, Description("Credentials of the Teams Admin"), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Name of the Azure Active Directory tenant used for authentication. Format contoso.onmicrosoft.com")] String TenantId;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Managed ID being used for authentication.")] Boolean ManagedIdentity;
};
