
[ClassVersion("1.0.0.0"), FriendlyName("IntuneDeviceEnrollmentConfigurationWindows10")]
class MSFT_IntuneDeviceEnrollmentConfigurationWindows10 : OMI_BaseResource
{
    [Key, Description("The display name of the device enrollment configuration")] String DisplayName;
    [Required, Description("The unique identifier for an entity. Read-only.")] String Id;
    [Write, Description("The description of the device enrollment configuration")] String Description;
    [Write, Description("Allow or block device reset on installation failure")] Boolean AllowDeviceResetOnInstallFailure;
    [Write, Description("Allow the user to continue using the device on installation failure")] Boolean AllowDeviceUseOnInstallFailure;
    [Write, Description("Allow or block log collection on installation failure")] Boolean AllowLogCollectionOnInstallFailure;
    [Write, Description("Install all required apps as non blocking apps during white glove")] Boolean AllowNonBlockingAppInstallation;
    [Write, Description("Allow the user to retry the setup on installation failure")] Boolean BlockDeviceSetupRetryByUser;
    [Write, Description("Set custom error message to show upon installation failure")] String CustomErrorMessage;
    [Write, Description("Only show installation progress for first user post enrollment")] Boolean DisableUserStatusTrackingAfterFirstUser;
    [Write, Description("Set installation progress timeout in minutes")] UInt32 InstallProgressTimeoutInMinutes;
    [Write, Description("Allows quality updates installation during OOBE")] Boolean InstallQualityUpdates;
    [Write, Description("Selected applications to track the installation status")] String SelectedMobileAppIds[];
    [Write, Description("Show or hide installation progress to user")] Boolean ShowInstallationProgress;
    [Write, Description("Only show installation progress for Autopilot enrollment scenarios")] Boolean TrackInstallProgressForAutopilotOnly;
    [Write, Description("Present ensures the policy exists, absent ensures it is removed."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] string Ensure;
    [Write, Description("Credentials of the Admin"), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Id of the Azure Active Directory tenant used for authentication.")] String TenantId;
    [Write, Description("Secret of the Azure Active Directory tenant used for authentication."), EmbeddedInstance("MSFT_Credential")] String ApplicationSecret;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Managed ID being used for authentication.")] Boolean ManagedIdentity;
};
