[ClassVersion("1.0.0.0"), FriendlyName("EXODataClassification")]
class MSFT_EXODataClassification : OMI_BaseResource
{
    [Key, Description("The Identity parameter specifies the data classification rule that you want to modify.")] String Identity;
    [Write, Description("The Description parameter specifies a description for the data classification rule. You use the Description parameter with the Locale and Name parameters to specify descriptions for the data classification rule in different languages. ")] String Description;
    [Write, Description("The Fingerprints parameter specifies the byte-encoded document files that are used as fingerprints by the data classification rule.")] String Fingerprints[];
    [Write, Description("IsDefault is used with the Locale parameter to specify the default language for the data classification rule.")] Boolean IsDefault;
    [Write, Description("The Locale parameter adds or removes languages that are associated with the data classification rule.")] String Locale;
    [Write, Description("The Name parameter specifies a name for the data classification rule. The value must be less than 256 characters.")] String Name;
    [Write, Description("Specifies if this policy should exist."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Write, Description("Credentials of the Exchange Global Admin"), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Id of the Azure Active Directory tenant used for authentication.")] String TenantId;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Username can be made up to anything but password will be used for CertificatePassword"), EmbeddedInstance("MSFT_Credential")] String CertificatePassword;
    [Write, Description("Path to certificate used in service principal usually a PFX file.")] String CertificatePath;
    [Write, Description("Managed ID being used for authentication.")] Boolean ManagedIdentity;
    [Write, Description("Access token used for authentication.")] String AccessTokens[];
};
