[ClassVersion("1.0.0.0"), FriendlyName("EXOHostedConnectionFilterPolicy")]
class MSFT_EXOHostedConnectionFilterPolicy : OMI_BaseResource
{
    [Key, Description("The Identity parameter specifies the Hosted Connection Filter Policy that you want to modify.")] String Identity;
    [Write, Description("The AdminDisplayName parameter specifies a description for the policy.")] String AdminDisplayName;
    [Write, Description("The EnableSafeList parameter enables or disables use of the safe list. The safe list is a dynamic allow list in the Microsoft datacenter that requires no customer configuration. Valid input for this parameter is $true or $false. The default value is $false.")] Boolean EnableSafeList;
    [Write, Description("The IPAllowList parameter specifies IP addresses from which messages are always allowed. Messages from the IP addresses you specify won't be identified as spam, despite any other spam characteristics of the messages. Valid values for this parameter are: A single IP address, an IP address range, a CIDR IP.")] String IPAllowList[];
    [Write, Description("The IPBlockList parameter specifies IP addresses from which messages are never allowed. Messages from the IP addresses you specify are blocked without any further spam scanning. Valid values for this parameter are: A single IP address, an IP address range, a CIDR IP.")] String IPBlockList[];
    [Write, Description("The MakeDefault parameter makes the specified policy the default connection filter policy. Default is $false.")] Boolean MakeDefault;
    [Write, Description("Specifies if this Hosted Connection Filter Policy should exist."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Required, Description("Credentials of the Exchange Global Admin"), EmbeddedInstance("MSFT_Credential")] String GlobalAdminAccount;
};
