
[ClassVersion("1.0.0.0"), FriendlyName("EXOIntraOrganizationConnector")]
class MSFT_EXOIntraOrganizationConnector : OMI_BaseResource
{
    [Key, Description("The Identity parameter specifies the intraorg connector that you want to modify.")] String Identity;
    [Write, Description("The DiscoveryEndpoint parameter specifies the externally-accessible URL that's used for the Autodiscover service for the domain that's configured in the Intra-Organization connector.")] String DiscoveryEndpoint;
    [Write, Description("Specifies whether connector is enabled.")] Boolean Enabled;
    [Write, Description("The TargetAddressDomains parameter specifies the domain namespaces that will be used in the Intra-organization connector. These domains must have valid Autodiscover endpoints defined in their organizations. The domains and their associated Autodiscover endpoints are used by the Intra-Organization connector for feature and service connectivity. You can specify multiple domains separated by commas.")] String TargetAddressDomains[];
    [Write, Description("Specifies if this Intra-Organization connector should exist."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Required, Description("Credentials of the Exchange Global Admin"), EmbeddedInstance("MSFT_Credential")] String GlobalAdminAccount;
};
