[ClassVersion("1.0.0.0"), FriendlyName("TeamsGuestMeetingConfiguration")]
class MSFT_TeamsGuestMeetingConfiguration : OMI_BaseResource
{
    [Key, Description("The only valid input is Global - the tenant wide configuration"), ValueMap{"Global"}, Values{"Global"}] string Identity;
    [Write, Description("Determines whether video is enabled in a user's meetings or calls. Set this to TRUE to allow guests to share their video. Set this to FALSE to prohibit guests from sharing their video.")] boolean AllowIPVideo;
    [Write, Description("Determines whether real-time captions are available for guests in Teams meetings."), ValueMap{"Disabled","DisabledUserOverride"}, Values{"Disabled","DisabledUserOverride"}] string LiveCaptionsEnabledType;
    [Write, Description("Determines the mode in which guests can share a screen in calls or meetings. Set this to SingleApplication to allow the user to share an application at a given point in time. Set this to EntireScreen to allow the user to share anything on their screens. Set this to Disabled to prohibit the user from sharing their screens."), ValueMap{"Disabled","EntireScreen","SingleApplication"}, Values{"Disabled","EntireScreen","SingleApplication"}] string ScreenSharingMode;
    [Write, Description("Determines whether guests can start ad-hoc meetings. Set this to TRUE to allow guests to start ad-hoc meetings. Set this to FALSE to prohibit guests from starting ad-hoc meetings.")] boolean AllowMeetNow;
    [Write, Description("Credentials of the Teams Admin"), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Name of the Azure Active Directory tenant used for authentication. Format contoso.onmicrosoft.com")] String TenantId;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Managed ID being used for authentication.")] Boolean ManagedIdentity;
};
