[ClassVersion("1.0.0.1"), FriendlyName("TeamsOnlineVoicemailPolicy")]
class MSFT_TeamsOnlineVoicemailPolicy : OMI_BaseResource
{
    [Key, Description("Identity of the Teams Online Voicemail Policy.")] String Identity;
    [Write, Description("Controls if editing call answer rule settings are enabled or disabled for a user. Possible values are $true or $false.")] Boolean EnableEditingCallAnswerRulesSetting;
    [Write, Description("Allows you to disable or enable voicemail transcription. Possible values are $true or $false.")] Boolean EnableTranscription;
    [Write, Description("Allows you to disable or enable profanity masking for the voicemail transcriptions. Possible values are $true or $false.")] Boolean EnableTranscriptionProfanityMasking;
    [Write, Description("Allows you to disable or enable translation for the voicemail transcriptions. Possible values are $true or $false.")] Boolean EnableTranscriptionTranslation;
    [Write, Description("A duration of voicemail maximum recording length. The length should be between 30 seconds to 600 seconds.")] SInt32 MaximumRecordingLength;
    [Write, Description("The audio file to play to the caller after the user's voicemail greeting has played and before the caller is allowed to leave a voicemail message.")] String PostambleAudioFile;
    [Write, Description("The audio file to play to the caller before the user's voicemail greeting is played.")] String PreambleAudioFile;
    [Write, Description("Is playing the Pre- or Post-amble mandatory before the caller can leave a message. Possible values are $true or $false.")] Boolean PreamblePostambleMandatory;
    [Write, Description("The primary (or first) language that voicemail system prompts will be presented in. Must also set SecondarySystemPromptLanguage. When set, this overrides the user language choice.")] String PrimarySystemPromptLanguage;
    [Write, Description("The secondary language that voicemail system prompts will be presented in. Must also set PrimarySystemPromptLanguage and may not be the same value as PrimarySystemPromptanguage. When set, this overrides the user language choice. ")] String SecondarySystemPromptLanguage;
    [Write, Description("Specifies whether voicemail and transcription data are shared with the service for training and improving accuracy. Possible values are Defer and Deny.")] String ShareData;
    [Write, Description("Present ensures the policy exists, absent ensures it is removed."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Write, Description("Credentials of the Teams Global Admin."), EmbeddedInstance("MSFT_Credential")] String Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Name of the Azure Active Directory tenant used for authentication. Format contoso.onmicrosoft.com")] String TenantId;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Username can be made up to anything but password will be used for CertificatePassword"), EmbeddedInstance("MSFT_Credential")] String CertificatePassword;
    [Write, Description("Path to certificate used in service principal usually a PFX file.")] String CertificatePath;
    [Write, Description("Managed ID being used for authentication.")] Boolean ManagedIdentity;
    [Write, Description("Access token used for authentication.")] String AccessTokens[];
};
