[ClassVersion("1.0.0.0"), FriendlyName("TeamsTargetingPolicy")]
class MSFT_TeamsTargetingPolicy : OMI_BaseResource
{
    [Key, Description("Only valid value is 'Yes'."), ValueMap{"Yes"}, Values{"Yes"}] String IsSingleInstance;
    [Write, Description("Determine whether Teams users can create tags in team. Set this to Enabled to allow users to create new tags. Set this to Disabled to prohibit them from creating new tags."), ValueMap{"Disabled","Enabled"}, Values{"Disabled","Enabled"}] String CustomTagsMode;
    [Write, Description("Pass in a new description if that field needs to be updated.")] String Description;
    [Write, Description("Determine whether team users can manage tag settings in Teams. Set this to EnabledTeamOwner to only allow Teams owners to manage tag settings in current Teams. Set this to EnabledTeamOwnerMember to allow Teams owners and Teams members to manage tag settings in current Teams. Set this to EnabledTeamOwnerMemberGuest to allow Teams owners, Teams members and guest users to manage tag settings in current Teams. Set this to MicrosoftDefault to user default setting in current Teams, which will be the same as EnabledTeamOwner. Set this to Disabled to prohibit all users from managing tag settings in current Teams."), ValueMap{"Disabled","EnabledTeamOwner","EnabledTeamOwnerMember","EnabledTeamOwnerMemberGuest","MicrosoftDefault"}, Values{"Disabled","EnabledTeamOwner","EnabledTeamOwnerMember","EnabledTeamOwnerMemberGuest","MicrosoftDefault"}] String ManageTagsPermissionMode;
    [Write, Description("Determine whether Teams can have tags created by Shift App. Set this to Enabled to allow tags created by Shift App. Set this to Disabled to prohibit tags from Shift App."), ValueMap{"Disabled","Enabled"}, Values{"Disabled","Enabled"}] String ShiftBackedTagsMode;
    [Write, Description("TBD")] String SuggestedPresetTags;
    [Write, Description("Determine whether Teams owners can change Tenant tag settings. Set this to Enabled to allow Teams owners to change Tenant tag settings for current Teams. Set this to Disabled to prohibit them from changing Tenant tag settings."), ValueMap{"Disabled","Enabled"}, Values{"Disabled","Enabled"}] String TeamOwnersEditWhoCanManageTagsMode;
    [Write, Description("Credentials of the workload's Admin"), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Id of the Azure Active Directory tenant used for authentication.")] String TenantId;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Path to certificate used in service principal usually a PFX file.")] String CertificatePath;
    [Write, Description("Username can be made up to anything but password will be used for CertificatePassword"), EmbeddedInstance("MSFT_Credential")] String CertificatePassword;
    [Write, Description("Managed ID being used for authentication.")] Boolean ManagedIdentity;
    [Write, Description("Access token used for authentication.")] String AccessTokens[];
};
