[ClassVersion("1.0.0.0"), FriendlyName("EXOManagementScope")]
class MSFT_EXOManagementScope : OMI_BaseResource
{
    [Key, Description("The Identity parameter specifies the name of the management scope to modify.")] String Identity;
    [Write, Description("The Name parameter specifies the name of the management scope.")] String Name;
    [Write, Description("The RecipientRestrictionFilter parameter uses OPATH filter syntax to specify the recipients that are included in the scope.")] String RecipientRestrictionFilter;
    [Write, Description("The RecipientRoot parameter specifies the organizational unit (OU) under which the filter specified with the RecipientRestrictionFilter parameter should be applied.")] String RecipientRoot;
    [Write, Description("The Exclusive switch specifies that the role should be an exclusive scope.")] Boolean Exclusive;
    [Write, Description("Specifies if this Outbound connector should exist."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Write, Description("Credentials of the workload's Admin"), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Id of the Azure Active Directory tenant used for authentication.")] String TenantId;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Managed ID being used for authentication.")] Boolean ManagedIdentity;
    [Write, Description("Access token used for authentication.")] String AccessTokens[];
};
