[ClassVersion("1.0.0.0"), FriendlyName("ADOPermissionGroup")]
class MSFT_ADOPermissionGroup : OMI_BaseResource
{
    [Key, Description("The name of the Azure DevOPS Organization.")] String OrganizationName;
    [Key, Description("Principal name to identify the group.")] String PrincipalName;
    [Write, Description("Display name for the group.")] String DisplayName;
    [Write, Description("Description of the group.")] String Description;
    [Write, Description("List of principal names of the members of the group.")] String Members[];
    [Write, Description("Unique identifier for the group.")] String Id;
    [Write, Description("Unique descriptor for the group.")] String Descriptor;
    [Write, Description("Determines at what level in the hierarchy the group exists. Valid values are Project or Organization."), ValueMap{"Organization", "Project"}, Values{"Organization", "Project"}] String Level;
    [Write, Description("Present ensures the instance exists, absent ensures it is removed."), ValueMap{"Present", "Absent"}, Values{"Present", "Absent"}] string Ensure;
    [Write, Description("Credentials of the workload's Admin"), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Id of the Azure Active Directory tenant used for authentication.")] String TenantId;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Managed ID being used for authentication.")] Boolean ManagedIdentity;
    [Write, Description("Access token used for authentication.")] String AccessTokens[];
};
