[ClassVersion("1.0.0.0"), FriendlyName("M365DSCRuleEvaluation")]
class MSFT_M365DSCRuleEvaluation : OMI_BaseResource
{
    [Key, Description("Name of the resource to monitor")] String ResourceTypeName;
    [Required, Description("Specify the rules to monitor the resource for.")] String RuleDefinition;
    [Write, Description("Query to check how many instances exist, using PowerShell format")] String AfterRuleCountQuery;
    [Write, Description("Credentials of the Azure Active Directory Admin"), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Id of the Azure Active Directory tenant used for authentication.")] String TenantId;
    [Write, Description("Secret of the Azure Active Directory application to authenticate with."), EmbeddedInstance("MSFT_Credential")] String ApplicationSecret;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Managed ID being used for authentication.")] Boolean ManagedIdentity;
    [Write, Description("Access token used for authentication.")] String AccessTokens[];
};
