[ClassVersion("1.0.0.0"), FriendlyName("SCRetentionCompliancePolicy")]
class MSFT_SCRetentionCompliancePolicy : OMI_BaseResource
{
    [Key, Description("The Name parameter specifies the unique name of the retention policy.")] String Name;
    [Write, Description("Specify if this policy should exist or not."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Write, Description("The Comment parameter specifies an optional comment.")] String Comment;
    [Write, Description("Location of the dynamic scope for this policy.")] String DynamicScopeLocation[];
    [Write, Description("Determines if the policy is enabled or not.")] Boolean Enabled;
    [Write, Description("The ExchangeLocation parameter specifies the mailboxes to include.")] String ExchangeLocation[];
    [Write, Description("This parameter specifies the mailboxes to remove from the list of excluded mailboxes when you use the value All for the ExchangeLocation parameter")] String ExchangeLocationException[];
    [Write, Description("The ModernGroupLocation parameter specifies the Office 365 groups to include in the policy.")] String ModernGroupLocation[];
    [Write, Description("The ModernGroupLocationException parameter specifies the Office 365 groups to exclude when you're using the value All for the ModernGroupLocation parameter.")] String ModernGroupLocationException[];
    [Write, Description("The OneDriveLocation parameter specifies the OneDrive for Business sites to include. You identify the site by its URL value, or you can use the value All to include all sites.")] String OneDriveLocation[];
    [Write, Description("This parameter specifies the OneDrive for Business sites to exclude when you use the value All for the OneDriveLocation parameter. You identify the site by its URL value.")] String OneDriveLocationException[];
    [Write, Description("The PublicFolderLocation parameter specifies that you want to include all public folders in the retention policy. You use the value All for this parameter.")] String PublicFolderLocation[];
    [Write, Description("The RestrictiveRetention parameter specifies whether Preservation Lock is enabled for the policy.")] Boolean RestrictiveRetention;
    [Write, Description("The SharePointLocation parameter specifies the SharePoint Online sites to include. You identify the site by its URL value, or you can use the value All to include all sites.")] String SharePointLocation[];
    [Write, Description("This parameter specifies the SharePoint Online sites to exclude when you use the value All for the SharePointLocation parameter. You identify the site by its URL value.")] String SharePointLocationException[];
    [Write, Description("The SkypeLocation parameter specifies the Skype for Business Online users to include in the policy.")] String SkypeLocation[];
    [Write, Description("This parameter is reserved for internal Microsoft use.")] String SkypeLocationException[];
    [Write, Description("The TeamsChannelLocation parameter specifies the Teams Channel to include in the policy.")] String TeamsChannelLocation[];
    [Write, Description("This parameter specifies the SharePoint Online sites to exclude when you use the value All for the TeamsChannelLocation parameter. You identify the site by its URL value.")] String TeamsChannelLocationException[];
    [Write, Description("The TeamsChatLocation parameter specifies the Teams Chat to include in the policy.")] String TeamsChatLocation[];
    [Write, Description("This parameter specifies the SharePoint Online sites to exclude when you use the value All for the TeamsChatLocation parameter. You identify the site by its URL value.")] String TeamsChatLocationException[];
    [Write, Description("Credentials of the Exchange Global Admin"), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Id of the Azure Active Directory tenant used for authentication.")] String TenantId;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Username can be made up to anything but password will be used for CertificatePassword"), EmbeddedInstance("MSFT_Credential")] String CertificatePassword;
    [Write, Description("Path to certificate used in service principal usually a PFX file.")] String CertificatePath;
    [Write, Description("Access token used for authentication.")] String AccessTokens[];
};
