[ClassVersion("1.0.0")]
class MSFT_DefenderRoleDefinitionRolePermissions
{
    [Write, Description("Set of tasks that can be performed on a resource.")] String allowedResourceActions[];
};

[ClassVersion("1.0.0.0"), FriendlyName("DefenderRoleDefinition")]
class MSFT_DefenderRoleDefinition : OMI_BaseResource
{
    [Key, Description("The display name for the role definition.")] String DisplayName;
    [Write, Description("The id of the role definition.")] String Id;
    [Write, Description("The description of the role definition.")] String Description;
    [Write, Description("List of permissions included in the role."), EmbeddedInstance("MSFT_DefenderRoleDefinitionRolePermissions")] String RolePermissions[];

    [Write, Description("Present ensures the instance exists, absent ensures it is removed."), ValueMap{"Absent","Present"}, Values{"Absent","Present"}] string Ensure;
    [Write, Description("Credentials of the workload's Admin"), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Id of the Azure Active Directory tenant used for authentication.")] String TenantId;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Managed ID being used for authentication.")] Boolean ManagedIdentity;
    [Write, Description("Access token used for authentication.")] String AccessTokens[];
};
