
[ClassVersion("1.0.0.0"), FriendlyName("EXOQuarantinePolicy")]
class MSFT_EXOQuarantinePolicy : OMI_BaseResource
{
    [Key, Description("The Identity parameter specifies the QuarantinePolicy you want to modify.")] String Identity;
    [Write, Description("The EndUserQuarantinePermissionsValue parameter specifies the end-user permissions for the quarantine policy.")] UInt32 EndUserQuarantinePermissionsValue;
    [Write, Description("The ESNEnabled parameter specifies whether to enable quarantine notifications (formerly known as end-user spam notifications) for the policy.")] Boolean ESNEnabled;
    [Write, Description("The MultiLanguageCustomDisclaimer parameter specifies the custom disclaimer text to use near the bottom of quarantine notifications.")] String MultiLanguageCustomDisclaimer[];
    [Write, Description("The MultiLanguageSenderName parameter specifies the email sender's display name to use in quarantine notifications.")] String MultiLanguageSenderName[];
    [Write, Description("The MultiLanguageSetting parameter specifies the language of quarantine notifications.")] String MultiLanguageSetting[];
    [Write, Description("The OrganizationBrandingEnabled parameter enables or disables organization branding in the end-user quarantine notification messages.")] Boolean OrganizationBrandingEnabled;
    [Write, Description("Specifies if this QuarantinePolicy should exist."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Write, Description("Credentials of the Exchange Global Admin"), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Id of the Azure Active Directory tenant used for authentication.")] String TenantId;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Username can be made up to anything but password will be used for CertificatePassword"), EmbeddedInstance("MSFT_Credential")] String CertificatePassword;
    [Write, Description("Path to certificate used in service principal usually a PFX file.")] String CertificatePath;
    [Write, Description("Managed ID being used for authentication.")] Boolean ManagedIdentity;
    [Write, Description("The EndUserSpamNotificationFrequency parameter species how often quarantine notifications are sent to users. Valid values are: 04:00:00 (4 hours),1.00:00:00 (1 day),7.00:00:00 (7 days)")] String EndUserSpamNotificationFrequency;
    [Write, Description("The QuarantinePolicyType parameter filters the results by the specified quarantine policy type. Valid values are: QuarantinePolicy, GlobalQuarantinePolicy")] String QuarantinePolicyType;
	[Write, Description("This parameter is reserved for internal Microsoft use.")] String EndUserSpamNotificationFrequencyInDays;
    [Write, Description("This parameter is reserved for internal Microsoft use.")] String CustomDisclaimer;
    [Write, Description("The EndUserSpamNotificationCustomFromAddress specifies the email address of an existing internal sender to use as the sender for quarantine notifications. To set this parameter back to the default email address quarantine@messaging.microsoft.com, use the value $null.")] String EndUserSpamNotificationCustomFromAddress;
    [Write, Description("The EsnCustomSubject parameter specifies the text to use in the Subject field of quarantine notifications.This setting is available only in the built-in quarantine policy named DefaultGlobalTag that controls global quarantine policy settings.")] String EsnCustomSubject[];
    [Write, Description("Access token used for authentication.")] String AccessTokens[];
};
