[ClassVersion("1.0.0.0"), FriendlyName("TeamsOrgWideAppSettings")]
class MSFT_TeamsOrgWideAppSettings : OMI_BaseResource
{
    [Key, Description("Specifies the resource is a single instance, the value must be 'Yes'"),ValueMap{"Yes"},Values{"Yes"}] String IsSingleInstance;
    [Write, Description("Determines whether or not to allow interaction with custom apps.")] Boolean IsSideloadedAppsInteractionEnabled;
    [Write, Description("Credentials of the Teams Admin"), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Managed ID being used for authentication.")] Boolean ManagedIdentity;
};
