
[ClassVersion("1.0.0.0"), FriendlyName("IntuneDeviceEnrollmentScopeConfigurationMam")]
class MSFT_IntuneDeviceEnrollmentScopeConfigurationMam : OMI_BaseResource
{
    [Key, Description("Only valid value is 'Yes'."), ValueMap{"Yes"}, Values{"Yes"}] String IsSingleInstance;
    [Write, Description("Indicates the user scope of the mobility management policy. The possible values are: none, all, selected."), ValueMap{"none","all","selected"}, Values{"none","all","selected"}] String AppliesTo;
    [Write, Description("Compliance URL of the mobility management application.")] String ComplianceUrl;
    [Write, Description("Discovery URL of the mobility management application.")] String DiscoveryUrl;
    [Write, Description("Terms of Use URL of the mobility management application.")] String TermsOfUseUrl;
    [Write, Description("The group display names that are included if the scope is set to 'Selected'.")] String IncludedGroups[];
    [Write, Description("Credentials of the Admin"), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Id of the Azure Active Directory tenant used for authentication.")] String TenantId;
    [Write, Description("Access token used for authentication.")] String AccessTokens[];
};
