[ClassVersion("1.0.0.0"), FriendlyName("EXOMailboxPlan")]
class MSFT_EXOMailboxPlan : OMI_BaseResource
{
    [Key, Description("The Identity parameter specifies the Mailbox Plan that you want to modify.")] String Identity;
    [Write, Description("The display name of the mailbox plan.")] String DisplayName;
    [Write, Description("MailboxPlans cannot be created/removed in O365.  This must be set to 'Present'"), ValueMap{"Present"}, Values{"Present"}] String Ensure;
    [Write, Description("The IssueWarningQuota parameter specifies the warning threshold for the size of the mailboxes that are created or enabled using the mailbox plan.")] String IssueWarningQuota;
    [Write, Description("The MaxReceiveSize parameter specifies the maximum size of a message that can be sent to the mailbox.")] String MaxReceiveSize;
    [Write, Description("The MaxSendSize parameter specifies the maximum size of a message that can be sent by the mailbox.")] String MaxSendSize;
    [Write, Description("The ProhibitSendQuota parameter specifies a size limit for the mailbox.")] String ProhibitSendQuota;
    [Write, Description("The ProhibitSendReceiveQuota parameter specifies a size limit for the mailbox.")] String ProhibitSendReceiveQuota;
    [Write, Description("The RetainDeletedItemsFor parameter specifies the length of time to keep soft-deleted items for the mailbox.")] String RetainDeletedItemsFor;
    [Write, Description("The RetentionPolicy parameter specifies the retention policy that's applied to the mailbox.")] String RetentionPolicy;
    [Write, Description("The RoleAssignmentPolicy parameter specifies the role assignment policy that's applied to the mailbox.")] String RoleAssignmentPolicy;
    [Write, Description("Credentials of the Exchange Global Admin"), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Id of the Azure Active Directory tenant used for authentication.")] String TenantId;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Username can be made up to anything but password will be used for CertificatePassword"), EmbeddedInstance("MSFT_Credential")] String CertificatePassword;
    [Write, Description("Path to certificate used in service principal usually a PFX file.")] String CertificatePath;
    [Write, Description("Managed ID being used for authentication.")] Boolean ManagedIdentity;
    [Write, Description("Access token used for authentication.")] String AccessTokens[];
};
