[ClassVersion("1.0.0.0"), FriendlyName("EXOAddressBookPolicy")]
class MSFT_EXOAddressBookPolicy : OMI_BaseResource
{
    [Key, Description("The Name parameter specifies the name that you want this address book policy to be called.")] String Name;
    [Write, Description("The AddressLists parameter specifies the address lists that will be used by mailbox users who are assigned this address book policy. This parameter accepts multiple values.")] String AddressLists[];
    [Write, Description("The GlobalAddressList parameter specifies the identity of the global address list (GAL) that will be used by mailbox users who are assigned this address book policy. You can specify only one GAL for each address book policy.")] String GlobalAddressList;
    [Write, Description("The OfflineAddressBook parameter specifies the identity of the offline address book (OAB) that will be used by mailbox users who are assigned this address book policy. You can specify only one OAB for each address book policy.")] String OfflineAddressBook;
    [Write, Description("The RoomList parameter specifies the name of the room address list.")] String RoomList;
    [Write, Description("Specify if the Address Book Policy should exist or not."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Required, Description("Credentials of the Exchange Global Admin"), EmbeddedInstance("MSFT_Credential")] string GlobalAdminAccount;
};
