[ClassVersion("1.0.0.0"), FriendlyName("SCComplianceCase")]
class MSFT_SCComplianceCase : OMI_BaseResource
{
    [Key, Description("The Name parameter specifies the unique name of the compliance case.")] String Name;
    [Write, Description("The description of the case.")] String Description;
    [Write, Description("Specify if this case should exist or not."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Write, Description("Status for the case. Can either be 'Active', 'Closed' or 'ClosedWithError'"), ValueMap{"Active","Closed", "ClosedWithError"}, Values{"Active","Closed", "ClosedWithError"}] String Status;
    [Required, Description("Credentials of the Global Admin Account"), EmbeddedInstance("MSFT_Credential")] String GlobalAdminAccount;
};
