[ClassVersion("1.0.0.0"), FriendlyName("EXOEmailAddressPolicy")]
class MSFT_EXOEmailAddressPolicy : OMI_BaseResource
{
    [Key, Description("The Name parameter specifies the unique name of the email address policy. The maximum length is 64 characters.")] String Name;
    [Write, Description("The Priority parameter specifies the order that the email address policies are evaluated. By default, every time that you add a new email address policy, the policy is assigned a priority of N+1, where N is the number of email address policies that you've created.")] String Priority;
    [Write, Description("The EnabledEmailAddressTemplates parameter specifies the rules in the email address policy that are used to generate email addresses for recipients.")] String EnabledEmailAddressTemplates[];
    [Write, Description("The EnabledPrimarySMTPAddressTemplate parameter specifies the specifies the rule in the email address policy that's used to generate the primary SMTP email addresses for recipients. You can use this parameter instead of the EnabledEmailAddressTemplates if the policy only applies the primary email address and no additional proxy addresses.")] String EnabledPrimarySMTPAddressTemplate[];
    [Write, Description("The ManagedByFilter parameter specifies the email address policies to apply to Office 365 groups based on the properties of the users who create the Office 365 groups.")] String ManagedByFilter;
    [Write, Description("Specify if the Email Address Policy should exist or not."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Required, Description("Credentials of the Exchange Global Admin"), EmbeddedInstance("MSFT_Credential")] string GlobalAdminAccount;
};
