[ClassVersion("1.0.0.0"), FriendlyName("DefenderSubscriptionPlan")]
class MSFT_DefenderSubscriptionPlan : OMI_BaseResource
{
    [Key, Description("The display name of the subscription.")] String SubscriptionName;
    [Key, Description("The Defender plan name, for the list all of possible Defender plans refer to Defender for Cloud documentation")] String PlanName;
    [Write, Description("The unique identifier of the Azure subscription.")] String SubscriptionId;
    [Write, Description("The pricing tier ('Standard' or 'Free')")] String PricingTier;
    [Write, Description("The Defender sub plan name, for the list all of possible sub plans refer to Defender for Cloud documentation")] String SubPlanName;
    [Write, Description("The extensions offered under the plan, for more information refer to Defender for Cloud documentation")] String Extensions;

    [Write, Description("Present ensures the instance exists, absent ensures it is removed."), ValueMap{"Present"}, Values{"Present"}] string Ensure;
    [Write, Description("Credentials of the workload's Admin"), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Id of the Azure Active Directory tenant used for authentication.")] String TenantId;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Managed ID being used for authentication.")] Boolean ManagedIdentity;
    [Write, Description("Access token used for authentication.")] String AccessTokens[];
};

