[ClassVersion("1.0.0.0"), FriendlyName("PPPowerAppsEnvironment")]
class MSFT_PPPowerAppsEnvironment : OMI_BaseResource
{
    [Key, Description("Display name for the PowerApps environment")] String DisplayName;
    [Required, Description("Location of the PowerApps environment."), ValueMap{"canada","unitesstates","europe","asia","australia","india","japan","unitedkingdom","unitedstatesfirstrelease","southamerica","france"}, Values{"canada","unitesstates","europe","asia","australia","india","japan","unitedkingdom","unitedstatesfirstrelease","southamerica","france"}] string Location;
    [Required, Description("Environment type."), ValueMap{"Production","Trial"}, Values{"Production","Trial"}] String EnvironmentSKU;

    [Write, Description("Only accepted value is 'Present'."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Required, Description("Credentials of the SharePoint Global Admin"), EmbeddedInstance("MSFT_Credential")] string GlobalAdminAccount;
};
