[ClassVersion("1.0.0.0")]
class MSFT_DeviceManagementConfigurationPolicyAssignments
{
    [Write, Description("The type of the target assignment."), ValueMap{"#microsoft.graph.groupAssignmentTarget","#microsoft.graph.allLicensedUsersAssignmentTarget","#microsoft.graph.allDevicesAssignmentTarget","#microsoft.graph.exclusionGroupAssignmentTarget","#microsoft.graph.configurationManagerCollectionAssignmentTarget"}, Values{"#microsoft.graph.groupAssignmentTarget","#microsoft.graph.allLicensedUsersAssignmentTarget","#microsoft.graph.allDevicesAssignmentTarget","#microsoft.graph.exclusionGroupAssignmentTarget","#microsoft.graph.configurationManagerCollectionAssignmentTarget"}] String dataType;
    [Write, Description("The type of filter of the target assignment i.e. Exclude or Include. Possible values are:none, include, exclude."), ValueMap{"none","include","exclude"}, Values{"none","include","exclude"}] String deviceAndAppManagementAssignmentFilterType;
    [Write, Description("The Id of the filter for the target assignment.")] String deviceAndAppManagementAssignmentFilterId;
    [Write, Description("The group Id that is the target of the assignment.")] String groupId;
    [Write, Description("The group Display Name that is the target of the assignment.")] String groupDisplayName;
    [Write, Description("The collection Id that is the target of the assignment.(ConfigMgr)")] String collectionId;
};
[ClassVersion("1.0.0")]
class MSFT_MicrosoftGraphVpnServer
{
    [Write, Description("Address (IP address, FQDN or URL)")] String address;
    [Write, Description("Description.")] String description;
    [Write, Description("Default server.")] Boolean isDefaultServer;
};
[ClassVersion("1.0.0")]
class MSFT_MicrosoftvpnProxyServer
{
    [Write, Description("Proxy's automatic configuration script url.")] String automaticConfigurationScriptUrl;
    [Write, Description("Address.")] String address;
    [Write, Description("Port. Valid values 0 to 65535.")] uint32 port;
};
[ClassVersion("1.0.0")]
class MSFT_targetedMobileApps
{
    [Write, Description("The application name.")] String name;
    [Write, Description("The publisher of the application.")] String publisher;
    [Write, Description("The Store URL of the application.")] String appStoreUrl;
    [Write, Description("The application or bundle identifier of the application.")] String appId;
};
class MSFT_CustomData
{
    [Write, Description("Key for the custom data entry.")] String key;
    [Write, Description("Value for the custom data entry.")] String value;
};
class MSFT_customKeyValueData
{
    [Write, Description("Name for the custom data entry.")] String name;
    [Write, Description("Value for the custom data entry.")] String value;
};

[ClassVersion("1.0.0.0"), FriendlyName("IntuneVPNConfigurationPolicyAndroidEnterprise")]
class MSFT_IntuneVPNConfigurationPolicyAndroidEnterprise : OMI_BaseResource
{
    [Write, Description("Id of the Intune policy.")] String Id;
    [Key, Description("Display name of the Intune policy.")] String DisplayName;
    [Write, Description("Description of the Intune policy.")] String Description;
    [Write, Description("Authentication method. Inherited from vpnConfiguration. Possible values are: certificate, usernameAndPassword, sharedSecret, derivedCredential, azureAD."), ValueMap{"certificate", "usernameAndPassword", "sharedSecret", "derivedCredential", "azureAD"}, Values{"certificate", "usernameAndPassword", "sharedSecret", "derivedCredential", "azureAD"}] String authenticationMethod;
    [Write, Description("Connection name displayed to the user.")] String connectionName;
    [Write, Description("Role when connection type is set to Pulse Secure. Inherited from vpnConfiguration.")] String role;
    [Write, Description("Realm when connection type is set to Pulse Secure. Inherited from vpnConfiguration.")] String realm;
    [Write, Description("VPN Server on the network. Make sure end users can access this network location."), EmbeddedInstance("MSFT_MicrosoftGraphvpnServer")] String servers[];
    [Write, Description("Connection type. Possible values are: ciscoAnyConnect, pulseSecure, f5EdgeClient, dellSonicWallMobileConnect, checkPointCapsuleVpn, citrix, microsoftTunnel, netMotionMobility, microsoftProtect."), ValueMap{"ciscoAnyConnect", "pulseSecure", "f5EdgeClient", "dellSonicWallMobileConnect", "checkPointCapsuleVpn", "citrix", "microsoftTunnel", "netMotionMobility", "microsoftProtect"}, Values{"ciscoAnyConnect", "pulseSecure", "f5EdgeClient", "dellSonicWallMobileConnect", "checkPointCapsuleVpn", "citrix", "microsoftTunnel", "netMotionMobility", "microsoftProtect"}] String  connectionType;
    [Write, Description("Proxy Server."), EmbeddedInstance("MSFT_MicrosoftvpnProxyServer")] String proxyServer[];
    [Write, Description("Targeted App package IDs.")] String targetedPackageIds[];
    [Write, Description("Targeted mobile apps. This collection can contain a maximum of 500 elements."),EmbeddedInstance("MSFT_targetedMobileApps")] String targetedMobileApps[];
    [Write, Description("Whether or not to enable always-on VPN connection.")] Boolean alwaysOn;
    [Write, Description("If always-on VPN connection is enabled, whether or not to lock network traffic when that VPN is disconnected.")] Boolean alwaysOnLockdown;
    [Write, Description("Microsoft Tunnel site ID.")] String microsoftTunnelSiteId;
    [Write, Description("List of hosts to exclude using the proxy on connections for. These hosts can use wildcards such as *.example.com.")] String proxyExclusionList[];
    [Write, Description("Custom data to define key/value pairs specific to a VPN provider. This collection can contain a maximum of 25 elements."), EmbeddedInstance("MSFT_customData")] String customData[];
    [Write, Description("Custom data to define key/value pairs specific to a VPN provider. This collection can contain a maximum of 25 elements."), EmbeddedInstance("MSFT_customKeyValueData")] String customKeyValueData[];
    [Write, Description("Represents the assignment to the Intune policy."), EmbeddedInstance("MSFT_DeviceManagementConfigurationPolicyAssignments")] String Assignments[];
    [Write, Description("Present ensures the policy exists, absent ensures it is removed."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] string Ensure;
    [Write, Description("Credentials of the Intune Admin"), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Id of the Azure Active Directory tenant used for authentication.")] String TenantId;
    [Write, Description("Secret of the Azure Active Directory tenant used for authentication."), EmbeddedInstance("MSFT_Credential")] String ApplicationSecret;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Managed ID being used for authentication.")] Boolean ManagedIdentity;
    [Write, Description("Access token used for authentication.")] String AccessTokens[];
};
