[ClassVersion("1.0.0.0"), FriendlyName("TeamsFeedbackPolicy")]
class MSFT_TeamsFeedbackPolicy : OMI_BaseResource
{
    [Key, Description("Specify the name of the Teams Feedback Policy.")] String Identity;
    [Write, Description("Specifies if users are allowed to give feedback.")] String UserInitiatedMode;
    [Write, Description("Specifies if users are allowed to receive the survey."), ValueMap{"Enabled","Disabled","EnabledUserOverride"}, Values{"Enabled","Disabled","EnabledUserOverride"}] String ReceiveSurveysMode;
    [Write, Description("Specifies if Screenshot Collection is enabled or not.")] Boolean AllowScreenshotCollection;
    [Write, Description("Specifies if Email Collection is enabled or not.")] Boolean AllowEmailCollection;
    [Write, Description("Specifies if Log Collection is enabled or not.")] Boolean AllowLogCollection;
    [Write, Description("Specifies if users are allowed to provide feature suggestions")] Boolean EnableFeatureSuggestions;
    [Write, Description("Present ensures the instance exists, absent ensures it is removed."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] string Ensure;
    [Write, Description("Credentials of the workload's Admin"), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Id of the Azure Active Directory tenant used for authentication.")] String TenantId;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Managed ID being used for authentication.")] Boolean ManagedIdentity;
    [Write, Description("Access token used for authentication.")] String AccessTokens[];
};
