[ClassVersion("1.0.0.0"), FriendlyName("EXOCASMailboxSettings")]
class MSFT_EXOCASMailboxSettings : OMI_BaseResource
{
    [Key, Description("The Identity parameter specifies the mailbox that you want to configure.")] String Identity;
    [Write, Description("TheActiveSyncAllowedDeviceIDs parameter specifies one or more Exchange ActiveSync device IDs that are allowed to synchronize with the mailbox.")] String ActiveSyncAllowedDeviceIDs[];
    [Write, Description("The ActiveSyncBlockedDeviceIDs parameter specifies one or more Exchange ActiveSync device IDs that aren't allowed to synchronize with the mailbox.")] String ActiveSyncBlockedDeviceIDs[];
    [Write, Description("The ActiveSyncDebugLogging parameter enables or disables Exchange ActiveSync debug logging for the mailbox.")] Boolean ActiveSyncDebugLogging;
    [Write, Description("The ActiveSyncEnabled parameter enables or disables access to the mailbox using Exchange ActiveSync.")] Boolean ActiveSyncEnabled;
    [Write, Description("The ActiveSyncMailboxPolicy parameter specifies the Exchange ActiveSync mailbox policy for the mailbox.")] String ActiveSyncMailboxPolicy;
    [Write, Description("The ActiveSyncSuppressReadReceipt parameter controls the behavior of read receipts for Exchange ActiveSync clients that access the mailbox.")] Boolean ActiveSyncSuppressReadReceipt;
    [Write, Description("The EwsAllowEntourage parameter enables or disables access to the mailbox by Microsoft Entourage clients that use Exchange Web Services.")] Boolean EwsAllowEntourage;
    [Write, Description("The EwsAllowList parameter specifies the Exchange Web Services applications (user agent strings) that are allowed to access the mailbox.")] String EwsAllowList[];
    [Write, Description("The EwsAllowMacOutlook parameter enables or disables access to the mailbox by Outlook for Mac clients that use Exchange Web Services.")] Boolean EwsAllowMacOutlook;
    [Write, Description("The EwsAllowOutlook parameter enables or disables access to the mailbox by Outlook clients that use Exchange Web Services.")] Boolean EwsAllowOutlook;
    [Write, Description("The EwsApplicationAccessPolicy parameter controls access to the mailbox using Exchange Web Services applications.")] String EwsApplicationAccessPolicy;
    [Write, Description("The EwsBlockList parameter specifies the Exchange Web Services applications (user agent strings) that aren't allowed to access the mailbox using Exchange Web Services.")] String EwsBlockList[];
    [Write, Description("The EwsEnabled parameter enables or disables access to the mailbox using Exchange Web Services clients.")] Boolean EwsEnabled;
    [Write, Description("The ImapEnabled parameter enables or disables access to the mailbox using IMAP4 clients.")] Boolean ImapEnabled;
    [Write, Description("The ImapMessagesRetrievalMimeFormat parameter specifies the message format for IMAP4 clients that access the mailbox.")] String ImapMessagesRetrievalMimeFormat;
    [Write, Description("The ImapForceICalForCalendarRetrievalOption parameter specifies how meeting requests are presented to IMAP4 clients that access the mailbox.")] Boolean ImapForceICalForCalendarRetrievalOption;
    [Write, Description("The ImapSuppressReadReceipt parameter controls the behavior of read receipts for IMAP4 clients that access the mailbox.")] Boolean ImapSuppressReadReceipt;
    [Write, Description("The ImapUseProtocolDefaults parameter specifies whether to use the IMAP4 protocol defaults for the mailbox.")] Boolean ImapUseProtocolDefaults;
    [Write, Description("The MacOutlookEnabled parameter enables or disables access to the mailbox using Outlook for Mac clients that use Microsoft Sync technology.")] Boolean MacOutlookEnabled;
    [Write, Description("The MAPIEnabled parameter enables or disables access to the mailbox using MAPI clients (for example, Outlook).")] Boolean MAPIEnabled;
    [Write, Description("The OneWinNativeOutlookEnabled parameter enables or disables access to the mailbox using the new Outlook for Windows.")] Boolean OneWinNativeOutlookEnabled;
    [Write, Description("The OutlookMobileEnabled parameter enables or disables access to the mailbox using Outlook for iOS and Android.")] Boolean OutlookMobileEnabled;
    [Write, Description("The OWAEnabled parameter enables or disables access to the mailbox using Outlook on the web (formerly known as Outlook Web App or OWA).")] Boolean OWAEnabled;
    [Write, Description("The OWAforDevicesEnabled parameter enables or disables access to the mailbox using the older Outlook Web App (OWA) app on iOS and Android devices.")] Boolean OWAforDevicesEnabled;
    [Write, Description("The OwaMailboxPolicy parameter specifies the Outlook on the web mailbox policy for the mailbox.")] String OwaMailboxPolicy;
    [Write, Description("The PopEnabled parameter enables or disables access to the mailbox using POP3 clients.")] Boolean PopEnabled;
    [Write, Description("The PopForceICalForCalendarRetrievalOption parameter specifies how meeting requests are presented to POP3 clients that access the mailbox.")] Boolean PopForceICalForCalendarRetrievalOption;
    [Write, Description("The PopMessagesRetrievalMimeFormat parameter specifies the message format for POP3 clients that access the mailbox.")] String PopMessagesRetrievalMimeFormat;
    [Write, Description("The PopSuppressReadReceipt parameter controls the behavior of read receipts for POP3 clients that access the mailbox.")] Boolean PopSuppressReadReceipt;
    [Write, Description("The PopUseProtocolDefaults parameter specifies whether to use the POP3 protocol defaults for the mailbox.")] Boolean PopUseProtocolDefaults;
    [Write, Description("The PublicFolderClientAccess parameter enables or disables access to public folders in Microsoft Outlook.")] Boolean PublicFolderClientAccess;
    [Write, Description("The ShowGalAsDefaultView parameter specifies whether the global address list (GAL) is the default recipient picker for messages.")] Boolean ShowGalAsDefaultView;
    [Write, Description("The SmtpClientAuthenticationDisabled parameter specifies whether to disable authenticated SMTP (SMTP AUTH) for the mailbox.")] Boolean SmtpClientAuthenticationDisabled;
    [Write, Description("The UniversalOutlookEnabled parameter enables or disables access to the mailbox using Windows 10 Mail and Calendar.")] Boolean UniversalOutlookEnabled;
    [Write, Description("Present ensures the Mailbox CAS settings are applied."), ValueMap{"Present"}, Values{"Present"}] string Ensure;
    [Write, Description("Credentials of the Exchange Global Admin"), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Id of the Azure Active Directory tenant used for authentication.")] String TenantId;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Username can be made up to anything but password will be used for CertificatePassword"), EmbeddedInstance("MSFT_Credential")] String CertificatePassword;
    [Write, Description("Path to certificate used in service principal usually a PFX file.")] String CertificatePath;
    [Write, Description("Managed ID being used for authentication.")] Boolean ManagedIdentity;
    [Write, Description("Access token used for authentication.")] String AccessTokens[];
};
