[ClassVersion("1.0.0.0"), FriendlyName("EXOMailboxCalendarConfiguration")]
class MSFT_EXOMailboxCalendarConfiguration: OMI_BaseResource
{

    [Write, Description("Credentials of the workload's Admin"), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Id of the Azure Active Directory tenant used for authentication.")] String TenantId;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Managed ID being used for authentication.")] Boolean ManagedIdentity;
    [Write, Description("Access token used for authentication.")] String AccessTokens[];

    [Key, Description("Specifies the mailbox identity.")] String Identity;
    [Write, Description("Enables or disables agenda mail introduction.")] Boolean AgendaMailIntroductionEnabled;
    [Write, Description("Automatically declines meeting requests when the user is busy.")] Boolean AutoDeclineWhenBusy;
    [Write, Description("Preferred language for calendar feeds.")] String CalendarFeedsPreferredLanguage;
    [Write, Description("Preferred region for calendar feeds.")] String CalendarFeedsPreferredRegion;
    [Write, Description("Root page ID for calendar feeds.")] String CalendarFeedsRootPageId;
    [Write, Description("Enables or disables conversational scheduling.")] Boolean ConversationalSchedulingEnabled;
    [Write, Description("Creates events from email as private.")] Boolean CreateEventsFromEmailAsPrivate;
    [Write, Description("Default minutes to reduce long events by.")] UInt32 DefaultMinutesToReduceLongEventsBy;
    [Write, Description("Default minutes to reduce short events by.")] UInt32 DefaultMinutesToReduceShortEventsBy;
    [Write, Description("Default online meeting provider.")] String DefaultOnlineMeetingProvider;
    [Write, Description("Default reminder time.")] String DefaultReminderTime;
    [Write, Description("Deletes meeting request on respond.")] Boolean DeleteMeetingRequestOnRespond;
    [Write, Description("Enables or disables dining events from email.")] Boolean DiningEventsFromEmailEnabled;
    [Write, Description("Enables or disables entertainment events from email.")] Boolean EntertainmentEventsFromEmailEnabled;
    [Write, Description("Enables or disables events from email.")] Boolean EventsFromEmailEnabled;
    [Write, Description("Specifies the first week of the year.")] String FirstWeekOfYear;
    [Write, Description("Enables or disables flight events from email.")] Boolean FlightEventsFromEmailEnabled;
    [Write, Description("Enables or disables hotel events from email.")] Boolean HotelEventsFromEmailEnabled;
    [Write, Description("Enables or disables invoice events from email.")] Boolean InvoiceEventsFromEmailEnabled;
    [Write, Description("Specifies location details in free/busy information.")] String LocationDetailsInFreeBusy;
    [Write, Description("Specifies the mailbox location.")] String MailboxLocation;
    [Write, Description("Enables or disables online meetings by default.")] Boolean OnlineMeetingsByDefaultEnabled;
    [Write, Description("Enables or disables package delivery events from email.")] Boolean PackageDeliveryEventsFromEmailEnabled;
    [Write, Description("Preserves declined meetings.")] Boolean PreserveDeclinedMeetings;
    [Write, Description("Enables or disables reminders.")] Boolean RemindersEnabled;
    [Write, Description("Enables or disables reminder sound.")] Boolean ReminderSoundEnabled;
    [Write, Description("Enables or disables rental car events from email.")] Boolean RentalCarEventsFromEmailEnabled;
    [Write, Description("Enables or disables service appointment events from email.")] Boolean ServiceAppointmentEventsFromEmailEnabled;
    [Write, Description("Specifies the default scope for shortening events.")] String ShortenEventScopeDefault;
    [Write, Description("Shows or hides week numbers.")] Boolean ShowWeekNumbers;
    [Write, Description("Specifies the time increment for calendar events.")] String TimeIncrement;
    [Write, Description("Uses a bright calendar color theme in Outlook on the web.")] Boolean UseBrightCalendarColorThemeInOwa;
    [Write, Description("Enables or disables weather information.")] String WeatherEnabled;
    [Write, Description("Specifies the weather location bookmark.")] UInt32 WeatherLocationBookmark;
    [Write, Description("Specifies the weather locations.")] String WeatherLocations[];
    [Write, Description("Specifies the weather unit.")] String WeatherUnit;
    [Write, Description("Specifies the start day of the week.")] String WeekStartDay;
    [Write, Description("Specifies the work days.")] String WorkDays;
    [Write, Description("Specifies the end time of working hours.")] String WorkingHoursEndTime;
    [Write, Description("Specifies the start time of working hours.")] String WorkingHoursStartTime;
    [Write, Description("Specifies the time zone for working hours.")] String WorkingHoursTimeZone;
    [Write, Description("Enables or disables workspace user.")] Boolean WorkspaceUserEnabled;
    [Write, Description("Ensures the presence or absence of the configuration.")] String Ensure;
};
