[ClassVersion("1.0.0.0"), FriendlyName("EXOAuthenticationPolicy")]
class MSFT_EXOAuthenticationPolicy : OMI_BaseResource
{
    [Key, Description("The Identity parameter specifies the authentication policy you want to view or modify.")] String Identity;
    [write, Description("The AllowBasicAuthActiveSync switch specifies whether to allow Basic authentication with Exchange Active Sync.")] Boolean AllowBasicAuthActiveSync;
    [write, Description("The AllowBasicAuthAutodiscover switch specifies whether to allow Basic authentication with Autodiscover.")] Boolean AllowBasicAuthAutodiscover;
    [write, Description("The AllowBasicAuthImap switch specifies whether to allow Basic authentication with IMAP.")] Boolean AllowBasicAuthImap;
    [write, Description("The AllowBasicAuthMapi switch specifies whether to allow Basic authentication with MAPI.")] Boolean AllowBasicAuthMapi;
    [write, Description("The AllowBasicAuthOfflineAddressBook switch specifies whether to allow Basic authentication with Offline Address Books.")] Boolean AllowBasicAuthOfflineAddressBook;
    [write, Description("The AllowBasicAuthOutlookService switch specifies whether to allow Basic authentication with the Outlook service.")] Boolean AllowBasicAuthOutlookService;
    [write, Description("The AllowBasicAuthPop switch specifies whether to allow Basic authentication with POP.")] Boolean AllowBasicAuthPop;
    [write, Description("The AllowBasicAuthPowerShell switch specifies whether to allow Basic authentication with PowerShell.")] Boolean AllowBasicAuthPowershell;
    [write, Description("The AllowBasicAuthReporting Web Services switch specifies whether to allow Basic authentication with reporting web services.")] Boolean AllowBasicAuthReportingWebServices;
    [write, Description("The AllowBasicAuthRpc switch specifies whether to allow Basic authentication with RPC.")] Boolean AllowBasicAuthRpc;
    [write, Description("The AllowBasicAuthSmtp switch specifies whether to allow Basic authentication with SMTP.")] Boolean AllowBasicAuthSmtp;
    [write, Description("The AllowBasicAuthWebServices switch specifies whether to allow Basic authentication with Exchange Web Services (EWS).")] Boolean AllowBasicAuthWebServices;
    [Write, Description("Specify if the authentication Policy should exist or not."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Write, Description("Credentials of the Exchange Global Admin"), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Id of the Azure Active Directory tenant used for authentication.")] String TenantId;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Username can be made up to anything but password will be used for CertificatePassword"), EmbeddedInstance("MSFT_Credential")] String CertificatePassword;
    [Write, Description("Path to certificate used in service principal usually a PFX file.")] String CertificatePath;
    [Write, Description("Managed ID being used for authentication.")] Boolean ManagedIdentity;
    [Write, Description("Access token used for authentication.")] String AccessTokens[];
};
