name: "Problem, bug, or enhancement with a resource"
description: If you have a problem, bug, or enhancement with a resource in this resource module.

body:
  - type: markdown
    attributes:
      value: |
        Your feedback and support is greatly appreciated, thanks for contributing!
        Thank you for opening an issue. Please fill in the following information to help us triage (and fix) your issue.

        Pleasse prefix the issue title with the resource name, e.g. **`ResourceNameHere: Your title here`.**

        Please make sure to have only one version of Microsoft365DSC installed on your system. If you have multiple versions installed, please remove all of them and install the latest version from the PowerShell Gallery.
        You can use the built-in Update-M365DSCModule cmdlet to update to the latest version.

        ```powershell
        Update-M365DSCModule
        ```

  - type: textarea
    attributes:
      label: "Description of the issue"
      description: |
        Details of the scenario you tried and the problem that is occurring

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: true

  - type: input
    attributes:
      label: "Microsoft 365 DSC Version"
      description: The version of the Microsoft 365 DSC module you are using.
      placeholder: DEV / V1.23.123.1
    validations:
      required: true

  - type: dropdown
    id: Workload
    attributes:
      label: "Which workloads are affected"
      description: The workload of the resource you are having an issue with.
      options:
        - "Azure Active Directory"
        - "Exchange Online"
        - "Office 365 Admin"
        - "OneDrive for Business"
        - "Planner"
        - "Power Platform"
        - "Security & Compliance Center"
        - "SharePoint Online"
        - "Teams"
        - "other"
      multiple: true
    validations:
      required: true

  - type: textarea
    attributes:
      label: "The DSC configuration"
      description: "The DSC configuration that is used to reproduce the issue (as detailed as possible)"
      render: powershell
    validations:
      required: false

  - type: textarea
    attributes:
      label: "Verbose logs showing the problem"
      render: powershell
    validations:
      required: false

  - type: textarea
    attributes:
      label: "Environment Information + PowerShell Version"
      description: |
        Please provide as much as possible about the target node, for example edition, version, build and language.
        On OS with WMF 5.1 the following command can help get this information.

        ```powershell
        Get-ComputerInfo -Property @(
        'OsName',
        'OsOperatingSystemSKU',
        'OSArchitecture',
        'WindowsVersion',
        'WindowsBuildLabEx',
        'OsLanguage',
        'OsMuiLanguages')

        $PSVersionTable
        ```
      render: powershell
    validations:
      required: false
