[ClassVersion("1.0.0.0")]
class MSFT_AzureBillingAccountScheduledActionNotification
{
    [Write, Description("Subject of the email. Length is limited to 70 characters.")] String subject;
    [Write, Description("Optional message to be added in the email. Length is limited to 250 characters.")] String message;
    [Write, Description("Array of email addresses.")] String to[];
};

[ClassVersion("1.0.0.0")]
class MSFT_AzureBillingAccountScheduledActionSchedule
{
    [Write, Description("UTC day on which cost analysis data will be emailed. Must be between 1 and 31. This property is applicable when frequency is Monthly and overrides weeksOfMonth or daysOfWeek.")] UInt32 dayOfMonth;
    [Write, Description("Day names in english on which cost analysis data will be emailed. This property is applicable when frequency is Weekly or Monthly.")] String daysOfWeek[];
    [Write, Description("The start date and time of the scheduled action (UTC).")] String startDate;
    [Write, Description("The end date and time of the scheduled action (UTC).")] String endDate;
    [Write, Description("Weeks in which cost analysis data will be emailed. This property is applicable when frequency is Monthly and used in combination with daysOfWeek.")] String weeksOfMonth[];
    [Write, Description("Frequency of the schedule.")] String frequency;
    [Write, Description("UTC time at which cost analysis data will be emailed.")] UInt32 hourOfDay;
};

[ClassVersion("1.0.0.0"), FriendlyName("AzureBillingAccountScheduledAction")]
class MSFT_AzureBillingAccountScheduledAction : OMI_BaseResource
{
    [Key, Description("Display name of the scheduled action.")] String DisplayName;
    [Write, Description("Associated billing account id.")] String BillingAccount;
    [Write, Description("Status of the scheduled action.")] String Status;
    [Write, Description("Associated view id.")] String View;
    [Write, Description("Notification properties based on scheduled action kind."), EmbeddedInstance("MSFT_AzureBillingAccountScheduledActionNotification")] String  Notification;
    [Write, Description("Email address of the point of contact that should get the unsubscribe requests and notification emails.")] String  NotificationEmail;
    [Write, Description("Schedule of the scheduled action."), EmbeddedInstance("MSFT_AzureBillingAccountScheduledActionSchedule")] String  Schedule;

    [Write, Description("Present ensures the instance exists, absent ensures it is removed."), ValueMap{"Absent","Present"}, Values{"Absent","Present"}] string Ensure;
    [Write, Description("Credentials of the workload's Admin"), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Id of the Azure Active Directory tenant used for authentication.")] String TenantId;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Managed ID being used for authentication.")] Boolean ManagedIdentity;
    [Write, Description("Access token used for authentication.")] String AccessTokens[];
};
