[ClassVersion("1.0.0.0"), FriendlyName("SPOStorageEntity")]
class MSFT_SPOStorageEntity : OMI_BaseResource
{
    [Key, Description("The key of the storage entity.")] string Key;
    [Write, Description("Scope of the storage entity."), ValueMap{"Tenant","Site"}, Values{"Tenant","Site"}] string EntityScope;
    [Write, Description("Value of the storage entity.")] string Value;
    [Write, Description("Description of storage entity.")] string Description;
    [Write, Description("Comment for the storage entity.")] string Comment;
    [Write, Description("Used to add or remove storage entity."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] string Ensure;
    [Required, Description("The url of site collection or tenant.")] string SiteUrl;
    [Required, Description("Credentials of the Office365 Tenant Admin."), EmbeddedInstance("MSFT_Credential")] string GlobalAdminAccount;
};
