[ClassVersion("1.0.0.0"), FriendlyName("SPOStorageEntity")]
class MSFT_SPOStorageEntity : OMI_BaseResource
{
    [Key, Description("The key of the storage entity.")] string Key;
    [Write, Description("Scope of the storage entity."), ValueMap{"Tenant","Site"}, Values{"Tenant","Site"}] string EntityScope;
    [Write, Description("Value of the storage entity.")] string Value;
    [Write, Description("Description of storage entity.")] string Description;
    [Write, Description("Comment for the storage entity.")] string Comment;
    [Write, Description("Used to add or remove storage entity."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] string Ensure;
    [Required, Description("The url of site collection or tenant.")] string SiteUrl;
    [Write, Description("Credentials of the Office365 Tenant Admin."), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Secret of the Azure Active Directory application to authenticate with."), EmbeddedInstance("MSFT_Credential")] String ApplicationSecret;
    [Write, Description("Name of the Azure Active Directory tenant used for authentication. Format contoso.onmicrosoft.com")] String TenantId;
    [Write, Description("Username can be made up to anything but password will be used for certificatePassword"), EmbeddedInstance("MSFT_Credential")] String CertificatePassword;
    [Write, Description("Path to certificate used in service principal usually a PFX file.")] String CertificatePath;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Managed ID being used for authentication.")] Boolean ManagedIdentity;
    [Write, Description("Access token used for authentication.")] String AccessTokens[];
};
