[ClassVersion("1.0.0.0"), FriendlyName("SPOSearchResultSource")]
class MSFT_SPOSearchResultSource : OMI_BaseResource
{
    [Key, Description("The Name of the Result Source.")] string Name;
    [Write, Description("Description of the Result Source.")] string Description;
    [Required, Description("The protocol of the Result Source."), ValueMap{"Local","Remote","OpenSearch","Exchange"}, Values{"Local","Remote","OpenSearch","Exchange"}] string Protocol;
    [Write, Description("Address of the root site collection of the remote SharePoint farm or Exchange server.")] string SourceURL;
    [Write, Description("Select SharePoint Search Results to search over the entire index. Select People Search Results to enable query processing specific to People Search, such as phonetic name matching or nickname matching. Only people profiles will be returned from a People Search source."), ValueMap{"SharePoint","People"}, Values{"SharePoint","People"}] string Type;
    [Write, Description("Change incoming queries to use this new query text instead. Include the incoming query in the new text by using the query variable '{searchTerms}'.")] string QueryTransform;
    [Write, Description("Show partial search or not")] boolean ShowPartialSearch;
    [Write, Description("Specifies if AutoDiscover should be used for the Exchange Source URL")] boolean UseAutoDiscover;
    [Write, Description("Present ensures the Search Result Source exists."), ValueMap{"Present"}, Values{"Present"}] string Ensure;
    [Required, Description("Credentials of the SharePoint Global Admin"), EmbeddedInstance("MSFT_Credential")] string GlobalAdminAccount;
};

