[ClassVersion("1.0.0.0"), FriendlyName("TeamsIPPhonePolicy")]
class MSFT_TeamsIPPhonePolicy : OMI_BaseResource
{
    [Key, Description("Specifies the policy instance name")] String Identity;
    [Write, Description("Determines whether Better Together mode is enabled, phones can lock and unlock in an integrated fashion when connected to their Windows PC running a 64-bit Teams desktop client."), ValueMap{"Enabled","Disabled"}, Values{"Enabled","Disabled"}] String AllowBetterTogether;
    [Write, Description("Determines whether the Home Screen feature of the Teams IP Phones is enabled."), ValueMap{"Enabled","EnabledUserOverride","Disabled"}, Values{"Enabled","EnabledUserOverride","Disabled"}] String AllowHomeScreen;
    [Write, Description("Determines whether hot desking mode is enabled.")] Boolean AllowHotDesking;
    [Write, Description("Specifies the description of the policy")] String Description;
    [Write, Description("Determines the idle timeout value in minutes for the signed in user account. When the timeout is reached, the account is logged out.")] UInt64 HotDeskingIdleTimeoutInMinutes;
    [Write, Description("Determines whether a user can search the Global Address List in Common Area Phone Mode."), ValueMap{"Enabled","Disabled"}, Values{"Enabled","Disabled"}] String SearchOnCommonAreaPhoneMode;
    [Write, Description("Determines the sign in mode for the device when signing in to Teams."), ValueMap{"UserSignIn","CommonAreaPhoneSignIn","MeetingSignIn"}, Values{"UserSignIn","CommonAreaPhoneSignIn","MeetingSignIn"}] String SignInMode;
    [Write, Description("Present ensures the instance exists, absent ensures it is removed."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] string Ensure;
    [Write, Description("Credentials of the workload's Admin"), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Id of the Azure Active Directory tenant used for authentication.")] String TenantId;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Managed ID being used for authentication.")] Boolean ManagedIdentity;
    [Write, Description("Access token used for authentication.")] String AccessTokens[];
};
