[ClassVersion("1.0.0.0"), FriendlyName("TeamsTeam")]
class MSFT_TeamsTeam : OMI_BaseResource
{
    [Key, Description("Display Name of the Team")] string DisplayName;
    [Write, Description("Converts current O365 group to a Team, all other parameters ignore when this is passed into resource.")] string Group;
    [Write, Description("Description of Team")] string Description;
    [Write, Description("Team group ID, only used to update existing Team ")] string GroupID;
    [Write, Description("Alias of O365 Group associated with Team")] string Alias;
    [Write, Description("Owner of the Team")] string Owner;
    [Write, Description("Classification of the Team ")] string Classification;
    [Write, Description("AccessType of the Team"),ValueMap{"Public","Private"},Values{"Public","Private"}] String AccessType;
    [Write, Description("Present ensures the Team exists, absent ensures it is removed"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Required, Description("Credentials of the SharePoint Global Admin"), EmbeddedInstance("MSFT_Credential")] String GlobalAdminAccount;
};

