[ClassVersion("1.0.0.0"), FriendlyName("SPOTenantCdnEnabled")]
class MSFT_SPOTenantCdnEnabled : OMI_BaseResource
{
    [Key, Description("Specifies the CDN type. The valid values are public or private."), ValueMap{"Public","Private"}, Values{"Public","Private"}] String CdnType;
    [Write, Description("Specify to enable or disable tenant CDN.")] Boolean Enable;
    [Write, Description("Get-PNPTenantCdnEnabled always returns a value, only support value is Present"), ValueMap{"Present"}, Values{"Present"}] String Ensure;
    [Write, Description("Credentials of the SharePoint Admin"), EmbeddedInstance("MSFT_Credential")] String GlobalAdminAccount;
};
