[ClassVersion("1.0.0.0"), FriendlyName("PPAdminDLPPolicy")]
class MSFT_PPAdminDLPPolicy : OMI_BaseResource
{
    [Key, Description("Creates the policy with the input display name")] String DisplayName;
    [Write, Description("Unique identifier of the policy.")] String PolicyName;
    [Write, Description("Comma separated string list used as input environments to either include or exclude, depending on the FilterType.")] String Environments[];
    [Write, Description("Identifies which filter type the policy will have, none, include, or exclude.")] String FilterType;

    [Write, Description("Present ensures the instance exists, absent ensures it is removed."), ValueMap{"Absent","Present"}, Values{"Absent","Present"}] string Ensure;
    [Write, Description("Credentials of the workload's Admin"), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Id of the Azure Active Directory tenant used for authentication.")] String TenantId;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Managed ID being used for authentication.")] Boolean ManagedIdentity;
    [Write, Description("Access token used for authentication.")] String AccessTokens[];
};
