[ClassVersion("1.0.0.0"), FriendlyName("SPOSharingSettings")]
class MSFT_SPOSharingSettings : OMI_BaseResource
{
    [Key, Description("Specifies the resource is a single instance, the value must be 'Yes'"),ValueMap{"Yes"},Values{"Yes"}] String IsSingleInstance;
    [Write, Description("Configures anonymous link types for folders"),ValueMap{"ExistingExternalUserSharingOnly","ExternalUserAndGuestSharing","Disabled","ExternalUserSharingOnly"},Values{"ExistingExternalUserSharingOnly","ExternalUserAndGuestSharing","Disabled","ExternalUserSharingOnly"}] string SharingCapability;
    [Write, Description("Enables the administrator to hide the Everyone claim in the People Picker.")] boolean ShowEveryoneClaim;
    [Write, Description("Enables the administrator to hide the All Users claim groups in People Picker.")] boolean ShowAllUsersClaim;
    [Write, Description("Enables the administrator to hide the Everyone except external users claim in the People Picker.")] boolean ShowEveryoneExceptExternalUsersClaim;
    [Write, Description("Creates a Shared with Everyone folder in every user's new OneDrive for Business document library.")] boolean ProvisionSharedWithEveryoneFolder;
    [Write, Description("Accelerates guest-enabled site collections as well as member-only site collections when the SignInAccelerationDomain parameter is set.")] boolean EnableGuestSignInAcceleration;
    [Write, Description("When the feature is enabled, all external sharing invitations that are sent will blind copy the e-mail messages listed in the BccExternalSharingsInvitationList.")] boolean BccExternalSharingInvitations;
    [Write, Description("Specifies a list of e-mail addresses to be BCC'd when the BCC for External Sharing feature is enabled.Multiple addresses can be specified by creating a comma separated list with no spaces.")] string BccExternalSharingInvitationsList;
    [Write, Description("Specifies all anonymous links that have been created (or will be created) will expire after the set number of days .")] uint32 RequireAnonymousLinksExpireInDays;
    [Write, Description("Specifies a list of email domains that is allowed for sharing with the external collaborators. Use the space character as the delimiter for entering multiple values. For example, “contoso.com fabrikam.com”. ")] string SharingAllowedDomainList;
    [Write, Description("Specifies a list of email domains that is blocked or prohibited for sharing with the external collaborators. Use space character as the delimiter for entering multiple values. For example, “contoso.com fabrikam.com”. ")] string SharingBlockedDomainList;
    [Write, Description("Specifies the external sharing mode for domains."),ValueMap{"None","AllowList","BlockList"},Values{"None","AllowList","BlockList"}] string SharingDomainRestrictionMode;
    [Write, Description("Lets administrators choose what type of link appears is selected in the 'Get a link' sharing dialog box in OneDrive for Business and SharePoint Online"),ValueMap{"None","Direct","Internal","AnonymousAccess"},Values{"None","Direct","Internal","AnonymousAccess"}] string DefaultSharingLinkType;
    [Write, Description("Allow or deny external users re-sharing")] boolean PreventExternalUsersFromResharing;
    [Write, Description("Enables the administrator to hide the guest users claim in the People Picker.")] boolean ShowPeoplePickerSuggestionsForGuestUsers;
    [Write, Description("Configures anonymous link types for files"),ValueMap{"View","Edit"},Values{"View","Edit"}] string FileAnonymousLinkType;
    [Write, Description("Configures anonymous link types for folders"),ValueMap{"View","Edit"},Values{"View","Edit"}] string FolderAnonymousLinkType;
    [Write, Description("When this parameter is set to $true and another user re-shares a document from a user’s OneDrive for Business, the OneDrive for Business owner is notified by e-mail.")] boolean NotifyOwnersWhenItemsReshared;
    [Write, Description("Specifies the link permission on the tenant level."),ValueMap{"None","View","Edit"},Values{"None","View","Edit"}] string DefaultLinkPermission;
    [Write, Description("Ensures that an external user can only accept an external sharing invitation with an account matching the invited email address.Administrators who desire increased control over external collaborators should consider enabling this feature. False (default) - When a document is shared with an external user, bob@contoso.com, it can be accepted by any user with access to the invitation link in the original e-mail.True - User must accept this invitation with bob@contoso.com.")] boolean RequireAcceptingAccountMatchInvitedAccount;
    [Write, Description("Only accepted value is 'Present'."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Required, Description("Credentials of the SharePoint Global Admin"), EmbeddedInstance("MSFT_Credential")] string GlobalAdminAccount;
};
