[ClassVersion("1.0.0.0")]
class MSFT_PPPowerAPpPolicyUrlPatternsRule
{
    [Write, Description("Rule priority order.")] String order;
    [Write, Description("Rule classification.")] String customConnectorRuleClassification;
    [Write, Description("Rule pattern.")] String pattern;
};

[ClassVersion("1.0.0.0"), FriendlyName("PPPowerAppPolicyUrlPatterns")]
class MSFT_PPPowerAppPolicyUrlPatterns : OMI_BaseResource
{
    [Key, Description("The policy name identifier.")] String PolicyName;
    [Key, Description("The tenant identifier.")] String PPTenantId;
    [Write, Description("Set of custom connector pattern rules associated with the policy."), EmbeddedInstance("MSFT_PPPowerAPpPolicyUrlPatternsRule")] String RuleSet[];

    [Write, Description("Present ensures the instance exists, absent ensures it is removed."), ValueMap{"Absent","Present"}, Values{"Absent","Present"}] string Ensure;
    [Write, Description("Credentials of the workload's Admin"), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Id of the Azure Active Directory tenant used for authentication.")] String TenantId;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Managed ID being used for authentication.")] Boolean ManagedIdentity;
    [Write, Description("Access token used for authentication.")] String AccessTokens[];
};
