[ClassVersion("1.0.0.0"), FriendlyName("SCAutoSensitivityLabelPolicy")]
class MSFT_SCAutoSensitivityLabelPolicy : OMI_BaseResource
{
    [Key, Description("The Name parameter specifies the unique name for the sensitivity label. The maximum length is 64 characters. If the value contains spaces, enclose the value in quotation marks.")] String Name;
    [Write, Description("Specify if this label policy should exist or not."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Write, Description("The Comment parameter specifies an optional comment.")] String Comment;
    [Write, Description("The ApplySensitivityLabel parameter specifies the label to use for the auto label policy.")] String ApplySensitivityLabel;
    [Write, Description("The ExchangeSender parameter specifies which senders to include in the policy.")] String ExchangeSender[];
    [Write, Description("The ExchangeSenderException parameter specifies which senders to exclude in the policy.")] String ExchangeSenderException[];
    [Write, Description("The ExchangeSenderMemberOf parameter specifies the distribution groups, mail-enabled security groups, or dynamic distribution groups to include in the auto-labeling policy.")] String ExchangeSenderMemberOf[];
    [Write, Description("he ExchangeSenderMemberOf parameter specifies the distribution groups, mail-enabled security groups, or dynamic distribution groups to exclude from the auto-labeling policy.")] String ExchangeSenderMemberOfException[];
    [Write, Description("The ExchangeSender parameter specifies which senders to include in the policy.")] String ExchangeLocation[];
    [Write, Description("This AddExchangeLocation parameter specifies new Exchange locations to be added to the policy without affecting the existing ones.")] String AddExchangeLocation[];
    [Write, Description("The RemoveExchangeLocation parameter removes locations on Exchange from the policy.")] String RemoveExchangeLocation[];
    [Write, Description("The Mode parameter specifies the action and notification level of the auto-labeling policy."),ValueMap{"Enable","Disable","TestWithNotifications","TestWithoutNotifications"},Values{"Enable","Disable","TestWithNotifications","TestWithoutNotifications"}] String Mode;
    [Write, Description("The OneDriveLocation parameter specifies the OneDrive for Business sites to include. You identify the site by its URL value, or you can use the value.")] String OneDriveLocation[];
    [Write, Description("The AddOneDriveLocation parameter specifies the OneDrive for Business sites to add to the list of included sites when you aren't using the value All for the OneDriveLocation parameter.")] String AddOneDriveLocation[];
    [Write, Description("The RemoveOneDriveLocation parameter specifies the OneDrive for Business sites to remove from the list of included sites when you aren't using the value All for the OneDriveLocation parameter.")] String RemoveOneDriveLocation[];
    [Write, Description("This parameter specifies the OneDrive for Business sites to exclude when you use the value All for the OneDriveLocation parameter.")] String AddOneDriveLocationException[];
    [Write, Description("This RemoveOneDriveLocationException parameter specifies the OneDrive for Business sites to remove from the list of excluded sites when you use the value All for the OneDriveLocation parameter.")] String RemoveOneDriveLocationException[];
    [Write, Description("The AddOneDriveLocationException parameter specifies the OneDrive for Business sites to add to the list of excluded sites when you use the value All for the OneDriveLocation parameter.")] String OneDriveLocationException[];
    [Write, Description("The Priority parameter specifies the priority of the policy. The highest priority policy will take action over lower priority policies if two policies are applicable for a file.")] uint32 Priority;
    [Write, Description("The SharePointLocation parameter specifies the SharePoint Online sites to include. You identify the site by its URL value, or you can use the value All to include all sites.")] String SharePointLocation[];
    [Write, Description("This parameter specifies the SharePoint Online sites to exclude when you use the value All for the SharePointLocation parameter.")] String SharePointLocationException[];
    [Write, Description("The AddSharePointLocation parameter specifies the SharePoint Online sites to add to the list of included sites when you aren't using the value All for the SharePointLocation parameter.")] String AddSharePointLocationException[];
    [Write, Description("The RemoveSharePointLocationException parameter specifies the SharePoint Online sites to remove from the list of excluded sites when you use the value All for the SharePointLocation parameter.")] String RemoveSharePointLocationException[];
    [Write, Description("The AddSharePointLocation parameter specifies the SharePoint Online sites to add to the list of included sites when you aren't using the value All for the SharePointLocation parameter.")] String AddSharePointLocation[];
    [Write, Description("The RemoveSharePointLocation parameter specifies the SharePoint Online sites to remove from the list of included sites when you aren't using the value All for the SharePointLocation parameter.")] String RemoveSharePointLocation[];
    [Write, Description("Credentials of the Exchange Global Admin"), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Id of the Azure Active Directory tenant used for authentication.")] String TenantId;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Username can be made up to anything but password will be used for CertificatePassword"), EmbeddedInstance("MSFT_Credential")] String CertificatePassword;
    [Write, Description("Path to certificate used in service principal usually a PFX file.")] String CertificatePath;
    [Write, Description("Access token used for authentication.")] String AccessTokens[];
};
