#
# Module manifest for module 'Microsoft365DSC'
#
# Generated by: Microsoft Corporation
#
# Generated on: 2024-10-02

@{

  # Script module or binary module file associated with this manifest.
  # RootModule = ''

  # Version number of this module.
  ModuleVersion     = '1.24.1002.1'

  # Supported PSEditions
  # CompatiblePSEditions = @()

  # ID used to uniquely identify this module
  GUID              = '39f599a6-d212-4480-83b3-a8ea2124d8cf'

  # Author of this module
  Author            = 'Microsoft Corporation'

  # Company or vendor of this module
  CompanyName       = 'Microsoft Corporation'

  # Copyright statement for this module
  Copyright         = '(c) 2024 Microsoft Corporation. All rights reserved.'

  # Description of the functionality provided by this module
  Description       = 'This DSC module is used to configure and monitor Microsoft tenants, including SharePoint Online, Exchange, Teams, etc.'

  # Minimum version of the PowerShell engine required by this module
  PowerShellVersion = '5.1'

  # Name of the PowerShell host required by this module
  # PowerShellHostName = ''

  # Minimum version of the PowerShell host required by this module
  # PowerShellHostVersion = ''

  # Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
  # DotNetFrameworkVersion = ''

  # Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
  # CLRVersion = ''

  # Processor architecture (None, X86, Amd64) required by this module
  # ProcessorArchitecture = ''

  # Modules that must be imported into the global environment prior to importing this module
  RequiredModules   = @()

  # Assemblies that must be loaded prior to importing this module
  # RequiredAssemblies = @()

  # Script files (.ps1) that are run in the caller's environment prior to importing this module.
  # ScriptsToProcess = @()

  # Type files (.ps1xml) to be loaded when importing this module
  # TypesToProcess = @()

  # Format files (.ps1xml) to be loaded when importing this module
  # FormatsToProcess = @()

  # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
  NestedModules     = @(
    'Modules/M365DSCAgent.psm1',
    'Modules/M365DSCDocGenerator.psm1',
    'Modules/M365DSCErrorHandler.psm1',
    'Modules/M365DSCLogEngine.psm1',
    'Modules/M365DSCPermissions.psm1',
    'Modules/M365DSCReport.psm1',
    'Modules/M365DSCReverse.psm1',
    'Modules/M365DSCStubsUtility.psm1',
    'Modules/M365DSCTelemetryEngine.psm1',
    'Modules/M365DSCUtil.psm1',
    'Modules/M365DSCDRGUtil.psm1',
    'Modules/EncodingHelpers/M365DSCEmojis.psm1',
    'Modules/EncodingHelpers/M365DSCStringEncoding.psm1',
    'Modules/WorkloadHelpers/M365DSCAzureDevOPSHelper.psm1',
    'Modules/WorkloadHelpers/M365DSCFabricHelper.psm1',
    'Modules/M365DSCConfigurationHelper.psm1'
  )

  # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
  #FunctionsToExport = @()

  # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
  CmdletsToExport   = @('Assert-M365DSCBlueprint',
    'Compare-M365DSCConfigurations',
    'Confirm-M365DSCDependencies',
    'Export-M365DSCConfiguration',
    'Export-M365DSCDiagnosticData',
    'Get-M365DSCNotificationEndPointRegistration',
    'Get-M365DSCEvaluationRulesForConfiguration',
    'Import-M365DSCDependencies',
    'New-M365DSCDeltaReport',
    'New-M365DSCNotificationEndPointRegistration',
    'New-M365DSCReportFromConfiguration',
    'New-M365DSCStubFiles',
    'Remove-M365DSCNotificationEndPointRegistration',
    'Set-M365DSCAgentCertificateConfiguration',
    'Start-M365DSCConfiguration',
    'Test-M365DSCAgent',
    'Test-M365DSCDependenciesForNewVersions',
    'Test-M365DSCModuleValidity',
    'Uninstall-M365DSCOutdatedDependencies',
    'Update-M365DSCAllowedGraphScopes',
    'Update-M365DSCAzureAdApplication',
    'Update-M365DSCDependencies',
    'Update-M365DSCModule',
    'Update-M365DSCResourceDocumentationPage',
    'Update-M365DSCResourcesSettingsJSON'
  )

  # Variables to export from this module
  # VariablesToExport = @()

  # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
  AliasesToExport   = @()

  # List of all modules packaged with this module
  # ModuleList = @()

  # List of all files packaged with this module
  # FileList = @()

  # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
  PrivateData       = @{

    PSData = @{
      # Tags applied to this module. These help with module discovery in online galleries.
      Tags         = 'DesiredStateConfiguration', 'DSC', 'DSCResourceKit', 'DSCResource', 'Microsoft365'

      # A URL to the license for this module.
      LicenseUri   = 'https://github.com/Microsoft/Microsoft365DSC/blob/master/LICENSE'

      # A URL to the main website for this project.
      ProjectUri   = 'https://github.com/Microsoft/Microsoft365DSC'

      # A URL to an icon representing this module.
      IconUri      = 'https://github.com/microsoft/Microsoft365DSC/blob/Dev/Modules/Microsoft365DSC/Dependencies/Images/Logo.png?raw=true'

      # ReleaseNotes of this module
      ReleaseNotes = '* AADApplication
  * Added AppRoles
  * Added AuthenticationBehavior
  * Added KeyCredentials
  * Added OptionalClaims
  * Added PasswordCredentials
  * Added PreAuthorizationApplications
* AADAuthenticationMethodPolicy
  * Added ReportSuspiciousActivitySettings
* AADAuthenticationMethodPolicyHardware
  * Initial release.
* AADEntitlementManagementSettings
  * Initial release.
* AADFeatureRolloutPolicy
  * Initial release
* AADGroup
  * Fixes logic to evaluate license assignments and disabled plans.
    FIXES [#5101](https://github.com/microsoft/Microsoft365DSC/issues/5101)
  * Adds support to assign Service Principal as members or owners.
    FIXES [#4972](https://github.com/microsoft/Microsoft365DSC/issues/4972)
* AADPasswordRuleSettings
  * Initial release
* ADOOrganizationOwner
  * Initial release.
* ADOPermissionGroup
  * Initial release.
* ADOSecurityPolicy
  * Initial release.
* AzureSubscription
  * Initial Release.
* DefenderSubscriptionDefenderPlan
  * Initial release.
* EXOAntiPhishPolicy
  * Use correct type integer for variable `PhishThresholdLevel`
* EXOArcConfig
  * Initial Release.
* EXODnssecForVerifiedDomain
  * Initial Release.
* EXOEmailTenantSettings
  * Initial Release.
* EXOFocusedInbox
  * Initial Release.
* EXOMailboxCalendarConfiguration
  * Initial Release.
* EXOMailboxIRMAccess
  * Initial Release.
* EXOMailboxFolderPermission
  * Initial Release.
* EXOMailboxIRMAccess
  * Initial Release.
* EXOMailTips
  * Remove property `Ensure` since this resource is of type `IsSingleInstance`
* EXOManagementScope
  * Initial Release.
* EXORetentionPolicy
  * Initial Release.
* EXOPhishSimOverrideRule
  * Initial Release.
* IntuneAntivirusPolicyWindows10SettingCatalog
  * Fixes an issue with invalid parameter definition.
    FIXES [#5015](https://github.com/microsoft/Microsoft365DSC/issues/5015)
  * Fixes an issue where the `AccessTokens` parameter was not available.
    FIXES [#5121](https://github.com/microsoft/Microsoft365DSC/issues/5121)
* IntuneAppCategory
  * Initial release.
* IntuneDeviceCompliancePolicyWindows10
  * Fixes an issue where the property `ValidOperatingSystemBuildRanges` was
    not exported properly.
    FIXES [#5030](https://github.com/microsoft/Microsoft365DSC/issues/5030)
* IntuneDeviceConfigurationSharedMultiDevicePolicyWindows10
  * Add missing `AccessTokens` parameter to `Export-TargetResource`
    FIXES [#5034](https://github.com/microsoft/Microsoft365DSC/issues/5034)
* IntuneFirewallPolicyWindows10
  * Initial release
    FIXES [#3033](https://github.com/microsoft/Microsoft365DSC/issues/3033)
* IntuneSettingCatalogCustomPolicyWindows10
  * Update export logic to target more specific policy types.
  * Prevent thrown exception to be caught by exception handler.
    FIXES [#5088](https://github.com/microsoft/Microsoft365DSC/issues/5088)
* M365DSCDRGUtil
  * Add support for more complex Intune Settings Catalog properties
  * Update handling of `Update-IntuneDeviceConfigurationPolicy` to throw on error
    FIXES [#5055](https://github.com/microsoft/Microsoft365DSC/issues/5055)
* M365DSCResourceGenerator
  * Update Intune resource generation for the Settings Catalog.
* O365ExternalConnection
  * Initial release.
* SCDeviceConditionalAccessRule
  * Initial release.
* SCDeviceConfigurationRule
  * Initial release.
* SCInsiderRiskEntityList
  * Initial release.
* SCInsiderRiskPolicy
  * Initial release.
* SCRecordReviewNotificationTemplateConfig
  * Initial release.
* SCRoleGroup
  * Fixes an issue with creation without specifying Displayname
  * Fixes an issue with Drifts because of returned Role format
    FIXES [#5036](https://github.com/microsoft/Microsoft365DSC/issues/5036)
* SCAutoSensitivityLabelRule
  * Fixed issue with incorrectly applying HeaderMatchesPatterns, even when
    parameter wasn`t specified.
    FIXES [#4641](https://github.com/microsoft/Microsoft365DSC/issues/4641)
* SCSensitivityLabel
  * Added support for Auto Labeling settings
    FIXES [#3784](https://github.com/microsoft/Microsoft365DSC/issues/3784)
* SentinelSetting
  * Initial release.
* SentinelWatchlist
  * Initial release.
* SPOAccessControlSettings
  * Added support for property EnableRestrictedAccessControl.
* M365DSCUtil
  * Fixes an issue where the O365Group workload was not properly detected.
    FIXES [#5095](https://github.com/microsoft/Microsoft365DSC/issues/5095)
* DEPENDENCIES
  * Updated DSCParser to version 2.0.0.10.
  * Updated Microsoft.Graph to version 2.23.0.
  * Added dependencies on Az.Accounts, Az.Resources and Az.SecurityInsights
  * Updated DSCParser to version 2.0.0.9.
  * Updated MSCloudLoginAssistant to version 1.1.25.
  * Added dependency on Microsoft.Graph.Beta.Search.
  * Removed unnecessary dependency PSDesiredStateConfiguration v1.1'

      # Flag to indicate whether the module requires explicit user acceptance for install/update
      # RequireLicenseAcceptance = $false

      # External dependent modules of this module
      # ExternalModuleDependencies = @()

    } # End of PSData hashtable

  } # End of PrivateData hashtable

  # HelpInfo URI of this module
  # HelpInfoURI = ''

  # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
  # DefaultCommandPrefix = ''
}
