#
# Module manifest for module 'Microsoft365DSC'
#
# Generated by: Microsoft Corporation
#
# Generated on: 2025-07-04

@{

  # Script module or binary module file associated with this manifest.
  # RootModule = ''

  # Version number of this module.
  ModuleVersion     = '1.25.702.1'

  # Supported PSEditions
  # CompatiblePSEditions = @()

  # ID used to uniquely identify this module
  GUID              = '39f599a6-d212-4480-83b3-a8ea2124d8cf'

  # Author of this module
  Author            = 'Microsoft Corporation'

  # Company or vendor of this module
  CompanyName       = 'Microsoft Corporation'

  # Copyright statement for this module
  Copyright         = '(c) 2025 Microsoft Corporation. All rights reserved.'

  # Description of the functionality provided by this module
  Description       = 'This DSC module is used to configure and monitor Microsoft tenants, including SharePoint Online, Exchange, Teams, etc.'

  # Minimum version of the PowerShell engine required by this module
  PowerShellVersion = '5.1'

  # Name of the PowerShell host required by this module
  # PowerShellHostName = ''

  # Minimum version of the PowerShell host required by this module
  # PowerShellHostVersion = ''

  # Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
  # DotNetFrameworkVersion = ''

  # Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
  # CLRVersion = ''

  # Processor architecture (None, X86, Amd64) required by this module
  # ProcessorArchitecture = ''

  # Modules that must be imported into the global environment prior to importing this module
  RequiredModules   = @()

  # Assemblies that must be loaded prior to importing this module
  # RequiredAssemblies = @()

  # Script files (.ps1) that are run in the caller's environment prior to importing this module.
  ScriptsToProcess = @(
    'Update-MaximumFunctionCount.ps1'
  )

  # Type files (.ps1xml) to be loaded when importing this module
  # TypesToProcess = @()

  # Format files (.ps1xml) to be loaded when importing this module
  # FormatsToProcess = @()

  # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
  NestedModules     = @(
    'Modules/M365DSCAgent.psm1',
    'Modules/M365DSCDocGenerator.psm1',
    'Modules/M365DSCErrorHandler.psm1',
    'Modules/M365DSCLogEngine.psm1',
    'Modules/M365DSCPermissions.psm1',
    'Modules/M365DSCReport.psm1',
    'Modules/M365DSCReverse.psm1',
    'Modules/M365DSCStubsUtility.psm1',
    'Modules/M365DSCTelemetryEngine.psm1',
    'Modules/M365DSCUtil.psm1',
    'Modules/M365DSCDRGUtil.psm1',
    'Modules/M365DSCIntuneSettingsCatalogUtil.psm1',
    'Modules/EncodingHelpers/M365DSCEmojis.psm1',
    'Modules/WorkloadHelpers/M365DSCAzureHelper.psm1',
    'Modules/WorkloadHelpers/M365DSCAzureDevOPSHelper.psm1',
    'Modules/WorkloadHelpers/M365DSCDefenderHelper.psm1',
    'Modules/WorkloadHelpers/M365DSCFabricHelper.psm1',
    'Modules/WorkloadHelpers/M365DSCLicensingHelper.psm1',
    'Modules/WorkloadHelpers/M365DSCPowerPlatformRESTHelper.psm1',
    'Modules/WorkloadHelpers/M365DSCServicesHubHelper.psm1',
    'Modules/M365DSCConfigurationHelper.psm1'
  )

  # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
  #FunctionsToExport = @()

  # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
  CmdletsToExport   = @(
    'Assert-M365DSCBlueprint',
    'Compare-M365DSCConfigurations',
    'Confirm-M365DSCDependencies',
    'Export-M365DSCConfiguration',
    'Export-M365DSCDiagnosticData',
    'Get-M365DSCNotificationEndPointRegistration',
    'Get-M365DSCEvaluationRulesForConfiguration',
    'Join-M365DSCConfiguration',
    'New-M365DSCDeltaReport',
    'New-M365DSCNotificationEndPointRegistration',
    'New-M365DSCReportFromConfiguration',
    'New-M365DSCStubFiles',
    'Remove-M365DSCNotificationEndPointRegistration',
    'Set-M365DSCAgentCertificateConfiguration',
    'Test-M365DSCAgent',
    'Test-M365DSCDependenciesForNewVersions',
    'Test-M365DSCModuleValidity',
    'Uninstall-M365DSCOutdatedDependencies',
    'Update-M365DSCAllowedGraphScopes',
    'Update-M365DSCAzureAdApplication',
    'Update-M365DSCDependencies',
    'Update-M365DSCModule',
    'Update-M365DSCResourceDocumentationPage',
    'Update-M365DSCResourcesSettingsJSON'
  )

  # Variables to export from this module
  # VariablesToExport = @()

  # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
  AliasesToExport   = @()

  # List of all modules packaged with this module
  # ModuleList = @()

  # List of all files packaged with this module
  # FileList = @()

  # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
  PrivateData       = @{

    PSData = @{
      # Tags applied to this module. These help with module discovery in online galleries.
      Tags         = 'DesiredStateConfiguration', 'DSC', 'DSCResourceKit', 'DSCResource', 'Microsoft365'

      # A URL to the license for this module.
      LicenseUri   = 'https://github.com/Microsoft/Microsoft365DSC/blob/master/LICENSE'

      # A URL to the main website for this project.
      ProjectUri   = 'https://github.com/Microsoft/Microsoft365DSC'

      # A URL to an icon representing this module.
      IconUri      = 'https://github.com/microsoft/Microsoft365DSC/blob/Dev/Modules/Microsoft365DSC/Dependencies/Images/Logo.png?raw=true'

      # ReleaseNotes of this module
      ReleaseNotes = '* AADAdministrativeUnit
  * Throw if an unsupported Member or ScopedRoleMember type is returned.
  * Fix verbose logging for assigned memberships, make update calls type-agnostic.
* AADAgreement
  * Initial release.
* AADApplication
  * Fix to properly handle PreAuthorizedApplications in the Set-TargetResource method
    FIXES [#6182](https://github.com/microsoft/Microsoft365DSC/issues/6182)
* AADConditionalAccessPolicy
  * Fix for removing or resetting builtInControls, customAuthenticationFactors,
    authenticationStrength or termsOfUse
    FIXES [#6218](https://github.com/microsoft/Microsoft365DSC/issues/6218)
  * FIXES [#6198] Adds support for ServicePrincipalRiskLevels
  * FIXES [[#6242](https://github.com/microsoft/Microsoft365DSC/issues/6242)]
    Avoids creating or updating a policy with a missing/unknown location.
* AADEntitlementManagementAccessPackage
  * Fix catalogId variables used when adding resource to access package from catalog
* AADGroup
  * Fix for removing Group owner.
* AADGroupElegibilityScheduleSettings
  * New resource AADGroupElegibilityScheduleSettings
* AADIdentityB2XUserFlow
  * Corrected permission in settings.json
* AADRoleAssignmentScheduleRequest
  * FIXES [#5710](https://github.com/microsoft/Microsoft365DSC/issues/5710)
* AADServicePrincipal
  * Fixed an issue where the `AppId` won`t be exported.
    FIXES [#6200](https://github.com/microsoft/Microsoft365DSC/issues/6200)
    FIXES [#6181](https://github.com/microsoft/Microsoft365DSC/issues/6181)
    FIXES [#6045](https://github.com/microsoft/Microsoft365DSC/issues/6045)
    FIXES [#5419](https://github.com/microsoft/Microsoft365DSC/issues/5419)
  * Fixed an issue where updating the configuration with `CustomSecurityAttributes`
    would fail.
    FIXES [#6208](https://github.com/microsoft/Microsoft365DSC/issues/6208)
* EXODistributionGroup
  * Always use the retrieved Identity when updating the distribution group
    to ensure correct group is updated when retrieved with PrimarySmtpAddress.
* FabricAdminTenantSettings
  * Fixed an issue where exported titles could contain unescaped string literals.
    FIXES [#6199](https://github.com/microsoft/Microsoft365DSC/issues/6199)
* IntuneDeviceAndAppManagementAssignmentFilter
  * Added property `AssignmentFilterManagementType` to supported properties.
* IntuneDeviceCompliancePolicyAndroidDeviceOwner
  * Added new property `SecurityBlockJailbrokenDevices`.
* IntuneDeviceConfigurationAdministrativeTemplatePolicyWindows10
  * Added support for property `RoleScopeTagIds`.
* IntuneDefenderGlobalExclusionsPolicyLinux
  * Initial release.
* IntuneDeviceConfigurationDeliveryOptimizationPolicyWindows10
  * Deprecated resource.
* IntuneDeviceConfigurationDeliveryOptimizationPolicyWindows10SettingCatalog
  * Initial release.
* IntuneWindowsHelloForBusinessGlobalPolicy
  * Initial release.
    FIXES [#4561](https://github.com/microsoft/Microsoft365DSC/issues/4561)
* SCComplianceSearchAction
  * Fixed an issue where the export would fail for preview actions.
    FIXES [#6215](https://github.com/microsoft/Microsoft365DSC/issues/6215)
    FIXES [#3534](https://github.com/microsoft/Microsoft365DSC/issues/3534)
* SCDLPComplianceRule
  * Fixed an issue where the export of `SetHeader` is wrongly formatted.
    FIXES [#6140](https://github.com/microsoft/Microsoft365DSC/issues/6140)
  * Fixed an issue where the export of `AdvancedRule` with multiple and nested subconditions
    would throw an error during removal of the sensitive type id.
* SPOSharingSettings
  * Removing calls to deprecated RequireAcceptingAccountMatchInvitedAccount setting
    that prevent SharingDomainRestrictionMode from being set properly.
* TeamsCallQueue
  * Fixed an issue with the export where we can now export more than 100 instances.
* TeamsMeetingPolicy
  * Added missing Parameter `RoomAttributeUserOverride` to Get-TargetResource`s output.
    Fixes [#6183](https://github.com/microsoft/Microsoft365DSC/issues/6183)
* M365DSCPermissions
  * Fixed an issue when accessing permissions from the compiled list returns no permissions.
* M365DSCReverse
  * Fixed an issue where a provided file name with spaces leads to an invalid export config name.
    FIXES [#6247](https://github.com/microsoft/Microsoft365DSC/issues/6247)
* M365DSCUtil
  * Add -ExcludeComponents parameter to `Export-M365DSCConfiguration`to allow
    for easy skipping of certain components.
    FIXES [#6192(https://github.com/microsoft/Microsoft365DSC/issues/6192)]
  * Moved `Get-M365DSCIntuneDeviceConfigurationSettings` function to central location.
* MISC
  * Added `deviceAndAppManagementAssignmentFilterDisplayName` property to Intune assignments.
    FIXES [#4609](https://github.com/microsoft/Microsoft365DSC/issues/4609)
  * Added module pinning.
    FIXES [#6168](https://github.com/microsoft/Microsoft365DSC/issues/6168)
  * Streamlined `Test-TargetResource` for many resources.
  * Streamlined usage of `Get-M365DSCIntuneDeviceConfigurationSettings` in combination with
    updating Intune intent policy type settings.
    FIXES [#6252](https://github.com/microsoft/Microsoft365DSC/issues/6252)
* DEPENDENCIES
  * Updated MSCloudLoginAssistant to version 1.1.48.'

      # Flag to indicate whether the module requires explicit user acceptance for install/update
      # RequireLicenseAcceptance = $false

      # External dependent modules of this module
      # ExternalModuleDependencies = @()

    } # End of PSData hashtable

  } # End of PrivateData hashtable

  # HelpInfo URI of this module
  # HelpInfoURI = ''

  # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
  # DefaultCommandPrefix = ''
}
