[ClassVersion("1.0.0.0"), FriendlyName("EXOAntiPhishPolicy")]
class MSFT_EXOAntiPhishPolicy : OMI_BaseResource
{
    [Key, Description("The Identity parameter specifies the antiphishing policy that you want to modify.")] String Identity;
    [Write, ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Write, Description("The AdminDisplayName parameter specifies a description for the policy.")] String AdminDisplayName;
    [Write, ValueMap{"1","2","3","4"}, Values{"1","2","3","4"}] String PhishThresholdLevel;
    [Write, ValueMap{"MoveToJmf","Quarantine"}, Values{"MoveToJmf","Quarantine"}] String AuthenticationFailAction;
    [Write, ValueMap{"BccMessage","Delete","MoveToJmf","NoAction","Quarantine","Redirect"}, Values{"BccMessage","Delete","MoveToJmf","NoAction","Quarantine","Redirect"}] String TargetedDomainProtectionAction;
    [Write, ValueMap{"BccMessage","Delete","MoveToJmf","NoAction","Quarantine","Redirect"}, Values{"BccMessage","Delete","MoveToJmf","NoAction","Quarantine","Redirect"}] String TargetedUserProtectionAction;
    [Write] Boolean Enabled;
    [Write] Boolean EnableAntispoofEnforcement;
    [Write] Boolean EnableAuthenticationSafetyTip;
    [Write] Boolean EnableAuthenticationSoftPassSafetyTip;
    [Write] Boolean EnableMailboxIntelligence;
    [Write] Boolean EnableOrganizationDomainsProtection;
    [Write] Boolean EnableSimilarDomainsSafetyTips;
    [Write] Boolean EnableSimilarUsersSafetyTips;
    [Write] Boolean EnableTargetedDomainsProtection;
    [Write] Boolean EnableTargetedUserProtection;
    [Write] Boolean EnableUnusualCharactersSafetyTips;
    [Write] Boolean MakeDefault;
    [Write] Boolean TreatSoftPassAsAuthenticated;
    [Write] String ExcludedDomains[];
    [Write] String ExcludedSenders[];
    [Write] String TargetedDomainActionRecipients[];
    [Write] String TargetedDomainsToProtect[];
    [Write] String TargetedUserActionRecipients[];
    [Write] String TargetedUsersToProtect[];
    [Required, Description("Credentials of the Exchange Global Admin"), EmbeddedInstance("MSFT_Credential")] String GlobalAdminAccount;
};
