[ClassVersion("1.0.0.0"), FriendlyName("EXOAvailabilityConfig")]
class MSFT_EXOAvailabilityConfig : OMI_BaseResource
{
    [Key, Description("Specify the OrgWideAccount for the AvailabilityConfig.")] String OrgWideAccount;
    [Write, Description("Specify if the AvailabilityConfig should exist or not."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Required, Description("Credentials of the Exchange Global Admin"), EmbeddedInstance("MSFT_Credential")] string GlobalAdminAccount;
};
