[ClassVersion("1.0.0.0"), FriendlyName("SCCaseHoldRule")]
class MSFT_SCCaseHoldRule : OMI_BaseResource
{
    [Key, Description("The Name parameter specifies a unique name for the case hold rule.")] String Name;
    [Key, Description("The Policy parameter specifies the case hold policy that contains the rule. You can use any value that uniquely identifies the policy.")] String Policy;
    [Write, Description("The Comment parameter specifies an optional comment.")] String Comment;
    [Write, Description("The ContentMatchQuery parameter specifies a content search filter. Use this parameter to create a query-based hold so only the content that matches the specified search query is placed on hold. This parameter uses a text search string or a query that's formatted by using the Keyword Query Language (KQL).")] String ContentMatchQuery;
    [Write, Description("The Disabled parameter specifies whether the case hold rule is enabled or disabled.")] Boolean Disabled;
    [Write, Description("Present ensures the rule exists, absent ensures it is removed"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Write, Description("Credentials of the Global Admin Account"), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Id of the Azure Active Directory tenant used for authentication.")] String TenantId;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Username can be made up to anything but password will be used for CertificatePassword"), EmbeddedInstance("MSFT_Credential")] String CertificatePassword;
    [Write, Description("Path to certificate used in service principal usually a PFX file.")] String CertificatePath;
    [Write, Description("Access token used for authentication.")] String AccessTokens[];
};
