[ClassVersion("1.0.0.0"), FriendlyName("TeamsWorkloadPolicy")]
class MSFT_TeamsWorkloadPolicy : OMI_BaseResource
{
    [Key, Description("Unique identity for the Teams workload policy")] String Identity;
    [Write, Description("Allows calling.")] Boolean AllowCalling;
    [Write, Description("Allows pinning a call.")] Boolean AllowCallingPinned;
    [Write, Description("Allows meetins.")] Boolean AllowMeeting;
    [Write, Description("Allows pinning meetings.")] Boolean AllowMeetingPinned;
    [Write, Description("Allows messaging.")] Boolean AllowMessaging;
    [Write, Description("Allows pinning a message.")] Boolean AllowMessagingPinned;
    [Write, Description("Description of the policy.")] String Description;
    [Write, Description("Present ensures the instance exists, absent ensures it is removed."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] string Ensure;
    [Write, Description("Credentials of the workload's Admin"), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Id of the Azure Active Directory tenant used for authentication.")] String TenantId;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Managed ID being used for authentication.")] Boolean ManagedIdentity;
};
