[ClassVersion("1.0.0.0"), FriendlyName("EXODynamicDistributionGroup")]
class MSFT_EXODynamicDistributionGroup : OMI_BaseResource
{
    [Write, Description("The AcceptMessagesOnlyFrom parameter specifies who is allowed to send messages to this recipient.")] String AcceptMessagesOnlyFrom[];
    [Write, Description("The AcceptMessagesOnlyFromDLMembers parameter specifies who is allowed to send messages to this recipient. Messages from other senders are rejected.")] String AcceptMessagesOnlyFromDLMembers[];
    [Write, Description("The Alias parameter specifies the Exchange alias (also known as the mail nickname) for the recipient. This value identifies the recipient as a mail-enabled object, and shouldn't be confused with multiple email addresses for the same recipient (also known as proxy addresses). A recipient can have only one Alias value. The maximum length is 64 characters.")] String Alias;
    [Write, Description("The BypassModerationFromSendersOrMembers parameter specifies who is allowed to send messages to this moderated recipient without approval from a moderator. Valid values for this parameter are individual senders and groups in your organization. Specifying a group means all members of the group are allowed to send messages to this recipient without approval from a moderator.")] String BypassModerationFromSendersOrMembers[];
    [Write, Description("The ConditionalCompany parameter specifies a precanned filter that's based on the value of the recipient's Company property. When you use multiple values for this parameter, the OR Boolean operator is applied.")] String ConditionalCompany;
    [Write, Description("The ConditionalCustomAttribute1 parameter specifies a precanned filter that's based on the value of the recipient's CustomAttribute1 property. You can specify multiple values separated by commas. When you use multiple values for this parameter, the OR Boolean operator is applied.")] String ConditionalCustomAttribute1[];
    [Write, Description("The ConditionalCustomAttribute10 parameter specifies a precanned filter that's based on the value of the recipient's CustomAttribute10 property. You can specify multiple values separated by commas. When you use multiple values for this parameter, the OR Boolean operator is applied.")] String ConditionalCustomAttribute10[];
    [Write, Description("The ConditionalCustomAttribute11 parameter specifies a precanned filter that's based on the value of the recipient's CustomAttribute11 property. You can specify multiple values separated by commas. When you use multiple values for this parameter, the OR Boolean operator is applied.")] String ConditionalCustomAttribute11[];
    [Write, Description("The ConditionalCustomAttribute12 parameter specifies a precanned filter that's based on the value of the recipient's CustomAttribute12 property. You can specify multiple values separated by commas. When you use multiple values for this parameter, the OR Boolean operator is applied.")] String ConditionalCustomAttribute12[];
    [Write, Description("The ConditionalCustomAttribute13 parameter specifies a precanned filter that's based on the value of the recipient's CustomAttribute13 property. You can specify multiple values separated by commas. When you use multiple values for this parameter, the OR Boolean operator is applied.")] String ConditionalCustomAttribute13[];
    [Write, Description("The ConditionalCustomAttribute14 parameter specifies a precanned filter that's based on the value of the recipient's CustomAttribute14 property. You can specify multiple values separated by commas. When you use multiple values for this parameter, the OR Boolean operator is applied.")] String ConditionalCustomAttribute14[];
    [Write, Description("The ConditionalCustomAttribute15 parameter specifies a precanned filter that's based on the value of the recipient's CustomAttribute15 property. You can specify multiple values separated by commas. When you use multiple values for this parameter, the OR Boolean operator is applied.")] String ConditionalCustomAttribute15[];
    [Write, Description("The ConditionalCustomAttribute2 parameter specifies a precanned filter that's based on the value of the recipient's CustomAttribute2 property. You can specify multiple values separated by commas. When you use multiple values for this parameter, the OR Boolean operator is applied.")] String ConditionalCustomAttribute2[];
    [Write, Description("The ConditionalCustomAttribute3 parameter specifies a precanned filter that's based on the value of the recipient's CustomAttribute3 property. You can specify multiple values separated by commas. When you use multiple values for this parameter, the OR Boolean operator is applied.")] String ConditionalCustomAttribute3[];
    [Write, Description("The ConditionalCustomAttribute4 parameter specifies a precanned filter that's based on the value of the recipient's CustomAttribute4 property. You can specify multiple values separated by commas. When you use multiple values for this parameter, the OR Boolean operator is applied.")] String ConditionalCustomAttribute4[];
    [Write, Description("The ConditionalCustomAttribute5 parameter specifies a precanned filter that's based on the value of the recipient's CustomAttribute5 property. You can specify multiple values separated by commas. When you use multiple values for this parameter, the OR Boolean operator is applied.")] String ConditionalCustomAttribute5[];
    [Write, Description("The ConditionalCustomAttribute6 parameter specifies a precanned filter that's based on the value of the recipient's CustomAttribute6 property. You can specify multiple values separated by commas. When you use multiple values for this parameter, the OR Boolean operator is applied.")] String ConditionalCustomAttribute6[];
    [Write, Description("The ConditionalCustomAttribute7 parameter specifies a precanned filter that's based on the value of the recipient's CustomAttribute7 property. You can specify multiple values separated by commas. When you use multiple values for this parameter, the OR Boolean operator is applied.")] String ConditionalCustomAttribute7[];
    [Write, Description("The ConditionalCustomAttribute8 parameter specifies a precanned filter that's based on the value of the recipient's CustomAttribute8 property. You can specify multiple values separated by commas. When you use multiple values for this parameter, the OR Boolean operator is applied.")] String ConditionalCustomAttribute8[];
    [Write, Description("The ConditionalCustomAttribute9 parameter specifies a precanned filter that's based on the value of the recipient's CustomAttribute9 property. You can specify multiple values separated by commas. When you use multiple values for this parameter, the OR Boolean operator is applied.")] String ConditionalCustomAttribute9[];
    [Write, Description("The ConditionalDepartment parameter specifies a precanned filter that's based on the value of the recipient's Department property. You can specify multiple values separated by commas. When you use multiple values for this parameter, the OR Boolean operator is applied.")] String ConditionalDepartment[];
    [Write, Description("The ConditionalStateOrProvince parameter specifies a precanned filter that's based on the value of the recipient's StateOrProvince property. You can specify multiple values separated by commas. When you use multiple values for this parameter, the OR Boolean operator is applied.")] String ConditionalStateOrProvince[];
    [Write, Description("This parameter specifies a value for the CustomAttribute1 property on the recipient. You can use this property to store custom information about the recipient, and to identify the recipient in filters. The maximum length is 1024 characters.")] String CustomAttribute1;
    [Write, Description("This parameter specifies a value for the CustomAttribute10 property on the recipient. You can use this property to store custom information about the recipient, and to identify the recipient in filters. The maximum length is 1024 characters. ")] String CustomAttribute10;
    [Write, Description("This parameter specifies a value for the CustomAttribute11 property on the recipient. You can use this property to store custom information about the recipient, and to identify the recipient in filters. The maximum length is 1024 characters.")] String CustomAttribute11;
    [Write, Description("This parameter specifies a value for the CustomAttribute12 property on the recipient. You can use this property to store custom information about the recipient, and to identify the recipient in filters. The maximum length is 1024 characters.")] String CustomAttribute12;
    [Write, Description("This parameter specifies a value for the CustomAttribute13 property on the recipient. You can use this property to store custom information about the recipient, and to identify the recipient in filters. The maximum length is 1024 characters.")] String CustomAttribute13;
    [Write, Description("This parameter specifies a value for the CustomAttribute14 property on the recipient. You can use this property to store custom information about the recipient, and to identify the recipient in filters. The maximum length is 1024 characters.")] String CustomAttribute14;
    [Write, Description("This parameter specifies a value for the CustomAttribute15 property on the recipient. You can use this property to store custom information about the recipient, and to identify the recipient in filters. The maximum length is 1024 characters.")] String CustomAttribute15;
    [Write, Description("This parameter specifies a value for the CustomAttribute2 property on the recipient. You can use this property to store custom information about the recipient, and to identify the recipient in filters. The maximum length is 1024 characters.")] String CustomAttribute2;
    [Write, Description("This parameter specifies a value for the CustomAttribute3 property on the recipient. You can use this property to store custom information about the recipient, and to identify the recipient in filters. The maximum length is 1024 characters.")] String CustomAttribute3;
    [Write, Description("This parameter specifies a value for the CustomAttribute4 property on the recipient. You can use this property to store custom information about the recipient, and to identify the recipient in filters. The maximum length is 1024 characters.")] String CustomAttribute4;
    [Write, Description("This parameter specifies a value for the CustomAttribute5 property on the recipient. You can use this property to store custom information about the recipient, and to identify the recipient in filters. The maximum length is 1024 characters.")] String CustomAttribute5;
    [Write, Description("This parameter specifies a value for the CustomAttribute6 property on the recipient. You can use this property to store custom information about the recipient, and to identify the recipient in filters. The maximum length is 1024 characters.")] String CustomAttribute6;
    [Write, Description("This parameter specifies a value for the CustomAttribute7 property on the recipient. You can use this property to store custom information about the recipient, and to identify the recipient in filters. The maximum length is 1024 characters.")] String CustomAttribute7;
    [Write, Description("This parameter specifies a value for the CustomAttribute8 property on the recipient. You can use this property to store custom information about the recipient, and to identify the recipient in filters. The maximum length is 1024 characters.")] String CustomAttribute8;
    [Write, Description("This parameter specifies a value for the CustomAttribute9 property on the recipient. You can use this property to store custom information about the recipient, and to identify the recipient in filters. The maximum length is 1024 characters.")] String CustomAttribute9;
    [Write, Description("The DisplayName parameter specifies the display name of the dynamic distribution group. The display name is visible in the Exchange admin center and in address lists. The maximum length is 256 characters.")] String DisplayName;
    [Write, Description("The EmailAddresses parameter specifies all email addresses (proxy addresses) for the recipient, including the primary SMTP address. ")] String EmailAddresses[];
    [Write, Description("This parameter specifies a value for the ExtensionCustomAttribute1 property on the recipient. You can use this property to store custom information about the recipient, and to identify the recipient in filters. You can specify up to 1300 values separated by commas.")] String ExtensionCustomAttribute1[];
    [Write, Description("This parameter specifies a value for the ExtensionCustomAttribute2 property on the recipient. You can use this property to store custom information about the recipient, and to identify the recipient in filters. You can specify up to 1300 values separated by commas.")] String ExtensionCustomAttribute2;
    [Write, Description("This parameter specifies a value for the ExtensionCustomAttribute3 property on the recipient. You can use this property to store custom information about the recipient, and to identify the recipient in filters. You can specify up to 1300 values separated by commas.")] String ExtensionCustomAttribute3;
    [Write, Description("This parameter specifies a value for the ExtensionCustomAttribute4 property on the recipient. You can use this property to store custom information about the recipient, and to identify the recipient in filters. You can specify up to 1300 values separated by commas.")] String ExtensionCustomAttribute4;
    [Write, Description("This parameter specifies a value for the ExtensionCustomAttribute5 property on the recipient. You can use this property to store custom information about the recipient, and to identify the recipient in filters. You can specify up to 1300 values separated by commas.")] String ExtensionCustomAttribute5;
    [Write, Description("The GrantSendOnBehalfTo parameter specifies who can send on behalf of this dynamic distribution group. Although messages send on behalf of the group clearly show the sender in the From field (<Sender> on behalf of <Group>), replies to these messages are delivered to the group, not the sender.")] String GrantSendOnBehalfTo[];
    [Write, Description("The HiddenFromAddressListsEnabled parameter specifies whether this recipient is visible in address lists. Valid values are: $true: The recipient isn't visible in address lists. $false: The recipient is visible in address lists. This value is the default.")] Boolean HiddenFromAddressListsEnabled;
    [Key, Description("The Identity parameter specifies the dynamic distribution group that you want to modify. You can use any value that uniquely identifies the dynamic distribution group.")] String Identity;
    [Write, Description("The IncludedRecipients parameter specifies a precanned filter that's based on the recipient type. Valid values are: AllRecipients: This value can be used only by itself. MailboxUsers. MailContacts. MailGroups. MailUsers. Resources: This value indicates room or equipment mailboxes. You can specify multiple values separated by commas. When you use multiple values, the OR Boolean operator is applied."), ValueMap{"AllRecipients","MailboxUsers","MailboxContacts","MailGroups","MailUsers","Resources"}, Values{"AllRecipients","MailboxUsers","MailboxContacts","MailGroups","MailUsers","Resources"}] String IncludedRecipients[];
    [Write, Description("The MailTip parameter specifies the custom MailTip text for this recipient. The MailTip is shown to senders when they start drafting an email message to this recipient. If the value contains spaces, enclose the value in quotation marks (\").")] String MailTip;
    [Write, Description("The MailTipTranslations parameter specifies additional languages for the custom MailTip text that's defined by the MailTip parameter. HTML tags are automatically added to the MailTip translation, additional HTML tags aren't supported, and the length of the MailTip translation can't exceed 175 displayed characters.")] String MailTipTranslations[];
    [Write, Description("The ManagedBy parameter specifies an owner for the group. A dynamic group can only have one owner.")] String ManagedBy;
    [Write, Description("The ModeratedBy parameter specifies one or more moderators for this recipient. A moderator approves messages sent to the recipient before the messages are delivered. A moderator must be a mailbox, mail user, or mail contact in your organization. You can use any value that uniquely identifies the moderator.")] String ModeratedBy[];
    [Write, Description("The ModerationEnabled parameter specifies whether moderation is enabled for this recipient.")] Boolean ModerationEnabled;
    [Write, Description("The Name parameter specifies the unique name of the dynamic distribution group. The maximum length is 64 characters.")] String Name;
    [Write, Description("The Notes parameters specifies additional information about the object.")] String Notes;
    [Write, Description("The PhoneticDisplayName parameter specifies an alternate spelling of the user's name that's used for text to speech in Unified Messaging (UM) environments. Typically, you use this parameter when the pronunciation and spelling of the user's name don't match. The maximum length is 256 characters.")] String PhoneticDisplayName;
    [Write, Description("The PrimarySmtpAddress parameter specifies the primary return email address that's used for the recipient.")] String PrimarySmtpAddress;
    [Write, Description("The RecipientContainer parameter specifies a filter that's based on the recipient's location in Active Directory. Valid input for this parameter is an organizational unit (OU) or domain that's returned by the Get-OrganizationalUnit cmdlet. You can use any value that uniquely identifies the OU or domain.")] String RecipientContainer;
    [Write, Description("The RecipientFilter parameter specifies a custom OPATH filter that's based on the value of any available recipient property. You can use any available Windows PowerShell operator, and wildcards and partial matches are supported. The search criteria uses the syntax \"Property -ComparisonOperator 'Value'\".")] String RecipientFilter;
    [Write, Description("The RejectMessagesFrom parameter specifies who isn't allowed to send messages to this recipient. Messages from these senders are rejected.")] String RejectMessagesFrom[];
    [Write, Description("The RejectMessagesFromDLMembers parameter specifies who isn't allowed to send messages to this recipient. Messages from these senders are rejected.")] String RejectMessagesFromDLMembers[];
    [Write, Description("The RejectMessagesFromSendersOrMembers parameter specifies who isn't allowed to send messages to this recipient. Messages from these senders are rejected.")] String RejectMessagesFromSendersOrMembers[];
    [Write, Description("The ReportToManagerEnabled parameter specifies whether delivery status notifications (also known as DSNs, non-delivery reports, NDRs, or bounce messages) are sent to the owners of the group (defined by the ManagedBy property).")] Boolean ReportToManagerEnabled;
    [Write, Description("The ReportToOriginatorEnabled parameter specifies whether delivery status notifications (also known as DSNs, non-delivery reports, NDRs, or bounce messages) are sent to senders who send messages to this group.")] Boolean ReportToOriginatorEnabled;
    [Write, Description("The RequireSenderAuthenticationEnabled parameter specifies whether to accept messages only from authenticated (internal) senders.")] Boolean RequireSenderAuthenticationEnabled;
    [Write, Description("The SendModerationNotifications parameter specifies when moderation notification messages are sent. Valid values are: Always: Notify all senders when their messages aren't approved. This value is the default. Internal: Notify senders in the organization when their messages aren't approved. Never: Don't notify anyone when a message isn't approved."), ValueMap{"Always","Internal","Never"}, Values{"Always","Internal","Never"}] String SendModerationNotifications;
    [Write, Description("The SendOofMessageToOriginatorEnabled parameter specifies how to handle out of office (OOF) messages for members of the group.")] Boolean SendOofMessageToOriginatorEnabled;
    [Write, Description("The SimpleDisplayName parameter is used to display an alternative description of the object when only a limited set of characters is permitted.")] String SimpleDisplayName;
    [Write, Description("The WindowsEmailAddress parameter specifies the Windows email address for this recipient. This is a common Active Directory attribute that's present in all environments, including environments without Exchange.")] String WindowsEmailAddress;
    [Write, Description("Present ensures the policy exists, absent ensures it is removed."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] string Ensure;
    [Write, Description("Credentials of the Exchange Global Admin"), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Id of the Azure Active Directory tenant used for authentication.")] String TenantId;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Username can be made up to anything but password will be used for CertificatePassword"), EmbeddedInstance("MSFT_Credential")] String CertificatePassword;
    [Write, Description("Path to certificate used in service principal usually a PFX file.")] String CertificatePath;
    [Write, Description("Managed ID being used for authentication.")] Boolean ManagedIdentity;
    [Write, Description("Access token used for authentication.")] String AccessTokens[];
};
