[ClassVersion("1.0.0.0"), FriendlyName("EXOManagementRoleEntry")]
class MSFT_EXOManagementRoleEntry : OMI_BaseResource
{
    [Key, Description("The Identity parameter specifies the role entry that you want to modify.")] String Identity;
    [Write, Description("The Parameters parameter specifies the parameters to be added to or removed from the role entry.")] String Parameters[];
    [Write, Description("The Type parameter specifies the type of role entry to return."), ValueMap{"Cmdlet","Script","ApplicationPermission","WebService"}, Values{"Cmdlet","Script","ApplicationPermission","WebService"}] String Type;
    [Write, Description("Credentials of the Exchange Global Admin"), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Id of the Azure Active Directory tenant used for authentication.")] String TenantId;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Username can be made up to anything but password will be used for CertificatePassword"), EmbeddedInstance("MSFT_Credential")] String CertificatePassword;
    [Write, Description("Path to certificate used in service principal usually a PFX file.")] String CertificatePath;
    [Write, Description("Managed ID being used for authentication.")] Boolean ManagedIdentity;
    [Write, Description("Access token used for authentication.")] String AccessTokens[];
};
