[ClassVersion("1.0.0.0"), FriendlyName("TeamsUser")]
class MSFT_TeamsUser : OMI_BaseResource
{
    [Key, Description("Team Group")] string GroupId;
    [Key, Description("DisplayName of the User")] string DisplayName;
    [Key, Description("UPN of user to add to Team")] String User;
    [Write, Description("User role in Team"),ValueMap{"Guest","Member","Owner"},Values{"Guest","Member","Owner"}] String Role;
    [Write, Description("Present ensures the Team user exists, absent ensures it is removed"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Required, Description("Credentials of the SharePoint Global Admin"), EmbeddedInstance("MSFT_Credential")] String GlobalAdminAccount;
};

