[ClassVersion("1.0.0.0"), FriendlyName("O365ExternalConnection")]
class MSFT_O365ExternalConnection : OMI_BaseResource
{
    [Key, Description("The name of the external connector.")] String Name;
    [Write, Description("The unique identifier of the external connector.")] String Id;
    [Write, Description("The description of the external connector.")] String Description;
    [Write, Description("A collection of application IDs for registered Microsoft Entra apps that are allowed to manage the externalConnection and to index content in the externalConnection.")] String AuthorizedAppIds[];
    [Write, Description("Present ensures the instance exists, absent ensures it is removed."), ValueMap{"Absent","Present"}, Values{"Absent","Present"}] string Ensure;
    [Write, Description("Credentials of the workload's Admin"), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Id of the Azure Active Directory tenant used for authentication.")] String TenantId;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Managed ID being used for authentication.")] Boolean ManagedIdentity;
    [Write, Description("Access token used for authentication.")] String AccessTokens[];
};
