[ClassVersion("1.0.0.0"), FriendlyName("EXOAddressList")]
class MSFT_EXOAddressList : OMI_BaseResource
{
    [Key, Description("The Name parameter specifies a unique name for the address list. The maximum length is 64 characters, and it can't include a carriage return or a backslash (\). If the value contains spaces, enclose the value in quotation marks (").")] String Name;
    [Write, Description("The ConditionalCompany parameter specifies a precanned filter that's based on the value of the recipient's Company property.")] String ConditionalCompany;
    [Write, Description("The ConditionalCustomAttribute1 parameter specifies a precanned filter that's based on the value of the recipient's CustomAttribute1 property. You can specify multiple values separated by commas.")] String ConditionalCustomAttribute1;
    [Write, Description("The ConditionalCustomAttribute10 parameter specifies a precanned filter that's based on the value of the recipient's CustomAttribute10 property. You can specify multiple values separated by commas.")] String ConditionalCustomAttribute10;
    [Write, Description("The ConditionalCustomAttribute11 parameter specifies a precanned filter that's based on the value of the recipient's CustomAttribute11 property. You can specify multiple values separated by commas.")] String ConditionalCustomAttribute11;
    [Write, Description("The ConditionalCustomAttribute12 parameter specifies a precanned filter that's based on the value of the recipient's CustomAttribute12 property. You can specify multiple values separated by commas.")] String ConditionalCustomAttribute12;
    [Write, Description("The ConditionalCustomAttribute13 parameter specifies a precanned filter that's based on the value of the recipient's CustomAttribute13 property. You can specify multiple values separated by commas.")] String ConditionalCustomAttribute13;
    [Write, Description("The ConditionalCustomAttribute14 parameter specifies a precanned filter that's based on the value of the recipient's CustomAttribute14 property. You can specify multiple values separated by commas.")] String ConditionalCustomAttribute14;
    [Write, Description("The ConditionalCustomAttribute15 parameter specifies a precanned filter that's based on the value of the recipient's CustomAttribute15 property. You can specify multiple values separated by commas.")] String ConditionalCustomAttribute15;
    [Write, Description("The ConditionalCustomAttribute2 parameter specifies a precanned filter that's based on the value of the recipient's CustomAttribute2 property. You can specify multiple values separated by commas.")] String ConditionalCustomAttribute2;
    [Write, Description("The ConditionalCustomAttribute3 parameter specifies a precanned filter that's based on the value of the recipient's CustomAttribute3 property. You can specify multiple values separated by commas.")] String ConditionalCustomAttribute3;
    [Write, Description("The ConditionalCustomAttribute4 parameter specifies a precanned filter that's based on the value of the recipient's CustomAttribute4 property. You can specify multiple values separated by commas.")] String ConditionalCustomAttribute4;
    [Write, Description("The ConditionalCustomAttribute5 parameter specifies a precanned filter that's based on the value of the recipient's CustomAttribute5 property. You can specify multiple values separated by commas.")] String ConditionalCustomAttribute5;
    [Write, Description("The ConditionalCustomAttribute6 parameter specifies a precanned filter that's based on the value of the recipient's CustomAttribute6 property. You can specify multiple values separated by commas.")] String ConditionalCustomAttribute6;
    [Write, Description("The ConditionalCustomAttribute7 parameter specifies a precanned filter that's based on the value of the recipient's CustomAttribute7 property. You can specify multiple values separated by commas.")] String ConditionalCustomAttribute7;
    [Write, Description("The ConditionalCustomAttribute8 parameter specifies a precanned filter that's based on the value of the recipient's CustomAttribute8 property. You can specify multiple values separated by commas.")] String ConditionalCustomAttribute8;
    [Write, Description("The ConditionalCustomAttribute9 parameter specifies a precanned filter that's based on the value of the recipient's CustomAttribute9 property. You can specify multiple values separated by commas.")] String ConditionalCustomAttribute9;
    [Write, Description("The ConditionalDepartment parameter specifies a precanned filter that's based on the value of the recipient's Department property. You can specify multiple values separated by commas.")] String ConditionalDepartment;
    [Write, Description("The ConditionalStateOrProvince parameter specifies a precanned filter that's based on the value of the recipient's StateOrProvince property. You can specify multiple values separated by commas.")] String ConditionalStateOrProvince;
    [Write, Description("The DisplayName parameter specifies the display name of the group. The display name is visible in the Exchange admin center and in Outlook. The maximum length is 256 characters. If the value contains spaces, enclose the value in quotation marks (").")] String DisplayName;
    [Write, Description("The IncludedRecipients parameter specifies a precanned filter that's based on the recipient type. Valid values are: AllRecipients: This value can be used only by itself. MailboxUsers. MailContacts. MailGroups. MailUsers. Resources: This value indicates room or equipment mailboxes."), ValuMap{'AllRecipients', 'MailboxUsers', 'MailContacts', 'MailGroups', 'MailUsers', 'Resources'}, Values{'AllRecipients', 'MailboxUsers', 'MailContacts', 'MailGroups', 'MailUsers', 'Resources'}] String  IncludedRecipients;
    [Write, Description("The RecipientFilter parameter specifies a custom OPath filter that's based on the value of any available recipient property. You can use any available Windows PowerShell operator, and wildcards and partial matches are supported. The search criteria uses the syntax "Property -ComparisonOperator 'Value'".")] String RecipientFilter;
    [Write, Description("Specifies if this AddressList should exist."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Required, Description("Credentials of the Exchange Global Admin"), EmbeddedInstance("MSFT_Credential")] String GlobalAdminAccount;
};
