[ClassVersion("1.0.0.0"), FriendlyName("EXOAddressList")]
class MSFT_EXOAddressList : OMI_BaseResource
{
    [Key, Description("The Identity parameter specifies the client access rule that you want to modify.")] String Identity;
    [Required, Description("The Action parameter specifies the action for the client access rule. Valid values for this parameter are AllowAccess and DenyAccess."), ValueMap{"AllowAccess","DenyAccess"}, Values{"AllowAccess","DenyAccess"}] String Action;
    [Write, Description("The AnyOfAuthenticationTypes parameter specifies a condition for the client access rule that is based on the client's authentication type. Valid values for this parameter are AdfsAuthentication, BasicAuthentication, CertificateBasedAuthentication, NonBasicAuthentication, OAuthAuthentication."), ValueMap{"AdfsAuthentication","BasicAuthentication","CertificateBasedAuthentication","NonBasicAuthentication","OAuthAuthentication"}, Values{"AdfsAuthentication","BasicAuthentication","CertificateBasedAuthentication","NonBasicAuthentication","OAuthAuthentication"}] String AnyOfAuthenticationTypes[];
    [Write, Description("The AnyOfClientIPAddressesOrRanges parameter specifies a condition for the client access rule that is based on the client's IP address. Valid values for this parameter are: A single IP address, an IP address range, a CIDR IP.")] String AnyOfClientIPAddressesOrRanges[];
    [Write, Description("Specifies if this Client Access Rule should exist."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Required, Description("Credentials of the Exchange Global Admin"), EmbeddedInstance("MSFT_Credential")] String GlobalAdminAccount;
};
