[ClassVersion("1.0.0.0"), FriendlyName("SCComplianceSearchAction")]
class MSFT_SCComplianceSearchAction : OMI_BaseResource
{
    [Key, Description("The Action parameter specifies what type of action to define. Accepted values are Export, Retention and Purge."), ValueMap{"Export","Preview","Purge","Retention"}, Values{"Export","Preview","Purge","Retention"}] String Action;
    [Key, Description("The SearchName parameter specifies the name of the existing content search to associate with the content search action. You can specify multiple content searches separated by commas.")] String SearchName;
    [Write, Description("The FileTypeExclusionsForUnindexedItems specifies the file types to exclude because they can't be indexed. You can specify multiple values separated by commas.")] String FileTypeExclusionsForUnindexedItems[];
    [Write, Description("The EnableDedupe parameter eliminates duplication of messages when you export content search results.")] Boolean EnableDedupe;
    [Write, Description("The IncludeCredential switch specifies whether to include the credential in the results.")] Boolean IncludeCredential;
    [Write, Description("The IncludeSharePointDocumentVersions parameter specifies whether to export previous versions of the document when you use the Export switch.")] Boolean IncludeSharePointDocumentVersions;
    [Write, Description("The PurgeType parameter specifies how to remove items when the action is Purge."), ValueMap{"SoftDelete","HardDelete"}, Values{"SoftDelete","HardDelete"}] String PurgeType;
    [Write, Description("The RetryOnError switch specifies whether to retry the action on any items that failed without re-running the entire action all over again.")] Boolean RetryOnError;
    [Write, Description("The ActionScope parameter specifies the items to include when the action is Export."), ValueMap{"IndexedItemsOnly", "UnindexedItemsOnly", "BothIndexedAndUnindexedItems"}, Values{"IndexedItemsOnly", "UnindexedItemsOnly", "BothIndexedAndUnindexedItems"}] String ActionScope;
    [Write, Description("Specify if this action should exist or not."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Required, Description("Credentials of the Exchange Global Admin"), EmbeddedInstance("MSFT_Credential")] String GlobalAdminAccount;
};
