[ClassVersion("1.0.0.0"), FriendlyName("SCDLPSensitiveInformationTypeRulePackage")]
class MSFT_SCDLPSensitiveInformationTypeRulePackage : OMI_BaseResource
{
    [Key, Description("The Name parameter specifies a name for the sensitive information type rule package. The value must be less than 256 characters.")] String Name;
    [Write, Description("Unique identifier of the Sensitive Information Type Rule Package.")] String Identity;
    [Write, Description("The XML file data for the Sensitive Information Type Rule Package.")] String XmlFileData;
    [Write, Description("Present ensures the instance exists, absent ensures it is removed."), ValueMap{"Absent","Present"}, Values{"Absent","Present"}] string Ensure;
    [Write, Description("Credentials of the workload's Admin"), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Id of the Azure Active Directory tenant used for authentication.")] String TenantId;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Managed ID being used for authentication.")] Boolean ManagedIdentity;
    [Write, Description("Access token used for authentication.")] String AccessTokens[];
};
