[ClassVersion("1.0.0.0"), FriendlyName("IntuneDeviceManagementEnrollmentAndroidGooglePlay")]
class MSFT_IntuneDeviceManagementEnrollmentAndroidGooglePlay : OMI_BaseResource
{
    [Key, Description("Primary key identifier of the Android Managed Store Account Enterprise Setting.")] String Id;
    [Write, Description("Binding status of the Android Managed Store Account Enterprise Setting (e.g., 'bound', 'notBound').")] String BindStatus;
    [Write, Description("The user principal name of the owner of the Android Managed Store Account.")] String OwnerUserPrincipalName;
    [Write, Description("The organization name of the owner of the Android Managed Store Account.")] String OwnerOrganizationName;
    [Write, Description("Specifies the enrollment target for the account enterprise setting (e.g., 'defaultEnrollmentRestrictions', 'targetedAsEnrollmentRestrictions').")] String EnrollmentTarget;
    [Write, Description("Specifies whether device owner management is enabled.")] Boolean DeviceOwnerManagementEnabled;
    [Write, Description("Specifies whether fully managed enrollment is enabled for Android devices.")] Boolean AndroidDeviceOwnerFullyManagedEnrollmentEnabled;
    [Write, Description("Present ensures the instance exists, absent ensures it is removed."), ValueMap{"Absent","Present"}, Values{"Absent","Present"}] String Ensure;
    [Write, Description("Credentials of the workload's Admin."), EmbeddedInstance("MSFT_Credential")] String Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Id of the Azure Active Directory tenant used for authentication.")] String TenantId;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Credential for the application secret used in authentication."), EmbeddedInstance("MSFT_Credential")] String ApplicationSecret;
    [Write, Description("Indicates whether a Managed Identity is used for authentication.")] Boolean ManagedIdentity;
    [Write, Description("Access tokens used for authentication in scenarios requiring multiple tokens.")] String AccessTokens[];
};
