[ClassVersion("1.0.0.0"), FriendlyName("TeamsTemplatesPolicy")]
class MSFT_TeamsTemplatesPolicy : OMI_BaseResource
{
    [Key, Description("Identity of the Teams Templates Policy.")] String Identity;
    [Write, Description("Description of the Teams Templates Policy.")] String Description;
    [Write, Description("The list of Teams templates to hide.")] String HiddenTemplates[];
    [Write, Description("Present ensures the policy exists, absent ensures it is removed."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Write, Description("Credentials of the Teams Admin."), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Name of the Azure Active Directory tenant used for authentication. Format contoso.onmicrosoft.com")] String TenantId;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Managed ID being used for authentication.")] Boolean ManagedIdentity;
};
