[ClassVersion("1.0.0.0"), FriendlyName("EXOAcceptedDomain")]
class MSFT_EXOAcceptedDomain : OMI_BaseResource
{
    [Key, Description("Specify the Fully Qualified Domain Name for the AcceptedDomain.")] String Identity;
    [Write, Description("Specify if the AcceptedDomain should exist or not."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Write, Description("The type of AcceptedDomain.  Currently the EXOAcceptedDomain DSC Resource accepts a value of 'Authoritative' and 'InternalRelay'."), ValueMap{"Authoritative","InternalRelay"}, Values{"Authoritative","InternalRelay"}] String DomainType;
    [Write, Description("The MatchSubDomains parameter must be false on Authoritative domains. The default value is false.")] Boolean MatchSubDomains;
    [Write, Description("The OutboundOnly must be false on Authoritative domains. The default value is false.")] Boolean OutboundOnly;
    [Required, Description("Credentials of the Exchange Global Admin"), EmbeddedInstance("MSFT_Credential")] string GlobalAdminAccount;
};

