[ClassVersion("1.0.0.0"), FriendlyName("IntuneDeviceComplianceScriptWindows10")]
class MSFT_IntuneDeviceComplianceScriptWindows10 : OMI_BaseResource
{
    [Write, Description("Optional description for the device compliance script.")] String Description;
    [Key, Description("Name of the device compliance script.")] String DisplayName;
    [Write, Description("Indicate whether the script signature needs be checked.")] Boolean EnforceSignatureCheck;
    [Write, Description("Publisher of the script.")] String Publisher;
    [Write, Description("List of Scope Tag IDs for this PowerShellScript instance.")] String RoleScopeTagIds[];
    [Write, Description("A value indicating whether the PowerShell script should run as 32-bit")] Boolean RunAs32Bit;
    [Write, Description("Indicates the type of execution context. Possible values are: system, user."), ValueMap{"system","user"}, Values{"system","user"}] String RunAsAccount;
    [Write, Description("The script content in Base64.")] String DetectionScriptContent;
    [Write, Description("The unique identifier for an entity. Read-only.")] String Id;
    [Write, Description("Present ensures the policy exists, absent ensures it is removed."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] string Ensure;
    [Write, Description("Credentials of the Admin"), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Id of the Azure Active Directory tenant used for authentication.")] String TenantId;
    [Write, Description("Secret of the Azure Active Directory tenant used for authentication."), EmbeddedInstance("MSFT_Credential")] String ApplicationSecret;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Managed ID being used for authentication.")] Boolean ManagedIdentity;
    [Write, Description("Access token used for authentication.")] String AccessTokens[];
};
