[ClassVersion("1.0.0.0"), FriendlyName("EXORetentionPolicyTag")]
class MSFT_EXORetentionPolicyTag : OMI_BaseResource
{
    [Key, Description("The Identity parameter specifies the name of the tag.")] String Identity;
    [Write, Description("The Description parameter specifies a comment for the tag.")] String Comment;
    [Write, Description("The AgeLimitForRetention parameter specifies the age at which retention is enforced on an item. The age limit corresponds to the number of days from the date the item was delivered, or the date an item was created if it wasn't delivered. If this parameter isn't present and the RetentionEnabled parameter is set to $true, an error is returned.")] String AgeLimitForRetention;
    [Write, Description("The MessageClass parameter specifies the message type to which the tag applies. If not specified, the default value is set to *.")] String MessageClass;
    [Write, Description("The MustDisplayCommentEnabled parameter specifies whether the comment can be hidden. The default value is $true.")] Boolean MustDisplayCommentEnabled;
    [Write, Description("The RetentionAction parameter specifies the action for the retention policy.")] String RetentionAction;
    [Write, Description("The RetentionEnabled parameter specifies whether the tag is enabled. When set to $false, the tag is disabled, and no retention action is taken on messages that have the tag applied.")] Boolean RetentionEnabled;
    [Write, Description("The Type parameter specifies the type of retention tag being created.")] String Type;
    [Write, Description("Present ensures the instance exists, absent ensures it is removed."), ValueMap{"Absent","Present"}, Values{"Absent","Present"}] string Ensure;
    [Write, Description("Credentials of the workload's Admin"), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Id of the Azure Active Directory tenant used for authentication.")] String TenantId;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Managed ID being used for authentication.")] Boolean ManagedIdentity;
    [Write, Description("Access token used for authentication.")] String AccessTokens[];
};
