[ClassVersion("1.0.0.0"), FriendlyName("EXOCASMailboxPlan")]
class MSFT_EXOCASMailboxPlan : OMI_BaseResource
{
    [Key, Description("The Identity parameter specifies the CAS Mailbox Plan that you want to modify.")] String Identity;
    [Write, Description("CASMailboxPlans cannot be created/removed in O365.  This must be set to 'Present'"), ValueMap{"Present"}, Values{"Present"}] String Ensure;
    [Write, Description("The ActiveSyncEnabled parameter enables or disables access to the mailbox by using Exchange Active Sync. Default is $true.")] Boolean ActiveSyncEnabled;
    [Write, Description("The ImapEnabled parameter enables or disables access to the mailbox by using IMAP4 clients. The default value is $true for all CAS mailbox plans except ExchangeOnlineDeskless which is $false by default.")] Boolean ImapEnabled;
    [Write, Description("The OwaMailboxPolicy parameter specifies the Outlook on the web (formerly known as Outlook Web App) mailbox policy for the mailbox plan. The default value is OwaMailboxPolicy-Default. You can use the Get-OwaMailboxPolicy cmdlet to view the available Outlook on the web mailbox policies.")] String OwaMailboxPolicy;
    [Write, Description("The PopEnabled parameter enables or disables access to the mailbox by using POP3 clients. Default is $true.")] Boolean PopEnabled;
    [Required, Description("Credentials of the Exchange Global Admin"), EmbeddedInstance("MSFT_Credential")] String GlobalAdminAccount;
};
