[ClassVersion("1.0.0.0"), FriendlyName("TeamsFunSettings")]
class MSFT_TeamsFunSettings : OMI_BaseResource
{
    [Key, Description("The Name of the team")] string TeamName;
    [Write, Description("Allow giphy in team ")] string AllowGiphy;
    [Write, Description("Giphy content rating"),ValueMap{"Strict","Moderate"}, Values{"Strict","Moderate"}] string GiphyContentRating;
    [Write, Description("Allow stickers and mimes")] string AllowStickersAndMemes;
    [Write, Description("Allow custom memes")] string AllowCustomMemes;
    [Write, Description("Placeholder only not used in resource."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Required, Description("Credentials of the SharePoint Global Admin"), EmbeddedInstance("MSFT_Credential")] string GlobalAdminAccount;
};

