[ClassVersion("1.0.0.0"), FriendlyName("TeamsFunSettings")]
class MSFT_TeamsFunSettings : OMI_BaseResource
{
    [Key, Description("The group id of the team")] string GroupID;
    [Write, Description("Allow gilphy in team ")] string AllowGiphy;
    [Write, Description("Gilphy content rating"),ValueMap{"Strict","Moderate"}, Values{"Strict","Moderate"}] string GiphyContentRating;
    [Write, Description("Allow stickers and mimes")] string AllowStickersAndMemes;
    [Write, Description("Allow custom memes")] string AllowCustomMemes;
    [Required, Description("Credentials of the SharePoint Global Admin"), EmbeddedInstance("MSFT_Credential")] string GlobalAdminAccount;
};

