#
# Module manifest for module 'M365DSCGraphShim'
#
# Generated by: Team Microsoft365DSC
#
# Generated on: 01.05.2026
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'M365DSCGraphShim.psm1'

# Version number of this module.
ModuleVersion = '0.1.0'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = '730f252e-c4a5-4290-b1da-5d410df44e2d'

# Author of this module
Author = 'Team Microsoft365DSC'

# Company or vendor of this module
CompanyName = 'Unknown'

# Copyright statement for this module
Copyright = '(c) Team Microsoft365DSC. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Auto-generated Graph SDK shim module for Microsoft365DSC. Replaces typed Graph SDK cmdlets with Invoke-MgGraphRequest wrappers.'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @('Microsoft.Graph.Authentication')

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = 'Add-MgBetaGroupToLifecyclePolicy', 'Get-MgAdminSharepointSetting',
               'Get-MgApplication', 'Get-MgBetaAgreement', 'Get-MgBetaApplication',
               'Get-MgBetaDeviceAppManagementAndroidManagedAppProtection',
               'Get-MgBetaDeviceAppManagementAndroidManagedAppProtectionApp',
               'Get-MgBetaDeviceAppManagementAndroidManagedAppProtectionAssignment',
               'Get-MgBetaDeviceAppManagementiOSManagedAppProtection',
               'Get-MgBetaDeviceAppManagementiOSManagedAppProtectionApp',
               'Get-MgBetaDeviceAppManagementiOSManagedAppProtectionAssignment',
               'Get-MgBetaDeviceAppManagementManagedAppPolicy',
               'Get-MgBetaDeviceAppManagementManagedAppStatus',
               'Get-MgBetaDeviceAppManagementMdmWindowsInformationProtectionPolicy',
               'Get-MgBetaDeviceAppManagementMobileApp',
               'Get-MgBetaDeviceAppManagementMobileAppAssignment',
               'Get-MgBetaDeviceAppManagementMobileAppCategory',
               'Get-MgBetaDeviceAppManagementMobileAppConfiguration',
               'Get-MgBetaDeviceAppManagementMobileAppConfigurationAssignment',
               'Get-MgBetaDeviceAppManagementPolicySet',
               'Get-MgBetaDeviceAppManagementTargetedManagedAppConfiguration',
               'Get-MgBetaDeviceAppManagementTargetedManagedAppConfigurationApp',
               'Get-MgBetaDeviceAppManagementTargetedManagedAppConfigurationAssignment',
               'Get-MgBetaDeviceAppManagementWindowsManagedAppProtection',
               'Get-MgBetaDeviceAppManagementWindowsManagedAppProtectionApp',
               'Get-MgBetaDeviceAppManagementWindowsManagedAppProtectionAssignment',
               'Get-MgBetaDeviceManagementAndroidDeviceOwnerEnrollmentProfile',
               'Get-MgBetaDeviceManagementAndroidManagedStoreAccountEnterpriseSetting',
               'Get-MgBetaDeviceManagementApplePushNotificationCertificate',
               'Get-MgBetaDeviceManagementAssignmentFilter',
               'Get-MgBetaDeviceManagementConfigurationPolicy',
               'Get-MgBetaDeviceManagementConfigurationPolicyAssignment',
               'Get-MgBetaDeviceManagementConfigurationPolicySetting',
               'Get-MgBetaDeviceManagementConfigurationPolicyTemplateSettingTemplate',
               'Get-MgBetaDeviceManagementDataSharingConsent',
               'Get-MgBetaDeviceManagementDerivedCredential',
               'Get-MgBetaDeviceManagementDeviceCategory',
               'Get-MgBetaDeviceManagementDeviceCompliancePolicy',
               'Get-MgBetaDeviceManagementDeviceCompliancePolicyAssignment',
               'Get-MgBetaDeviceManagementDeviceConfiguration',
               'Get-MgBetaDeviceManagementDeviceConfigurationAssignment',
               'Get-MgBetaDeviceManagementDeviceEnrollmentConfiguration',
               'Get-MgBetaDeviceManagementDeviceEnrollmentConfigurationAssignment',
               'Get-MgBetaDeviceManagementDeviceHealthScript',
               'Get-MgBetaDeviceManagementDeviceHealthScriptAssignment',
               'Get-MgBetaDeviceManagementDeviceShellScript',
               'Get-MgBetaDeviceManagementGroupPolicyConfiguration',
               'Get-MgBetaDeviceManagementGroupPolicyConfigurationAssignment',
               'Get-MgBetaDeviceManagementGroupPolicyConfigurationDefinitionValue',
               'Get-MgBetaDeviceManagementGroupPolicyConfigurationDefinitionValueDefinition',
               'Get-MgBetaDeviceManagementGroupPolicyConfigurationDefinitionValuePresentationValue',
               'Get-MgBetaDeviceManagementIntent',
               'Get-MgBetaDeviceManagementIntentAssignment',
               'Get-MgBetaDeviceManagementIntentSetting',
               'Get-MgBetaDeviceManagementIntuneBrandingProfile',
               'Get-MgBetaDeviceManagementIntuneBrandingProfileAssignment',
               'Get-MgBetaDeviceManagementManagedDeviceCleanupRule',
               'Get-MgBetaDeviceManagementMobileThreatDefenseConnector',
               'Get-MgBetaDeviceManagementMonitoringAlertRule',
               'Get-MgBetaDeviceManagementNotificationMessageTemplate',
               'Get-MgBetaDeviceManagementRoleAssignment',
               'Get-MgBetaDeviceManagementRoleDefinition',
               'Get-MgBetaDeviceManagementRoleScopeTag',
               'Get-MgBetaDeviceManagementRoleScopeTagAssignment',
               'Get-MgBetaDeviceManagementScript',
               'Get-MgBetaDeviceManagementScriptAssignment',
               'Get-MgBetaDeviceManagementTemplateCategory',
               'Get-MgBetaDeviceManagementTemplateCategoryRecommendedSetting',
               'Get-MgBetaDeviceManagementTermAndCondition',
               'Get-MgBetaDeviceManagementTermAndConditionAssignment',
               'Get-MgBetaDeviceManagementVirtualEndpointOnPremiseConnection',
               'Get-MgBetaDeviceManagementVirtualEndpointProvisioningPolicy',
               'Get-MgBetaDeviceManagementVirtualEndpointUserSetting',
               'Get-MgBetaDeviceManagementWindowsAutopilotDeploymentProfile',
               'Get-MgBetaDeviceManagementWindowsAutopilotDeploymentProfileAssignment',
               'Get-MgBetaDeviceManagementWindowsFeatureUpdateProfile',
               'Get-MgBetaDeviceManagementWindowsFeatureUpdateProfileAssignment',
               'Get-MgBetaDeviceManagementWindowsQualityUpdateProfile',
               'Get-MgBetaDeviceManagementWindowsQualityUpdateProfileAssignment',
               'Get-MgBetaDirectoryAttributeSet',
               'Get-MgBetaDirectoryCertificateAuthorityCertificateBasedApplicationConfiguration',
               'Get-MgBetaDirectoryCertificateAuthorityCertificateBasedApplicationConfigurationTrustedCertificateAuthority',
               'Get-MgBetaDirectoryCustomSecurityAttributeDefinition',
               'Get-MgBetaDirectoryDeletedItemAsApplication',
               'Get-MgBetaDirectoryObject', 'Get-MgBetaDirectoryObjectById',
               'Get-MgBetaDirectorySetting', 'Get-MgBetaDirectorySettingTemplate',
               'Get-MgBetaDomain', 'Get-MgBetaDomainFederationConfiguration',
               'Get-MgBetaEntitlementManagementAccessPackage',
               'Get-MgBetaEntitlementManagementAccessPackageAssignmentPolicy',
               'Get-MgBetaEntitlementManagementAccessPackageCatalog',
               'Get-MgBetaEntitlementManagementAccessPackageCatalogAccessPackageResource',
               'Get-MgBetaEntitlementManagementAccessPackageCatalogAccessPackageResourceRole',
               'Get-MgBetaEntitlementManagementAccessPackageIncompatibleAccessPackage',
               'Get-MgBetaEntitlementManagementAccessPackageIncompatibleGroup',
               'Get-MgBetaEntitlementManagementAccessPackageIncompatibleWith',
               'Get-MgBetaEntitlementManagementConnectedOrganization',
               'Get-MgBetaEntitlementManagementConnectedOrganizationExternalSponsor',
               'Get-MgBetaEntitlementManagementConnectedOrganizationInternalSponsor',
               'Get-MgBetaEntitlementManagementSetting',
               'Get-MgBetaExternalConnection', 'Get-MgBetaGroup',
               'Get-MgBetaGroupLifecyclePolicy', 'Get-MgBetaGroupMember',
               'Get-MgBetaIdentityApiConnector', 'Get-MgBetaIdentityB2XUserFlow',
               'Get-MgBetaIdentityB2XUserFlowApiConnectorConfiguration',
               'Get-MgBetaIdentityB2XUserFlowIdentityProvider',
               'Get-MgBetaIdentityB2XUserFlowUserAttributeAssignment',
               'Get-MgBetaIdentityConditionalAccessAuthenticationContextClassReference',
               'Get-MgBetaIdentityConditionalAccessNamedLocation',
               'Get-MgBetaIdentityConditionalAccessPolicy',
               'Get-MgBetaIdentityCustomAuthenticationExtension',
               'Get-MgBetaIdentityGovernanceAccessReviewDefinition',
               'Get-MgBetaIdentityGovernanceLifecycleWorkflow',
               'Get-MgBetaIdentityGovernanceLifecycleWorkflowCustomTaskExtension',
               'Get-MgBetaIdentityGovernanceLifecycleWorkflowSetting',
               'Get-MgBetaIdentityGovernanceLifecycleWorkflowTask',
               'Get-MgBetaIdentityGovernancePrivilegedAccessGroupEligibilitySchedule',
               'Get-MgBetaIdentityProvider', 'Get-MgBetaIdentityUserFlowAttribute',
               'Get-MgBetaNetworkAccessConnectivityRemoteNetwork',
               'Get-MgBetaNetworkAccessFilteringPolicy',
               'Get-MgBetaNetworkAccessFilteringPolicyRule',
               'Get-MgBetaNetworkAccessFilteringProfile',
               'Get-MgBetaNetworkAccessFilteringProfilePolicy',
               'Get-MgBetaNetworkAccessForwardingPolicy',
               'Get-MgBetaNetworkAccessForwardingProfile',
               'Get-MgBetaNetworkAccessForwardingProfilePolicy',
               'Get-MgBetaNetworkAccessSettingConditionalAccess',
               'Get-MgBetaNetworkAccessSettingCrossTenantAccess',
               'Get-MgBetaOnPremisePublishingProfileConnectorGroup',
               'Get-MgBetaOrganization',
               'Get-MgBetaOrganizationCertificateBasedAuthConfiguration',
               'Get-MgBetaOrganizationSettingItemInsight',
               'Get-MgBetaOrganizationSettingPersonInsight',
               'Get-MgBetaPolicyAccessReviewPolicy',
               'Get-MgBetaPolicyActivityBasedTimeoutPolicy',
               'Get-MgBetaPolicyAdminConsentRequestPolicy',
               'Get-MgBetaPolicyAppManagementPolicy',
               'Get-MgBetaPolicyAuthenticationFlowPolicy',
               'Get-MgBetaPolicyAuthenticationMethodPolicy',
               'Get-MgBetaPolicyAuthenticationMethodPolicyAuthenticationMethodConfiguration',
               'Get-MgBetaPolicyAuthenticationStrengthPolicy',
               'Get-MgBetaPolicyAuthorizationPolicy',
               'Get-MgBetaPolicyB2BManagementPolicy',
               'Get-MgBetaPolicyB2CAuthenticationMethodPolicy',
               'Get-MgBetaPolicyClaimMappingPolicy',
               'Get-MgBetaPolicyCrossTenantAccessPolicy',
               'Get-MgBetaPolicyCrossTenantAccessPolicyDefault',
               'Get-MgBetaPolicyCrossTenantAccessPolicyPartner',
               'Get-MgBetaPolicyCrossTenantAccessPolicyPartnerIdentitySynchronization',
               'Get-MgBetaPolicyCrossTenantAccessPolicyTemplateMultiTenantOrganizationIdentitySynchronization',
               'Get-MgBetaPolicyDefaultAppManagementPolicy',
               'Get-MgBetaPolicyDeviceRegistrationPolicy',
               'Get-MgBetaPolicyExternalIdentityPolicy',
               'Get-MgBetaPolicyFeatureRolloutPolicy',
               'Get-MgBetaPolicyHomeRealmDiscoveryPolicy',
               'Get-MgBetaPolicyIdentitySecurityDefaultEnforcementPolicy',
               'Get-MgBetaPolicyMobileAppManagementPolicy',
               'Get-MgBetaPolicyMobileDeviceManagementPolicy',
               'Get-MgBetaPolicyPermissionGrantPolicy',
               'Get-MgBetaPolicyRoleManagementPolicy',
               'Get-MgBetaPolicyRoleManagementPolicyAssignment',
               'Get-MgBetaPolicyRoleManagementPolicyRule',
               'Get-MgBetaPolicyTokenIssuancePolicy',
               'Get-MgBetaPolicyTokenLifetimePolicy', 'Get-MgBetaProgram',
               'Get-MgBetaRoleManagementCloudPcRoleAssignment',
               'Get-MgBetaRoleManagementCloudPcRoleDefinition',
               'Get-MgBetaRoleManagementDirectoryRoleAssignment',
               'Get-MgBetaRoleManagementDirectoryRoleAssignmentSchedule',
               'Get-MgBetaRoleManagementDirectoryRoleDefinition',
               'Get-MgBetaRoleManagementDirectoryRoleEligibilitySchedule',
               'Get-MgBetaRoleManagementEntitlementManagementRoleAssignment',
               'Get-MgBetaRoleManagementEntitlementManagementRoleDefinition',
               'Get-MgBetaSubscribedSku', 'Get-MgBetaTeam', 'Get-MgBetaTeamChannel',
               'Get-MgBetaTeamChannelTab', 'Get-MgDevice',
               'Get-MgDeviceManagementRoleDefinition',
               'Get-MgDeviceManagementRoleDefinitionRoleAssignment',
               'Get-MgDirectoryAdministrativeUnit',
               'Get-MgDirectoryAdministrativeUnitMember',
               'Get-MgDirectoryAdministrativeUnitScopedRoleMember',
               'Get-MgDirectoryRole', 'Get-MgDirectoryRoleTemplate', 'Get-MgGroup',
               'Get-MgGroupLifecyclePolicy', 'Get-MgGroupMember', 'Get-MgGroupOwner',
               'Get-MgGroupPlannerPlan', 'Get-MgGroupPlannerPlanTask',
               'Get-MgPlannerPlanBucket', 'Get-MgPlannerPlanDetail',
               'Get-MgPlannerTask', 'Get-MgPlannerTaskDetail',
               'Get-MgPolicyRoleManagementPolicyAssignment',
               'Get-MgServicePrincipal', 'Get-MgServicePrincipalAppRoleAssignedTo',
               'Get-MgUser', 'Invoke-MgBetaForceDomainDelete',
               'Invoke-MgBetaInstantiateApplicationTemplate',
               'Invoke-MgBetaUploadIdentityApiConnectorClientCertificate',
               'New-MgApplication', 'New-MgApplicationOwnerByRef',
               'New-MgApplicationTokenLifetimePolicyByRef',
               'New-MgBetaDeviceAppManagementAndroidManagedAppProtection',
               'New-MgBetaDeviceAppManagementiOSManagedAppProtection',
               'New-MgBetaDeviceAppManagementMdmWindowsInformationProtectionPolicy',
               'New-MgBetaDeviceAppManagementMobileApp',
               'New-MgBetaDeviceAppManagementMobileAppCategory',
               'New-MgBetaDeviceAppManagementMobileAppConfiguration',
               'New-MgBetaDeviceAppManagementPolicySet',
               'New-MgBetaDeviceAppManagementTargetedManagedAppConfiguration',
               'New-MgBetaDeviceAppManagementWindowsManagedAppProtection',
               'New-MgBetaDeviceManagementAndroidDeviceOwnerEnrollmentProfile',
               'New-MgBetaDeviceManagementAssignmentFilter',
               'New-MgBetaDeviceManagementConfigurationPolicy',
               'New-MgBetaDeviceManagementDerivedCredential',
               'New-MgBetaDeviceManagementDeviceCategory',
               'New-MgBetaDeviceManagementDeviceCompliancePolicy',
               'New-MgBetaDeviceManagementDeviceConfiguration',
               'New-MgBetaDeviceManagementDeviceConfigurationAssignment',
               'New-MgBetaDeviceManagementDeviceEnrollmentConfiguration',
               'New-MgBetaDeviceManagementDeviceHealthScript',
               'New-MgBetaDeviceManagementDeviceShellScript',
               'New-MgBetaDeviceManagementGroupPolicyConfiguration',
               'New-MgBetaDeviceManagementIntent',
               'New-MgBetaDeviceManagementIntuneBrandingProfile',
               'New-MgBetaDeviceManagementManagedDeviceCleanupRule',
               'New-MgBetaDeviceManagementMobileThreatDefenseConnector',
               'New-MgBetaDeviceManagementMonitoringAlertRule',
               'New-MgBetaDeviceManagementNotificationMessageTemplate',
               'New-MgBetaDeviceManagementNotificationMessageTemplateLocalizedNotificationMessage',
               'New-MgBetaDeviceManagementRoleAssignment',
               'New-MgBetaDeviceManagementRoleDefinition',
               'New-MgBetaDeviceManagementRoleScopeTag',
               'New-MgBetaDeviceManagementScript',
               'New-MgBetaDeviceManagementTermAndCondition',
               'New-MgBetaDeviceManagementTermAndConditionAssignment',
               'New-MgBetaDeviceManagementVirtualEndpointOnPremiseConnection',
               'New-MgBetaDeviceManagementVirtualEndpointProvisioningPolicy',
               'New-MgBetaDeviceManagementVirtualEndpointUserSetting',
               'New-MgBetaDeviceManagementWindowsAutopilotDeploymentProfile',
               'New-MgBetaDeviceManagementWindowsAutopilotDeploymentProfileAssignment',
               'New-MgBetaDeviceManagementWindowsFeatureUpdateProfile',
               'New-MgBetaDeviceManagementWindowsQualityUpdateProfile',
               'New-MgBetaDirectoryAttributeSet',
               'New-MgBetaDirectoryCertificateAuthorityCertificateBasedApplicationConfigurationTrustedCertificateAuthority',
               'New-MgBetaDirectoryCustomSecurityAttributeDefinition',
               'New-MgBetaDirectoryCustomSecurityAttributeDefinitionAllowedValue',
               'New-MgBetaDirectorySetting', 'New-MgBetaDomain',
               'New-MgBetaDomainFederationConfiguration',
               'New-MgBetaEntitlementManagementAccessPackage',
               'New-MgBetaEntitlementManagementAccessPackageAssignmentPolicy',
               'New-MgBetaEntitlementManagementAccessPackageCatalog',
               'New-MgBetaEntitlementManagementAccessPackageIncompatibleAccessPackageByRef',
               'New-MgBetaEntitlementManagementAccessPackageIncompatibleGroupByRef',
               'New-MgBetaEntitlementManagementAccessPackageResourceRequest',
               'New-MgBetaEntitlementManagementAccessPackageResourceRoleScope',
               'New-MgBetaEntitlementManagementConnectedOrganization',
               'New-MgBetaEntitlementManagementConnectedOrganizationExternalSponsorByRef',
               'New-MgBetaEntitlementManagementConnectedOrganizationInternalSponsorByRef',
               'New-MgBetaExternalConnection', 'New-MgBetaGroupMemberByRef',
               'New-MgBetaIdentityApiConnector', 'New-MgBetaIdentityB2XUserFlow',
               'New-MgBetaIdentityB2XUserFlowIdentityProviderByRef',
               'New-MgBetaIdentityB2XUserFlowUserAttributeAssignment',
               'New-MgBetaIdentityConditionalAccessAuthenticationContextClassReference',
               'New-MgBetaIdentityCustomAuthenticationExtension',
               'New-MgBetaIdentityGovernanceAccessReviewDefinition',
               'New-MgBetaIdentityGovernanceLifecycleWorkflow',
               'New-MgBetaIdentityGovernanceLifecycleWorkflowCustomTaskExtension',
               'New-MgBetaIdentityGovernanceLifecycleWorkflowNewVersion',
               'New-MgBetaIdentityGovernancePrivilegedAccessGroupEligibilityScheduleRequest',
               'New-MgBetaIdentityProvider', 'New-MgBetaIdentityUserFlowAttribute',
               'New-MgBetaNetworkAccessConnectivityRemoteNetwork',
               'New-MgBetaNetworkAccessConnectivityRemoteNetworkDeviceLink',
               'New-MgBetaNetworkAccessFilteringPolicy',
               'New-MgBetaNetworkAccessFilteringPolicyRule',
               'New-MgBetaNetworkAccessFilteringProfile',
               'New-MgBetaNetworkAccessForwardingPolicyRule',
               'New-MgBetaOnPremisePublishingProfileConnectorGroup',
               'New-MgBetaPolicyActivityBasedTimeoutPolicy',
               'New-MgBetaPolicyAppManagementPolicy',
               'New-MgBetaPolicyAuthenticationMethodPolicyAuthenticationMethodConfiguration',
               'New-MgBetaPolicyAuthenticationStrengthPolicy',
               'New-MgBetaPolicyB2BManagementPolicy',
               'New-MgBetaPolicyClaimMappingPolicy',
               'New-MgBetaPolicyCrossTenantAccessPolicyPartner',
               'New-MgBetaPolicyFeatureRolloutPolicy',
               'New-MgBetaPolicyFeatureRolloutPolicyApplyToByRef',
               'New-MgBetaPolicyHomeRealmDiscoveryPolicy',
               'New-MgBetaPolicyPermissionGrantPolicy',
               'New-MgBetaPolicyPermissionGrantPolicyExclude',
               'New-MgBetaPolicyPermissionGrantPolicyInclude',
               'New-MgBetaPolicyTokenIssuancePolicy',
               'New-MgBetaPolicyTokenLifetimePolicy', 'New-MgBetaProgram',
               'New-MgBetaRoleManagementCloudPcRoleAssignment',
               'New-MgBetaRoleManagementCloudPcRoleDefinition',
               'New-MgBetaRoleManagementDirectoryRoleAssignment',
               'New-MgBetaRoleManagementDirectoryRoleAssignmentScheduleRequest',
               'New-MgBetaRoleManagementDirectoryRoleDefinition',
               'New-MgBetaRoleManagementDirectoryRoleEligibilityScheduleRequest',
               'New-MgBetaRoleManagementEntitlementManagementRoleAssignment',
               'New-MgBetaTeamChannelTab', 'New-MgDirectoryAdministrativeUnit',
               'New-MgDirectoryAdministrativeUnitMemberByRef',
               'New-MgDirectoryAdministrativeUnitScopedRoleMember',
               'New-MgDirectoryRole', 'New-MgGroup', 'New-MgGroupLifecyclePolicy',
               'New-MgGroupMemberByRef', 'New-MgGroupOwnerByRef',
               'New-MgPlannerBucket', 'New-MgPlannerPlan', 'New-MgPlannerTask',
               'New-MgServicePrincipal', 'New-MgServicePrincipalAppRoleAssignedTo',
               'New-MgServicePrincipalOwnerByRef', 'New-MgUser',
               'Remove-MgApplication',
               'Remove-MgApplicationOwnerDirectoryObjectByRef',
               'Remove-MgApplicationTokenLifetimePolicyTokenLifetimePolicyByRef',
               'Remove-MgBetaAgreement',
               'Remove-MgBetaDeviceAppManagementAndroidManagedAppProtection',
               'Remove-MgBetaDeviceAppManagementiOSManagedAppProtection',
               'Remove-MgBetaDeviceAppManagementMdmWindowsInformationProtectionPolicy',
               'Remove-MgBetaDeviceAppManagementMobileApp',
               'Remove-MgBetaDeviceAppManagementMobileAppCategory',
               'Remove-MgBetaDeviceAppManagementMobileAppConfiguration',
               'Remove-MgBetaDeviceAppManagementPolicySet',
               'Remove-MgBetaDeviceAppManagementTargetedManagedAppConfiguration',
               'Remove-MgBetaDeviceAppManagementWindowsManagedAppProtection',
               'Remove-MgBetaDeviceManagementAndroidDeviceOwnerEnrollmentProfile',
               'Remove-MgBetaDeviceManagementAssignmentFilter',
               'Remove-MgBetaDeviceManagementConfigurationPolicy',
               'Remove-MgBetaDeviceManagementDerivedCredential',
               'Remove-MgBetaDeviceManagementDeviceCategory',
               'Remove-MgBetaDeviceManagementDeviceCompliancePolicy',
               'Remove-MgBetaDeviceManagementDeviceConfiguration',
               'Remove-MgBetaDeviceManagementDeviceConfigurationAssignment',
               'Remove-MgBetaDeviceManagementDeviceEnrollmentConfiguration',
               'Remove-MgBetaDeviceManagementDeviceHealthScript',
               'Remove-MgBetaDeviceManagementDeviceShellScript',
               'Remove-MgBetaDeviceManagementGroupPolicyConfiguration',
               'Remove-MgBetaDeviceManagementIntent',
               'Remove-MgBetaDeviceManagementIntuneBrandingProfile',
               'Remove-MgBetaDeviceManagementManagedDeviceCleanupRule',
               'Remove-MgBetaDeviceManagementMobileThreatDefenseConnector',
               'Remove-MgBetaDeviceManagementNotificationMessageTemplate',
               'Remove-MgBetaDeviceManagementNotificationMessageTemplateLocalizedNotificationMessage',
               'Remove-MgBetaDeviceManagementRoleAssignment',
               'Remove-MgBetaDeviceManagementRoleDefinition',
               'Remove-MgBetaDeviceManagementRoleScopeTag',
               'Remove-MgBetaDeviceManagementScript',
               'Remove-MgBetaDeviceManagementTermAndCondition',
               'Remove-MgBetaDeviceManagementTermAndConditionAssignment',
               'Remove-MgBetaDeviceManagementVirtualEndpointOnPremiseConnection',
               'Remove-MgBetaDeviceManagementVirtualEndpointProvisioningPolicy',
               'Remove-MgBetaDeviceManagementVirtualEndpointUserSetting',
               'Remove-MgBetaDeviceManagementWindowsAutopilotDeploymentProfile',
               'Remove-MgBetaDeviceManagementWindowsAutopilotDeploymentProfileAssignment',
               'Remove-MgBetaDeviceManagementWindowsFeatureUpdateProfile',
               'Remove-MgBetaDeviceManagementWindowsQualityUpdateProfile',
               'Remove-MgBetaDirectoryCertificateAuthorityCertificateBasedApplicationConfiguration',
               'Remove-MgBetaDirectoryCertificateAuthorityCertificateBasedApplicationConfigurationTrustedCertificateAuthority',
               'Remove-MgBetaDirectorySetting',
               'Remove-MgBetaDomainFederationConfiguration',
               'Remove-MgBetaEntitlementManagementAccessPackage',
               'Remove-MgBetaEntitlementManagementAccessPackageAssignmentPolicy',
               'Remove-MgBetaEntitlementManagementAccessPackageCatalog',
               'Remove-MgBetaEntitlementManagementAccessPackageIncompatibleAccessPackageByRef',
               'Remove-MgBetaEntitlementManagementAccessPackageIncompatibleGroupByRef',
               'Remove-MgBetaEntitlementManagementAccessPackageResourceRoleScope',
               'Remove-MgBetaEntitlementManagementConnectedOrganization',
               'Remove-MgBetaEntitlementManagementConnectedOrganizationExternalSponsorDirectoryObjectByRef',
               'Remove-MgBetaEntitlementManagementConnectedOrganizationInternalSponsorDirectoryObjectByRef',
               'Remove-MgBetaExternalConnection',
               'Remove-MgBetaGroupFromLifecyclePolicy',
               'Remove-MgBetaGroupMemberDirectoryObjectByRef',
               'Remove-MgBetaIdentityApiConnector',
               'Remove-MgBetaIdentityB2XUserFlow',
               'Remove-MgBetaIdentityB2XUserFlowIdentityProviderBaseByRef',
               'Remove-MgBetaIdentityB2XUserFlowUserAttributeAssignment',
               'Remove-MgBetaIdentityConditionalAccessAuthenticationContextClassReference',
               'Remove-MgBetaIdentityConditionalAccessNamedLocation',
               'Remove-MgBetaIdentityConditionalAccessPolicy',
               'Remove-MgBetaIdentityCustomAuthenticationExtension',
               'Remove-MgBetaIdentityGovernanceAccessReviewDefinition',
               'Remove-MgBetaIdentityGovernanceLifecycleWorkflow',
               'Remove-MgBetaIdentityGovernanceLifecycleWorkflowCustomTaskExtension',
               'Remove-MgBetaIdentityProvider',
               'Remove-MgBetaIdentityUserFlowAttribute',
               'Remove-MgBetaNetworkAccessConnectivityRemoteNetwork',
               'Remove-MgBetaNetworkAccessConnectivityRemoteNetworkDeviceLink',
               'Remove-MgBetaNetworkAccessFilteringPolicy',
               'Remove-MgBetaNetworkAccessFilteringPolicyRule',
               'Remove-MgBetaNetworkAccessFilteringProfile',
               'Remove-MgBetaNetworkAccessForwardingPolicyRule',
               'Remove-MgBetaOnPremisePublishingProfileConnectorGroup',
               'Remove-MgBetaPolicyActivityBasedTimeoutPolicy',
               'Remove-MgBetaPolicyAppManagementPolicy',
               'Remove-MgBetaPolicyAuthenticationMethodPolicyAuthenticationMethodConfiguration',
               'Remove-MgBetaPolicyAuthenticationStrengthPolicy',
               'Remove-MgBetaPolicyClaimMappingPolicy',
               'Remove-MgBetaPolicyCrossTenantAccessPolicyPartner',
               'Remove-MgBetaPolicyCrossTenantAccessPolicyPartnerIdentitySynchronization',
               'Remove-MgBetaPolicyFeatureRolloutPolicy',
               'Remove-MgBetaPolicyFeatureRolloutPolicyApplyToDirectoryObjectByRef',
               'Remove-MgBetaPolicyHomeRealmDiscoveryPolicy',
               'Remove-MgBetaPolicyPermissionGrantPolicy',
               'Remove-MgBetaPolicyPermissionGrantPolicyExclude',
               'Remove-MgBetaPolicyPermissionGrantPolicyInclude',
               'Remove-MgBetaPolicyTokenIssuancePolicy',
               'Remove-MgBetaPolicyTokenLifetimePolicy', 'Remove-MgBetaProgram',
               'Remove-MgBetaRoleManagementCloudPcRoleAssignment',
               'Remove-MgBetaRoleManagementCloudPcRoleDefinition',
               'Remove-MgBetaRoleManagementDirectoryRoleAssignment',
               'Remove-MgBetaRoleManagementDirectoryRoleDefinition',
               'Remove-MgBetaRoleManagementEntitlementManagementRoleAssignment',
               'Remove-MgBetaTeamChannelTab',
               'Remove-MgDirectoryAdministrativeUnit',
               'Remove-MgDirectoryAdministrativeUnitMemberDirectoryObjectByRef',
               'Remove-MgDirectoryAdministrativeUnitScopedRoleMember',
               'Remove-MgGroup', 'Remove-MgGroupLifecyclePolicy',
               'Remove-MgGroupMemberDirectoryObjectByRef',
               'Remove-MgGroupOwnerDirectoryObjectByRef', 'Remove-MgPlannerTask',
               'Remove-MgServicePrincipal',
               'Remove-MgServicePrincipalAppRoleAssignedTo',
               'Remove-MgServicePrincipalOwnerDirectoryObjectByRef',
               'Remove-MgUser', 'Restore-MgBetaDirectoryDeletedItem',
               'Set-MgBetaEntitlementManagementAccessPackageAssignmentPolicy',
               'Set-MgBetaIdentityB2XUserFlowPostAttributeCollectionByRef',
               'Set-MgBetaIdentityB2XUserFlowPostFederationSignupByRef',
               'Set-MgBetaIdentityGovernanceAccessReviewDefinition',
               'Set-MgBetaPolicyCrossTenantAccessPolicyPartnerIdentitySynchronization',
               'Set-MgGroupLicense', 'Set-MgUserLicense',
               'Update-MgAdminSharepointSetting', 'Update-MgApplication',
               'Update-MgBetaApplication',
               'Update-MgBetaDeviceAppManagementAndroidManagedAppProtection',
               'Update-MgBetaDeviceAppManagementiOSManagedAppProtection',
               'Update-MgBetaDeviceAppManagementMdmWindowsInformationProtectionPolicy',
               'Update-MgBetaDeviceAppManagementMobileApp',
               'Update-MgBetaDeviceAppManagementMobileAppCategory',
               'Update-MgBetaDeviceAppManagementMobileAppConfiguration',
               'Update-MgBetaDeviceAppManagementPolicySet',
               'Update-MgBetaDeviceAppManagementTargetedManagedAppConfiguration',
               'Update-MgBetaDeviceAppManagementWindowsManagedAppProtection',
               'Update-MgBetaDeviceManagement',
               'Update-MgBetaDeviceManagementApplePushNotificationCertificate',
               'Update-MgBetaDeviceManagementAssignmentFilter',
               'Update-MgBetaDeviceManagementDeviceCategory',
               'Update-MgBetaDeviceManagementDeviceCompliancePolicy',
               'Update-MgBetaDeviceManagementDeviceConfiguration',
               'Update-MgBetaDeviceManagementDeviceEnrollmentConfiguration',
               'Update-MgBetaDeviceManagementDeviceHealthScript',
               'Update-MgBetaDeviceManagementDeviceShellScript',
               'Update-MgBetaDeviceManagementGroupPolicyConfiguration',
               'Update-MgBetaDeviceManagementIntent',
               'Update-MgBetaDeviceManagementIntuneBrandingProfile',
               'Update-MgBetaDeviceManagementManagedDeviceCleanupRule',
               'Update-MgBetaDeviceManagementMobileThreatDefenseConnector',
               'Update-MgBetaDeviceManagementMonitoringAlertRule',
               'Update-MgBetaDeviceManagementNotificationMessageTemplate',
               'Update-MgBetaDeviceManagementNotificationMessageTemplateLocalizedNotificationMessage',
               'Update-MgBetaDeviceManagementRoleAssignment',
               'Update-MgBetaDeviceManagementRoleDefinition',
               'Update-MgBetaDeviceManagementRoleScopeTag',
               'Update-MgBetaDeviceManagementScript',
               'Update-MgBetaDeviceManagementTermAndCondition',
               'Update-MgBetaDeviceManagementVirtualEndpointOnPremiseConnection',
               'Update-MgBetaDeviceManagementVirtualEndpointProvisioningPolicy',
               'Update-MgBetaDeviceManagementVirtualEndpointUserSetting',
               'Update-MgBetaDeviceManagementWindowsAutopilotDeploymentProfile',
               'Update-MgBetaDeviceManagementWindowsFeatureUpdateProfile',
               'Update-MgBetaDeviceManagementWindowsQualityUpdateProfile',
               'Update-MgBetaDirectoryAttributeSet',
               'Update-MgBetaDirectoryCertificateAuthorityCertificateBasedApplicationConfiguration',
               'Update-MgBetaDirectoryCertificateAuthorityCertificateBasedApplicationConfigurationTrustedCertificateAuthority',
               'Update-MgBetaDirectoryCustomSecurityAttributeDefinition',
               'Update-MgBetaDirectoryCustomSecurityAttributeDefinitionAllowedValue',
               'Update-MgBetaDirectorySetting', 'Update-MgBetaDomain',
               'Update-MgBetaDomainFederationConfiguration',
               'Update-MgBetaEntitlementManagementAccessPackage',
               'Update-MgBetaEntitlementManagementAccessPackageCatalog',
               'Update-MgBetaEntitlementManagementConnectedOrganization',
               'Update-MgBetaEntitlementManagementSetting',
               'Update-MgBetaExternalConnection',
               'Update-MgBetaIdentityApiConnector',
               'Update-MgBetaIdentityB2XUserFlowUserAttributeAssignment',
               'Update-MgBetaIdentityConditionalAccessAuthenticationContextClassReference',
               'Update-MgBetaIdentityCustomAuthenticationExtension',
               'Update-MgBetaIdentityGovernanceLifecycleWorkflowCustomTaskExtension',
               'Update-MgBetaIdentityGovernanceLifecycleWorkflowSetting',
               'Update-MgBetaIdentityProvider',
               'Update-MgBetaIdentityUserFlowAttribute',
               'Update-MgBetaNetworkAccessFilteringPolicy',
               'Update-MgBetaNetworkAccessFilteringPolicyRule',
               'Update-MgBetaNetworkAccessForwardingProfile',
               'Update-MgBetaNetworkAccessForwardingProfilePolicy',
               'Update-MgBetaNetworkAccessSettingConditionalAccess',
               'Update-MgBetaNetworkAccessSettingCrossTenantAccess',
               'Update-MgBetaOnPremisePublishingProfileConnectorGroup',
               'Update-MgBetaOrganization',
               'Update-MgBetaOrganizationSettingItemInsight',
               'Update-MgBetaOrganizationSettingPersonInsight',
               'Update-MgBetaPolicyAccessReviewPolicy',
               'Update-MgBetaPolicyActivityBasedTimeoutPolicy',
               'Update-MgBetaPolicyAppManagementPolicy',
               'Update-MgBetaPolicyAuthenticationFlowPolicy',
               'Update-MgBetaPolicyAuthenticationMethodPolicy',
               'Update-MgBetaPolicyAuthenticationMethodPolicyAuthenticationMethodConfiguration',
               'Update-MgBetaPolicyAuthenticationStrengthPolicy',
               'Update-MgBetaPolicyAuthenticationStrengthPolicyAllowedCombination',
               'Update-MgBetaPolicyAuthorizationPolicy',
               'Update-MgBetaPolicyB2BManagementPolicy',
               'Update-MgBetaPolicyB2CAuthenticationMethodPolicy',
               'Update-MgBetaPolicyClaimMappingPolicy',
               'Update-MgBetaPolicyCrossTenantAccessPolicy',
               'Update-MgBetaPolicyCrossTenantAccessPolicyPartner',
               'Update-MgBetaPolicyCrossTenantAccessPolicyTemplateMultiTenantOrganizationIdentitySynchronization',
               'Update-MgBetaPolicyDefaultAppManagementPolicy',
               'Update-MgBetaPolicyExternalIdentityPolicy',
               'Update-MgBetaPolicyFeatureRolloutPolicy',
               'Update-MgBetaPolicyHomeRealmDiscoveryPolicy',
               'Update-MgBetaPolicyIdentitySecurityDefaultEnforcementPolicy',
               'Update-MgBetaPolicyPermissionGrantPolicy',
               'Update-MgBetaPolicyRoleManagementPolicyRule',
               'Update-MgBetaPolicyTokenIssuancePolicy',
               'Update-MgBetaPolicyTokenLifetimePolicy', 'Update-MgBetaProgram',
               'Update-MgBetaRoleManagementCloudPcRoleAssignment',
               'Update-MgBetaRoleManagementCloudPcRoleDefinition',
               'Update-MgBetaRoleManagementDirectoryRoleDefinition',
               'Update-MgBetaTeamChannelTab',
               'Update-MgDirectoryAdministrativeUnit', 'Update-MgGroup',
               'Update-MgGroupLifecyclePolicy', 'Update-MgPlannerPlan',
               'Update-MgServicePrincipal', 'Update-MgUser'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        # Tags = @()

        # A URL to the license for this module.
        # LicenseUri = ''

        # A URL to the main website for this project.
        # ProjectUri = ''

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        # ReleaseNotes = ''

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

