[ClassVersion("1.0.0.0"), FriendlyName("SPOSiteDesignRights")]
class MSFT_SPOSiteDesignRights : OMI_BaseResource
{
    [Key, Description("The title of the site design")] string SiteDesignTitle;
    [Key, Description("Rights to grant user principals on site design rights."), ValueMap{"View","None"}, Values{"View","None"}] string Rights;
    [Write, Description("List of user principals with seperated by commas to site design rights.")] string UserPrincipals[];
    [Write, Description("Used to add or remove list of users from site design rights."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Write, Description("Credentials of the Office365 Tenant Admin."), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Secret of the Azure Active Directory application to authenticate with."), EmbeddedInstance("MSFT_Credential")] String ApplicationSecret;
    [Write, Description("Name of the Azure Active Directory tenant used for authentication. Format contoso.onmicrosoft.com")] String TenantId;
    [Write, Description("Username can be made up to anything but password will be used for certificatePassword"), EmbeddedInstance("MSFT_Credential")] String CertificatePassword;
    [Write, Description("Path to certificate used in service principal usually a PFX file.")] String CertificatePath;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Managed ID being used for authentication.")] Boolean ManagedIdentity;
    [Write, Description("Access token used for authentication.")] String AccessTokens[];
};
