[ClassVersion("1.0.0.0"), FriendlyName("EXOOrganizationRelationship")]
class MSFT_EXOOrganizationRelationship : OMI_BaseResource
{
    [Key, Description("The Name parameter specifies the unique name of the organization relationship. The maximum length is 64 characters.")] String Name;
    [Write, Description("The ArchiveAccessEnabled parameter specifies whether the organization relationship has been configured to provide remote archive access.")] Boolean ArchiveAccessEnabled;
    [Write, Description("The DeliveryReportEnabled parameter specifies whether Delivery Reports should be shared over the organization relationship.")] Boolean DeliveryReportEnabled;
    [Write, Description("The DomainNames parameter specifies the SMTP domains of the external organization. You can specify multiple domains separated by commas.")] String DomainNames[];
    [Write, Description("The Enabled parameter specifies whether to enable the organization relationship.")] Boolean Enabled;
    [Write, Description("The FreeBusyAccessEnabled parameter specifies whether the organization relationship should be used to retrieve free/busy information from the external organization.")] Boolean FreeBusyAccessEnabled;
    [Write, Description("The FreeBusyAccessLevel parameter specifies the maximum amount of detail returned to the requesting organization. Valid values are: None, AvailabilityOnly or LimitedDetails"), ValueMap{"None","AvailabilityOnly","LimitedDetails"}, Values{"None","AvailabilityOnly","LimitedDetails"}] String FreeBusyAccessLevel;
    [Write, Description("The FreeBusyAccessScope parameter specifies a mail-enabled security group in the internal organization that contains users whose free/busy information is accessible by an external organization. You can use any value that uniquely identifies the group.")] String FreeBusyAccessScope;
    [Write, Description("The MailboxMoveEnabled parameter specifies whether the organization relationship enables moving mailboxes to or from the external organization.")] Boolean MailboxMoveEnabled;
    [Write, Description("The MailTipsAccessEnabled parameter specifies whether MailTips for users in this organization are returned over this organization relationship.")] Boolean MailTipsAccessEnabled;
    [Write, Description("The MailTipsAccessLevel parameter specifies the level of MailTips data externally shared over this organization relationship. This parameter can have the following values: All, Limited, None"), ValueMap{"None","All","Limited"}, Values{"None","All","Limited"}] String MailTipsAccessLevel;
    [Write, Description("The MailTipsAccessScope parameter specifies a mail-enabled security group in the internal organization that contains users whose free/busy information is accessible by an external organization. You can use any value that uniquely identifies the group.")] String MailTipsAccessScope;
    [Write, Description("The OrganizationContact parameter specifies the email address that can be used to contact the external organization (for example, administrator@fourthcoffee.com).")] String OrganizationContact;
    [Write, Description("The PhotosEnabled parameter specifies whether photos for users in the internal organization are returned over the organization relationship.")] Boolean PhotosEnabled;
    [Write, Description("The TargetApplicationUri parameter specifies the target Uniform Resource Identifier (URI) of the external organization. The TargetApplicationUri parameter is specified by Exchange when requesting a delegated token to retrieve free and busy information, for example, mail.contoso.com.")] String TargetApplicationUri;
    [Write, Description("The TargetAutodiscoverEpr parameter specifies the Autodiscover URL of Exchange Web Services for the external organization. Exchange uses Autodiscover to automatically detect the correct Exchangeserver endpoint to use for external requests.")] String TargetAutodiscoverEpr;
    [Write, Description("The TargetOwaURL parameter specifies the Outlook on the web (formerly Outlook Web App) URL of the external organization that's defined in the organization relationship. It is used for Outlook on the web redirection in a cross-premise Exchange scenario. Configuring this attribute enables users in the organization to use their current Outlook on the web URL to access Outlook on the web in the external organization.")] String TargetOwaURL;
    [Write, Description("The TargetSharingEpr parameter specifies the URL of the target Exchange Web Services for the external organization.")] String TargetSharingEpr;
    [Write, Description("Specify if the OrganizationRelationship should exist or not."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Required, Description("Credentials of the Exchange Global Admin"), EmbeddedInstance("MSFT_Credential")] string GlobalAdminAccount;
};
