[ClassVersion("1.0.0.0"), FriendlyName("SCInsiderRiskPolicy")]
class MSFT_SCInsiderRiskPolicy : OMI_BaseResource
{
    [Key, Description("Name of the insider risk policy.")] string Name;
    [Write, Description("")] Boolean DLPUserRiskSync;
    [Write, Description("")] Boolean OptInIRMDataExport;
    [Write, Description("")] Boolean RaiseAuditAlert;
    [Write, Description("")] String FileVolCutoffLimits;
    [Write, Description("")] String AlertVolume;
    [Write, Description("")] Boolean AnomalyDetections;
    [Write, Description("")] Boolean CopyToPersonalCloud;
    [Write, Description("")] Boolean CopyToUSB;
    [Write, Description("")] Boolean CumulativeExfiltrationDetector;
    [Write, Description("")] Boolean EmailExternal;
    [Write, Description("")] Boolean EmployeeAccessedEmployeePatientData;
    [Write, Description("")] Boolean EmployeeAccessedFamilyData;
    [Write, Description("")] Boolean EmployeeAccessedHighVolumePatientData;
    [Write, Description("")] Boolean EmployeeAccessedNeighbourData;
    [Write, Description("")] Boolean EmployeeAccessedRestrictedData;
    [Write, Description("")] Boolean EpoBrowseToChildAbuseSites;
    [Write, Description("")] Boolean EpoBrowseToCriminalActivitySites;
    [Write, Description("")] Boolean EpoBrowseToCultSites;
    [Write, Description("")] Boolean EpoBrowseToGamblingSites;
    [Write, Description("")] Boolean EpoBrowseToHackingSites;
    [Write, Description("")] Boolean EpoBrowseToHateIntoleranceSites;
    [Write, Description("")] Boolean EpoBrowseToIllegalSoftwareSites;
    [Write, Description("")] Boolean EpoBrowseToKeyloggerSites;
    [Write, Description("")] Boolean EpoBrowseToLlmSites;
    [Write, Description("")] Boolean EpoBrowseToMalwareSites;
    [Write, Description("")] Boolean EpoBrowseToPhishingSites;
    [Write, Description("")] Boolean EpoBrowseToPornographySites;
    [Write, Description("")] Boolean EpoBrowseToUnallowedDomain;
    [Write, Description("")] Boolean EpoBrowseToViolenceSites;
    [Write, Description("")] Boolean EpoCopyToClipboardFromSensitiveFile;
    [Write, Description("")] Boolean EpoCopyToNetworkShare;
    [Write, Description("")] Boolean EpoFileArchived;
    [Write, Description("")] Boolean EpoFileCopiedToRemoteDesktopSession;
    [Write, Description("")] Boolean EpoFileDeleted;
    [Write, Description("")] Boolean EpoFileDownloadedFromBlacklistedDomain;
    [Write, Description("")] Boolean EpoFileDownloadedFromEnterpriseDomain;
    [Write, Description("")] Boolean EpoFileRenamed;
    [Write, Description("")] Boolean EpoFileStagedToCentralLocation;
    [Write, Description("")] Boolean EpoHiddenFileCreated;
    [Write, Description("")] Boolean EpoRemovableMediaMount;
    [Write, Description("")] Boolean EpoSensitiveFileRead;
    [Write, Description("")] Boolean Mcas3rdPartyAppDownload;
    [Write, Description("")] Boolean Mcas3rdPartyAppFileDelete;
    [Write, Description("")] Boolean Mcas3rdPartyAppFileSharing;
    [Write, Description("")] Boolean McasActivityFromInfrequentCountry;
    [Write, Description("")] Boolean McasImpossibleTravel;
    [Write, Description("")] Boolean McasMultipleFailedLogins;
    [Write, Description("")] Boolean McasMultipleStorageDeletion;
    [Write, Description("")] Boolean McasMultipleVMCreation;
    [Write, Description("")] Boolean McasMultipleVMDeletion;
    [Write, Description("")] Boolean McasSuspiciousAdminActivities;
    [Write, Description("")] Boolean McasSuspiciousCloudCreation;
    [Write, Description("")] Boolean McasSuspiciousCloudTrailLoggingChange;
    [Write, Description("")] Boolean McasTerminatedEmployeeActivity;
    [Write, Description("")] Boolean OdbDownload;
    [Write, Description("")] Boolean OdbSyncDownload;
    [Write, Description("")] Boolean PeerCumulativeExfiltrationDetector;
    [Write, Description("")] Boolean PhysicalAccess;
    [Write, Description("")] Boolean PotentialHighImpactUser;
    [Write, Description("")] Boolean Print;
    [Write, Description("")] Boolean PriorityUserGroupMember;
    [Write, Description("")] Boolean SecurityAlertDefenseEvasion;
    [Write, Description("")] Boolean SecurityAlertUnwantedSoftware;
    [Write, Description("")] Boolean SpoAccessRequest;
    [Write, Description("")] Boolean SpoApprovedAccess;
    [Write, Description("")] Boolean SpoDownload;
    [Write, Description("")] Boolean SpoDownloadV2;
    [Write, Description("")] Boolean SpoFileAccessed;
    [Write, Description("")] Boolean SpoFileDeleted;
    [Write, Description("")] Boolean SpoFileDeletedFromFirstStageRecycleBin;
    [Write, Description("")] Boolean SpoFileDeletedFromSecondStageRecycleBin;
    [Write, Description("")] Boolean SpoFileLabelDowngraded;
    [Write, Description("")] Boolean SpoFileLabelRemoved;
    [Write, Description("")] Boolean SpoFileSharing;
    [Write, Description("")] Boolean SpoFolderDeleted;
    [Write, Description("")] Boolean SpoFolderDeletedFromFirstStageRecycleBin;
    [Write, Description("")] Boolean SpoFolderDeletedFromSecondStageRecycleBin;
    [Write, Description("")] Boolean SpoFolderSharing;
    [Write, Description("")] Boolean SpoSiteExternalUserAdded;
    [Write, Description("")] Boolean SpoSiteInternalUserAdded;
    [Write, Description("")] Boolean SpoSiteLabelRemoved;
    [Write, Description("")] Boolean SpoSiteSharing;
    [Write, Description("")] Boolean SpoSyncDownload;
    [Write, Description("")] Boolean TeamsChannelFileSharedExternal;
    [Write, Description("")] Boolean TeamsChannelMemberAddedExternal;
    [Write, Description("")] Boolean TeamsChatFileSharedExternal;
    [Write, Description("")] Boolean TeamsFileDownload;
    [Write, Description("")] Boolean TeamsFolderSharedExternal;
    [Write, Description("")] Boolean TeamsMemberAddedExternal;
    [Write, Description("")] Boolean TeamsSensitiveMessage;
    [Write, Description("")] Boolean UserHistory;
    [Write, Description("")] Boolean AWSS3BlockPublicAccessDisabled;
    [Write, Description("")] Boolean AWSS3BucketDeleted;
    [Write, Description("")] Boolean AWSS3PublicAccessEnabled;
    [Write, Description("")] Boolean AWSS3ServerLoggingDisabled;
    [Write, Description("")] Boolean AzureElevateAccessToAllSubscriptions;
    [Write, Description("")] Boolean AzureResourceThreatProtectionSettingsUpdated;
    [Write, Description("")] Boolean AzureSQLServerAuditingSettingsUpdated;
    [Write, Description("")] Boolean AzureSQLServerFirewallRuleDeleted;
    [Write, Description("")] Boolean AzureSQLServerFirewallRuleUpdated;
    [Write, Description("")] Boolean AzureStorageAccountOrContainerDeleted;
    [Write, Description("")] Boolean BoxContentAccess;
    [Write, Description("")] Boolean BoxContentDelete;
    [Write, Description("")] Boolean BoxContentDownload;
    [Write, Description("")] Boolean BoxContentExternallyShared;
    [Write, Description("")] Boolean CCFinancialRegulatoryRiskyTextSent;
    [Write, Description("")] Boolean CCInappropriateContentSent;
    [Write, Description("")] Boolean CCInappropriateImagesSent;
    [Write, Description("")] Boolean DropboxContentAccess;
    [Write, Description("")] Boolean DropboxContentDelete;
    [Write, Description("")] Boolean DropboxContentDownload;
    [Write, Description("")] Boolean DropboxContentExternallyShared;
    [Write, Description("")] Boolean GoogleDriveContentAccess;
    [Write, Description("")] Boolean GoogleDriveContentDelete;
    [Write, Description("")] Boolean GoogleDriveContentExternallyShared;
    [Write, Description("")] Boolean PowerBIDashboardsDeleted;
    [Write, Description("")] Boolean PowerBIReportsDeleted;
    [Write, Description("")] Boolean PowerBIReportsDownloaded;
    [Write, Description("")] Boolean PowerBIReportsExported;
    [Write, Description("")] Boolean PowerBIReportsViewed;
    [Write, Description("")] Boolean PowerBISemanticModelsDeleted;
    [Write, Description("")] Boolean PowerBISensitivityLabelDowngradedForArtifacts;
    [Write, Description("")] Boolean PowerBISensitivityLabelRemovedFromArtifacts;
    [Write, Description("")] String HistoricTimeSpan;
    [Write, Description("")] String InScopeTimeSpan;
    [Write, Description("")] Boolean EnableTeam;
    [Write, Description("")] Boolean AnalyticsNewInsightEnabled;
    [Write, Description("")] Boolean AnalyticsTurnedOffEnabled;
    [Write, Description("")] Boolean HighSeverityAlertsEnabled;
    [Write, Description("")] String HighSeverityAlertsRoleGroups[];
    [Write, Description("")] Boolean PoliciesHealthEnabled;
    [Write, Description("")] String PoliciesHealthRoleGroups[];
    [Write, Description("")] Boolean NotificationDetailsEnabled;
    [Write, Description("")] String NotificationDetailsRoleGroups[];
    [Write, Description("")] Boolean ClipDeletionEnabled;
    [Write, Description("")] Boolean SessionRecordingEnabled;
    [Write, Description("")] String RecordingTimeframePreEventInSec;
    [Write, Description("")] String RecordingTimeframePostEventInSec;
    [Write, Description("")] String BandwidthCapInMb;
    [Write, Description("")] String OfflineRecordingStorageLimitInMb;
    [Write, Description("Present ensures the instance exists, absent ensures it is removed."), ValueMap{"Present"}, Values{"Present"}] string Ensure;
    [Write, Description("Credentials of the workload's Admin"), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Id of the Azure Active Directory tenant used for authentication.")] String TenantId;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Managed ID being used for authentication.")] Boolean ManagedIdentity;
    [Write, Description("Access token used for authentication.")] String AccessTokens[];
};
