[ClassVersion("1.0.0.0"), FriendlyName("EXOOrganizationConfig")]
class MSFT_EXOOrganizationConfig : OMI_BaseResource
{
    [Key, Description("Only valid value is 'Yes'."), ValueMap{"Yes"}, Values{"Yes"}] String IsSingleInstance;
    [Write, Description("The ActivityBasedAuthenticationTimeoutEnabled parameter specifies whether the timed logoff feature is enabled. The default value is $true")] Boolean ActivityBasedAuthenticationTimeoutEnabled;
    [Write, Description("The ActivityBasedAuthenticationTimeoutInterval parameter specifies the time span for logoff. You enter this value as a time span: hh:mm:ss where hh = hours, mm = minutes and ss = seconds. Valid values for this parameter are from 00:05:00 to 08:00:00 (5 minutes to 8 hours). The default value is 06:00:00 (6 hours).")] String ActivityBasedAuthenticationTimeoutInterval;
    [Write, Description("The ActivityBasedAuthenticationTimeoutWithSingleSignOnEnabled parameter specifies whether to keep single sign-on enabled. The default value is $true.")] Boolean ActivityBasedAuthenticationTimeoutWithSingleSignOnEnabled;
    [Write, Description("The AppsForOfficeEnabled parameter specifies whether to enable apps for Outlook features. By default, the parameter is set to $true. If the flag is set to $false, no new apps can be activated for any user in the organization.")] Boolean AppsForOfficeEnabled;
    [Write, Description("The AsyncSendEnabled parameter specifies whether to enable or disable async send in Outlook on the web.")] Boolean AsyncSendEnabled;
    [Write, Description("The AuditDisabled parameter specifies whether to disable or enable mailbox auditing for the organization.")] Boolean AuditDisabled;
    [Write, Description("The AutoExpandingArchive switch enables the unlimited archiving feature (called auto-expanding archiving) in an Exchange Online organization. You don't need to specify a value with this switch.")] Boolean AutoExpandingArchive;
    [Write, Description("The BookingsEnabled parameter specifies whether to enable Microsoft Bookings in an Exchange Online organization.")] Boolean BookingsEnabled;
    [Write, Description("The BookingsPaymentsEnabled parameter specifies whether to enable online payment node inside Bookings.")] Boolean BookingsPaymentsEnabled;
    [Write, Description("The BookingsSocialSharingRestricted parameter allows you to control whether, or not, your users can see social sharing options inside Bookings.")] Boolean BookingsSocialSharingRestricted;
    [Write, Description("The ByteEncoderTypeFor7BitCharsets parameter specifies the 7-bit transfer encoding method for MIME format for messages sent to this remote domain.")] UInt32 ByteEncoderTypeFor7BitCharsets;
    [Write, Description("The ConnectorsActionableMessagesEnabled parameter specifies whether to enable or disable actionable buttons in messages (connector cards) from connected apps on Outlook on the web.")] Boolean ConnectorsActionableMessagesEnabled;
    [Write, Description("The ConnectorsEnabled parameter specifies whether to enable or disable all connected apps in organization.")] Boolean ConnectorsEnabled;
    [Write, Description("The ConnectorsEnabledForOutlook parameter specifies whether to enable or disable connected apps in Outlook on the web. ")] Boolean ConnectorsEnabledForOutlook;
    [Write, Description("The ConnectorsEnabledForSharepoint parameter specifies whether to enable or disable connected apps on Sharepoint.")] Boolean ConnectorsEnabledForSharepoint;
    [Write, Description("The ConnectorsEnabledForTeams parameter specifies whether to enable or disable connected apps on Teams.")] Boolean ConnectorsEnabledForTeams;
    [Write, Description("The ConnectorsEnabledForYammer parameter specifies whether to enable or disable connected apps on Yammer.")] Boolean ConnectorsEnabledForYammer;
    [Write, Description("The DefaultAuthenticationPolicy parameter specifies the authentication policy that's used for the whole organization. You can use any value that uniquely identifies the policy.")] String DefaultAuthenticationPolicy;
    [Write, Description("The DefaultGroupAccessType parameter specifies the default access type for Office 365 groups."), ValueMap{"Private","Public"}, Values{"Private","Public"}] String DefaultGroupAccessType;
    [Write, Description("The DefaultPublicFolderAgeLimit parameter specifies the default age limit for the contents of public folders across the entire organization. Content in a public folder is automatically deleted when this age limit is exceeded. This attribute applies to all public folders in the organization that don't have their own AgeLimit setting. To specify a value, enter it as a time span: dd.hh:mm:ss where d = days, h = hours, m = minutes, and s = seconds. Or, enter the value $null. The default value is blank ($null).")] String DefaultPublicFolderAgeLimit;
    [Write, Description("The DefaultPublicFolderDeletedItemRetention parameter specifies the default value of the length of time to retain deleted items for public folders across the entire organization. This attribute applies to all public folders in the organization that don't have their own RetainDeletedItemsFor attribute set.")] String DefaultPublicFolderDeletedItemRetention;
    [Write, Description("The DefaultPublicFolderIssueWarningQuota parameter specifies the default value across the entire organization for the public folder size at which a warning message is sent to this folder's owners, warning that the public folder is almost full. This attribute applies to all public folders within the organization that don't have their own warning quota attribute set. The default value of this attribute is unlimited. The valid input range for this parameter is from 0 through 2199023254529 bytes(2 TB). If you enter a value of unlimited, no size limit is imposed on the public folder.")] String DefaultPublicFolderIssueWarningQuota;
    [Write, Description("The DefaultPublicFolderMaxItemSize parameter specifies the default maximum size for posted items within public folders across the entire organization. Items larger than the value of the DefaultPublicFolderMaxItemSize parameter are rejected. This attribute applies to all public folders within the organization that don't have their own MaxItemSize attribute set. The default value of this attribute is unlimited.")] String DefaultPublicFolderMaxItemSize;
    [Write, Description("The DefaultPublicFolderMovedItemRetention parameter specifies how long items that have been moved between mailboxes are kept in the source mailbox for recovery purposes before being removed by the Public Folder Assistant.")] String DefaultPublicFolderMovedItemRetention;
    [Write, Description("The DefaultPublicFolderProhibitPostQuota parameter specifies the size of a public folder at which users are notified that the public folder is full. Users can't post to a folder whose size is larger than the DefaultPublicFolderProhibitPostQuota parameter value. The default value of this attribute is unlimited.")] String DefaultPublicFolderProhibitPostQuota;
    [Write, Description("The DirectReportsGroupAutoCreationEnabled parameter specifies whether to enable or disable the automatic creation of direct report Office 365 groups.")] Boolean DirectReportsGroupAutoCreationEnabled;
    [Write, Description("The DistributionGroupDefaultOU parameter specifies the container where distribution groups are created by default.")] String DistributionGroupDefaultOU;
    [Write, Description("The DistributionGroupNameBlockedWordsList parameter specifies words that can't be included in the names of distribution groups. Separate multiple values with commas.")] String DistributionGroupNameBlockedWordsList[];
    [Write, Description("The DistributionGroupNamingPolicy parameter specifies the template applied to the name of distribution groups that are created in the organization. You can enforce that a prefix or suffix be applied to all distribution groups. Prefixes and suffixes can be either a string or an attribute, and you can combine strings and attributes.")] String DistributionGroupNamingPolicy;
    [Write, Description("The ElcProcessingDisabled parameter specifies whether to enable or disable the processing of mailboxes by the Managed Folder Assistant.")] Boolean ElcProcessingDisabled;
    [Write, Description("The EndUserDLUpgradeFlowsDisabled parameter specifies whether to prevent users from upgrading their own distribution groups to Office 365 groups in an Exchange Online organization.")] Boolean EndUserDLUpgradeFlowsDisabled;
    [Write, Description("The EwsAllowEntourage parameter specifies whether to enable or disable Entourage 2008 to access Exchange Web Services (EWS) for the entire organization.")] Boolean EwsAllowEntourage;
    [Write, Description("The EwsAllowList parameter specifies the applications that are allowed to access EWS or REST when the EwsApplicationAccessPolicy parameter is set to EwsAllowList. Other applications that aren't specified by this parameter aren't allowed to access EWS or REST. You identify the application by its user agent string value. Wildcard characters (*) are supported.")] String EwsAllowList[];
    [Write, Description("The EwsAllowMacOutlook parameter enables or disables access to mailboxes by Outlook for Mac clients that use Exchange Web Services (for example, Outlook for Mac 2011 or later).")] Boolean EwsAllowMacOutlook;
    [Write, Description("The EwsAllowOutlook parameter enables or disables access to mailboxes by Outlook clients that use Exchange Web Services. Outlook uses Exchange Web Services for free/busy, out-of-office settings, and calendar sharing.")] Boolean EwsAllowOutlook;
    [Write, Description("The EwsApplicationAccessPolicy parameter specifies the client applications that have access to EWS and REST."), ValueMap{"EnforceAllowList","EnforceBlockList"}, Values{"EnforceAllowList","EnforceBlockList"}] String EwsApplicationAccessPolicy;
    [Write, Description("The EwsBlockList parameter specifies the applications that aren't allowed to access EWS or REST when the EwsApplicationAccessPolicy parameter is set to EnforceBlockList. All other applications that aren't specified by this parameter are allowed to access EWS or REST. You identify the application by its user agent string value. Wildcard characters (*) are supported.")] String EwsBlockList[];
    [Write, Description("The EwsEnabled parameter specifies whether to globally enable or disable EWS access for the entire organization, regardless of what application is making the request.")] Boolean EwsEnabled;
    [Write, Description("The ExchangeNotificationEnabled parameter enables or disables Exchange notifications sent to administrators regarding their organizations. Valid input for this parameter is $true or $false.")] Boolean ExchangeNotificationEnabled;
    [Write, Description("The ExchangeNotificationRecipients parameter specifies the recipients for Exchange notifications sent to administrators regarding their organizations. If the ExchangeNotificationEnabled parameter is set to $false, no notification messages are sent. Be sure to enclose values that contain spaces in quotation marks and separate multiple values with commas. If this parameter isn't set, Exchange notifications are sent to all administrators.")] String ExchangeNotificationRecipients[];
    [Write, Description("The FocusedInboxOn parameter enables or disables Focused Inbox for the organization.")] Boolean FocusedInboxOn;
    [Write, Description("The HierarchicalAddressBookRoot parameter specifies the user, contact, or group to be used as the root organization for a hierarchical address book in the Exchange organization. You can use any value that uniquely identifies the recipient.")] String HierarchicalAddressBookRoot;
    [Write, Description("The IPListBlocked parameter specifies the blocked IP addresses that aren't allowed to connect to Exchange Online organization. These settings affect client connections that use Basic authentication where on-premises Active Directory Federation Services (ADFS) servers federate authentication with Azure Active Directory. Note that the new settings might take up to 4 hours to fully propagate across the service.")] String IPListBlocked[];
    [Write, Description("The LeanPopoutEnabled parameter specifies whether to enable faster loading of pop-out messages in Outlook on the web for Internet Explorer and Microsoft Edge.")] Boolean LeanPopoutEnabled;
    [Write, Description("The LinkPreviewEnabled parameter specifies whether link preview of URLs in email messages is allowed for the organization.")] Boolean LinkPreviewEnabled;
    [Write, Description("The MailTipsAllTipsEnabled parameter specifies whether MailTips are enabled. The default value is $true.")] Boolean MailTipsAllTipsEnabled;
    [Write, Description("The MailTipsExternalRecipientsTipsEnabled parameter specifies whether MailTips for external recipients are enabled. The default value is $false.")] Boolean MailTipsExternalRecipientsTipsEnabled;
    [Write, Description("The MailTipsGroupMetricsEnabled parameter specifies whether MailTips that rely on group metrics data are enabled. The default value is $true.")] Boolean MailTipsGroupMetricsEnabled;
    [Write, Description("The MailTipsLargeAudienceThreshold parameter specifies what a large audience is. The default value is 25.")] UInt32 MailTipsLargeAudienceThreshold;
    [Write, Description("The MailTipsMailboxSourcedTipsEnabled parameter specifies whether MailTips that rely on mailbox data (out-of-office or full mailbox) are enabled.")] Boolean MailTipsMailboxSourcedTipsEnabled;
    [Write, Description("The OAuth2ClientProfileEnabled parameter enables or disables modern authentication in the Exchange organization.")] Boolean OAuth2ClientProfileEnabled;
    [Write, Description("The OutlookMobileGCCRestrictionsEnabled parameter specifies whether to enable or disable features within Outlook for iOS and Android that are not FedRAMP compliant for Office 365 US Government Community Cloud (GCC) customers.")] Boolean OutlookMobileGCCRestrictionsEnabled;
    [Write, Description("The OutlookPayEnabled parameter enables or disables Payments in Outlook in the Office 365 organization.")] Boolean OutlookPayEnabled;
    [Write, Description("The PublicComputersDetectionEnabled parameter specifies whether Outlook on the web will detect when a user signs from a public or private computer or network, and then enforces the attachment handling settings from public networks. The default is $false. However, if you set this parameter to $true, Outlook on the web will determine if the user is signing in from a public computer, and all public attachment handling rules will be applied and enforced.")] Boolean PublicComputersDetectionEnabled;
    [Write, Description("The PublicFoldersEnabled parameter specifies how public folders are deployed in your organization."), ValueMap{"None","Local","Remote"}, Values{"None","Local","Remote"}] String PublicFoldersEnabled;
    [Write, Description("The PublicFolderShowClientControl parameter enables or disables access to public folders in Microsoft Outlook.")] Boolean PublicFolderShowClientControl;
    [Write, Description("The ReadTrackingEnabled parameter specifies whether the tracking for read status for messages in an organization is enabled. The default value is $false.")] Boolean ReadTrackingEnabled;
    [Write, Description("The RemotePublicFolderMailboxes parameter specifies the identities of the public folder objects (represented as mail user objects locally) corresponding to the public folder mailboxes created in the remote forest. The public folder values set here are used only if the public folder deployment is a remote deployment.")] String RemotePublicFolderMailboxes[];
    [Write, Description("The SiteMailboxCreationURL parameter specifies the URL that's used to create site mailboxes. Site mailboxes improve collaboration and user productivity by allowing access to both SharePoint documents and Exchange email in Outlook 2013 or later.")] String SiteMailboxCreationURL;
    [Write, Description("The SmtpActionableMessagesEnabled parameter specifies whether to enable or disable action buttons in email messages in Outlook on the web.")] Boolean SmtpActionableMessagesEnabled;
    [Write, Description("The VisibleMeetingUpdateProperties parameter specifies whether meeting message updates will be auto-processed on behalf of attendees. Auto-processed updates are applied to the attendee's calendar item, and then the meeting message is moved to the deleted items. The attendee never sees the update in their inbox, but their calendar is updated.")] String VisibleMeetingUpdateProperties;
    [Write, Description("The WebPushNotificationsDisabled parameter specifies whether to enable or disable Web Push Notifications in Outlook on the Web. This feature provides web push notifications which appear on a user's desktop while the user is not using Outlook on the Web. This brings awareness of incoming messages while they are working elsewhere on their computer.")] Boolean WebPushNotificationsDisabled;
    [Write, Description("The WebSuggestedRepliesDisabled parameter specifies whether to enable or disable Suggested Replies in Outlook on the web. This feature provides suggested replies to emails so users can easily and quickly respond to messages.")] Boolean WebSuggestedRepliesDisabled;
    [Required, Description("Credentials of the Exchange Global Admin."), EmbeddedInstance("MSFT_Credential")] string GlobalAdminAccount;
};

