[ClassVersion("1.0.0.0"), FriendlyName("SCDLPSensitiveInformationType")]
class MSFT_SCDLPSensitiveInformationType : OMI_BaseResource
{
    [Key, Description("The Name parameter specifies a name for the sensitive information type rule. The value must be less than 256 characters.")] String Name;
    [Write, Description("Unique identifier of the Sensitive Information Type.")] String Identity;
    [Write, Description("The Description parameter specifies a description for the sensitive information type rule.")] String Description;
    [Write, Description("The fingerprint file data for the Sensitive Information Type.")] String FileData;
    [Write, Description("The Locale parameter specifies the language that's associated with the sensitive information type rule.")] String Locale;
    [Write, Description("Present ensures the instance exists, absent ensures it is removed."), ValueMap{"Absent","Present"}, Values{"Absent","Present"}] string Ensure;
    [Write, Description("Credentials of the workload's Admin"), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Id of the Azure Active Directory tenant used for authentication.")] String TenantId;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Username can be made up to anything but password will be used for CertificatePassword"), EmbeddedInstance("MSFT_Credential")] String CertificatePassword;
    [Write, Description("Path to certificate used in service principal usually a PFX file.")] String CertificatePath;
    [Write, Description("Managed ID being used for authentication.")] Boolean ManagedIdentity;
    [Write, Description("Access token used for authentication.")] String AccessTokens[];
};
