[ClassVersion("1.0.0.0"), FriendlyName("EXOOwaMailboxPolicy")]
class MSFT_EXOOwaMailboxPolicy : OMI_BaseResource
{
    [Key, Description("The Name parameter specifies the unique name for the policy. The maximum length is 64 characters.")] String Name;

    [Write, Description("The ActionForUnknownFileAndMIMETypes parameter specifies how to handle file types that aren't specified in the Allow, Block, and Force Save lists for file types and MIME types"), ValueMap{"Allow","ForceSave","Block"}, Values{"Allow","ForceSave","Block"}] String ActionForUnknownFileAndMIMETypes;

    [Write, Description("The ActiveSyncIntegrationEnabled parameter specifies whether to enable or disable Exchange ActiveSync settings in Outlook on the web. ")] Boolean ActiveSyncIntegrationEnabled;

    [Write, Description("The AdditionalStorageProvidersAvailable parameter specifies whether to allow additional storage providers (for example, Box, Dropbox, Facebook, Google Drive, Egnyte, personal OneDrive) attachments in Outlook on the web.")] Boolean AdditionalStorageProvidersAvailable;

    [Write, Description("The AllAddressListsEnabled parameter specifies which address lists are available in Outlook on the web.")] Boolean AllAddressListsEnabled;

    [Write, Description("The AllowCopyContactsToDeviceAddressBook parameter specifies whether users can copy the contents of their Contacts folder to a mobile device's native address book when using Outlook on the web for devices.")] Boolean AllowCopyContactsToDeviceAddressBook;

    [Write, Description("The AllowedFileTypes parameter specifies the attachment file types (file extensions) that can be saved locally or viewed from Outlook on the web.")] String AllowedFileTypes[];

    [Write, Description("The AllowedMimeTypes parameter specifies the MIME extensions of attachments that allow the attachments to be saved locally or viewed from Outlook on the web.")] String AllowedMimeTypes[];

    [Write, Description("The BlockedFileTypes parameter specifies a list of attachment file types (file extensions) that can't be saved locally or viewed from Outlook on the web.")] String BlockedFileTypes[];

    [Write, Description("The BlockedMimeTypes parameter specifies MIME extensions in attachments that prevent the attachments from being saved locally or viewed from Outlook on the web.")] String BlockedMimeTypes[];

    [Write, Description("The ClassicAttachmentsEnabled parameter specifies whether users can attach local files as regular email attachments in Outlook on the web.")] Boolean ClassicAttachmentsEnabled;

    [Write, Description("The ConditionalAccessPolicy parameter specifies the Outlook on the Web Policy for limited access. For this feature to work properly, you also need to configure a Conditional Access policy in the Azure Active Directory Portal."), ValueMap{"Off","ReadOnly","ReadOnlyPlusAttachmentsBlocked"}, Values{"Off","ReadOnly","ReadOnlyPlusAttachmentsBlocked"}] String ConditionalAccessPolicy;

    [Write, Description("The DefaultTheme parameter specifies the default theme that's used in Outlook on the web when the user hasn't selected a theme. The default value is blank ($null).")] String DefaultTheme;

    [Write, Description("The DirectFileAccessOnPrivateComputersEnabled parameter specifies the left-click options for attachments in Outlook on the web for private computer sessions. ")] Boolean DirectFileAccessOnPrivateComputersEnabled;

    [Write, Description("The DirectFileAccessOnPrivateComputersEnabled parameter specifies the left-click options for attachments in Outlook on the web for public computer sessions.")] Boolean DirectFileAccessOnPublicComputersEnabled;

    [Write, Description("The DisableFacebook switch specifies whether users can synchronize their Facebook contacts to their Contacts folder in Outlook on the web. By default, Facebook integration is enabled.")] Boolean DisableFacebook;

    [Write, Description("The DisplayPhotosEnabled parameter specifies whether users see sender photos in Outlook on the web.")] Boolean DisplayPhotosEnabled;

    [Write, Description("The ExplicitLogonEnabled parameter specifies whether to allow a user to open someone else's mailbox in Outlook on the web (provided that user has permissions to the mailbox).")] Boolean ExplicitLogonEnabled;

    [Write, Description("The ExternalImageProxyEnabled parameter specifies whether to load all external images through the Outlook external image proxy.")] Boolean ExternalImageProxyEnabled;

    [Write, Description("The ExternalSPMySiteHostURL specifies the My Site Host URL for external users.")] String ExternalSPMySiteHostURL;

    [Write, Description("The ForceSaveAttachmentFilteringEnabled parameter specifies whether files are filtered before they can be saved from Outlook on the web.")] Boolean ForceSaveAttachmentFilteringEnabled;

    [Write, Description("The ForceSaveFileTypes parameter specifies the attachment file types (file extensions) that can only be saved from Outlook on the web (not opened).")] String ForceSaveFileTypes[];

    [Write, Description("The ForceSaveMimeTypes parameter specifies the MIME extensions in attachments that only allow the attachments to be saved locally (not opened).")] String ForceSaveMimeTypes[];

    [Write, Description("The ForceWacViewingFirstOnPrivateComputers parameter specifies whether private computers must first preview an Office file as a web page in Office Online Server (formerly known as Office Web Apps Server and Web Access Companion Server) before opening the file in the local application.")] Boolean ForceWacViewingFirstOnPrivateComputers;

    [Write, Description("The ForceWacViewingFirstOnPublicComputers parameter specifies whether public computers must first preview an Office file as a web page in Office Online Server before opening the file in the local application.")] Boolean ForceWacViewingFirstOnPublicComputers;

    [Write, Description("The FreCardsEnabled parameter specifies whether the theme, signature, and phone cards are available in Outlook on the web.")] Boolean FreCardsEnabled;

    [Write, Description("The GlobalAddressListEnabled parameter specifies whether the global address list is available in Outlook on the web.")] Boolean GlobalAddressListEnabled;

    [Write, Description("The GroupCreationEnabled parameter specifies whether Office 365 group creation is available in Outlook on the web.")] Boolean GroupCreationEnabled;

    [Write, Description("The InstantMessagingEnabled parameter specifies whether instant messaging is available in Outlook on the web.")] Boolean InstantMessagingEnabled;

    [Write, Description("The InstantMessagingType parameter specifies the type of instant messaging provider in Outlook on the web."), ValueMap{"None","Ocs"}, Values{"None","Ocs"}] String InstantMessagingType;

    [Write, Description("The InterestingCalendarsEnabled parameter specifies whether interesting calendars are available in Outlook on the web.")] Boolean InterestingCalendarsEnabled;

    [Write, Description("The InternalSPMySiteHostURL specifies the My Site Host URL for internal users.")] String InternalSPMySiteHostURL;

    [Write, Description("The IRMEnabled parameter specifies whether Information Rights Management (IRM) features are available in Outlook on the web.")] Boolean IRMEnabled;

    [Write, Description("The IsDefault switch specifies whether the Outlook on the web policy is the default policy that's used to configure the Outlook on the web settings for new mailboxes.")] Boolean IsDefault;

    [Write, Description("The JournalEnabled parameter specifies whether the Journal folder is available in Outlook on the web.")] Boolean JournalEnabled;

    [Write, Description("The LocalEventsEnabled parameter specifies whether local events calendars are available in Outlook on the web.")] Boolean LocalEventsEnabled;

    [Write, Description("The LogonAndErrorLanguage parameter specifies the language that used in Outlook on the web for forms-based authentication and for error messages when a user's current language setting can't be read. A valid value is a supported Microsoft Windows Language Code Identifier (LCID). For example, 1033 is US English.")] SInt32 LogonAndErrorLanguage;

    [Write, Description("The NotesEnabled parameter specifies whether the Notes folder is available in Outlook on the web.")] Boolean NotesEnabled;

    [Write, Description("The NPSMailboxPolicy parameter specifies whether to enable or disable the Net Promoter Score (NPS) survey in Outlook on the web. The survey allows uses to rate Outlook on the web on a scale of 1 to 5, and to provide feedback and suggested improvements in free text.")] Boolean NpsMailboxPolicy;

    [Write, Description("When the OrganizationEnabled parameter is set to $false, the Automatic Reply option doesn't include external and internal options, the address book doesn't show the organization hierarchy, and the Resources tab in Calendar forms is disabled.")] Boolean OrganizationEnabled;

    [Write, Description("The OnSendAddinsEnabled parameter specifies whether to enable or disable on send add-ins in Outlook on the web (add-ins that support events when a user clicks Send).")] Boolean OnSendAddinsEnabled;

    [Write, Description("The OutboundCharset parameter specifies the character set that's used for outgoing messages in Outlook on the web."), ValueMap{"AutoDetect","AlwaysUTF8","UserLanguageChoice"}, Values{"AutoDetect","AlwaysUTF8","UserLanguageChoice"}] String OutboundCharset;

    [Write, Description("The OutlookBetaToggleEnabled parameter specifies whether to enable or disable the Outlook on the web Preview toggle. The Preview toggle allows users to try the new Outlook on the web experience.")] Boolean OutlookBetaToggleEnabled;

    [Write, Description("The OWALightEnabled parameter controls the availability of the light version of Outlook on the web.")] Boolean OWALightEnabled;

    [Write, Description("The PersonalAccountCalendarsEnabled parameter specifies whether to allow users to connect to their personal Outlook.com or Google Calendar in Outlook on the web.")] Boolean PersonalAccountCalendarsEnabled;

    [Write, Description("The PhoneticSupportEnabled parameter specifies phonetically spelled entries in the address book. This parameter is available for use in Japan.")] Boolean PhoneticSupportEnabled;

    [Write, Description("The PlacesEnabled parameter specifies whether to enable or disable Places in Outlook on the web. Places lets users search, share, and map location details by using Bing.")] Boolean PlacesEnabled;

    [Write, Description("The PremiumClientEnabled parameter controls the availability of the full version of Outlook Web App.")] Boolean PremiumClientEnabled;

    [Write, Description("The PrintWithoutDownloadEnabled specifies whether to allow printing of supported files without downloading the attachment in Outlook on the web.")] Boolean PrintWithoutDownloadEnabled;

    [Write, Description("The PublicFoldersEnabled parameter specifies whether a user can browse or read items in public folders in Outlook Web App.")] Boolean PublicFoldersEnabled;

    [Write, Description("The RecoverDeletedItemsEnabled parameter specifies whether a user can use Outlook Web App to view, recover, or delete permanently items that have been deleted from the Deleted Items folder.")] Boolean RecoverDeletedItemsEnabled;

    [Write, Description("The ReferenceAttachmentsEnabled parameter specifies whether users can attach files from the cloud as linked attachments in Outlook on the web.")] Boolean ReferenceAttachmentsEnabled;

    [Write, Description("The RemindersAndNotificationsEnabled parameter specifies whether notifications and reminders are enabled in Outlook on the web.")] Boolean RemindersAndNotificationsEnabled;

    [Write, Description("The ReportJunkEmailEnabled parameter specifies whether users can report messages to Microsoft or unsubscribe from messages in Outlook on the web. ")] Boolean ReportJunkEmailEnabled;

    [Write, Description("The RulesEnabled parameter specifies whether a user can view, create, or modify server-side rules in Outlook on the web.")] Boolean RulesEnabled;

    [Write, Description("The SatisfactionEnabled parameter specifies whether to enable or disable the satisfaction survey.")] Boolean SatisfactionEnabled;

    [Write, Description("The SaveAttachmentsToCloudEnabled parameter specifies whether users can save regular email attachments to the cloud.")] Boolean SaveAttachmentsToCloudEnabled;

    [Write, Description("The SearchFoldersEnabled parameter specifies whether Search Folders are available in Outlook on the web.")] Boolean SearchFoldersEnabled;

    [Write, Description("The SetPhotoEnabled parameter specifies whether users can add, change, and remove their sender photo in Outlook on the web.")] Boolean SetPhotoEnabled;

    [Write, Description("The SetPhotoURL parameter controls where users go to select their photo. Note that you can't specify a URL that contains one or more picture files, as there is no mechanism to copy a URL photo to the properties of the users' Exchange Online mailboxes.")] String SetPhotoURL;

    [Write, Description("The SignaturesEnabled parameter specifies whether to enable or disable the use of signatures in Outlook on the web.")] Boolean SignaturesEnabled;

    [Write, Description("The SkipCreateUnifiedGroupCustomSharepointClassification parameter specifies whether to skip a custom SharePoint page during the creation of Office 365 Groups in Outlook web app.")] Boolean SkipCreateUnifiedGroupCustomSharepointClassification;

    [Write, Description("The TeamSnapCalendarsEnabled parameter specifies whether to allow users to connect to their personal TeamSnap calendars in Outlook on the web.")] Boolean TeamSnapCalendarsEnabled;

    [Write, Description("The TextMessagingEnabled parameter specifies whether users can send and receive text messages in Outlook on the web.")] Boolean TextMessagingEnabled;

    [Write, Description("The ThemeSelectionEnabled parameter specifies whether users can change the theme in Outlook on the web.")] Boolean ThemeSelectionEnabled;

    [Write, Description("The UMIntegrationEnabled parameter specifies whether Unified Messaging (UM) integration is enabled in Outlook on the web.")] Boolean UMIntegrationEnabled;

    [Write, Description("The UseGB18030 parameter specifies whether to use the GB18030 character set instead of GB2312 in Outlook on the web.")] Boolean UseGB18030;

    [Write, Description("The UseISO885915 parameter specifies whether to use the character set ISO8859-15 instead of ISO8859-1 in Outlook on the web.")] Boolean UseISO885915;

    [Write, Description("The UserVoiceEnabled parameter specifies whether to enable or disable Outlook UserVoice in Outlook on the web. Outlook UserVoice is a customer feedback area that's available in Office 365.")] Boolean UserVoiceEnabled;

    [Write, Description("The WacEditingEnabled parameter specifies whether to enable or disable editing documents in Outlook on the web by using Office Online Server (formerly known as Office Web Apps Server and Web Access Companion Server). ")] Boolean WacEditingEnabled;

    [Write, Description("The WacExternalServicesEnabled parameter specifies whether to enable or disable external services when viewing documents in Outlook on the web (for example, machine translation) by using Office Online Server.")] Boolean WacExternalServicesEnabled;

    [Write, Description("The WacOMEXEnabled parameter specifies whether to enable or disable apps for Outlook in Outlook on the web in Office Online Server.")] Boolean WacOMEXEnabled;

    [Write, Description("The WacViewingOnPrivateComputersEnabled parameter specifies whether to enable or disable web viewing of supported Office documents private computer sessions in Office Online Server (formerly known as Office Web Apps Server and Web Access Companion Server). By default, all Outlook on the web sessions are considered to be on private computers.")] Boolean WacViewingOnPrivateComputersEnabled;

    [Write, Description("The WacViewingOnPublicComputersEnabled parameter specifies whether to enable or disable web viewing of supported Office documents in public computer sessions in Office Online Server. ")] Boolean WacViewingOnPublicComputersEnabled;

    [Write, Description("The WeatherEnabled parameter specifies whether to enable or disable weather information in the calendar in Outlook on the web.")] Boolean WeatherEnabled;

    [Write, Description("The WebPartsFrameOptionsType parameter specifies what sources can access web parts in IFRAME or FRAME elements in Outlook on the web."), ValueMap{"None","SameOrigin","Deny"}, Values{"None","SameOrigin","Deny"}] String WebPartsFrameOptionsType;

    [Write, Description("Specify if the OWA Mailbox Policy should exist or not."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;

    [Required, Description("Credentials of the Exchange Global Admin"), EmbeddedInstance("MSFT_Credential")] string GlobalAdminAccount;
};
