[ClassVersion("1.0.0.3")]
class MSFT_DeviceManagementConfigurationPolicyAssignments
{
    [Required, Description("The type of the target assignment."), ValueMap{"#microsoft.graph.cloudPcManagementGroupAssignmentTarget","#microsoft.graph.groupAssignmentTarget","#microsoft.graph.allLicensedUsersAssignmentTarget","#microsoft.graph.allDevicesAssignmentTarget","#microsoft.graph.exclusionGroupAssignmentTarget","#microsoft.graph.configurationManagerCollectionAssignmentTarget"}, Values{"#microsoft.graph.cloudPcManagementGroupAssignmentTarget","#microsoft.graph.groupAssignmentTarget","#microsoft.graph.allLicensedUsersAssignmentTarget","#microsoft.graph.allDevicesAssignmentTarget","#microsoft.graph.exclusionGroupAssignmentTarget","#microsoft.graph.configurationManagerCollectionAssignmentTarget"}] String dataType;
    [Write, Description("The type of filter of the target assignment i.e. Exclude or Include. Possible values are:none, include, exclude."), ValueMap{"none","include","exclude"}, Values{"none","include","exclude"}] String deviceAndAppManagementAssignmentFilterType;
    [Write, Description("The Id of the filter for the target assignment.")] String deviceAndAppManagementAssignmentFilterId;
    [Write, Description("The display name of the filter for the target assignment.")] String deviceAndAppManagementAssignmentFilterDisplayName;
    [Write, Description("The group Id that is the target of the assignment.")] String groupId;
    [Write, Description("The group Display Name that is the target of the assignment.")] String groupDisplayName;
    [Write, Description("The collection Id that is the target of the assignment.(ConfigMgr)")] String collectionId;
};

[ClassVersion("1.0.0.0"), FriendlyName("IntuneAntivirusPolicySecurityExperienceWindows10ConfigMgr")]
class MSFT_IntuneAntivirusPolicySecurityExperienceWindows10ConfigMgr : OMI_BaseResource
{
    [Write, Description("Policy description")] String Description;
    [Key, Description("Policy name")] String DisplayName;
    [Write, Description("List of Scope Tags for this Entity instance.")] String RoleScopeTagIds[];
    [Write, Description("The unique identifier for an entity. Read-only.")] String Id;
    [Write, Description("Disable Account Protection UI (0: (Disable) The users can see the display of the Account protection area in Windows Defender Security Center., 1: (Enable) The users cannot see the display of the Account protection area in Windows Defender Security Center.)"), ValueMap{"0", "1"}, Values{"0", "1"}] SInt32 DisableAccountProtectionUI;
    [Write, Description("Disable App Browser UI (0: (Disable) The users can see the display of the app and browser protection area in Windows Defender Security Center., 1: (Enable) The users cannot see the display of the app and browser protection area in Windows Defender Security Center.)"), ValueMap{"0", "1"}, Values{"0", "1"}] SInt32 DisableAppBrowserUI;
    [Write, Description("Disable Clear Tpm Button (0: (Disabled or not configured) The security processor troubleshooting page shows a button that initiates the process to clear the security processor (TPM)., 1: (Enabled) The security processor troubleshooting page will not show a button to initiate the process to clear the security processor (TPM))"), ValueMap{"0", "1"}, Values{"0", "1"}] SInt32 DisableClearTpmButton;
    [Write, Description("Disable Device Security UI (0: (Disable) The users can see the display of the Device security area in Windows Defender Security Center., 1: (Enable) The users cannot see the display of the Device security area in Windows Defender Security Center.)"), ValueMap{"0", "1"}, Values{"0", "1"}] SInt32 DisableDeviceSecurityUI;
    [Write, Description("Disable Family UI (0: (Disable) The users can see the display of the family options area in Windows Defender Security Center., 1: (Enable) The users cannot see the display of the family options area in Windows Defender Security Center.)"), ValueMap{"0", "1"}, Values{"0", "1"}] SInt32 DisableFamilyUI;
    [Write, Description("Disable Health UI (0: (Disable) The users can see the display of the device performance and health area in Windows Defender Security Center., 1: (Enable) The users cannot see the display of the device performance and health area in Windows Defender Security Center.)"), ValueMap{"0", "1"}, Values{"0", "1"}] SInt32 DisableHealthUI;
    [Write, Description("Disable Network UI (0: (Disable) The users can see the display of the firewall and network protection area in Windows Defender Security Center., 1: (Enable) The users cannot see the display of the firewall and network protection area in Windows Defender Security Center.)"), ValueMap{"0", "1"}, Values{"0", "1"}] SInt32 DisableNetworkUI;
    [Write, Description("Disable Notifications (0: (Disable) The users can see the display of Windows Defender Security Center notifications., 1: (Enable) The users cannot see the display of Windows Defender Security Center notifications.)")] SInt32 DisableNotifications;
    [Write, Description("Disable Enhanced Notifications (0: (Disable) Windows Defender Security Center will display critical and non-critical notifications to users.., 1: (Enable) Windows Defender Security Center only display notifications which are considered critical on clients.)"), ValueMap{"0", "1"}, Values{"0", "1"}] SInt32 DisableEnhancedNotifications;
    [Write, Description("Disable Tpm Firmware Update Warning (0: (Disable or Not configured) A warning will be displayed if the firmware of the security processor (TPM) should be updated for TPMs that have a vulnerability., 1: (Enabled) No warning will be displayed if the firmware of the security processor (TPM) should be updated.)"), ValueMap{"0", "1"}, Values{"0", "1"}] SInt32 DisableTpmFirmwareUpdateWarning;
    [Write, Description("Disable Virus UI (0: (Disable) The users can see the display of the virus and threat protection area in Windows Defender Security Center., 1: (Enable) The users cannot see the display of the virus and threat protection area in Windows Defender Security Center.)"), ValueMap{"0", "1"}, Values{"0", "1"}] SInt32 DisableVirusUI;
    [Write, Description("Hide Ransomware Data Recovery (0: (Disable or not configured) The Ransomware data recovery area will be visible., 1: (Enable) The Ransomware data recovery area is hidden.)"), ValueMap{"0", "1"}, Values{"0", "1"}] SInt32 HideRansomwareDataRecovery;
    [Write, Description("Hide Windows Security Notification Area Control (0: , 1: Enabled)"), ValueMap{"0", "1"}, Values{"0", "1"}] SInt32 HideWindowsSecurityNotificationAreaControl;
    [Write, Description("Company Name")] String CompanyName;
    [Write, Description("Email")] String Email;
    [Write, Description("Phone")] String Phone;
    [Write, Description("URL")] String URL;
    [Write, Description("TamperProtection (Device) (1: Offboarding, 0: Onboarding)"), ValueMap{"1", "0"}, Values{"1", "0"}] String TamperProtection;
    [Write, Description("Represents the assignment to the Intune policy."), EmbeddedInstance("MSFT_DeviceManagementConfigurationPolicyAssignments")] String Assignments[];
    [Write, Description("Present ensures the policy exists, absent ensures it is removed."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] string Ensure;
    [Write, Description("Credentials of the Admin"), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Id of the Azure Active Directory tenant used for authentication.")] String TenantId;
    [Write, Description("Secret of the Azure Active Directory tenant used for authentication."), EmbeddedInstance("MSFT_Credential")] String ApplicationSecret;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Username can be made up to anything but password will be used for CertificatePassword"), EmbeddedInstance("MSFT_Credential")] String CertificatePassword;
    [Write, Description("Path to certificate used in service principal usually a PFX file.")] String CertificatePath;
    [Write, Description("Managed ID being used for authentication.")] Boolean ManagedIdentity;
    [Write, Description("Access token used for authentication.")] String AccessTokens[];
};
