[ClassVersion("1.0.0.0"), FriendlyName("SentinelSetting")]
class MSFT_SentinelSetting : OMI_BaseResource
{
    [Key, Description("The Resource Group Name")] String ResourceGroupName;
    [Required, Description("The name of the workspace.")] String WorkspaceName;
    [Write, Description("Gets subscription credentials which uniquely identify Microsoft Azure subscription. The subscription ID forms part of the URI for every service call.")] String SubscriptionId;
    [Write, Description("Specififies if Anomaly detection should be enabled or not.")] Boolean AnomaliesIsEnabled;
    [Write, Description("Specififies if Entity Analyticsshould be enabled or not.")] Boolean EntityAnalyticsIsEnabled;
    [Write, Description("Specififies if Auditing and Health Monitoring should be enabled or not.")] Boolean EyesOnIsEnabled;
    [Write, Description("The list of Data sources associated with the UEBA.")] String UebaDataSource[];
    [Write, Description("Credentials of the workload's Admin"), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Id of the Azure Active Directory tenant used for authentication.")] String TenantId;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Managed ID being used for authentication.")] Boolean ManagedIdentity;
    [Write, Description("Access token used for authentication.")] String AccessTokens[];
};
