[ClassVersion("1.0.0.0"), FriendlyName("SentinelWatchlist")]
class MSFT_SentinelWatchlist : OMI_BaseResource
{
    [Key, Description("Tha name of the watchlist.")] String Name;
    [Write, Description("The name of the resource group. The name is case insensitive.")] String SubscriptionId;
    [Write, Description("The name of the resource group. The name is case insensitive.")] String ResourceGroupName;
    [Write, Description("The name of the workspace.")] String WorkspaceName;
    [Write, Description("The id (a Guid) of the watchlist")] String Id;
    [Write, Description("The display name of the watchlist.")] String DisplayName;
    [Write, Description("The source of the watchlist. Only accepts 'Local file' and 'Remote storage'. And it must included in the request.")] String SourceType;
    [Write, Description("The search key is used to optimize query performance when using watchlists for joins with other data. For example, enable a column with IP addresses to be the designated SearchKey field, then use this field as the key field when joining to other event data by IP address.")] String ItemsSearchKey;
    [Write, Description("A description of the watchlist")] String Description;
    [Write, Description("The default duration of a watchlist (in ISO 8601 duration format)")] String DefaultDuration;
    [Write, Description("The watchlist alias")] String Alias;
    [Write, Description("The number of lines in a csv content to skip before the header")] UInt32 NumberOfLinesToSkip;
    [Write, Description("The raw content that represents to watchlist items to create. Example : This line will be skipped header1,header2 value1,value2")] String RawContent;
    [Write, Description("Present ensures the instance exists, absent ensures it is removed."), ValueMap{"Absent","Present"}, Values{"Absent","Present"}] string Ensure;
    [Write, Description("Credentials of the workload's Admin"), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Id of the Azure Active Directory tenant used for authentication.")] String TenantId;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Managed ID being used for authentication.")] Boolean ManagedIdentity;
    [Write, Description("Access token used for authentication.")] String AccessTokens[];
};
