[ClassVersion("1.0.0.0"), FriendlyName("EXORoleAssignmentPolicy")]
class MSFT_EXORoleAssignmentPolicy : OMI_BaseResource
{
    [Key, Description("The Name parameter specifies the new name of the assignment policy. The maximum length is 64 characters.")] String Name;
    [Write, Description("The Description parameter specifies the description that's displayed when the role assignment policy is viewed using the Get-RoleAssignmentPolicy cmdlet.")] String Description;
    [Write, Description("The IsDefault switch makes the assignment policy the default assignment policy.")] Boolean IsDefault;
    [Write, Description("The Roles parameter specifies the management roles to assign to the role assignment policy when it's created.")] String Roles[];
    [Write, Description("Specify if the Role Assignment Policy should exist or not."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Required, Description("Credentials of the Exchange Global Admin"), EmbeddedInstance("MSFT_Credential")] string GlobalAdminAccount;
};
