[ClassVersion("1.0.0.0"), FriendlyName("AADAgreement")]
class MSFT_AADAgreement : OMI_BaseResource
{
    [Key, Description("The display name of the agreement.")] String DisplayName;
    [Write, Description("The unique identifier of the agreement.")] String Id;
    [Write, Description("Whether the user is required to view the agreement document before accepting.")] Boolean IsViewingBeforeAcceptanceRequired;
    [Write, Description("Whether the agreement is per device or per user.")] Boolean IsPerDeviceAcceptanceRequired;
    [Write, Description("Duration after which the user must re-accept the terms of use. Must be in ISO 8601 duration format.")] String UserReacceptRequiredFrequency;
    [Write, Description("The acceptance statement included in the agreement.")] String AcceptanceStatement;
    [Write, Description("The content of the agreement file.")] String FileData;
    [Write, Description("The name of the agreement file.")] String FileName;
    [Write, Description("The language of the agreement file.")] String Language;
    [Write, Description("Specify if the agreement should exist or not."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Write, Description("Credentials of the workload's Admin"), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Id of the Azure Active Directory tenant used for authentication.")] String TenantId;
    [Write, Description("Secret of the Azure Active Directory application to authenticate with."), EmbeddedInstance("MSFT_Credential")] String ApplicationSecret;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Managed ID being used for authentication.")] Boolean ManagedIdentity;
    [Write, Description("Access token used for authentication.")] String AccessTokens[];
};