[ClassVersion("1.0.0.0"), FriendlyName("EXOManagementRole")]
class MSFT_EXOManagementRole : OMI_BaseResource
{
    [Key, Description("The Name parameter specifies the name of the role. The maximum length of the name is 64 characters.")] String Name;
    [Key, Description("The Parent parameter specifies the identity of the role to copy. Mandatory for management role creation/update or when Ensure=Present. Non-mandatory for Ensure=Absent")] String Parent;
    [Write, Description("The Description parameter specifies the description that's displayed when the management role is viewed using the Get-ManagementRole cmdlet.")] String Description;
    [Write, Description("Specify if the Management Role should exist or not."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Write, Description("Credentials of the Exchange Global Admin"), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Id of the Azure Active Directory tenant used for authentication.")] String TenantId;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Username can be made up to anything but password will be used for CertificatePassword"), EmbeddedInstance("MSFT_Credential")] String CertificatePassword;
    [Write, Description("Path to certificate used in service principal usually a PFX file.")] String CertificatePath;
    [Write, Description("Managed ID being used for authentication.")] Boolean ManagedIdentity;
    [Write, Description("Access token used for authentication.")] String AccessTokens[];
};
