[ClassVersion("1.0.0.0"), FriendlyName("EXODnssecForVerifiedDomain")]
class MSFT_EXODnssecForVerifiedDomain : OMI_BaseResource
{
    [Key, Description("DomainName parameter specifies the accepted domain in the Exchange Online organization where you want to view information about DNSSEC")] String DomainName;
    [Write, Description("Status of the DnsSec for the given Domain Name."), ValueMap{"Enabled","Disabled","Unknown"}, Values{"Enabled","Disabled","Unknown"}] string DnssecFeatureStatus;

    [Write, Description("Credentials of the workload's Admin"), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Id of the Azure Active Directory tenant used for authentication.")] String TenantId;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Managed ID being used for authentication.")] Boolean ManagedIdentity;
    [Write, Description("Access token used for authentication.")] String AccessTokens[];
};
