
[ClassVersion("1.0.0")]
class MSFT_MicrosoftGraphaccesspackageresourceattribute
{
    [Write, Description("Information about how to set the attribute, currently a accessPackageUserDirectoryAttributeStore object type."), EmbeddedInstance("MSFT_MicrosoftGraphaccesspackageresourceattributedestination")] String AttributeDestination;
    [Write, Description("The name of the attribute in the end system.")] String AttributeName;
    [Write, Description("Information about how to populate the attribute value when an accessPackageAssignmentRequest is being fulfilled, currently a accessPackageResourceAttributeQuestion object type."), EmbeddedInstance("MSFT_MicrosoftGraphaccesspackageresourceattributesource")] String AttributeSource;
    [Write, Description("Id of the access package resource attribute.")] String Id;
    [Write, Description("Specifies whether or not an existing attribute value can be edited by the requester.")] Boolean IsEditable;
    [Write, Description("Specifies whether the attribute will remain in the end system after an assignment ends.")] Boolean IsPersistedOnAssignmentRemoval;
};
[ClassVersion("1.0.0")]
class MSFT_MicrosoftGraphaccesspackageresourceattributedestination
{
    [Write, Description("Type of the access package resource attribute destination."), ValueMap{"#microsoft.graph.accessPackageUserDirectoryAttributeStore"}, Values{"#microsoft.graph.accessPackageUserDirectoryAttributeStore"}] String odataType;

};
[ClassVersion("1.0.0")]
class MSFT_MicrosoftGraphaccesspackageresourceattributesource
{
    [Write, Description("Type of the access package resource attribute source."), ValueMap{"#microsoft.graph.accessPackageResourceAttributeQuestion"}, Values{"#microsoft.graph.accessPackageResourceAttributeQuestion"}] String odataType;
    [Write, Description("The question asked in order to get the value of the attribute."), EmbeddedInstance("MSFT_MicrosoftGraphaccessPackageResourceAttributeQuestion")] String Question;
};

[ClassVersion("1.0.0")]
class MSFT_MicrosoftGraphaccessPackageResourceAttributeQuestion
{
    [Write, Description("Type of the access package resource attribute question."), ValueMap{"#microsoft.graph.accessPackageTextInputQuestion","#microsoft.graph.accessPackageMultipleChoiceQuestion"}, Values{"#microsoft.graph.accessPackageTextInputQuestion","#microsoft.graph.accessPackageMultipleChoiceQuestion"}] String odataType;
    [Write, Description("Id of the access package resource attribute question.")] String Id;
    [Write, Description("Indicates whether the requestor is required to supply an answer or not.")] Boolean IsRequired;
    [Write, Description("Indicates whether the answer will be in single or multiple line format.")] Boolean IsSingleLine;
    [Write, Description("This is the regex pattern that the corresponding text answer must follow.")] String RegexPattern;
    [Write, Description("Relative position of this question when displaying a list of questions to the requestor.")] UInt32 Sequence;
    [Write, Description("The text of the question to show to the requestor."),EmbeddedInstance("MSFT_MicrosoftGraphaccessPackageLocalizedContent")] String QuestionText;
    [Write, Description("Indicates whether requestor can select multiple choices as their answer.")] Boolean AllowsMultipleSelection;
    [Write, Description("List of answer choices."),EmbeddedInstance("MSFT_MicrosoftGraphaccessPackageAnswerChoice")] String Choices[];
};

[ClassVersion("1.0.0")]
class MSFT_MicrosoftGraphaccessPackageLocalizedContent
{
    [Write, Description("The fallback string, which is used when a requested localization is not available. Required.")] String DefaultText;
    [Write, Description("Content represented in a format for a specific locale."),EmbeddedInstance("MSFT_MicrosoftGraphaccessPackageLocalizedText")] String LocalizedTexts[];
};

[ClassVersion("1.0.0")]
class MSFT_MicrosoftGraphaccessPackageLocalizedText
{
    [Write, Description("The text in the specific language. Required.")] String Text;
    [Write, Description("The ISO code for the intended language. Required.")] String LanguageCode;
};

[ClassVersion("1.0.0")]
class MSFT_MicrosoftGraphaccessPackageAnswerChoice
{
    [Write, Description("The actual value of the selected choice. This is typically a string value which is understandable by applications. Required.")] String ActualValue;
    [Write, Description("The localized display values shown to the requestor and approvers. Required."),EmbeddedInstance("MSFT_MicrosoftGraphaccessPackageLocalizedContent")] String displayValue;
};

[ClassVersion("1.0.0.0"), FriendlyName("AADEntitlementManagementAccessPackageCatalogResource")]
class MSFT_AADEntitlementManagementAccessPackageCatalogResource : OMI_BaseResource
{
    [Key, Description("The display name of the resource, such as the application name, group name or site name.")] String DisplayName;
    [Write, Description("Id of the access package catalog resource.")] String Id;
    [Write, Description("The unique ID of the access package catalog.")] String CatalogId;
    [Write, Description("The name of the user or application that first added this resource. Read-only.")] String AddedBy;
    [Write, Description("The Timestamp type represents date and time information using ISO 8601 format and is always in UTC time. For example, midnight UTC on Jan 1, 2014 is 2014-01-01T00:00:00Z. Read-only.")] String AddedOn;
    [Write, Description("Contains information about the attributes to be collected from the requestor and sent to the resource application."), EmbeddedInstance("MSFT_MicrosoftGraphaccesspackageresourceattribute")] String Attributes[];
    [Write, Description("A description for the resource.")] String Description;
    [Write, Description("True if the resource is not yet available for assignment. Read-only.")] Boolean IsPendingOnboarding;
    [Write, Description("The unique identifier of the resource in the origin system. In the case of an Azure AD group, this is the identifier of the group.")] String OriginId;
    [Write, Description("The type of the resource in the origin system.")] String OriginSystem;
    [Write, Description("The type of the resource.")] String ResourceType;
    [Write, Description("A unique resource locator for the resource, such as the URL for signing a user into an application.")] String Url;
    [Write, Description("Present ensures the policy exists, absent ensures it is removed."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] string Ensure;
    [Write, Description("Credentials of the Intune Admin"), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Id of the Azure Active Directory tenant used for authentication.")] String TenantId;
    [Write, Description("Secret of the Azure Active Directory tenant used for authentication."), EmbeddedInstance("MSFT_Credential")] String ApplicationSecret;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Managed ID being used for authentication.")] Boolean ManagedIdentity;
    [Write, Description("Access token used for authentication.")] String AccessTokens[];
};
