[ClassVersion("1.0.0.0"), FriendlyName("SCDeviceConditionalAccessPolicy")]
class MSFT_SCDeviceConditionalAccessPolicy : OMI_BaseResource
{
    [Key, Description("The name of the Device Conditional Access Policy.")] String Name;
    [Write, Description("Specify if this policy should exist or not."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Write, Description("The Comment parameter specifies an optional comment.")] String Comment;
    [Write, Description("The Enabled parameter specifies whether the policy is enabled.")] Boolean Enabled;
    [Write, Description("Credentials of Security and Compliance Center Admin"), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Id of the Azure Active Directory tenant used for authentication.")] String TenantId;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Username can be made up to anything but password will be used for CertificatePassword"), EmbeddedInstance("MSFT_Credential")] String CertificatePassword;
    [Write, Description("Path to certificate used in service principal usually a PFX file.")] String CertificatePath;
    [Write, Description("Access token used for authentication.")] String AccessTokens[];
};
