[ClassVersion("1.0.0.0"), FriendlyName("SCComplianceSearch")]
class MSFT_SCComplianceSearch : OMI_BaseResource
{
    [Key, Description("The Name parameter specifies the unique name of the complaiance tag.")] String Name;
    [Write, Description("Compliance Case (eDiscovery) that this Search is associated with")] String Case;
    [Write, Description("The AllowNotFoundExchangeLocationsEnabled parameter specifies whether to include mailboxes other than regular user mailboxes in the compliance search.")] Boolean AllowNotFoundExchangeLocationsEnabled;
    [Write, Description("The ContentMatchQuery parameter specifies a content search filter. This parameter uses a text search string or a query that's formatted by using the Keyword Query Language (KQL).")] String ContentMatchQuery;
    [Write, Description("The Description parameter specifies an optional description for the compliance search. If the value contains spaces, enclose the value in quotation marks.")] String Description;
    [Write, Description("The ExchangeLocation parameter specifies the mailboxes to include.")] String ExchangeLocation[];
    [Write, Description("This parameter specifies the mailboxes to exclude when you use the value All for the ExchangeLocation parameter.")] String ExchangeLocationExclusion[];
    [Write, Description("The HoldNames parameter specifies that the content locations that have been placed on hold in the specified eDiscovery case will be searched. You use the value All for this parameter. You also need to specify the name of an eDiscovery case by using the Case parameter.")] String HoldNames[];
    [Write, Description("The IncludeUserAppContent parameter specifies that you want to search the cloud-based storage location for users who don't have a regular Office 365 user account in your organization. These types of users include users without an Exchange Online license who use Office applications, Office 365 guest users, and on-premises users whose identity is synchronized with your Office 365 organization.")] Boolean IncludeUserAppContent;
    [Write, Description("The Language parameter specifies the language for the compliance search. Valid input for this parameter is a supported culture code value from the Microsoft .NET Framework CultureInfo class. For example, da-DK for Danish or ja-JP for Japanese.")] String Language;
    [Write, Description("The PublicFolderLocation parameter specifies that you want to include all public folders in the search. You use the value All for this parameter.")] String PublicFolderLocation[];
    [Write, Description("The SharePointLocation parameter specifies the SharePoint Online sites to include. You identify the site by its URL value, or you can use the value All to include all sites.")] String SharePointLocation[];
    [Write, Description("This parameter specifies the SharePoint Online sites to exclude when you use the value All for the SharePointLocation parameter. You identify the site by its URL value.")] String SharePointLocationExclusion[];
    [Write, Description("Specify if this search should exist or not."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Write, Description("Credentials of the Global Admin Account"), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Id of the Azure Active Directory tenant used for authentication.")] String TenantId;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Username can be made up to anything but password will be used for CertificatePassword"), EmbeddedInstance("MSFT_Credential")] String CertificatePassword;
    [Write, Description("Path to certificate used in service principal usually a PFX file.")] String CertificatePath;
    [Write, Description("Access token used for authentication.")] String AccessTokens[];
};
