[ClassVersion("1.0.0.0"), FriendlyName("OneDriveSyncSettings")]
class MSFT_OneDriveSyncSettings : OMI_BaseResource
{
    [Key, Description("The Url of the SharePoint Online Central Administration")] string CentralAdminUrl;
    [Write, Description("Block sync client on Mac")] Boolean BlockMacSync;
    [Write, Description("Disable dialog box")] Boolean DisableReportProblemDialog;
    [Write, Description("Safe domain list")] String DomainGuids[];
    [Write, Description("Block / unblock non domain join workstations ")] Boolean Enabled;
    [Write, Description("Exclude files from being synced to OneDrive")] String ExcludedFileExtensions[];
    [Write, Description("Block old groove client")] String GrooveBlockOption;
    [Required, Description("Credentials of the SharePoint Global Admin"), EmbeddedInstance("MSFT_Credential")] String GlobalAdminAccount;
};

