[ClassVersion("1.0.0.0"), FriendlyName("EXODataEncryptionPolicy")]
class MSFT_EXODataEncryptionPolicy : OMI_BaseResource
{
    [Key, Description("The Identity parameter specifies the data encryption policy that you want to modify.")] String Identity;
    [Write, Description("The AzureKeyIDs parameter specifies the URI values of the Azure Key Vault keys to associate with the data encryption policy.")] String AzureKeyIDs[];
    [Write, Description("The Description parameter specifies an optional description for the data encryption policy")] String Description;
    [Write, Description("The Enabled parameter enables or disable the data encryption policy.")] Boolean Enabled;
    [Write, Description("The Name parameter specifies the unique name for the data encryption policy.")] String Name;
    [Write, Description("The PermanentDataPurgeContact parameter specifies a contact for the purge of all data that's encrypted by the data encryption policy.")] String PermanentDataPurgeContact;
    [Write, Description("The PermanentDataPurgeReason parameter specifies a descriptive reason for the purge of all data that's encrypted by the data encryption policy")] String PermanentDataPurgeReason;
    [Write, Description("Specifies if this policy should exist."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Write, Description("Credentials of the Exchange Global Admin"), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Id of the Azure Active Directory tenant used for authentication.")] String TenantId;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Username can be made up to anything but password will be used for CertificatePassword"), EmbeddedInstance("MSFT_Credential")] String CertificatePassword;
    [Write, Description("Path to certificate used in service principal usually a PFX file.")] String CertificatePath;
    [Write, Description("Managed ID being used for authentication.")] Boolean ManagedIdentity;
    [Write, Description("Access token used for authentication.")] String AccessTokens[];
};
