[ClassVersion("1.0.0.0"), FriendlyName("EXOOnPremisesOrganization")]
class MSFT_EXOOnPremisesOrganization : OMI_BaseResource
{
    [Key, Description("The Identity parameter specifies the identity of the on-premises organization object.")] String Identity;
    [Write, Description("The HybridDomains parameter specifies the domains that are configured in the hybrid deployment between an Office 365 tenant and an on-premises Exchange organization. The domains specified in this parameter must match the domains listed in the HybridConfiguration Active Directory object for the on-premises Exchange organization configured by the Hybrid Configuration wizard. ")] String HybridDomains[];
    [Write, Description("The InboundConnector parameter specifies the name of the inbound connector configured on the Microsoft Exchange Online Protection (EOP) service for a hybrid deployment configured with an on-premises Exchange organization.")] String InboundConnector;
    [Write, Description("The OutboundConnector parameter specifies the name of the outbound connector configured on the EOP service for a hybrid deployment configured with an on-premises Exchange organization.")] String OutboundConnector;
    [Write, Description("The OrganizationName parameter specifies the Active Directory object name of the on-premises Exchange organization.")] String OrganizationName;
    [Write, Description("The OrganizationGuid parameter specifies the globally unique identifier (GUID) of the on-premises Exchange organization object in the Office 365 tenant.")] String OrganizationGuid;
    [Write, Description("The OrganizationRelationship parameter specifies the organization relationship configured by the Hybrid Configuration wizard on the Office 365 tenant as part of a hybrid deployment with an on-premises Exchange organization. This organization relationship defines the federated sharing features enabled on the Office 365 tenant.")] String OrganizationRelationship;
    [Write, Description("The Comment parameter specifies an optional comment.")] String Comment;
    [Write, Description("Specify if the On-Premises Organization should exist or not."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Required, Description("Credentials of the Exchange Global Admin"), EmbeddedInstance("MSFT_Credential")] string GlobalAdminAccount;
};
