[ClassVersion("1.0.0.0"), FriendlyName("SCRecordReviewNotificationTemplateConfig")]
class MSFT_SCRecordReviewNotificationTemplateConfig : OMI_BaseResource
{
    [Key, Description("Specifies the resource is a single instance, the value must be 'Yes'"),ValueMap{"Yes"},Values{"Yes"}] String IsSingleInstance;
    [Write, Description("The CustomizedNotificationDataString parameter specifies the customized review notification text to use. If the value contains spaces, enclose the value in quotation marks.")] String CustomizedNotificationDataString;
    [Write, Description("The CustomizedReminderDataString parameter specifies the customized review reminder text to use. If the value contains spaces, enclose the value in quotation marks.")] String CustomizedReminderDataString;
    [Write, Description("The IsCustomizedNotificationTemplate switch specifies whether to use a customized review notification instead of the system default notification.")] Boolean IsCustomizedNotificationTemplate;
    [Write, Description("The IsCustomizedReminderTemplate switch specifies whether to use a customized review reminder instead of the system default reminder.")] Boolean IsCustomizedReminderTemplate;
    [Write, Description("Credentials of the workload's Admin"), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Id of the Azure Active Directory tenant used for authentication.")] String TenantId;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Managed ID being used for authentication.")] Boolean ManagedIdentity;
    [Write, Description("Access token used for authentication.")] String AccessTokens[];
};
