[ClassVersion("1.0.0.0"), FriendlyName("SCSupervisoryReviewRule")]
class MSFT_SCSupervisoryReviewRule : OMI_BaseResource
{
    [Key, Description("The Name parameter specifies the unique name for the supervisory review policy. The name can't exceed 64 characters. If the value contains spaces, enclose the value in quotation marks.")] String Name;
    [Key, Description("The Policy parameter specifies the supervisory review policy that's assigned to the rule. You can use any value that uniquely identifies the policy.")] String Policy;
    [Write, Description("The Condition parameter specifies the conditions and exceptions for the rule.")] String Condition;
    [Write, Description("The SamplingRate parameter specifies the percentage of communications for review. If you want reviewers to review all detected items, use the value 100.")] UInt32 SamplingRate;
    [Write, Description("Specify if this rule should exist or not."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Write, Description("Credentials of the Exchange Global Admin"), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Id of the Azure Active Directory tenant used for authentication.")] String TenantId;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Username can be made up to anything but password will be used for CertificatePassword"), EmbeddedInstance("MSFT_Credential")] String CertificatePassword;
    [Write, Description("Path to certificate used in service principal usually a PFX file.")] String CertificatePath;
    [Write, Description("Access token used for authentication.")] String AccessTokens[];
};
