[ClassVersion("1.0.0.1"), FriendlyName("AADDomainFederation")]
class MSFT_AADDomainFederation : OMI_BaseResource
{
    [Key, Description("The domain ID for which the federation configuration is being managed.")] String DomainId;
    [Write, Description("The unique identifier of the federation configuration.")] String Id;
    [Write, Description("The display name of the federation configuration.")] String DisplayName;
    [Write, Description("Issuer URI of the federation server.")] String IssuerUri;
    [Write, Description("URI of the metadata exchange endpoint used for authentication.")] String MetadataExchangeUri;
    [Write, Description("Current certificate used to sign tokens passed to the Microsoft identity platform. The certificate is formatted as a Base64 encoded string of the public portion of the federated IdP's token signing certificate.")] String SigningCertificate;
    [Write, Description("Next signing certificate that can be used to sign tokens passed to the Microsoft identity platform. The certificate is formatted as a Base64 encoded string of the public portion of the federated IdP's token signing certificate.")] String NextSigningCertificate;
    [Write, Description("URI that web-based clients are directed to when signing in to Microsoft Entra services.")] String PassiveSignInUri;
    [Write, Description("URI that active clients are directed to when signing in to Microsoft Entra services.")] String ActiveSignInUri;
    [Write, Description("URI to which clients are redirected when signing out of Microsoft Entra services.")] String SignOutUri;
    [Write, Description("Preferred authentication protocol. Supported values are wsFed and saml.")] String PreferredAuthenticationProtocol;
    [Write, Description("Prompt login behavior of the federated IdP.")] String PromptLoginBehavior;
    [Write, Description("Determines whether Microsoft Entra ID accepts the MFA performed by the federated IdP. Supported values are acceptIfMfaDoneByFederatedIdp, enforceMfaByFederatedIdp, rejectMfaByFederatedIdp.")] String FederatedIdpMfaBehavior;
    [Write, Description("URI that clients are redirected to for resetting their password.")] String PasswordResetUri;
    [Write, Description("Specifies whether the federation requires signed authentication requests.")] Boolean IsSignedAuthenticationRequestRequired;
    [Write, Description("Present ensures the instance exists, absent ensures it is removed."), ValueMap{"Absent","Present"}, Values{"Absent","Present"}] string Ensure;
    [Write, Description("Credentials of the workload's Admin"), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Id of the Azure Active Directory tenant used for authentication.")] String TenantId;
    [Write, Description("Secret of the Azure Active Directory application to authenticate with."), EmbeddedInstance("MSFT_Credential")] String ApplicationSecret;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Username can be made up to anything but password will be used for CertificatePassword"), EmbeddedInstance("MSFT_Credential")] String CertificatePassword;
    [Write, Description("Path to certificate used in service principal usually a PFX file.")] String CertificatePath;
    [Write, Description("Managed ID being used for authentication.")] Boolean ManagedIdentity;
    [Write, Description("Access token used for authentication.")] String AccessTokens[];
};
