[ClassVersion("1.0.0.0"), FriendlyName("EXOMailboxAutoReplyConfiguration")]
class MSFT_EXOMailboxAutoReplyConfiguration : OMI_BaseResource
{
    [Key, Description("The Identity parameter specifies the mailbox that you want to modify. You can use any value that uniquely identifies the mailbox.")] String Identity;
    [Write, Description("User Principal Name of the mailbox owner")] String Owner;
    [Write, Description("The AutoDeclineFutureRequestsWhenOOF parameter specifies whether to automatically decline new meeting requests that are sent to the mailbox during the scheduled time period when Automatic Replies are being sent. ")] Boolean AutoDeclineFutureRequestsWhenOOF;
    [Write, Description("The AutoReplyState parameter specifies whether the mailbox is enabled for Automatic Replies. Valid values are: Enabled, Disabled, Scheduled"), ValueMap{"Enabled", "Disabled", "Scheduled"}, Values{"Enabled", "Disabled", "Scheduled"}] String AutoReplyState;
    [Write, Description("The CreateOOFEvent parameter specifies whether to create a calendar event that corresponds to the scheduled time period when Automatic Replies are being sent for the mailbox.")] Boolean CreateOOFEvent;
    [Write, Description("The DeclineAllEventsForScheduledOOF parameter specifies whether to decline all existing calendar events in the mailbox during the scheduled time period when Automatic Replies are being sent.")] Boolean DeclineAllEventsForScheduledOOF;
    [Write, Description("The DeclineEventsForScheduledOOF parameter specifies whether it's possible to decline existing calendar events in the mailbox during the scheduled time period when Automatic Replies are being sent. ")] Boolean DeclineEventsForScheduledOOF;
    [Write, Description("The DeclineMeetingMessage parameter specifies the text in the message when meetings requests that are sent to the mailbox are automatically declined.")] String DeclineMeetingMessage;
    [Write, Description("The EndTime parameter specifies the end date and time that Automatic Replies are sent for the mailbox. You use this parameter only when the AutoReplyState parameter is set to Scheduled, and the value of this parameter is meaningful only when AutoReplyState is Scheduled.")] String EndTime;
    [Write, Description("The EventsToDeleteIDs parameter specifies the calendar events to delete from the mailbox when the DeclineEventsForScheduledOOF parameter is set to $true.")] String EventsToDeleteIDs[];
    [Write, Description("The ExternalAudience parameter specifies whether Automatic Replies are sent to external senders. Valid values are: None, Known, All"), ValueMap{"None", "Known", "All"}, Values{"None", "Known", "All"}] String ExternalAudience;
    [Write, Description("The ExternalMessage parameter specifies the Automatic Replies message that's sent to external senders or senders outside the organization. If the value contains spaces, enclose the value in quotation marks.")] String ExternalMessage;
    [Write, Description("The InternalMessage parameter specifies the Automatic Replies message that's sent to internal senders or senders within the organization. If the value contains spaces, enclose the value in quotation marks.")] String InternalMessage;
    [Write, Description("The OOFEventSubject parameter specifies the subject for the calendar event that's automatically created when the CreateOOFEvent parameter is set to $true.")] String OOFEventSubject;
    [Write, Description("The StartTime parameter specifies the start date and time that Automatic Replies are sent for the specified mailbox. You use this parameter only when the AutoReplyState parameter is set to Scheduled, and the value of this parameter is meaningful only when AutoReplyState is Scheduled.")] String StartTime;
    [Write, Description("Represents the existance of the instance. This must be set to 'Present'"), ValueMap{"Present"}, Values{"Present"}] String Ensure;
    [Write, Description("Credentials of the Exchange Global Admin"), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Id of the Azure Active Directory tenant used for authentication.")] String TenantId;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Username can be made up to anything but password will be used for CertificatePassword"), EmbeddedInstance("MSFT_Credential")] String CertificatePassword;
    [Write, Description("Path to certificate used in service principal usually a PFX file.")] String CertificatePath;
    [Write, Description("Managed ID being used for authentication.")] Boolean ManagedIdentity;
};
