[ClassVersion("1.0.0.0"), FriendlyName("EXOSharingPolicy")]
class MSFT_EXOSharingPolicy : OMI_BaseResource
{
    [Key, Description("The Name parameter specifies the unique name of the sharing policy. The maximum length is 64 characters.")] String Name;
    [Write, Description("The Default switch specifies that the sharing policy is the default sharing policy for all mailboxes.")] Boolean Default;
    [Write, Description("The Enabled parameter specifies whether to enable the sharing policy. Valid values for this parameter are $true or $false.")] Boolean Enabled;
    [Write, Description("The Domains parameter specifies domains to which this policy applies and the sharing policy action.")] String Domains[];
    [Write, Description("Specify if the Sharing Policy should exist or not."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Required, Description("Credentials of the Exchange Global Admin"), EmbeddedInstance("MSFT_Credential")] string GlobalAdminAccount;
};
