[ClassVersion("1.0.0.0"), FriendlyName("EXOPolicyTipConfig")]
class MSFT_EXOPolicyTipConfig : OMI_BaseResource
{
    [Key, Description("The Name parameter specifies the custom Policy Tip you want to modify.")] String Name;
    [Write, Description("The Value parameter specifies the text that's displayed by the Policy Tip.")] String Value;
    [Write, Description("Specify if the Policy Tip Config should exist or not."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Write, Description("Credentials of the Exchange Global Admin"), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Id of the Azure Active Directory tenant used for authentication.")] String TenantId;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Username can be made up to anything but password will be used for CertificatePassword"), EmbeddedInstance("MSFT_Credential")] String CertificatePassword;
    [Write, Description("Path to certificate used in service principal usually a PFX file.")] String CertificatePath;
    [Write, Description("Managed ID being used for authentication.")] Boolean ManagedIdentity;
    [Write, Description("Access token used for authentication.")] String AccessTokens[];
};
