[ClassVersion("1.0.0.0"), FriendlyName("TeamsDialInConferencingTenantSettings")]
class MSFT_TeamsDialInConferencingTenantSettings : OMI_BaseResource
{
    [Key, Description("Only accepted value is Yes."), ValueMap{"Yes"}, Values{"Yes"}] String IsSingleInstance;
    [Write, Description("Specifies the default value that gets assigned to the 'AllowPSTNOnlyMeetings' setting of users when they are enabled for dial-in conferencing, or when a user's dial-in conferencing provider is set to Microsoft. If set to $true, the 'AllowPSTNOnlyMeetings' setting of the user will also be set to true. If $false, the user setting will be false. The default value for AllowPSTNOnlyMeetingsByDefault is $false.")] Boolean AllowPSTNOnlyMeetingsByDefault;
    [Write, Description("Automatically Migrate User Meetings.")] Boolean AutomaticallyMigrateUserMeetings;
    [Write, Description("Automatically replace ACP Provider.")] Boolean AutomaticallyReplaceAcpProvider;
    [Write, Description("Specifies whether advisory emails will be sent to users when the events listed below occur. Setting the parameter to $true enables the emails to be sent, $false disables the emails. The default is $true.")] Boolean AutomaticallySendEmailsToUsers;
    [Write, Description("Enable Dial out join confirmation.")] Boolean EnableDialOutJoinConfirmation;
    [Write, Description("Specifies if, by default, announcements are made as users enter and exit a conference call. Set to $true to enable notifications, $false to disable notifications. The default is $true.")] Boolean EnableEntryExitNotifications;
    [Write, Description("Supported entry and exit announcement type.")] String EntryExitAnnouncementsType;
    [Write, Description("This parameter allows tenant administrators to configure masking of PSTN participant phone numbers in the roster view for Microsoft Teams meetings enabled for Audio Conferencing, scheduled within the organization. Possible values are MaskedForExternalUsers, MaskedForAllUsers or NoMasking"), ValueMap{"MaskedForExternalUsers","MaskedForAllUsers","NoMasking"}, Values{"MaskedForExternalUsers","MaskedForAllUsers","NoMasking"}] String MaskPstnNumbersType;
    [Write, Description("Specifies the number of digits in the automatically generated PINs. Organizers can enter their PIN to start a meeting they scheduled if they join via phone and are the first person to join. The minimum value is 4, the maximum is 12, and the default is 5.")] UInt32 PinLength;
    [Write, Description("Credentials of the Teams Global Admin."), EmbeddedInstance("MSFT_Credential")] String Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Name of the Azure Active Directory tenant used for authentication. Format contoso.onmicrosoft.com")] String TenantId;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Managed ID being used for authentication.")] Boolean ManagedIdentity;
};
