[ClassVersion("1.0.0")]
class MSFT_SCLabelSetting
{
    [Write, Description("Advanced settings key.")] String Key;
    [Write, Description("Advanced settings value.")] String Value[];
};

[ClassVersion("1.0.0.0"), FriendlyName("SCLabelPolicy")]
class MSFT_SCLabelPolicy : OMI_BaseResource
{
    [Key, Description("The Name parameter specifies the unique name for the sensitivity label. The maximum length is 64 characters. If the value contains spaces, enclose the value in quotation marks.")] String Name;
    [Write, Description("Specify if this label policy should exist or not."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Write, Description("The Comment parameter specifies an optional comment.")] String Comment;
    [Write, Description("The AdvancedSettings parameter enables client-specific features and capabilities on the sensitivity label. The settings that you configure with this parameter only affect apps that are designed for the setting."),EmbeddedInstance("MSFT_SCLabelSetting")] String AdvancedSettings[];
    [Write, Description("The ExchangeLocation parameter specifies the mailboxes to include in the policy.")] String ExchangeLocation[];
    [Write, Description("The ExchangeLocationException parameter specifies the mailboxes to exclude when you use the value All for the ExchangeLocation parameter.")] String ExchangeLocationException[];
    [Write, Description("The ModernGroupLocation parameter specifies the Microsoft 365 Groups to include in the policy.")] String ModernGroupLocation[];
    [Write, Description("The ModernGroupLocationException parameter specifies the Microsoft 365 Groups to exclude when you're using the value All for the ModernGroupLocation parameter.")] String ModernGroupLocationException[];
    [Write, Description("The Labels parameter specifies the sensitivity labels that are associated with the policy. You can use any value that uniquely identifies the label.")] String Labels[];
    [Write, Description("The AddExchangeLocation parameter specifies the mailboxes to add in the existing policy.")] String AddExchangeLocation[];
    [Write, Description("The AddExchangeLocationException parameter specifies the mailboxes to add to exclusions when you use the value All for the ExchangeLocation parameter.")] String AddExchangeLocationException[];
    [Write, Description("The AddModernGroupLocation parameter specifies the Microsoft 365 Groups to add to include the policy.")] String AddModernGroupLocation[];
    [Write, Description("The AddModernGroupLocationException parameter specifies the Microsoft 365 Groups to add to exclusions when you're using the value All for the ModernGroupLocation parameter.")] String AddModernGroupLocationException[];
    [Write, Description("The AddLabels parameter specifies the sensitivity labels to add to the policy. You can use any value that uniquely identifies the label.")] String AddLabels[];
    [Write, Description("The RemoveExchangeLocation parameter specifies the mailboxes to remove from the policy.")] String RemoveExchangeLocation[];
    [Write, Description("The RemoveExchangeLocationException parameter specifies the mailboxes to remove when you use the value All for the ExchangeLocation parameter.")] String RemoveExchangeLocationException[];
    [Write, Description("The RemoveModernGroupLocation parameter specifies the Microsoft 365 Groups to remove from the policy.")] String RemoveModernGroupLocation[];
    [Write, Description("The RemoveModernGroupLocationException parameter specifies the Microsoft 365 Groups to remove from excluded values when you're using the value All for the ModernGroupLocation parameter.")] String RemoveModernGroupLocationException[];
    [Write, Description("The RemoveLabels parameter specifies the sensitivity labels that are removed from the policy. You can use any value that uniquely identifies the label.")] String RemoveLabels[];
    [Required, Description("Credentials of the Exchange Global Admin"), EmbeddedInstance("MSFT_Credential")] String GlobalAdminAccount;
};
