[ClassVersion("1.0.0.0"), FriendlyName("TeamsMessageSettings")]
class MSFT_TeamsMessageSettings : OMI_BaseResource
{
    [Key, Description("The Name of the team")] string TeamName;
    [Write, Description("Allow members to edit messages within team.")] Boolean AllowUserEditMessages;
    [Write, Description("Allow members to delete messages within team.")] Boolean AllowUserDeleteMessages;
    [Write, Description("Allow owners to delete messages within team.")] Boolean AllowOwnerDeleteMessages;
    [Write, Description("Allow mentions in team.")] Boolean AllowTeamMentions;
    [Write, Description("Allow channel mention in team.")] Boolean AllowChannelMentions;
    [Write, Description("Placeholder only not used in resource."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Required, Description("Credentials of the Office365 Tenant Admin."), EmbeddedInstance("MSFT_Credential")] string GlobalAdminAccount;
};

