[ClassVersion("1.0.0.0"), FriendlyName("SCFilePlanPropertyReferenceId")]
class MSFT_SCFilePlanPropertyReferenceId : OMI_BaseResource
{
    [Key, Description("The Name parameter specifies the unique name of the reference id.")] String Name;
    [Write, Description("Specify if this reference id should exist or not."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Required, Description("Credentials of the Exchange Global Admin"), EmbeddedInstance("MSFT_Credential")] String GlobalAdminAccount;
};
