[ClassVersion("1.0.0.0"), FriendlyName("AADUserFlowAttribute")]
class MSFT_AADUserFlowAttribute : OMI_BaseResource
{
    [Write, Description("User flow attribute Id.")] String Id;
    [Key, Description("Display name of the user flow attribute.")] String DisplayName;
    [Write, Description("Description of the user flow attribute.")] String Description;
    [Write, Description("Defines the user flow attribute data type.")] String DataType;
    [Write, Description("Specify if the Azure AD role setting should exist or not."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Write, Description("Credentials for the Microsoft Graph delegated permissions."), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Id of the Azure Active Directory tenant used for authentication.")] String TenantId;
    [Write, Description("Secret of the Azure Active Directory application to authenticate with."), EmbeddedInstance("MSFT_Credential")] String ApplicationSecret;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Managed ID being used for authentication.")] Boolean ManagedIdentity;
    [Write, Description("Access token used for authentication.")] String AccessTokens[];
};
