[ClassVersion("1.0.0")]
class MSFT_SCInsiderRiskEntityListDomain
{
    [Required, Description("Domain name.")] String Dmn;
    [Write, Description("Defines if the entry should include multi-level subdomains or not.")] Boolean isMLSubDmn;
    [Write, Description("Type of the Sensitive Information label")] String type;
};

[ClassVersion("1.0.0.0"), FriendlyName("SCInsiderRiskEntityList")]
class MSFT_SCInsiderRiskEntityList : OMI_BaseResource
{
    [Key, Description("")] String Name;
    [Required, Description("")] String ListType;
    [Write, Description("")] String Description;
    [Write, Description("")] String DisplayName;
    [Write, Description(""), EmbeddedInstance("MSFT_SCInsiderRiskEntityListDomain")] String Domains[];
    [Write, Description("")] String FilePaths[];
    [Write, Description("")] String FileTypes[];
    [Write, Description("")] String Keywords[];
    [Write, Description("")] String SensitiveInformationTypes[];
    [Write, Description("")] String Sites[];
    [Write, Description("")] String TrainableClassifiers[];
    [Write, Description("")] String ExceptionKeyworkGroups[];
    [Write, Description("")] String ExcludedClassifierGroups[];
    [Write, Description("")] String ExcludedDomainGroups[];
    [Write, Description("")] String ExcludedFilePathGroup[];
    [Write, Description("")] String ExcludedFileTypeGroups[];
    [Write, Description("")] String ExcludedKeyworkGroups[];
    [Write, Description("")] String ExcludedSensitiveInformationTypeGroups[];
    [Write, Description("")] String ExcludedSiteGroups[];
    [Write, Description("Specify if this entity should exist or not."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Write, Description("Credentials of the workload's Admin"), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Id of the Azure Active Directory tenant used for authentication.")] String TenantId;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Managed ID being used for authentication.")] Boolean ManagedIdentity;
    [Write, Description("Access token used for authentication.")] String AccessTokens[];
};
