[ClassVersion("1.0.0.0"), FriendlyName("SCInsiderRiskEntityList")]
class MSFT_SCInsiderRiskEntityList : OMI_BaseResource
{
    [Key, Description("")] String Name;
    [Required, Description("")] String ListType;
    [Write, Description("")] String Description;
    [Write, Description("")] String DisplayName;
    [Write, Description("Specify if this entity should exist or not."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Write, Description("Credentials of the workload's Admin"), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Id of the Azure Active Directory tenant used for authentication.")] String TenantId;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Managed ID being used for authentication.")] Boolean ManagedIdentity;
    [Write, Description("Access token used for authentication.")] String AccessTokens[];
};
