[ClassVersion("1.0.0")]
class MSFT_SCInsiderRiskEntityListDomain
{
    [Required, Description("Domain name.")] String Dmn;
    [Write, Description("Defines if the entry should include multi-level subdomains or not.")] Boolean isMLSubDmn;
};
[ClassVersion("1.0.0")]
class MSFT_SCInsiderRiskEntityListSite
{
    [Required, Description("Url of the site.")] String Url;
    [Write, Description("Name of the site.")] String Name;
    [Write, Description("Unique identifier of the site.")] String Guid;
};
[ClassVersion("1.0.0.0"), FriendlyName("SCInsiderRiskEntityList")]
class MSFT_SCInsiderRiskEntityList : OMI_BaseResource
{
    [Key, Description("The name of the group or setting.")] String Name;
    [Required, Description("The setting type.")] String ListType;
    [Write, Description("Description for the group or setting.")] String Description;
    [Write, Description("The display name of the group or setting.")] String DisplayName;
    [Write, Description("List of domains"), EmbeddedInstance("MSFT_SCInsiderRiskEntityListDomain")] String Domains[];
    [Write, Description("List of file paths.")] String FilePaths[];
    [Write, Description("List of file types.")] String FileTypes[];
    [Write, Description("List of keywords.")] String Keywords[];
    [Write, Description("List of sensitive information types.")] String SensitiveInformationTypes[];
    [Write, Description("List of sites."), EmbeddedInstance("MSFT_SCInsiderRiskEntityListSite")] String Sites[];
    [Write, Description("List of trainable classifiers.")] String TrainableClassifiers[];
    [Write, Description("List of keywords for exception.")] String ExceptionKeyworkGroups[];
    [Write, Description("List of excluded trainable classifiers.")] String ExcludedClassifierGroups[];
    [Write, Description("List of excluded domains.")] String ExcludedDomainGroups[];
    [Write, Description("List of excluded file paths.")] String ExcludedFilePathGroups[];
    [Write, Description("List of excluded file types.")] String ExcludedFileTypeGroups[];
    [Write, Description("List of excluded keywords.")] String ExcludedKeyworkGroups[];
    [Write, Description("List of excluded sensitive information types.")] String ExcludedSensitiveInformationTypeGroups[];
    [Write, Description("List of excluded sites.")] String ExcludedSiteGroups[];
    [Write, Description("Specify if this entity should exist or not."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Write, Description("Credentials of the workload's Admin"), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Id of the Azure Active Directory tenant used for authentication.")] String TenantId;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Managed ID being used for authentication.")] Boolean ManagedIdentity;
    [Write, Description("Access token used for authentication.")] String AccessTokens[];
};
