[ClassVersion("1.0.0.0"), FriendlyName("AADApplicationFederatedIdentityCredential")]
class MSFT_AADApplicationFederatedIdentityCredential : OMI_BaseResource
{
    [Key, Description("Display name of the Azure AD application that owns the federated identity credential.")] String ApplicationDisplayName;
    [Key, Description("The unique name of the federated identity credential.")] String Name;
    [Write, Description("Object ID of the Azure AD application that owns the federated identity credential.")] String ApplicationObjectId;
    [Write, Description("The unique identifier of the federated identity credential.")] String Id;
    [Write, Description("The issuer URL of the external identity provider.")] String Issuer;
    [Write, Description("The subject identifier of the external workload.")] String Subject;
    [Write, Description("The audiences that can appear in the external token.")] String Audiences[];
    [Write, Description("The description of the federated identity credential.")] String Description;
    [Write, Description("Specify if the federated identity credential should exist or not."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Write, Description("Credentials for the Microsoft Graph delegated permissions."), EmbeddedInstance("MSFT_Credential")] String Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Id of the Azure Active Directory tenant used for authentication.")] String TenantId;
    [Write, Description("Secret of the Azure Active Directory application to authenticate with."), EmbeddedInstance("MSFT_Credential")] String ApplicationSecret;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Username can be made up to anything but password will be used for CertificatePassword."), EmbeddedInstance("MSFT_Credential")] String CertificatePassword;
    [Write, Description("Path to certificate used in service principal usually a PFX file.")] String CertificatePath;
    [Write, Description("Managed ID being used for authentication.")] Boolean ManagedIdentity;
    [Write, Description("Access token used for authentication.")] String AccessTokens[];
};
