[ClassVersion("1.0.0.0"), FriendlyName("AADTenantDetails")]
class MSFT_AADTenantDetails : OMI_BaseResource
{
    [Key, Description("Only valid value is 'Yes'."), ValueMap{"Yes"}, Values{"Yes"}] String IsSingleInstance;
    [Write, Description("Email-addresses from the people who should receive Marketing Notifications")] String MarketingNotificationEmails;
    [Write, Description("Email-addresses from the people who should receive Security Compliance Notifications")] String SecurityComplianceNotificationMails;
    [Write, Description("Phone Numbers from the people who should receive Security Notifications")] String SecurityComplianceNotificationPhones;
    [Write, Description("Email-addresses from the people who should receive Technical Notifications")] String TechnicalNotificationMails ;
    [Write, Description("Credentials of the Azure Active Directory Admin"), EmbeddedInstance("MSFT_Credential")] String GlobalAdminAccount;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Id of the Azure Active Directory tenant used for authentication.")] String TenantId;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
};
