[ClassVersion("1.0.0.1")]
class MSFT_AADGroupLicense
{
    [Write, Description("A collection of the unique identifiers for plans that have been disabled.")] String DisabledPlans[];
    [Required, Description("The unique identifier for the SKU.")] String SkuId;
};

[ClassVersion("1.0.0.1"), FriendlyName("AADGroup")]
class MSFT_AADGroup : OMI_BaseResource
{
    [Key, Description("DisplayName of the Azure Active Directory Group")] String DisplayName;
    [Key, Description("Specifies a mail nickname for the group.")] String MailNickname;
    [Write, Description("Specifies a description for the group.")] String Description;
    [Write, Description("Specifies an ID for the group.")] String Id;
    [Write, Description("User Service Principal values for the group's owners.")] String Owners[];
    [Write, Description("User Service Principal values for the group's members.")] String Members[];
    [Write, Description("Displayname values for the groups member of the group.")] String GroupAsMembers[];
    [Write, Description("DisplayName values for the groups that this group is a member of.")] String MemberOf[];
    [Write, Description("Specifies if the current group is part of a selected Group Lifecycle Policy configuration. Only applicable for Microsoft 365 Groups.")] Boolean GroupLifecyclePolicySelectedEnabled;
    [Write, Description("Specifies the type of the group. To create a security group, leave empty. To create a dynamic membership security group, specify DynamicMembership. To create a Microsoft 365 (aka Unified) group, specify Unified. To create a Microsoft 365 dynamic membership group, specify both Unified and DynamicMembership.")] String GroupTypes[];
    [Write, Description("Specifies the membership rule for a dynamic group.")] String MembershipRule;
    [Write, Description("Specifies the rule processing state. The acceptable values for this parameter are: On. Process the group rule or Paused. Stop processing the group rule."), ValueMap{"On","Paused"}, Values{"On","Paused"}] String MembershipRuleProcessingState;
    [Required, Description("Specifies whether the group is security enabled. For security groups, this value must be $True.")] Boolean SecurityEnabled;
    [Required, Description("Specifies whether this group is mail enabled. Currently, you cannot create mail enabled groups in Microsoft Graph, instead the EXODistributionGroup resource can be used.")] Boolean MailEnabled;
    [Write, Description("Specifies whether this group can be assigned a role. Only available when creating a group and can't be modified after group is created.")] Boolean IsAssignableToRole;
    [Write, Description("DisplayName values for the roles that the group is assigned to.")] String AssignedToRole[];
    [Write, Description("This parameter determines the visibility of the group's content and members list."), ValueMap{"Public","Private","HiddenMembership"}, Values{"Public","Private","HiddenMembership"}] String Visibility;
    [Write, Description("List of Licenses assigned to the group."),EmbeddedInstance("MSFT_AADGroupLicense")] String AssignedLicenses[];
    [Write, Description("Specify if the Azure AD Group should exist or not."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Write, Description("Credentials for the Microsoft Graph delegated permissions."), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Id of the Azure Active Directory tenant used for authentication.")] String TenantId;
    [Write, Description("Secret of the Azure Active Directory application to authenticate with."), EmbeddedInstance("MSFT_Credential")] String ApplicationSecret;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Username can be made up to anything but password will be used for CertificatePassword"), EmbeddedInstance("MSFT_Credential")] String CertificatePassword;
    [Write, Description("Path to certificate used in service principal usually a PFX file.")] String CertificatePath;
    [Write, Description("Managed ID being used for authentication.")] Boolean ManagedIdentity;
    [Write, Description("Access token used for authentication.")] String AccessTokens[];
};
