[ClassVersion("1.0.0.0"), FriendlyName("TeamsM365App")]
class MSFT_TeamsM365App : OMI_BaseResource
{
    [Key, Description("Application ID of Microsoft Teams app.")] String Id;
    [Write, Description("The state of the app in the tenant.")] Boolean IsBlocked;
    [Write, Description("App availability type."), ValueMap{"Everyone","UsersAndGroups","NoOne"}, Values{"Everyone","UsersAndGroups","NoOne"}] String AssignmentType;
    [Write, Description("List of all the users for whom the app is enabled or disabled.")] String Users[];
    [Write, Description("List of all the groups for whom the app is enabled or disabled.")] String Groups[];
    [Write, Description("Credentials of the workload's Admin"), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Id of the Azure Active Directory tenant used for authentication.")] String TenantId;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Managed ID being used for authentication.")] Boolean ManagedIdentity;
    [Write, Description("Access token used for authentication.")] String AccessTokens[];
};
