[ClassVersion("1.0.0.0"), FriendlyName("SPOTenant")]
class MSFT_SPOTenant : OMI_BaseResource
{
    [Key, Description("Name of the tenant")] string Tenant;
    [Write, Description("When the feature is enabled, all guest users are subject to conditional access policy. By default guest users who are accessing SharePoint Online files with pass code are exempt from the conditional access policy.")] boolean ApplyAppEnforcedRestrictionsToAdHocRecipients;
    [Write, Description("When the feature is enabled, all external sharing invitations that are sent will blind copy the e-mail messages listed in the BccExternalSharingsInvitationList.")] boolean BccExternalSharingInvitations;
    [Write, Description("When this feature is set to true, comments on site pages will be disabled")] boolean CommentsOnSitePagesDisabled;
    [Write,ValueMap{"MySites"},Values{"MySites"}, Description("By default Content Type Hub will no longer push content types to OneDrive for Business sites (formerly known as MySites")] string ContentTypeSyncSiteTemplatesList;
    [Write,Description("To disable the ContentTypeSyncSiteTemplatesList once it has been set to MySites, set this parameter to $true")] boolean disableContentTypeSyncSiteTemplatesList;
    [Write,ValueMap{"None","Direct","Internal","AnonymousAccess"},Values{"None","Direct","Internal","AnonymousAccess"}, Description("Lets administrators choose what type of link appears is selected in the “Get a link” sharing dialog box in OneDrive for Business and SharePoint Online")] string DefaultSharingLinkType;
    [Write, Description("Allows administrators prevent certain, specific web parts from being added to pages or rendering on pages on which they were previously added. Only web parts that utilize third-party services (Amazon Kindle, YouTube, Twitter) can be disabled in such a manner")] string DisabledWebPartIds;
    [Write, Description("Prevents the Download button from being displayed on the Virus Found warning page.")] boolean DisallowInfectedFileDownload;
    [Write, Description("Determines whether tenant users see the Start a Site menu option")] boolean DisplayStartASiteOption;
    [Write, Description("Accelerates guest-enabled site collections as well as member-only site collections when the SignInAccelerationDomain parameter is set.")] boolean EnableGuestSignInAcceleration;
    [Write, Description("Enables external services for a tenant.External services are defined as services that are not in the Office 365 datacenters.")] boolean ExternalServicesEnabled;
    [Write,ValueMap{"View","Edit"},Values{"View","Edit"}, Description("Configures anonymous link types for files")] string FileAnonymousLinkType;
    [Write,ValueMap{"View","Edit"},Values{"View","Edit"}, Description("Configures anonymous link types for folders")] string FolderAnonymousLinkType;
    [Write, Description("Configures multiple IP addresses or IP address ranges (IPv4 or IPv6).Use commas to separate multiple IP addresses or IP address ranges.")] string IPAddressAllowList;
    [Write, Description("Allows access from network locations that are defined by an administrator.")] boolean IPAddressEnforcement;
    [Write, Description("Office webapps TokenLifeTime in minutes")] uint32 IPAddressWACTokenLifetime;
    [Write, Description("By default this value is set to True, which means that authentication using legacy protocols is enabled.Setting this parameter to $False prevents Office clients using non-modern authentication protocols from accessing SharePoint Online resources.")] boolean LegacyAuthProtocolsEnabled;
    [Write, Description("Specifies the upper bound on the compatibility level for new sites")] uint32 MaxCompatibilityLevel;
    [Write, Description("Specifies the lower bound on the compatibility level for new sites")] uint32 MinCompatibilityLevel;
    [Write, Description("Specifies the URL of the redirected site for those site collections which have the locked state NoAccess")] string NoAccessRedirectUrl;
    [Write, Description("Setting to enable/disable notifications in OneDrive for business")] boolean NotificationsInOneDriveForBusinessEnabled;
    [Write, Description("Setting to enable/disable notifications in SharePoint")] boolean NotificationsInSharePointEnabled;
    [Write, Description("When this parameter is set to $true and when an external user accepts an invitation to a resource in a user’s OneDrive for Business, the OneDrive for Business owner is notified by e-mail.")] boolean NotifyOwnersWhenInvitationsAccepted;
    [Write, Description("When this parameter is set to $true and another user re-shares a document from a user’s OneDrive for Business, the OneDrive for Business owner is notified by e-mail.")] boolean NotifyOwnersWhenItemsReshared;
    [Write,ValueMap{"On","Off","Unspecified"},Values{"On","Off","Unspecified"}, Description("Lets administrators set policy on access requests and requests to share in OneDrive for Business.")] string ODBAccessRequests;
    [Write,ValueMap{"On","Off","Unspecified"},Values{"On","Off","Unspecified"}, Description("Lets administrators set policy on re-sharing behavior in OneDrive for Business.")] string ODBMembersCanShare;
    [Write, Description("When set to true this will disable the ability to use Modern Authentication that leverages ADAL across the tenant.")] boolean OfficeClientADALDisabled;
    //[Write, Description("Lets OneDrive for Business creation for administrator managed guest users. Administrator managed Guest users use credentials in the resource tenant to access the resources.")] boolean OneDriveForGuestsEnabled;
    //[Write, Description("Sets a default OneDrive for Business storage quota for the tenant. It will be used for new OneDrive for Business sites created.")] uint64 OneDriveStorageQuota;
    [Write, Description("Specifies the number of days after a user's Active Directory account is deleted that their OneDrive for Business content will be deleted. ")] uint32 OrphanedPersonalSitesRetentionPeriod;
    [Write, Description("not documented")] boolean OwnerAnonymousNotification;
    [Write, Description("Enables the Permissive browser file handling. By default, the browser file handling is set to Strict (false).")] boolean PermissiveBrowserFileHandlingOverride;
    [Write, Description("Allow or deny external users re-sharing")] boolean PreventExternalUsersFromResharing;
    [Write, Description("Creates a Shared with Everyone folder in every user's new OneDrive for Business document library.")] boolean ProvisionSharedWithEveryoneFolder;
    [Write, Description("Allowed file types for public CDNs")] string PublicCdnAllowedFileTypes;
    [Write, Description("Enabling or disabling public CDN")] boolean PublicCdnEnabled;
    [Write, Description("Ensures that an external user can only accept an external sharing invitation with an account matching the invited email address.Administrators who desire increased control over external collaborators should consider enabling this feature. False (default) - When a document is shared with an external user, bob@contoso.com, it can be accepted by any user with access to the invitation link in the original e-mail.True - User must accept this invitation with bob@contoso.com.")] boolean RequireAcceptingAccountMatchInvitedAccount;
    [Write, Description("Specifies all anonymous links that have been created (or will be created) will expire after the set number of days .")] uint32 RequireAnonymousLinksExpireInDays;
    [Write, Description("Removes the search capability from People Picker. Note, recently resolved names will still appear in the list until browser cache is cleared or expired. This also does not allow SharePoint users to search for security groups or SharePoint groups.")] boolean SearchResolveExactEmailOrUPN;
    [Write, Description("Specifies a list of email domains that is allowed for sharing with the external collaborators. Use the space character as the delimiter for entering multiple values. For example, “contoso.com fabrikam.com”. ")] string SharingAllowedDomainList;
    [Write, Description("Specifies a list of email domains that is blocked or prohibited for sharing with the external collaborators. Use space character as the delimiter for entering multiple values. For example, “contoso.com fabrikam.com”. ")] string SharingBlockedDomainList;
    [Write,ValueMap{"ExternalUserAndGuestSharing","Disabled","ExternalUserSharingOnly"},Values{"ExternalUserAndGuestSharing","Disabled","ExternalUserSharingOnly"}, Description("Configures anonymous link types for folders")] string SharingCapability;
    [Write,ValueMap{"None","AllowList","BlockList"},Values{"None","AllowList","BlockList"}, Description("Specifies the external sharing mode for domains.")] string SharingDomainRestrictionMode;
    [Write, Description("Enables the administrator to hide the All Users claim groups in People Picker.")] boolean ShowAllUsersClaim;
    [Write, Description("Enables the administrator to hide the Everyone claim in the People Picker.")] boolean ShowEveryoneClaim;
    [Write, Description("Enables the administrator to hide the Everyone except external users claim in the People Picker.")] boolean ShowEveryoneExceptExternalUsersClaim;
    [Write, Description("Enables the administrator to hide the guest users claim in the People Picker.")] boolean ShowPeoplePickerSuggestionsForGuestUsers;
    [Write, Description("Specifies the home realm discovery value to be sent to Azure Active Directory (AAD) during the user sign-in process. <emptystring> (default) - Blank by default, this will also remove or clear any value that has been set.Login Domain - For example: contoso.com")] string SignInAccelerationDomain;
    [Write, Description("Disables or enables the Social Bar.It will give users the ability to like a page, see the number of views, likes, and comments on a page, and see the people who have liked a page.")] boolean SocialBarOnSitePagesDisabled;
    [Write,ValueMap{"Allowed","Disallowed"},Values{"Allowed","Disallowed"}, Description("SPermits the use of special characters in file and folder names in SharePoint Online and OneDrive for Business document libraries. ")] string SpecialCharactersStateInFileFolderNames;
    [Write, Description("Specifies URL of the form to load in the Start a Site dialog.The valid values are:<emptyString> (default) - Blank by default, this will also remove or clear any value that has been set.Full URL - Example: https://contoso.sharepoint.com/path/to/form")] string StartASiteFormUrl;
    [Write, Description("When set to $true, users aren't able to share with security groups or SharePoint groups.")] boolean UseFindPeopleInPeoplePicker;
    [Write, Description("Lets SharePoint issue a special cookie that will allow this feature to work even when Keep Me Signed In is not selected.")] boolean UsePersistentCookiesForExplorerView;
    [Write, Description("When set to $true, the Feedback link will be shown at the bottom of all modern SharePoint Online pages.")] boolean UserVoiceForFeedbackEnabled;
    [Write, Description("Specifies a list of e-mail addresses to be BCC'd when the BCC for External Sharing feature is enabled.Multiple addresses can be specified by creating a comma separated list with no spaces.")] string BccExternalSharingInvitationsList;
    [Write,ValueMap{"View","Edit"},Values{"View","Edit"}, Description("Specifies the link permission on the tenant level.")] string DefaultLinkPermission;
    [Write,ValueMap{"AllowFullAccess", "AllowLimitedAccess", "BlockAccess"},Values{"AllowFullAccess", "AllowLimitedAccess","BlockAccess"}, Description("Specifies the conditional access settings on the tenant level.")] string ConditionalAccessPolicy;
    [Write,ValueMap{"OfficeOnlineFilesOnly","WebPreviewableFiles","OtherFiles"},Values{"OfficeOnlineFilesOnly","WebPreviewableFiles","OtherFiles"},Description("Prevents certain filetypes, that cannot be viewed on the web, from being downloaded.")] string LimitedAccessFileType;
    [Write, Description("Prevents certain filetypes, that cannot be viewed on the web, from being downloaded.")] boolean AllowDownloadingNonWebViewableFiles;
    [Write, Description("Prevents users from editing files in the browser and copying and pasting file contents out of the browser window")] boolean AllowEditing;
    [Write, Description("Enables file picker external image search")] boolean FilePickerExternalImageSearchEnabled;
    [Write, Description("Sets email attestation to required")] boolean EmailAttestationRequired;
    [Write, Description("Syncs privacy profile properties. Allowed values true,false")] boolean SyncPrivacyProfileProperties;
    [Write, Description("Enables minimum version requirement.")] boolean EnableMinimumVersionRequirement;
    [Write, Description("Sets email attestation re-auth days")] uint32 EmailAttestationReAuthDays;
    [Write, Description("Organization news site url")] string OrgNewsSiteUrl;
    [Required,ValueMap{"Present","Absent"},Values{"Present","Absent"}, Description("Specify if the resource should be present or absent.")] string Ensure;
    [Required, Description("The Url of the SharePoint Online Central Administration")] string CentralAdminUrl;
    [Required, Description("Credentials of the SharePoint Global Admin"), EmbeddedInstance("MSFT_Credential")] string GlobalAdminAccount;
};
