[ClassVersion("1.0.0.0"), FriendlyName("TeamsFederationConfiguration")]
class MSFT_TeamsFederationConfiguration : OMI_BaseResource
{
    [Key, Description("The only valid input is Global - the tenant wide configuration"), ValueMap{"Global"}, Values{"Global"}] string Identity;
    [Write, Description("When set to True users will be potentially allowed to communicate with users from other domains.")] Boolean AllowFederatedUsers;
    [Write, Description("List of federated domains to allow.")] String AllowedDomains[];
    [Write, Description("List of federated domains to block.")] String BlockedDomains[];
    [Write, Description("When set to True users will be potentially allowed to communicate with users who have accounts on public IM and presence providers.")] Boolean AllowPublicUsers;
    [Write, Description("Allows federation with people using Teams with an account that's not managed by an organization.")] Boolean AllowTeamsConsumer;
    [Write, Description("Allows people using Teams with an account that's not managed by an organization, to discover and start communication with users in your organization.")] Boolean AllowTeamsConsumerInbound;
    [Write, Description("When set to True, messages sent from discovered partners are considered unverified. That means that those messages will be delivered only if they were sent from a person who is on the recipient's Contacts list.")] Boolean TreatDiscoveredPartnersAsUnverified;
    [Write, Description("When set to True, indicates that the users homed on Skype for Business Online use the same SIP domain as users homed on the on-premises version of Skype for Business Server.")] Boolean SharedSipAddressSpace;
    [Write, Description("When set to True, Teamsconsumer have access only to external user profiles")] Boolean RestrictTeamsConsumerToExternalUserProfiles;
    [Write, Description("Credentials of the Teams Admin"), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Name of the Azure Active Directory tenant used for authentication. Format contoso.onmicrosoft.com")] String TenantId;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Managed ID being used for authentication.")] Boolean ManagedIdentity;
    [Write, Description("Access token used for authentication.")] String AccessTokens[];
};
