[ClassVersion("1.0.0.0"), FriendlyName("EXOMailboxIRMAccess")]
class MSFT_EXOMailboxIRMAccess : OMI_BaseResource
{
    [Key, Description("The Identity parameter specifies the mailbox that you want to modify")] String Identity;
    [Key, Description("The User parameter specifies the delegate who is blocked from reading IRM-protected messages in the mailbox.")] String User;
    [Write, Description("The AccessLevel parameter specifies what delegates can do to IRM-protected messages in the mailbox that's specified by the Identity parameter."), ValueMap{"Block"}, Values{"Block"}] string AccessLevel;
    [Write, Description("Present ensures the resource exists, absent ensures it is removed"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] string Ensure;
    [Write, Description("Credentials of the workload's Admin"), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Id of the Azure Active Directory tenant used for authentication.")] String TenantId;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Managed ID being used for authentication.")] Boolean ManagedIdentity;
    [Write, Description("Access token used for authentication.")] String AccessTokens[];
};
