[ClassVersion("1.0.0.0"), FriendlyName("AADB2CAuthenticationMethodsPolicy")]
class MSFT_AADB2CAuthenticationMethodsPolicy : OMI_BaseResource
{
    [Key, Description("Only valid value is 'Yes'."), ValueMap{"Yes"}, Values{"Yes"}] String IsSingleInstance;
    [Write, Description("The tenant admin can configure local accounts using email if the email and password authentication method is enabled.")] Boolean IsEmailPasswordAuthenticationEnabled;
    [Write, Description("The tenant admin can configure local accounts using username if the username and password authentication method is enabled.")] Boolean IsUserNameAuthenticationEnabled;
    [Write, Description("The tenant admin can configure local accounts using phone number if the phone number and one-time password authentication method is enabled.")] Boolean IsPhoneOneTimePasswordAuthenticationEnabled;

    [Write, Description("Present ensures the instance exists, absent ensures it is removed."), ValueMap{"Absent","Present"}, Values{"Absent","Present"}] string Ensure;
    [Write, Description("Credentials of the workload's Admin"), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Id of the Azure Active Directory tenant used for authentication.")] String TenantId;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Managed ID being used for authentication.")] Boolean ManagedIdentity;
    [Write, Description("Access token used for authentication.")] String AccessTokens[];
};
