[ClassVersion("1.0.0.1"), FriendlyName("TeamsCallingPolicy")]
class MSFT_TeamsCallingPolicy : OMI_BaseResource
{
    [Key, Description("Identity of the Teams Calling Policy.")] String Identity;
    [Write, Description("Description of the Teams Calling Policy.")] String Description;
    [Write, Description("Enables the user to use the AI Interpreter related features. Possible values are: Disabled, Enabled"), ValueMap{"Disabled","Enabled"}, Values{"Disabled","Enabled"}] String AIInterpreter;
    [Write, Description("The maximum amount a user can spend on outgoing PSTN calls, including all calls made through Pay-as-you-go Calling Plans and any overages on plans with bundled minutes.")] UInt32 CallingSpendUserLimit;
    [Write, Description("Setting this parameter lets you control how Copilot is used during calls and if transcription is needed to be turned on and saved after the call. Possible values: Enabled, EnabledWithTranscript, Disabled"), ValueMap{"Enabled","EnabledWithTranscript","Disabled"}, Values{"Enabled","EnabledWithTranscript","Disabled"}] String Copilot;
    [Write, Description("This setting allows an admin to enable or disable spend limits on PSTN calls for their user base.")] Boolean EnableSpendLimits;
    [Write, Description("Determines if MediaBypass is enabled for PSTN calls on specified Web platforms.")] Boolean EnableWebPstnMediaBypass;
    [Write, Description("This setting controls whether users must provide or obtain explicit consent before recording a 1:1 PSTN or Teams call. When enabled, both parties will receive a notification, and consent must be given before recording starts. Possible values: Enabled: Requires users to give and obtain explicit consent before starting a call recording. Disabled: Users are not required to obtain explicit consent before recording starts."), ValueMap{"Disabled","Enabled"}, Values{"Disabled","Enabled"}] String ExplicitRecordingConsent;
    [Write, Description("Setting this parameter lets you control how inbound federated calls should be routed. Possible values are: RegularIncoming, Unanswered, Voicemail."), ValueMap{"RegularIncoming","Unanswered","Voicemail"}, Values{"RegularIncoming","Unanswered","Voicemail"}] String InboundFederatedCallRoutingTreatment;
    [Write, Description("Setting this parameter lets you control how inbound PSTN calls should be routed. Possible values are: RegularIncoming, Unanswered, Voicemail, UserOverride."), ValueMap{"RegularIncoming","Unanswered","Voicemail","UserOverride"}, Values{"RegularIncoming","Unanswered","Voicemail","UserOverride"}] String InboundPstnCallRoutingTreatment;
    [Write, Description("Setting this parameter allows you to set the PopoutForIncomingPstnCalls setting's URL path of the website to launch upon receiving incoming PSTN calls. This parameter accepts an HTTPS URL with less than 1024 characters. The URL can contain a {phone} placeholder that is replaced with the caller's PSTN number in E.164 format when launched.")] String PopoutAppPathForIncomingPstnCalls;
    [Write, Description("Setting this parameter allows you to control the tenant users' ability to launch an external website URL automatically in the browser window upon incoming PSTN calls for specific users or user groups. Possible values are: Enabled, Disabled."), ValueMap{"Disabled","Enabled"}, Values{"Disabled","Enabled"}] String PopoutForIncomingPstnCalls;
    [Write, Description("Allows users to use real time text during a call, allowing them to communicate by typing their messages in real time. Possible values are: Disabled, Enabled"), ValueMap{"Disabled","Enabled"}, Values{"Disabled","Enabled"}] String RealTimeText;
    [Write, Description("Controls if Teams calls are shown in the call log.")] Boolean ShowTeamsCallsInCallLog;
    [Write, Description("Enables the user to use the voice simulation feature while being AI interpreted. Possible values are: Disabled, Enabled"), ValueMap{"Disabled","Enabled"}, Values{"Disabled","Enabled"}] String VoiceSimulationInInterpreter;
    [Write, Description("Controls all calling capabilities in Teams. Turning this off will turn off all calling functionality in Teams. If you use Skype for Business for calling, this policy will not affect calling functionality in Skype for Business.")] Boolean AllowPrivateCalling;
    [Write, Description("Enables inbound calls to be routed to voice mail. Valid options are: AlwaysEnabled, AlwaysDisabled, UserOverride."), ValueMap{"AlwaysEnabled","AlwaysDisabled","UserOverride"}, Values{"AlwaysEnabled","AlwaysDisabled","UserOverride"}] String AllowVoicemail;
    [Write, Description("Enables inbound calls to be routed to call groups.")] Boolean AllowCallGroups;
    [Write, Description("Enables inbound calls to be routed to delegates; allows delegates to make outbound calls on behalf of the users for whom they have delegated permissions.")] Boolean AllowDelegation;
    [Write, Description("Enables call forwarding or simultaneous ringing of inbound calls to other users in your tenant.")] Boolean AllowCallForwardingToUser;
    [Write, Description("Enables call forwarding or simultaneous ringing of inbound calls to any phone number.")] Boolean AllowCallForwardingToPhone;
    [Write, Description("Setting this parameter provides the ability to configure call redirection capabilities on Teams phones."), ValueMap{"Enabled","Disabled","UserOverride"}, Values{"Enabled","Disabled","UserOverride"}] String AllowCallRedirect;
    [Write, Description("Determines whether the user is allowed to use SIP devices for calling on behalf of a Teams client.")] Boolean AllowSIPDevicesCalling;
    [Write, Description("Allows PSTN calling from the Team web client")] Boolean AllowWebPSTNCalling;
    [Write, Description("Setting this parameter to True will send calls through PSTN and incur charges rather than going through the network and bypassing the tolls.")] Boolean PreventTollBypass;
    [Write, Description("Setting this parameter lets you configure how incoming calls are handled when a user is already in a call or conference or has a call placed on hold. New or incoming calls will be rejected with a busy signal. Valid options are: Enabled, Disabled and Unanswered."), ValueMap{"Enabled","Disabled","Unanswered","UserOverride"}, Values{"Enabled","Disabled","Unanswered","UserOverride"}] String BusyOnBusyEnabledType;
    [Write, Description("Sets the expiration of the recorded 1:1 calls.")] UInt32 CallRecordingExpirationDays;
    [Write, Description("Setting this parameter allows you to turn on or turn off music on hold when a PSTN caller is placed on hold. It is turned on by default. Valid options are: Enabled, Disabled, UserOverride. For now setting the value to UserOverride is the same as Enabled. This setting does not apply to call park and SLA boss delegate features. Valid options are: Enabled, Disabled, UserOverride."), ValueMap{"Enabled","Disabled","UserOverride"}, Values{"Enabled","Disabled","UserOverride"}] String MusicOnHoldEnabledType;
    [Write, Description("This parameter is not available for use. Valid options are: Enabled, Disabled, UserOverride."), ValueMap{"Enabled","Disabled","UserOverride"}, Values{"Enabled","Disabled","UserOverride"}] String SafeTransferEnabled;
    [Write, Description("Setting this parameter to True will allows 1:1 Calls to be recorded.")] Boolean AllowCloudRecordingForCalls;
    [Write, Description("Determines whether post-meeting captions and transcriptions are allowed in a user's meetings. Set this to TRUE to allow. Set this to FALSE to prohibit.")] Boolean AllowTranscriptionforCalling;
    [Write, Description("Determines whether real-time captions are available for the user in Teams meetings. Set this to DisabledUserOverride to allow user to turn on live captions. Set this to Disabled to prohibit."), ValueMap{"DisabledUserOverride", "Disabled"}, Values{"DisabledUserOverride", "Disabled"}] String LiveCaptionsEnabledTypeForCalling;
    [Write, Description("This setting allows the tenant admin to enable or disable the Auto-Answer setting. Valid options are: Enabled, Disabled."), ValueMap{"Enabled","Disabled"}, Values{"Enabled","Disabled"}] String AutoAnswerEnabledType;
    [Write, Description("Setting this parameter determines whether calls identified as Spam will be rejected or not (probably). Valid options are: Enabled, Disabled."), ValueMap{"Enabled","Disabled"}, Values{"Enabled","Disabled"}] String SpamFilteringEnabledType;
    [Write, Description("Present ensures the policyexists, absent ensures it is removed."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Write, Description("Credentials of the Teams Admin."), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Name of the Azure Active Directory tenant used for authentication. Format contoso.onmicrosoft.com")] String TenantId;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Managed ID being used for authentication.")] Boolean ManagedIdentity;
    [Write, Description("Access token used for authentication.")] String AccessTokens[];
};
