[ClassVersion("1.0.0.0"), FriendlyName("EXOSafeAttachmentPolicy")]
class MSFT_EXOSafeAttachmentPolicy : OMI_BaseResource
{
    [Key, Description("The Identity parameter specifies the name of the SafeAttachmentpolicy that you want to modify.")] String Identity;
    [Write, Description("The Action parameter specifies the action for the Safe Attachments policy."), ValueMap{"Block","Replace","Allow","DynamicDelivery"}, Values{"Block","Replace","Allow","DynamicDelivery"}] String Action;
    [Write, Description("The ActionOnError parameter specifies the error handling option for Safe Attachments scanning (what to do if scanning times out or an error occurs). Valid values are: $true: The action specified by the Action parameter is applied to messages even when the attachments aren't successfully scanned. $false: The action specified by the Action parameter isn't applied to messages when the attachments aren't successfully scanned. This is the default value.")] Boolean ActionOnError;
    [Write, Description("The AdminDisplayName parameter specifies a description for the policy.")] String AdminDisplayName;
    [Write, Description("Specify if this policy should be enabled. Default is $true.")] Boolean Enable;
    [Write, Description("The Redirect parameter specifies whether to send detected malware attachments to another email address. Valid values are: $true: Malware attachments are sent to the email address specified by the RedirectAddress parameter. $false: Malware attachments aren't sent to another email address. This is the default value.")] Boolean Redirect;
    [Write, Description("The RedirectAddress parameter specifies the email address where detected malware attachments are sent when the Redirect parameter is set to the value $true.")] String RedirectAddress;
    [Write, Description("Specify if this policy should exist or not."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Required, Description("Credentials of the Exchange Global Admin"), EmbeddedInstance("MSFT_Credential")] String GlobalAdminAccount;
};
