[ClassVersion("1.0.0.0")]
class MSFT_AzureBillingAccountPolicyEnterpriseAgreementPolicy
{
    [Write, Description("The policy that controls whether account owner can view charges.")] String accountOwnerViewCharges;
    [Write, Description("The state showing the enrollment auth level.")] String authenticationType;
    [Write, Description("The policy that controls whether department admin can view charges.")] String departmentAdminViewCharges;
};
[ClassVersion("1.0.0.0"), FriendlyName("AzureBillingAccountPolicy")]
class MSFT_AzureBillingAccountPolicy : OMI_BaseResource
{
    [Key, Description("Unique identifier of the associated billing account.")] String BillingAccount;
    [Write, Description("Name of the policy.")] String Name;
    [Write, Description("The policies for Enterprise Agreement enrollments."), EmbeddedInstance("MSFT_AzureBillingAccountPolicyEnterpriseAgreementPolicy")] String EnterpriseAgreementPolicies;
    [Write, Description("The policy that controls whether Azure marketplace purchases are allowed.")] String MarketplacePurchases;
    [Write, Description("The policy that controls whether Azure reservation purchases are allowed.")] String ReservationPurchases;
    [Write, Description("The policy that controls whether users with Azure savings plan purchase are allowed.")] String SavingsPlanPurchases;

    [Write, Description("Present ensures the instance exists, absent ensures it is removed."), ValueMap{"Absent","Present"}, Values{"Absent","Present"}] string Ensure;
    [Write, Description("Credentials of the workload's Admin"), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Id of the Azure Active Directory tenant used for authentication.")] String TenantId;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Managed ID being used for authentication.")] Boolean ManagedIdentity;
    [Write, Description("Access token used for authentication.")] String AccessTokens[];
};
