[ClassVersion("1.0.0.0"), FriendlyName("PPPowerAppsEnvironment")]
class MSFT_PPPowerAppsEnvironment : OMI_BaseResource
{
    [Key, Description("Display name for the PowerApps environment")] String DisplayName;
    [Required, Description("Location of the PowerApps environment."), ValueMap{"canada","unitedstates","europe","asia","australia","india","japan","unitedkingdom","unitedstatesfirstrelease","southamerica","france","usgov"}, Values{"canada","unitedstates","europe","asia","australia","india","japan","unitedkingdom","unitedstatesfirstrelease","southamerica","france","usgov"}] string Location;
    [Required, Description("Environment type."), ValueMap{"Production","Standard","Trial","Sandbox"}, Values{"Production","Standard","Trial","Sandbox"}] String EnvironmentSKU;

    [Write, Description("Only accepted value is 'Present'."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Required, Description("Credentials of the Azure Active Directory Global Admin"), EmbeddedInstance("MSFT_Credential")] string GlobalAdminAccount;
};
