[ClassVersion("1.0.0.0"), FriendlyName("TeamsUserPolicyAssignment")]
class MSFT_TeamsUserPolicyAssignment : OMI_BaseResource
{
    [Key, Description("User Principal Name of the user representing the policy assignments.")] string User;
    [Write, Description("Name of the Calling Line Policy.")] String CallingLineIdentity;
    [Write, Description("Name of the External Access Policy.")] String ExternalAccessPolicy;
    [Write, Description("Name of the Online Voicemail Policy.")] String OnlineVoicemailPolicy;
    [Write, Description("Name of the Online VOice Routing Policy.")] String OnlineVoiceRoutingPolicy;
    [Write, Description("Name of the Teams App Permission Policy.")] String TeamsAppPermissionPolicy;
    [Write, Description("Name of the Teams App Setup Policy.")] String TeamsAppSetupPolicy;
    [Write, Description("Name of the Teams Audio Conferencing Policy.")] String TeamsAudioConferencingPolicy;
    [Write, Description("Name of the Teams Call Hold Policy.")] String TeamsCallHoldPolicy;
    [Write, Description("Name of the Teams Calling Policy.")] String TeamsCallingPolicy;
    [Write, Description("Name of the Teams Call Park Policy.")] String TeamsCallParkPolicy;
    [Write, Description("Name of the Teams Channel Policy.")] String TeamsChannelsPolicy;
    [Write, Description("Name of the Teams Emergency Calling Policy.")] String TeamsEmergencyCallingPolicy;
    [Write, Description("Name of the Teams Emergency Call Routing Policy.")] String TeamsEmergencyCallRoutingPolicy;
    [Write, Description("Name of the Teams Enhanced Encryption Policy.")] String TeamsEnhancedEncryptionPolicy;
    [Write, Description("Name of the Teams Events Policy.")] String TeamsEventsPolicy;
    [Write, Description("Name of the Teams Meeting Broadcast Policy.")] String TeamsMeetingBroadcastPolicy;
    [Write, Description("Name of the Teams Meeting Policy.")] String TeamsMeetingPolicy;
    [Write, Description("Name of the Teams Messaging Policy.")] String TeamsMessagingPolicy;
    [Write, Description("Name of the Teams Mobility Policy.")] String TeamsMobilityPolicy;
    [Write, Description("Name of the Teams Update Management Policy.")] String TeamsUpdateManagementPolicy;
    [Write, Description("Name of the Teams Upgrade Policy.")] String TeamsUpgradePolicy;
    [Write, Description("Name of the Tenant Dial Plan Policy.")] String TenantDialPlan;
    [Write, Description("Credentials of the Teams Admin"), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Id of the Azure Active Directory tenant used for authentication.")] String TenantId;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Managed ID being used for authentication.")] Boolean ManagedIdentity;
    [Write, Description("Access token used for authentication.")] String AccessTokens[];
};
