[ClassVersion("1.0.0.0"), FriendlyName("SPOSite")]
class MSFT_SPOSite : OMI_BaseResource
{
    [Key, Description("The URL of the site collection.")] string Url;
    [Required, Description("The title of the site collection.")] string Title;
    [Required, Description("Specifies the owner of the site.")] string Owner;
    [Required, Description("TimeZone ID of the site collection.")] uint32 TimeZoneId;
    [Write, Description("Specifies with template of site to create.")] string Template;
    [Write, Description("The URL of the Hub site the site collection needs to get connected to.")] string HubUrl;
    [Write, Description("Disables Microsoft Flow for this site.")] boolean DisableFlows;
    [Write, Description("Specifies what the sharing capabilities are for the site. Possible values: Disabled, ExternalUserSharingOnly, ExternalUserAndGuestSharing, ExistingExternalUserSharingOnly."), ValueMap{"Disabled", "ExistingExternalUserSharingOnly", "ExternalUserSharingOnly", "ExternalUserAndGuestSharing"}, Values{"Disabled", "ExistingExternalUserSharingOnly", "ExternalUserSharingOnly", "ExternalUserAndGuestSharing"}] string SharingCapability;
    [Write, Description("Specifies the storage quota for this site collection in megabytes. This value must not exceed the company's available quota.")] uint32 StorageMaximumLevel;
    [Write, Description("Specifies the warning level for the storage quota in megabytes. This value must not exceed the values set for the StorageMaximumLevel parameter.")] uint32 StorageWarningLevel;
    [Write, Description("Specifies if the site administrator can upgrade the site collection.")] boolean AllowSelfServiceUpgrade;
    [Write, Description("Specifies if comments on site pages are enabled or disabled.")] boolean CommentsOnSitePagesDisabled;
    [Write, Description("Specifies the default link permission for the site collection. None - Respect the organization default link permission. View - Sets the default link permission for the site to 'view' permissions. Edit - Sets the default link permission for the site to 'edit' permissions."), ValueMap{"None", "View", "Edit"}, Values{"None", "View", "Edit"}] string DefaultLinkPermission;
    [Write, Description("Specifies the default link type for the site collection. None - Respect the organization default sharing link type. AnonymousAccess - Sets the default sharing link for this site to an Anonymous Access or Anyone link. Internal - Sets the default sharing link for this site to the 'organization' link or company shareable link. Direct - Sets the default sharing link for this site to the 'Specific people' link."), ValueMap{"None", "AnonymousAccess", "Internal", "Direct"}, Values{"None", "AnonymousAccess", "Internal", "Direct"}] string DefaultSharingLinkType;
    [Write, Description("Disables App Views."), ValueMap{"Unknown", "Disabled", "NotDisabled"}, Values{"Unknown", "Disabled", "NotDisabled"}] string DisableAppViews;
    [Write, Description("Disables Company wide sharing links."), ValueMap{"Unknown", "Disabled", "NotDisabled"}, Values{"Unknown", "Disabled", "NotDisabled"}] string DisableCompanyWideSharingLinks;
    [Write, Description("Specifies the language of the new site collection. Defaults to the current language of the web connected to.")] uint32 LocaleId;
    [Write, Description("Determines whether the Add And Customize Pages right is denied on the site collection. For more information about permission levels, see User permissions and permission levels in SharePoint.")] boolean DenyAddAndCustomizePages;
    [Write, Description("Defines geo-restriction settings for this site"), ValueMap{"NoRestriction", "BlockMoveOnly", "BlockFull", "Unknown"}, Values{"NoRestriction", "BlockMoveOnly", "BlockFull", "Unknown"}] string RestrictedToRegion;
    [Write, Description("Specifies a list of email domains that is allowed for sharing with the external collaborators. Use the space character as the delimiter.")] string SharingAllowedDomainList;
    [Write, Description("Specifies a list of email domains that is blocked for sharing with the external collaborators.")] string SharingBlockedDomainList;
    [Write, Description("Specifies the external sharing mode for domains."), ValueMap{"None","AllowList", "BlockList"}, Values{"None","AllowList", "BlockList"}] string SharingDomainRestrictionMode;
    [Write, Description("To enable the option to search for existing guest users at Site Collection Level, set this parameter to $true.")] boolean ShowPeoplePickerSuggestionsForGuestUsers;
    [Write, Description("Specifies that all anonymous/anyone links that have been created (or will be created) will expire after the set number of days. Only applies if OverrideTenantAnonymousLinkExpirationPolicy is set to true. To remove the expiration requirement, set the value to zero (0)")] uint32 AnonymousLinkExpirationInDays;
    [Write, Description("Disables or enables the Social Bar for Site Collection.")] boolean SocialBarOnSitePagesDisabled;
    [Write, Description("False - Respect the organization-level policy for anonymous or anyone link expiration. True - Override the organization-level policy for anonymous or anyone link expiration (can be more or less restrictive)")] boolean OverrideTenantAnonymousLinkExpirationPolicy;
    [Write, Description("Present ensures the site collection exists, absent ensures it is removed"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] string Ensure;
    [Required, Description("Credentials of the SharePoint Global Admin"), EmbeddedInstance("MSFT_Credential")] string GlobalAdminAccount;
};
