[ClassVersion("1.0.0.0"), FriendlyName("EXOOfflineAddressBook")]
class MSFT_EXOOfflineAddressBook : OMI_BaseResource
{
    [Key, Description("The Name parameter specifies the unique name of the Offline Address Book. The maximum length is 64 characters.")] String Name;
    [Write, Description("The AddressLists parameter specifies the address lists or global address lists that are included in the OAB. You can use any value that uniquely identifies the address list.")] String AddressLists[];
    [Write, Description("The ConfiguredAttributes parameter specifies the recipient MAPI properties that are available in the OAB.")] String ConfiguredAttributes[];
    [Write, Description("The DiffRetentionPeriod parameter specifies the number of days that the OAB difference files are stored on the server.")] String DiffRetentionPeriod;
    [Write, Description("The IsDefault parameter specifies whether the OAB is used by all mailboxes and mailbox databases that don't have an OAB specified.")] Boolean IsDefault;
    [Write, Description("Specify if the Offline Address Book should exist or not."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Required, Description("Credentials of the Exchange Global Admin"), EmbeddedInstance("MSFT_Credential")] string GlobalAdminAccount;
};
