[ClassVersion("1.0.0.0"), FriendlyName("TeamsOnlineVoicemailUserSettings")]
class MSFT_TeamsOnlineVoicemailUserSettings : OMI_BaseResource
{
    [Key, Description("The Identity parameter represents the ID of the specific user in your organization; this can be either a SIP URI or an Object ID.")] String Identity;
    [Write, Description("The CallAnswerRule parameter represents the value of the call answer rule, which can be any of the following: DeclineCall, PromptOnly, PromptOnlyWithTransfer, RegularVoicemail, VoicemailWithTransferOption."), ValueMap{"DeclineCall", "PromptOnly", "PromptOnlyWithTransfer", "RegularVoicemail", "VoicemailWithTransferOption"}, Values{"DeclineCall", "PromptOnly", "PromptOnlyWithTransfer", "RegularVoicemail", "VoicemailWithTransferOption"}] String CallAnswerRule;
    [Write, Description("The DefaultGreetingPromptOverwrite parameter represents the contents that overwrite the default normal greeting prompt. If the user's normal custom greeting is not set and DefaultGreetingPromptOverwrite is not empty, the voicemail service will play this overwrite greeting instead of the default normal greeting in the voicemail deposit scenario.")] String DefaultGreetingPromptOverwrite;
    [Write, Description("The DefaultOofGreetingPromptOverwrite parameter represents the contents that overwrite the default out-of-office greeting prompt. If the user's out-of-office custom greeting is not set and DefaultOofGreetingPromptOverwrite is not empty, the voicemail service will play this overwrite greeting instead of the default out-of-office greeting in the voicemail deposit scenario.")] String DefaultOofGreetingPromptOverwrite;
    [Write, Description("The OofGreetingEnabled parameter represents whether to play out-of-office greeting in voicemail deposit scenario.")] Boolean OofGreetingEnabled;
    [Write, Description("The OofGreetingFollowAutomaticRepliesEnabled parameter represents whether to play out-of-office greeting in voicemail deposit scenario when user set automatic replies in Outlook.")] Boolean OofGreetingFollowAutomaticRepliesEnabled;
    [Write, Description("The OofGreetingFollowCalendarEnabled parameter represents whether to play out-of-office greeting in voicemail deposit scenario when user set out-of-office in calendar.")] Boolean OofGreetingFollowCalendarEnabled;
    [Write, Description("The PromptLanguage parameter represents the language that is used to play voicemail prompts.")] String PromptLanguage;
    [Write, Description("Specifies whether voicemail and transcription data is shared with the service for training and improving accuracy.")] Boolean ShareData;
    [Write, Description("The TransferTarget parameter represents the target to transfer the call when call answer rule set to PromptOnlyWithTransfer or VoicemailWithTransferOption. Value of this parameter should be a SIP URI of another user in your organization. For user with Enterprise Voice enabled, a valid telephone number could also be accepted as TransferTarget.")] String TransferTarget;
    [Write, Description("The VoicemailEnabled parameter represents whether to enable voicemail service. If set to $false, the user has no voicemail service.")] Boolean VoicemailEnabled;
    [Write, Description("Present ensures the policy exists, absent ensures it is removed."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Write, Description("Credentials of the Teams Global Admin."), EmbeddedInstance("MSFT_Credential")] String Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Name of the Azure Active Directory tenant used for authentication. Format contoso.onmicrosoft.com")] String TenantId;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Managed ID being used for authentication.")] Boolean ManagedIdentity;
};
