
[ClassVersion("1.0.0.0"), FriendlyName("EXOMailTips")]
class MSFT_EXOMailTips : OMI_BaseResource
{
    [Key] String Organization;
    [Write, Description("Specifies whether MailTips are enabled.")] Boolean MailTipsAllTipsEnabled;
    [Write, Description("Specifies whether MailTips that rely on group metrics data are enabled.")] Boolean MailTipsGroupMetricsEnabled;
    [Write, Description("Specifies what a large audience is.")] UInt32 MailTipsLargeAudienceThreshold;
    [Write, Description("Specifies whether MailTips that rely on mailbox data (out-of-office or full mailbox) are enabled.")] Boolean MailTipsMailboxSourcedTipsEnabled;
    [Write, Description("Specifies whether MailTips for external recipients are enabled.")] Boolean MailTipsExternalRecipientsTipsEnabled;
    [Write, ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Required, Description("Credentials of the Exchange Global Admin"), EmbeddedInstance("MSFT_Credential")] string GlobalAdminAccount;
};

