
[ClassVersion("1.0.0.0"), FriendlyName("EXOPlace")]
class MSFT_EXOPlace : OMI_BaseResource
{
    [Key, Description("The Identity parameter specifies the room mailbox that you want to modify. You can use any value that uniquely identifies the room.")] String Identity;
    [Write, Description("The display name of the place.")] String DisplayName;
    [Write, Description("The AudioDeviceName parameter specifies the name of the audio device in the room. If the value contains spaces, enclose the value in quotation marks.")] String AudioDeviceName;
    [Write, Description("The Building parameter specifies the building name or building number that the room is in. If the value contains spaces, enclose the value in quotation marks.")] String Building;
    [Write, Description("The Capacity parameter specifies the capacity of the room. A valid value is an integer.")] UInt32 Capacity;
    [Write, Description("The City parameter specifies the room's city. If the value contains spaces, enclose the value in quotation marks.")] String City;
    [Write, Description("The CountryOrRegion parameter specifies the room's country or region. A valid value is a valid ISO 3166-1 two-letter country code (for example, AU for Australia) or the corresponding friendly name for the country (which might be different from the official ISO 3166 Maintenance Agency short name).")] String CountryOrRegion;
    [Write, Description("N/A")] String Desks[];
    [Write, Description("The DisplayDeviceName parameter specifies the name of the display device in the room. If the value contains spaces, enclose the value in quotation marks.")] String DisplayDeviceName;
    [Write, Description("The Floor parameter specifies the floor number that the room is on.")] String Floor;
    [Write, Description("The FloorLabel parameter specifies a descriptive label for the floor that the room is on. If the value contains spaces, enclose the value in quotation marks.")] String FloorLabel;
    [Write, Description("The GeoCoordinates parameter specifies the room's location in latitude, longitude and (optionally) altitude coordinates.")] String GeoCoordinates;
    [Write, Description("The IsWheelChairAccessible parameter specifies whether the room is wheelchair accessible.")] Boolean IsWheelChairAccessible;
    [Write, Description("The Label parameter specifies a descriptive label for the room (for example, a number or name). If the value contains spaces, enclose the value in quotation marks.")] String Label;
    [Write, Description("The MTREnabled parameter identifies the room as configured with a Microsoft Teams room system. You can add Teams room systems as audio sources in Teams meetings that involve the room.")] Boolean MTREnabled;
    [Write, Description("The ParentId parameter specifies the ID of a Place in the parent location hierarchy in Microsoft Places.")] String ParentId;
    [Write, Description("The ParentType parameter specifies the parent type of the ParentId in Microsoft Places. Valid values are: Floor, Section"), ValueMap{"Floor","Section","None"}, Values{"Floor","Section","None"}] String ParentType;
    [Write, Description("The Phone parameter specifies the room's telephone number.")] String Phone;
    [Write, Description("The PostalCode parameter specifies the room's postal code.")] String PostalCode;
    [Write, Description("The State parameter specifies the room's state or province.")] String State;
    [Write, Description("The Street parameter specifies the room's physical address.")] String Street;
    [Write, Description("The Tags parameter specifies additional features of the room (for example, details like the type of view or furniture type).")] String Tags[];
    [Write, Description("The VideoDeviceName parameter specifies the name of the video device in the room. If the value contains spaces, enclose the value in quotation marks.")] String VideoDeviceName;
    [Write, Description("Specifies if this Outbound connector should exist."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Write, Description("Credentials of the Exchange Global Admin"), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Id of the Azure Active Directory tenant used for authentication.")] String TenantId;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Username can be made up to anything but password will be used for CertificatePassword"), EmbeddedInstance("MSFT_Credential")] String CertificatePassword;
    [Write, Description("Path to certificate used in service principal usually a PFX file.")] String CertificatePath;
    [Write, Description("Managed ID being used for authentication.")] Boolean ManagedIdentity;
};
