[ClassVersion("1.0.0")]
class MSFT_SPOUserProfilePropertyInstance
{
    [Write, Description("Name of the User Profile Property.")] String Key;
    [Write, Description("Value of the User Profile Property.")] String Value;
};
[ClassVersion("1.0.0.0"), FriendlyName("SPOUserProfileProperty")]
class MSFT_SPOUserProfileProperty : OMI_BaseResource
{
    [Key, Description("Username of the user to configure the profile properties for. E.g. John.Smith@contoso.com")] String UserName;
    [Write, Description("Array of MSFT_SPOUserProfilePropertyInstance representing the profile properties to set."), EmbeddedInstance("MSFT_SPOUserProfilePropertyInstance")] String Properties[];
    [Write, Description("Only accepted value is 'Present'."), ValueMap{"Present"}, Values{"Present"}] String Ensure;
    [Write, Description("Credentials of the Global Admin."), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Secret of the Azure Active Directory application to authenticate with."), EmbeddedInstance("MSFT_Credential")] String ApplicationSecret;
    [Write, Description("Name of the Azure Active Directory tenant used for authentication. Format contoso.onmicrosoft.com")] String TenantId;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Managed ID being used for authentication.")] Boolean ManagedIdentity;
    [Write, Description("Access token used for authentication.")] String AccessTokens[];
};
