[ClassVersion("1.0.0")]
Class MSFT_SPOUserProfilePropertyInstance
{
    [Write, Description("Name of the User Profile Property.")] String Key;
    [Write, Description("Value of the User Profile Property.")] String Value;
};
[ClassVersion("1.0.0.0"), FriendlyName("SPOUserProfileProperty")]
class MSFT_SPOUserProfileProperty : OMI_BaseResource
{
    [Key, Description("Username of the user to configure the profile properties for. E.g. John.Smith@contoso.com")] String UserName;
    [Write, Description("Array of MSFT_SPOUserProfilePropertyInstance representing the profile properties to set."), EmbeddedInstance("MSFT_SPOUserProfilePropertyInstance")] String Properties[];
    [Write, Description("Only accepted value is 'Present'."), ValueMap{"Present"}, Values{"Present"}] String Ensure;
    [Required, Description("Credentials of the Global Admin."), EmbeddedInstance("MSFT_Credential")] string GlobalAdminAccount;
};
