[ClassVersion("1.0.0.0"), FriendlyName("SPOTenantCDNPolicy")]
class MSFT_SPOTenantCDNPolicy : OMI_BaseResource
{
    [Key, Description("Type of Content Delivery Network. Can be 'Private' or 'Public'."), ValueMap{"Private","Public"}, Values{"Private","Public"}] string CDNType;
    [Write, Description("List of site classifications to exclude.")] string ExcludeRestrictedSiteClassifications[];
    [Write, Description("List of file extensions to include in the Policy.")] string IncludeFileExtensions[];
    [Required, Description("Credentials of the Office365 Tenant Admin."), EmbeddedInstance("MSFT_Credential")] string GlobalAdminAccount;
};
