[ClassVersion("1.0.0.0"), FriendlyName("SPOTenantCDNPolicy")]
class MSFT_SPOTenantCDNPolicy : OMI_BaseResource
{
    [Key, Description("Type of Content Delivery Network. Can be 'Private' or 'Public'."), ValueMap{"Private","Public"}, Values{"Private","Public"}] string CDNType;
    [Write, Description("List of site classifications to exclude.")] string ExcludeRestrictedSiteClassifications[];
    [Write, Description("List of file extensions to include in the Policy.")] string IncludeFileExtensions[];
    [Write, Description("Credentials of the Office365 Tenant Admin."), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Secret of the Azure Active Directory application to authenticate with."), EmbeddedInstance("MSFT_Credential")] String ApplicationSecret;
    [Write, Description("Name of the Azure Active Directory tenant used for authentication. Format contoso.onmicrosoft.com")] String TenantId;
    [Write, Description("Username can be made up to anything but password will be used for certificatePassword"), EmbeddedInstance("MSFT_Credential")] String CertificatePassword;
    [Write, Description("Path to certificate used in service principal usually a PFX file.")] String CertificatePath;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Managed ID being used for authentication.")] Boolean ManagedIdentity;
    [Write, Description("Access token used for authentication.")] String AccessTokens[];
};
