[ClassVersion("1.0.0.0"), FriendlyName("EXOEmailTenantSettings")]
class MSFT_EXOEmailTenantSettings : OMI_BaseResource
{
    [Key, Description("Only valid value is 'Yes'."), ValueMap{"Yes"}, Values{"Yes"}] String IsSingleInstance;
    [Write, Description("Identity which indicates the organization name.")] String Identity;
    [Write, Description("Specifies whether priority account protection is enabled.")] Boolean EnablePriorityAccountProtection;
    [Write, Description("Specifies whether the migration configuration is valid.")] Boolean IsValid;
    [Write, Description("Specifies the state of the object.")] String ObjectState;
    [Write, Description("Specifies the name of the object.")] String Name;
    [Write, Description("Credentials of the Exchange Global Admin"), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Id of the Azure Active Directory tenant used for authentication.")] String TenantId;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Path to certificate used in service principal usually a PFX file.")] String CertificatePath;
    [Write, Description("Username can be made up to anything but password will be used for CertificatePassword"), EmbeddedInstance("MSFT_Credential")] String CertificatePassword;
    [Write, Description("Managed ID being used for authentication.")] Boolean ManagedIdentity;
    [Write, Description("Access token used for authentication.")] String AccessTokens[];
};
