[ClassVersion("1.0.0.0"), FriendlyName("AADFilteringPolicy")]
class MSFT_AADFilteringPolicy : OMI_BaseResource
{
    [Key, Description("Name of the policy.")] String Name;
    [Write, Description("Unique identifier of the policy.")] String Id;
    [Write, Description("Description for the policy.")] String Description;
    [Write, Description("Action associated with the policy.")] String Action;

    [Write, Description("Present ensures the instance exists, absent ensures it is removed."), ValueMap{"Absent","Present"}, Values{"Absent","Present"}] string Ensure;
    [Write, Description("Credentials of the workload's Admin"), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Id of the Azure Active Directory tenant used for authentication.")] String TenantId;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Managed ID being used for authentication.")] Boolean ManagedIdentity;
    [Write, Description("Access token used for authentication.")] String AccessTokens[];
};
