[ClassVersion("1.0.0.0"), FriendlyName("IntuneDerivedCredential")]
class MSFT_IntuneDerivedCredential : OMI_BaseResource
{
    [Key, Description("The name of the app category.")] String DisplayName;
    [Write, Description("The unique identifier for an entity. Read-only.")] String Id;

    [Write, Description("The URL that will be accessible to end users as they retrieve a derived credential using the Company Portal.")] String HelpUrl;
    [Write, Description("The nominal percentage of time before certificate renewal is initiated by the client.")] Uint32 RenewalThresholdPercentage;
    [Write, Description("Supported values for the derived credential issuer."),
        ValueMap{"intercede", "entrustDatacard", "purebred"},
        Values{"intercede", "entrustDatacard", "purebred"}]
        String Issuer;

    [Write, Description("Supported values for the notification type to use."),
        ValueMap{"none", "email", "companyPortal", "companyPortal,email"},
        Values{"none", "email", "companyPortal", "companyPortal,email"}]
        String NotificationType;

    [Write, Description("Supported values for the notification type to use."),
        ValueMap{"Present", "Absent"},
        Values{"Present", "Absent"}]
        String Ensure;

    [Write, Description("Credentials of the Intune Admin"), EmbeddedInstance("MSFT_Credential")] String Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Name of the Azure Active Directory tenant used for authentication. Format contoso.onmicrosoft.com")] String TenantId;
    [Write, Description("Secret of the Azure Active Directory tenant used for authentication."), EmbeddedInstance("MSFT_Credential")] String ApplicationSecret;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
	[Write, Description("Managed ID being used for authentication.")] Boolean ManagedIdentity;
    [Write, Description("Access token used for authentication.")] String AccessTokens[];
};
