[ClassVersion("1.0.0.0"), Description("Represents a key-value pair.")]
class KeyValuePair {
    [Key, Description("The key of the dictionary entry.")]
    string Key;

    [Description("The value of the dictionary entry.")]
    string Value;
};

[ClassVersion("1.0.0.0"), FriendlyName("IntuneDeviceCredential")]
class MSFT_IntuneDeviceCredential : OMI_BaseResource {
    [Key, Description("The name of the app category.")]
    string DisplayName;

    [Write, Description("The unique identifier for an entity. Read-only.")]
    string Id;

    [Write, Description("The URL that will be accessible to end users as they retrieve a derived credential using the Company Portal.")]
    string HelpUrl;

    [Write, Description("Supported values for the derived credential issuer."), ValueMap{"Intercede", "Entrust", "DISA Purebred"}, Values{"Intercede", "Entrust", "DISA Purebred"}]
    string Issuer;

    [Write, Description("Supported values for the notification type to use."), ValueMap{"Email", "Company Portal (iOS) Microsoft Intune (Android) app"}, Values{"Email", "Company Portal (iOS) Microsoft Intune (Android) app"}]
    string NotificationType;

    [Write, Description("The nominal percentage of time before certificate renewal is initiated by the client.")]
    uint32 ThresholdPercentage;

    [Write, Description("Optional headers that will be added to the request.")]
    KeyValuePair[] Header;
};
