[ClassVersion("1.0.0.0"), FriendlyName("TeamsAudioConferencingPolicy")]
class MSFT_TeamsAudioConferencingPolicy : OMI_BaseResource
{
    [Key, Description("Specify the name of the policy that you are creating")] String Identity;
    [Write, Description("Determines whether users of the Policy can have Toll free numbers")] Boolean AllowTollFreeDialin;
    [Write, Description("Determines the list of audio-conferencing Toll- and Toll-free telephone numbers that will be included in meetings invites created by users of this policy.")] String MeetingInvitePhoneNumbers;
    [Write, Description("Present ensures the instance exists, absent ensures it is removed."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] string Ensure;
    [Write, Description("Credentials of the workload's Admin"), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Id of the Azure Active Directory tenant used for authentication.")] String TenantId;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Managed ID being used for authentication.")] Boolean ManagedIdentity;
    [Write, Description("Access token used for authentication.")] String AccessTokens[];
};
