[ClassVersion("1.0.0.0"), FriendlyName("EXOMigration")]
class MSFT_EXOMigration : OMI_BaseResource
{
    [Key, Description("The Identity parameter identifies the name of the current migration batch.")] String Identity;
    [Write, Description("The NotificationEmails parameter specifies one or more email addresses that migration status reports are sent to.")] String NotificationEmails[];
    [Write, Description("The CompleteAfter parameter specifies a delay before the batch is completed.")] String CompleteAfter;
    [Write, Description("The AddUsers parameter controls whether additional users can be dynamically added to an existing migration batch after it has been created.")] Boolean AddUsers;
    [Write, Description("The BadItemLimit parameter specifies the maximum number of bad items that are allowed before the migration request fails.")] String BadItemLimit;
    [Write, Description("The LargeItemLimit parameter specifies the maximum number of large items that are allowed before the migration request fails.")] String LargeItemLimit;
    [Write, Description("The MoveOptions parameter specifies the stages of the migration that you want to skip for debugging purposes.")] String MoveOptions[];
    [Write, Description("The SkipMerging parameter specifies the stages of the migration that you want to skip for debugging purposes.")] String SkipMerging[];
    [Write, Description("The StartAfter parameter specifies a delay before the data migration for the users within the batch is started.")] String StartAfter;
    [Write, Description("The Update switch sets the Update flag on the migration batch.")] Boolean Update;
    [Write, Description("The Status parameter returns information about migration users that have the specified status state.")] String Status;
    [Write, Description("Migration Users states the list of the users/mailboxes that are part of a migration batch that are to be migrated.")] String MigrationUsers[];
    [Write, Description("The SourceEndpoint parameter specifies the migration endpoint to use for the source of the migration batch.")] String SourceEndpoint;
    [Write, Description("The TargetDeliveryDomain parameter specifies the FQDN of the external email address created in the source forest for the mail-enabled user when the migration batch is complete.")] String TargetDeliveryDomain;

    [Write, Description("Specifies if the migration endpoint should exist or not."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Write, Description("Credentials of the workload's Admin"), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Id of the Azure Active Directory tenant used for authentication.")] String TenantId;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Managed ID being used for authentication.")] Boolean ManagedIdentity;
    [Write, Description("Access token used for authentication.")] String AccessTokens[];
};
