[ClassVersion("1.0.0")]
class MSFT_MicrosoftGraphdomainstate
{
    [Write, Description("")] String LastActionDateTime;
    [Write, Description("")] String Operation;
    [Write, Description("")] String Status;
};
[ClassVersion("1.0.0")]
class MSFT_MicrosoftGraphdirectoryobject
{
    [Write, Description("")] String DeletedDateTime;
};
[ClassVersion("1.0.0")]
class MSFT_MicrosoftGraphdomaindnsrecord
{
    [Write, Description("")] Boolean IsOptional;
    [Write, Description("")] String Label;
    [Write, Description("")] String RecordType;
    [Write, Description("")] String SupportedService;
    [Write, Description("")] UInt32 Ttl;
};

[ClassVersion("1.0.0.0"), FriendlyName("AADDomain")]
class MSFT_AADDomain : OMI_BaseResource
{
    [Write, Description("")] String Id;
    [Write, Description("")] String AuthenticationType;
    [Write, Description("")] String AvailabilityStatus;
    [Write, Description("")] Boolean IsAdminManaged;
    [Write, Description("")] Boolean IsDefault;
    [Write, Description("")] Boolean IsInitial;
    [Write, Description("")] Boolean IsRoot;
    [Write, Description("")] Boolean IsVerified;
    [Write, Description("")] String Manufacturer;
    [Write, Description("")] String Model;
    [Write, Description("")] UInt32 PasswordNotificationWindowInDays;
    [Write, Description("")] UInt32 PasswordValidityPeriodInDays;
    [Write, Description(""), EmbeddedInstance("MSFT_MicrosoftGraphdomainstate")] String State;
    [Write, Description("")] String SupportedServices[];
    [Write, Description(""), EmbeddedInstance("MSFT_MicrosoftGraphdirectoryobject")] String DomainNameReferences[];
    [Write, Description(""), EmbeddedInstance("MSFT_MicrosoftGraphdomaindnsrecord")] String ServiceConfigurationRecords[];
    [Write, Description(""), EmbeddedInstance("MSFT_MicrosoftGraphdomaindnsrecord")] String VerificationDnsRecords[];
    [Write, Description("Present ensures the policy exists, absent ensures it is removed."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] string Ensure;
    [Write, Description("Credentials of the Intune Admin"), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Id of the Azure Active Directory tenant used for authentication.")] String TenantId;
    [Write, Description("Secret of the Azure Active Directory tenant used for authentication.")] String ApplicationSecret;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
};
