[ClassVersion("1.0.0.0"), FriendlyName("SCDLPCompliancePolicy")]
class MSFT_SCDLPCompliancePolicy : OMI_BaseResource
{
    [Key, Description("The Name parameter specifies the unique name of the DLP policy. If the value contains spaces, enclose the value in quotation marks.")] String Name;
    [Write, Description("The Comment parameter specifies an optional comment.")] String Comment;
    [Write, Description("The EndpointDLPLocation parameter specifies the user accounts to include in the DLP policy for Endpoint DLP when they are logged on to an onboarded device. You identify the account by name or email address. You can use the value All to include all user accounts.")] String EndpointDlpLocation[];
    [Write, Description("The EndpointDlpLocationException parameter specifies the user accounts to exclude from Endpoint DLP when you use the value All for the EndpointDlpLocation parameter. You identify the account by name or email address.")] String EndpointDlpLocationException[];
    [Write, Description("The OnPremisesScannerDlpLocation parameter specifies the on-premises file shares and SharePoint document libraries and folders to include in the DLP policy. You can use the value All to include all on-premises file shares and SharePoint document libraries and folders.")] String OnPremisesScannerDlpLocation[];
    [Write, Description("The OnPremisesScannerDlpLocationException parameter specifies the on-premises file shares and SharePoint document libraries and folders to exclude from the DLP policy if you use the value All for the OnPremisesScannerDlpLocation parameter.")] String OnPremisesScannerDlpLocationException[];
    [Write, Description("The PowerBIDlpLocation parameter specifies the Power BI workspace IDs to include in the DLP policy. Only workspaces hosted in Premium Gen2 capacities are permitted. You can use the value All to include all supported workspaces.")] String PowerBIDlpLocation[];
    [Write, Description("The PowerBIDlpLocationException parameter specifies the Power BI workspace IDs to exclude from the DLP policy when you use the value All for the PowerBIDlpLocation parameter. Only workspaces hosted in Premium Gen2 capacities are permitted.")] String PowerBIDlpLocationException[];
    [Write, Description("The ThirdPartyAppDlpLocation parameter specifies the non-Microsoft cloud apps to include in the DLP policy. You can use the value All to include all connected apps.")] String ThirdPartyAppDlpLocation[];
    [Write, Description("The ThirdPartyAppDlpLocationException parameter specifies the non-Microsoft cloud apps to exclude from the DLP policy when you use the value All for the ThirdPartyAppDlpLocation parameter.")] String ThirdPartyAppDlpLocationException[];
    [Write, Description("The ExchangeLocation parameter specifies Exchange Online mailboxes to include in the DLP policy. You can only use the value All for this parameter to include all mailboxes.")] String ExchangeLocation[];
    [Write, Description("Exchange members to include.")] String ExchangeSenderMemberOf[];
    [Write, Description("Exchange members to exclude.")] String ExchangeSenderMemberOfException[];
    [Write, Description("The Mode parameter specifies the action and notification level of the DLP policy. Valid values are: Enable, TestWithNotifications, TestWithoutNotifications, Disable and PendingDeletion."), ValueMap{"Enable","TestWithNotifications","TestWithoutNotifications","Disable","PendingDeletion"}, Values{"Enable","TestWithNotifications","TestWithoutNotifications","Disable","PendingDeletion"}] String Mode;
    [Write, Description("The OneDriveLocation parameter specifies the OneDrive for Business sites to include. You identify the site by its URL value, or you can use the value All to include all sites.")] String OneDriveLocation[];
    [Write, Description("This parameter specifies the OneDrive for Business sites to exclude when you use the value All for the OneDriveLocation parameter. You identify the site by its URL value.")] String OneDriveLocationException[];
    [Write, Description("Priority for the Policy.")] UInt32 Priority;
    [Write, Description("The SharePointLocation parameter specifies the SharePoint Online sites to include. You identify the site by its URL value, or you can use the value All to include all sites.")] String SharePointLocation[];
    [Write, Description("This parameter specifies the SharePoint Online sites to exclude when you use the value All for the SharePointLocation parameter. You identify the site by its URL value.")] String SharePointLocationException[];
    [Write, Description("Teams locations to include")] String TeamsLocation[];
    [Write, Description("Teams locations to exclude.")] String TeamsLocationException[];
    [Write, Description("Specify if this policy should exist or not."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Write, Description("Credentials of the Exchange Global Admin"), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Id of the Azure Active Directory tenant used for authentication.")] String TenantId;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Username can be made up to anything but password will be used for CertificatePassword"), EmbeddedInstance("MSFT_Credential")] String CertificatePassword;
    [Write, Description("Path to certificate used in service principal usually a PFX file.")] String CertificatePath;
    [Write, Description("Access token used for authentication.")] String AccessTokens[];
};
