[ClassVersion("1.0.0.0"), FriendlyName("SPOSiteGroup")]
class MSFT_SPOSiteGroup : OMI_BaseResource
{
    [Key, Description("The name of the site group")] string Identity;
    [Key, Description("The URL of the site.")] string Url;
    [Write, Description("The owner (email address) of the site group")] string Owner;
    [Write, Description("The permission level of the site group")] string PermissionLevels[];
    [Write, Description("Used to add or remove site design."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Required, Description("Credentials of the Office365 Tenant Admin."), EmbeddedInstance("MSFT_Credential")] string GlobalAdminAccount;
};

