[ClassVersion("1.0.0.0"), FriendlyName("AADRoleDefinition")]
class MSFT_AADRoleDefinition : OMI_BaseResource
{
    [Key, Description("Specifies a display name for the role definition.")] String DisplayName;
    [Write, Description("Specifies Id for the role definition.")] string Id;
    [Write, Description("Specifies a description for the role definition.")] String Description;
    [Write, Description("Specifies the resource scopes for the role definition.")] String ResourceScopes[];
    [Required, Description("Specifies whether the role definition is enabled.")] Boolean IsEnabled;
    [Required, Description("Specifies permissions for the role definition.")] String RolePermissions[];
    [Write, Description("Specifies template id for the role definition.")] String TemplateId;
    [Write, Description("Specifies version for the role definition.")] String Version;
    [Write, Description("Specify if the Azure AD Role definition should exist or not."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Write, Description("Credentials of the Azure AD Admin"), EmbeddedInstance("MSFT_Credential")] string GlobalAdminAccount;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Id of the Azure Active Directory tenant used for authentication.")] String TenantId;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
};
