[ClassVersion("1.0.0.0"), FriendlyName("SPOSiteDesignRights")]
class MSFT_SPOSiteDesignRights: OMI_BaseResource
{
    [Key, Description("The Name of the site design")] string SiteDesignTitle;
    [Write, Description("List of user principals with seperated by commas to grant permissions")] string UserPrincipals[];
    [Write, Description("Rights to grant user principals on site design"),ValueMap{"View","None"}, Values{"View","None"}] string Rights;
    [Write, Description("Placeholder only not used in resource."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Required, Description("The Url of the SharePoint Online Central Administration")] string CentralAdminUrl;
    [Required, Description("Credentials of the Office365 Tenant Admin."), EmbeddedInstance("MSFT_Credential")] string GlobalAdminAccount;
};

