[ClassVersion("1.0.0.0"), FriendlyName("SPOSiteAuditSettings")]
class MSFT_SPOSiteAuditSettings : OMI_BaseResource
{
    [Key, Description("URL of the site collection to configure.")] String Url;
    [Required, Description("Audit flag for the site collection. Can be 'All' or 'None'."), ValueMap{"All","None"}, Values{"All","None"}] String AuditFlags;
    [Write, Description("Credentials of the SharePoint Global Admin"), EmbeddedInstance("MSFT_Credential")] string GlobalAdminAccount;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Name of the Azure Active Directory tenant used for authentication. Format contoso.onmicrosoft.com")] String TenantId;
    [Write, Description("Username can be made up to anything but password will be used for certificatePassword"), EmbeddedInstance("MSFT_Credential")] String CertificatePassword;
    [Write, Description("Path to certificate used in service principal usually a PFX file.")] String CertificatePath;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
};
