[ClassVersion("1.0.0.0"), FriendlyName("O365SearchAndIntelligenceConfigurations")]
class MSFT_O365SearchAndIntelligenceConfigurations : OMI_BaseResource
{
    [Key, Description("Specifies the resource is a single instance, the value must be 'Yes'"), ValueMap{"Yes"}, Values{"Yes"}] String IsSingleInstance;
    [Write, Description("Specifies whether or not Item Insights should be available for the organization.")] Boolean ItemInsightsIsEnabledInOrganization;
    [Write, Description("Specifies a single Azure AD Group for which Item Insights needs to be disabled.")] String ItemInsightsDisabledForGroup;
    [Write, Description("Specifies whether or not Person Insights should be available for the organization.")] Boolean PersonInsightsIsEnabledInOrganization;
    [Write, Description("Specifies a single Azure AD Group for which Person Insights needs to be disabled.")] String PersonInsightsDisabledForGroup;
    [Write, Description("Credentials of the Global Admin"), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Access token used for authentication.")] String AccessTokens[];
};
