[ClassVersion("1.0.0.0"), FriendlyName("TeamsMessagingConfiguration")]
class MSFT_TeamsMessagingConfiguration : OMI_BaseResource
{
    [Key, Description("Only valid value is 'Yes'."), ValueMap{"Yes"}, Values{"Yes"}] String IsSingleInstance;
    [Write, Description("This setting determines if closed captions will be displayed, for Teams Video Clips, during playback. Possible values: True, False")] Boolean EnableVideoMessageCaptions;
    [Write, Description("This setting determines if chat regulation for internal communication in tenant is allowed. Possible Values: True, False")] Boolean EnableInOrganizationChatControl;
    [Write, Description("This setting enables/disables the use of custom emojis and reactions across the whole tenant. Upon enablement, admins and/or users can define a user group that is allowed. Possible Values: True, False")] Boolean CustomEmojis;
    [Write, Description("This setting enables/disables the availability of Viva Engage storylines in Teams chats across the whole tenant."), ValueMap{"Disabled","Enabled"}, Values{"Disabled","Enabled"}] String Storyline;
    [Write, Description("This setting enables/disables MessagingNotes integration across the whole tenant. Possible Values: Disabled, Enabled"), ValueMap{"Disabled","Enabled"}, Values{"Disabled","Enabled"}] String MessagingNotes;
    [Write, Description("This setting enables weaponizable file detection in Teams messages in the tenant. Possible Values: Enabled, Disabled"), ValueMap{"Disabled","Enabled"}, Values{"Disabled","Enabled"}] String FileTypeCheck;
    [Write, Description("This setting enables malicious URL detection in Teams messages in the tenant. Possible Values: Enabled, Disabled"), ValueMap{"Disabled","Enabled"}, Values{"Disabled","Enabled"}] String UrlReputationCheck;
    [Write, Description("This setting enables content-based phishing detection for Teams messages in the tenant."), ValueMap{"Disabled","Enabled"}, Values{"Disabled","Enabled"}] String ContentBasedPhishingCheck;
    [Write, Description("This setting enables the end users to Report incorrect security detections in Teams messages in the tenant. Possible Values: Enabled, Disabled"), ValueMap{"Disabled","Enabled"}, Values{"Disabled","Enabled"}] String ReportIncorrectSecurityDetections;
    [Write, Description("Credentials of the workload's Admin"), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Id of the Azure Active Directory tenant used for authentication.")] String TenantId;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
};
