[ClassVersion("1.0.0.0"), FriendlyName("TeamsChannelTab")]
class MSFT_TeamsChannelTab : OMI_BaseResource
{
    [Key, Description("Display Name of the Channel Tab.")]String DisplayName;
    [Key, Description("Display Name of the Team.")]String TeamName;
    [Key, Description("Display Name of the Channel.")]String ChannelName;
    [Write, Description("Unique Id of the Team of the instance on the source tenant.")]String TeamId;
    [Write, Description("Id of the Teams App associated with the custom tab.")]String TeamsApp;
    [Write, Description("Index of the sort order for the custom tab.")]UInt32 SortOrderIndex;
    [Write, Description("Url of the website linked to the Channel Tab.")]String WebSiteUrl;
    [Write, Description("Url of the content linked to the Channel Tab.")]String ContentUrl;
    [Write, Description("Url of the location used to remove the app.")]String RemoveUrl;
    [Write, Description("Id of the Entity linked to the Channel Tab.")]String EntityId;
    [Write, Description("Present ensures the Tab exists, absent ensures it is removed."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Required, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Required, Description("Id of the Azure Active Directory tenant used for authentication.")] String TenantId;
    [Required, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Required, Description("Credentials of the Teams Global Admin"), EmbeddedInstance("MSFT_Credential")] String GlobalAdminAccount;
};

