name: Generate Wiki Content
on: [pull_request]

jobs:
  GenerateWiki:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Modules
      shell: powershell
      run: |
       git clone https://github.com/PowerShell/DscResource.Tests
       Import-Module -Name "./DscResource.Tests/AppVeyor.psm1"
       Invoke-AppveyorInstallTask
       $env:APPVEYOR_BUILD_FOLDER = Get-Location | select -ExpandProperty Path
       $env:APPVEYOR_BUILD_VERSION = "1.0.0"
       Invoke-AppveyorAfterTestTask `
            -Type 'Wiki' `
            -MainModulePath 'Modules\Microsoft365DSC' `
            -ResourceModuleName 'Microsoft365DSC'
    - uses: actions/upload-artifact@v2
      with:
        name: Upload Wiki Content
        path: D:\a\Microsoft365DSC\Microsoft365DSC\Microsoft365DSC_1.0.0_wikicontent.zip
