name: Publish Docker Images (Nightly)

on:
  schedule:
    - cron: '0 0 * * *' # Every day at midnight UTC
  workflow_dispatch:

jobs:
  BuildAndPushDockerImages:
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: Dockerfile.linux.dev
            runner: ubuntu-latest
          - dockerfile: Dockerfile.windows.dev
            runner: windows-latest

    runs-on: ${{ matrix.runner }}

    # Only when run from the main repo
    if: github.repository == 'Microsoft365DSC/Microsoft365DSC'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Infer Docker Tag
        id: tag
        shell: pwsh
        run: |
          $filename = '${{ matrix.dockerfile }}'
          $inferredTag = $filename -replace '^Dockerfile\.', ''
          "value=$inferredTag" >> $env:GITHUB_OUTPUT

      - name: Log in to Docker Hub
        shell: pwsh
        env:
          DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          $env:DOCKERHUB_TOKEN | docker login --username $env:DOCKERHUB_USERNAME --password-stdin

      - name: Build and push
        shell: pwsh
        env:
          DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
        run: |
          $baseName = "$($env:DOCKERHUB_USERNAME)/microsoft365dsc"
          $imageTag = "$($baseName):${{ steps.tag.outputs.value }}-nightly"
          Write-Host "Building with version tag for ${{ matrix.dockerfile }}"
          docker build --file ./${{ matrix.dockerfile }} --tag $imageTag .
          docker image push $baseName --all-tags
