name: Update M365DSC Schema Definition

on:
  pull_request:
    branches: [ Dev ]
    types: [ closed ]  # Only when PR is closed
  workflow_dispatch:   # Still allow manual trigger

jobs:
  update-schema:
    runs-on: windows-latest
    permissions:
      contents: write
      pull-requests: write

    if: github.repository == 'Microsoft365DSC/Microsoft365DSC' && github.event.pull_request.merged == true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Import Module and Generate Schema Definition
        shell: pwsh
        run: |
          $ErrorActionPreference = "Stop"
          Import-Module -Name .\Modules\Microsoft365DSC\Modules\M365DSCSchemaHandler.psm1
          New-M365DSCSchemaDefinition
          $content = (Get-Content ./Modules/Microsoft365DSC/SchemaDefinition.json -Raw).Replace('\r\n', '\n').Replace('\n', '\r\n')
          $content | Set-Content ./Modules/Microsoft365DSC/SchemaDefinition.json -Force -Encoding utf8 -NoNewline

      - name: Check for changes
        id: git-check
        shell: pwsh
        run: |
          git config --global core.autocrlf false
          if ((git status --porcelain).Count -eq 0) {
            echo "no_changes=true" >> $env:GITHUB_OUTPUT
          } else {
            echo "no_changes=false" >> $env:GITHUB_OUTPUT
          }

      - name: Commit and push changes
        if: steps.git-check.outputs.no_changes == 'false'
        id: commit
        shell: pwsh
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git fetch --all
          git stash push -m "schema-update"
          $branch = "update/schema-definition"
          git checkout -b $branch origin/$branch
          if (-not $?) { git checkout -b $branch }
          git stash pop -q
          git add Modules/Microsoft365DSC/SchemaDefinition.json
          git commit -m "Update SchemaDefinition.json"
          git push origin $branch
          echo "branch=$branch" >> $env:GITHUB_OUTPUT

      - name: Create Pull Request
        if: steps.git-check.outputs.no_changes == 'false'
        env:
          GH_TOKEN: ${{ github.token }}
        shell: pwsh
        run: |
          gh pr create `
            --title "Update SchemaDefinition.json" `
            --body "Automated update of SchemaDefinition.json using New-M365DSCSchemaDefinition." `
            --base Dev `
            --head ${{ steps.commit.outputs.branch }}
          if ($?) {
            echo "Pull request created successfully."
          } else {
            Write-Warning "Failed to create pull request, it probably already exists."
          }
