[ClassVersion("1.0.0.0"), FriendlyName("EXOOMEConfiguration")]
class MSFT_EXOOMEConfiguration : OMI_BaseResource
{
    [Key, Description("The Identity parameter specifies the OME Configuration policy that you want to modify.")] String Identity;
    [Write, Description("The BackgroundColor parameter specifies the background color")] String BackgroundColor;
    [Write, Description("The DisclaimerText parameter specifies the disclaimer text in the email that contains the encrypted message")] String DisclaimerText;
    [Write, Description("The EmailText parameter specifies the default text that accompanies encrypted email messages.")] String EmailText;
    [Write, Description("The ExternalMailExpiryInDays parameter specifies the number of days that the encrypted message is available to external recipients in the Microsoft 365 portal. A valid value is an integer from 0 to 730.")] UInt32 ExternalMailExpiryInDays;
    [Write, Description("The IntroductionText parameter specifies the default text that accompanies encrypted email messages.")] String IntroductionText;
    [Write, Description("The OTPEnabled parameter specifies whether to allow recipients to use a one-time passcode to view encrypted messages.")] Boolean OTPEnabled;
    [Write, Description("The PortalText parameter specifies the text that appears at the top of the encrypted email viewing portal.")] String PortalText;
    [Write, Description("The PrivacyStatementUrl parameter specifies the Privacy Statement link in the encrypted email notification message.")] String PrivacyStatementUrl;
    [Write, Description("The ReadButtonText parameter specifies the text that appears on the 'Read the message' button. ")] String ReadButtonText;
    [Write, Description("The SocialIdSignIn parameter specifies whether a user is allowed to view an encrypted message in the Microsoft 365 admin center using their own social network id (Google, Yahoo, and Microsoft account).")] Boolean SocialIdSignIn;
    [Write, Description("Specifies if this Outbound connector should exist."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Write, Description("Credentials of the Exchange Global Admin"), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Id of the Azure Active Directory tenant used for authentication.")] String TenantId;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Username can be made up to anything but password will be used for CertificatePassword"), EmbeddedInstance("MSFT_Credential")] String CertificatePassword;
    [Write, Description("Path to certificate used in service principal usually a PFX file.")] String CertificatePath;
    [Write, Description("Managed ID being used for authentication.")] Boolean ManagedIdentity;
};
