[ClassVersion("1.0.0.0"), FriendlyName("SentinelThreatIntelligenceIndicator")]
class MSFT_SentinelThreatIntelligenceIndicator : OMI_BaseResource
{
    [Key, Description("The display name of the indicator")] String DisplayName;
    [Write, Description("The name of the resource group. The name is case insensitive.")] String SubscriptionId;
    [Write, Description("The name of the resource group. The name is case insensitive.")] String ResourceGroupName;
    [Write, Description("The name of the workspace.")] String WorkspaceName;
    [Write, Description("The unique id of the indicator.")] String Id;
    [Write, Description("The name of the workspace.")] String Description;
    [Write, Description("Pattern type of a threat intelligence entity")] String PatternType;
    [Write, Description("Pattern of a threat intelligence entity")] String Pattern;
    [Write, Description("Is threat intelligence entity revoked")] String Revoked;
    [Write, Description("Valid from")] String ValidFrom;
    [Write, Description("Valid until")] String ValidUntil;
    [Write, Description("Source type.")] String Source;
    [Write, Description("Labels of threat intelligence entity")] String Labels[];
    [Write, Description("List of tags")] String ThreatIntelligenceTags[];
    [Write, Description("Threat types")] String ThreatTypes[];
    [Write, Description("Kill chain phases")] String KillChainPhases[];
    [Write, Description("Confidence of threat intelligence entity")] UInt32 Confidence;

    [Write, Description("Present ensures the instance exists, absent ensures it is removed."), ValueMap{"Absent","Present"}, Values{"Absent","Present"}] string Ensure;
    [Write, Description("Credentials of the workload's Admin"), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Id of the Azure Active Directory tenant used for authentication.")] String TenantId;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Managed ID being used for authentication.")] Boolean ManagedIdentity;
    [Write, Description("Access token used for authentication.")] String AccessTokens[];
};
