[ClassVersion("1.0.0.0"), FriendlyName("IntuneDeviceManagementDeviceDiagnosticSettings")]
class MSFT_IntuneDeviceManagementDeviceDiagnosticSettings : OMI_BaseResource
{
    [Key, Description("Only valid value is 'Yes'."), ValueMap{"Yes"}, Values{"Yes"}] String IsSingleInstance;
    [Write, Description("Determines whether the log collection feature should be available for use.")] Boolean EnableLogCollection;
    [Write, Description("Determines whether the autopilot diagnostic feature is enabled or not.")] Boolean EnableAutopilotDiagnostics;
    [Write, Description("The property to determine if M365 App log collection is enabled for account. When TRUE it indicates that M365 app log collection is enabled for account. When FALSE it indicates that M365 app log collection is disabled for account. Default value is FALSE")] Boolean M365AppDiagnosticsEnabled;
    [Write, Description("Credentials of the Intune Admin"), EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write, Description("Id of the Azure Active Directory application to authenticate with.")] String ApplicationId;
    [Write, Description("Id of the Azure Active Directory tenant used for authentication.")] String TenantId;
    [Write, Description("Secret of the Azure Active Directory tenant used for authentication."), EmbeddedInstance("MSFT_Credential")] String ApplicationSecret;
    [Write, Description("Thumbprint of the Azure Active Directory application's authentication certificate to use for authentication.")] String CertificateThumbprint;
    [Write, Description("Username can be made up to anything but password will be used for CertificatePassword"), EmbeddedInstance("MSFT_Credential")] String CertificatePassword;
    [Write, Description("Path to certificate used in service principal usually a PFX file.")] String CertificatePath;
    [Write, Description("Managed ID being used for authentication.")] Boolean ManagedIdentity;
    [Write, Description("Access token used for authentication.")] String AccessTokens[];
};
