[ClassVersion("1.0.0.0"), FriendlyName("SCDeviceConditionalAccessRule")]
class MSFT_SCDeviceConditionalAccessRule : OMI_BaseResource
{
    [Key, Description("Name of the Device Conditional Access Rule.")] String Name;
    [Required, Description("Name of the associated Device Conditional Access Policy.")] String Policy;
    [Write, Description("The AccountName parameter specifies the account name. Valid values for this parameter are: A TEXT value or NULL/Blank which is the default.")] String AccountName;
    [Write, Description("The AccountUserName parameter specifies the account user name. Valid values for this parameter are:A TEXT value or NULL/Blank which is the default.")] String AccountUserName;
    [Write, Description("The AllowAppStore parameter specifies whether to allow access to the app store on devices. Valid values for this parameter are:$true: Access to the app store is allowed. $false: Access to the app store isn't allowed. $null (blank): The setting isn't configured. This is the default value.")] Boolean AllowAppStore;
    [Write, Description("The AllowAssistantWhileLocked parameter specifies whether to allow the use of the voice assistant while devices are locked. Valid values for this parameter are: $true: The voice assistant can be used while devices are locked. $false: The voice assistant can't be used while devices are locked. $null (blank): The setting isn't configured. This is the default value.")] Boolean AllowAssistantWhileLocked;
    [Write, Description("The AllowConvenienceLogon parameter specifies whether to allow convenience logons on devices. Valid values for this parameter are: $true: Convenience logons are allowed. $false: Convenience logons aren't allowed. $null (blank): The setting isn't configured. This is the default value.")] Boolean AllowConvenienceLogon;
    [Write, Description("The AllowDiagnosticSubmission parameter specifies whether to allow diagnostic submissions from devices. Valid values for this parameter are: $true: Diagnostic submissions are allowed. $false: Diagnostic submissions aren't allowed. $null (blank): The setting isn't configured. This is the default value.")] Boolean AllowDiagnosticSubmission;
    [Write, Description("The AllowiCloudBackup parameter specifies whether to allow Apple iCloud Backup from devices. Valid values for this parameter are: $true: iCloud Backup is allowed. $false: iCloud Backup isn't allowed. $null (blank): The setting isn't configured. This is the default value.")] Boolean AllowiCloudBackup;
    [Write, Description("The AllowiCloudDocSync parameter specifies whether to allow Apple iCloud Documents & Data sync on devices. Valid values for this parameter are: $true: iCloud Documents & Data sync is allowed. $false: iCloud Documents & Data sync isn't allowed. $null (blank): The setting isn't configured. This is the default value.")] Boolean AllowiCloudDocSync;
    [Write, Description("The AllowiCloudPhotoSync parameter specifies whether to allow Apple iCloud Photos sync on devices. Valid values for this parameter are: $true: iCloud Photos sync is allowed. $false: iCloud Photo sync isn't allowed. $null (blank): The setting isn't configured. This is the default value.")] Boolean AllowiCloudPhotoSync;
    [Write, Description("The AllowJailbroken parameter specifies whether to allow access to your organization by jailbroken or rooted devices. $true: Jailbroken devices are allowed. $false: Jailbroken devices aren't allowed. $null (blank): The setting isn't configured. This is the default value.")] Boolean AllowJailbroken;
    [Write, Description("The AllowPassbookWhileLocked parameter specifies whether to allow the use of Apple Passbook while devices are locked. Valid values for this parameter are: $true: Passbook is available while devices are locked. $false: Passbook isn't available while devices are locked. $null (blank): The setting isn't configured. This is the default value.")] Boolean AllowPassbookWhileLocked;
    [Write, Description("The AllowScreenshot parameter specifies whether to allow screenshots on devices. Valid values for this parameter are: $true: Screenshots are allowed. $false: Screenshots aren't allowed. $null (blank): The setting isn't configured. This is the default value.")] Boolean AllowScreenshot;
    [Write, Description("The AllowSimplePassword parameter specifies whether to allow simple or non-complex passwords on devices. Valid values for this parameter are: $true: Simple passwords are allowed. $false: Simple passwords aren't allowed. $null (blank): The setting isn't configured. This is the default value.")] Boolean AllowSimplePassword;
    [Write, Description("The AllowVideoConferencing parameter specifies whether to allow video conferencing on devices. Valid values for this parameter are: $true: Video conferencing is allowed. $false: Video conferencing isn't allowed. $null (blank): The setting isn't configured. This is the default value.")] Boolean AllowVideoConferencing;
    [Write, Description("The AllowVoiceAssistant parameter specifies whether to allow using the voice assistant on devices. Valid values for this parameter are: $true: The voice assistant is allowed. $false: The voice assistant isn't allowed. $null (blank): The setting isn't configured. This is the default value.")] Boolean AllowVoiceAssistant;
    [Write, Description("The AllowVoiceDialing parameter specifies whether to allow voice-activated telephone dialing. Valid values for this parameter are: $true: Voice dialing is allowed. $false: Voice dialing isn't allowed. $null (blank): The setting isn't configured. This is the default value.")] Boolean AllowVoiceDialing;
    [Write, Description("The AntiVirusSignatureStatus parameter specifies the antivirus signature status. Valid values for this parameter are: An Integer. $null (blank): The setting isn't configured. This is the default value.")] Int64 AntiVirusSignatureStatus;
    [Write, Description("The AntiVirusStatus parameter specifies the antivirus status. Valid values for this parameter are: An Integer. $null (blank): The setting isn't configured. This is the default value.")] Int64 AntiVirusStatus;
    [Write, Description("The AppsRating parameter species the maximum or most restrictive rating of apps that are allowed on devices."), ValueMap{"AllowAll","DontAllow", "Rating9Plus", "Rating12Plus", "Rating17Plus", "None"}, Values{"AllowAll","DontAllow", "Rating9Plus", "Rating12Plus", "Rating17Plus", "None"}] String AppsRating;
    [Write, Description("The AutoUpdateStatus parameter specifies the update settings for devices."), ValueMap{"AutomaticCheckForUpdates","AutomaticDownloadUpdates", "AutomaticUpdatesRequired", "AutomaticUpdatesRequired", "NeverCheckUpdates", "None"}, Values{"AutomaticCheckForUpdates","AutomaticDownloadUpdates", "AutomaticUpdatesRequired", "AutomaticUpdatesRequired", "NeverCheckUpdates", "None"}] String AutoUpdateStatus;
    [Write, Description("The BluetoothEnabled parameter specifies whether to enable or disable Bluetooth on devices. Valid values for this parameter are: $true: Bluetooth is enabled. $false: Bluetooth is disabled. $null (blank): The setting isn't configured. This is the default value.")] Boolean BluetoothEnabled;
    [Write, Description("The CameraEnabled parameter specifies whether to enable or disable cameras on devices. Valid values for this parameter are: $true: Cameras are enabled. $false: Cameras are disabled. $null (blank): The setting isn't configured. This is the default value.")] Boolean CameraEnabled;
    [Write, Description("The EmailAddress parameter specifies the email address. Valid values are: An email address: For example, julia@contoso.com. $null (blank): The setting isn't configured. This is the default value.")] String EmailAddress;
    [Write, Description("The EnableRemovableStorage parameter specifies whether removable storage can be used by devices. Valid values for this parameter are: $true: Removable storage can be used. $false: Removable storage can't be used. $null (blank): The setting isn't configured. This is the default value.")] Boolean EnableRemovableStorage;
    [Write, Description("The ExchangeActiveSyncHost parameter specifies the Exchange ActiveSync host. Valid values for this parameter are: A text value. $null (blank): The setting isn't configured. This is the default value.")] String ExchangeActiveSyncHost;
    [Write, Description("The FirewallStatus parameter specifies the acceptable firewall status values on devices. Valid values for this parameter are: Required. $null (blank): The setting isn't configured. This is the default value."), ValueMap{"Required", "None"}, Values{"Required", "None"}]  String FirewallStatus;
    [Write, Description("The ForceAppStorePassword parameter specifies whether to require a password to use the app store on devices. Valid values for this parameter are: $true: App store passwords are required. $false: App store passwords aren't required. $null (blank): The feature isn't allowed or blocked by the rule. This is the default value.")] Boolean ForceAppStorePassword;
    [Write, Description("The ForceEncryptedBackup parameter specifies whether to force encrypted backups for devices. Valid values for this parameter are: $true: Encrypted backups are required. $false: Encrypted backups aren't required. $null (blank): The setting isn't configured. This is the default value.")] Boolean ForceEncryptedBackup;
    [Write, Description("The MaxPasswordAttemptsBeforeWipe parameter specifies the number of incorrect password attempts that cause devices to be automatically wiped. Valid values for this parameter are: An Integer. $null (blank): The setting isn't configured. This is the default value.")] Int32 MaxPasswordAttemptsBeforeWipe;
    [Write, Description("The MaxPasswordGracePeriod parameter specifies the length of time users are allowed to reset expired passwords on devices. To specify a value, enter it as a time span: dd.hh:mm:ss where dd = days, hh = hours, mm = minutes, and ss = seconds.")]  MaxPasswordGracePeriod;
    [Write, Description("The MoviesRating parameter species the maximum or most restrictive rating of movies that are allowed on devices. You specify the country rating system to use with the RegionRatings parameter. Valid values for the MoviesRating parameter are: AllowAll: All movies are allowed, regardless of their rating. DontAllow: No movies are allowed, regardless of their rating. $null (blank): The setting isn't configured. This is the default value."), ValueMap{"AllowAll","DontAllow", "None"}, Values{"AllowAll","DontAllow", "None"}] String MoviesRating;
    [Write, Description("The PasswordComplexity parameter specifies the password complexity. Valid values for this parameter are: An Integer. $null (blank): The setting isn't configured. This is the default value.")] Int64 PasswordComplexity;
    [Write, Description("The PasswordExpirationDays parameter specifies the number of days that the same password can be used on devices before users are required to change their passwords . Valid values for this parameter are: An integer. $null (blank): The setting isn't configured. This is the default value.")] Int32 PasswordExpirationDays;
    [Write, Description("The PasswordHistoryCount parameter specifies the minimum number of unique new passwords that are required on devices before an old password can be reused. Valid values for this parameter are: An Integer. $null (blank): The setting isn't configured. This is the default value.")] Int32 PasswordHistoryCount;
    [Write, Description("The PasswordMinComplexChars parameter specifies the minimum number of complex characters that are required for device passwords. A complex character isn't a letter. Valid values for this parameter are: An Integer. $null (blank): The setting isn't configured. This is the default value.")] Int32 PasswordMinComplexChars;
    [Write, Description("The PasswordMinimumLength parameter specifies the minimum number of characters that are required for device passwords. Valid values for this parameter are: An integer. $null (blank): The setting isn't configured. This is the default value.")] Int32 PasswordMinimumLength;
    [Write, Description("The PasswordQuality parameter specifies the minimum password quality rating that's required for device passwords. Password quality is a numeric scale that indicates the security and complexity of the password. A higher quality value indicates a more secure password. Valid values for this parameter are: An Integer. $null (blank): The setting isn't configured. This is the default value.")] Int32 PasswordQuality;
    [Write, Description("The PasswordRequired parameter specifies whether a password is required to access devices. Valid values for this parameter are: $true: Device passwords are required. $false: Device passwords aren't required. $null (blank): The setting isn't configured. This is the default value.")] Boolean PasswordRequired;
    [Write, Description("The PasswordTimeout parameter specifies the length of time that devices can be inactive before a password is required to reactivate them. To specify a value, enter it as a time span: dd.hh:mm:ss where dd = days, hh = hours, mm = minutes, and ss = seconds.")] PasswordTimeout;
    [Write, Description("The PhoneMemoryEncrypted parameter specifies whether to encrypt the memory on devices. Valid values for this parameter are: $true: Memory is encrypted. $false: Memory isn't encrypted. $null (blank): The setting isn't configured. This is the default value.")] Boolean PhoneMemoryEncrypted;
    [Write, Description("The RegionRatings parameter specifies the rating system (country) to use for movie and television ratings with the MoviesRating and TVShowsRating parameters. Valid values for the RegionRating parameter are: $null (blank): The setting isn't configured. This is the default value. au: Australia ca: Canada de: Germany fr: France gb: United Kingdom ie: Ireland jp: Japan nz: New Zealand us: United States"), ValueMap{"au","ca", "de", "fr", "gb", "ie", "jp", "nz", "us"}, Values{"au","ca", "de", "fr", "gb", "ie", "jp", "nz", "us"}] String RegionRatings;
    [Write, Description("The RequireEmailProfile parameter specifies whether an email profile is required on devices. Valid values for this parameter are: $true: An email profile is required. This value is required for selective wipe on iOS devices. $false: An email profile isn't required. $null (blank): The setting isn't configured. This is the default value.")] Boolean RequireEmailProfile;
    [Write, Description("The SmartScreenEnabled parameter specifies whether to requireWindows SmartScreen on devices. Valid values for this parameter are: $true: SmartScreen is enabled. $false: SmartScreen is disabled. $null (blank): The setting isn't configured. This is the default value.")] Boolean SmartScreenEnabled;
    [Write, Description("The SystemSecurityTLS parameter specifies whether TLS encryption is used on devices. Valid values for this parameter are: $true: TLS encryption is used. $false: TLS encryption isn't used. $null (blank): The setting isn't configured. This is the default value.")] Boolean SystemSecurityTLS;
    [Write, Description("The TVShowsRating parameter species the maximum or most restrictive rating of television shows that are allowed on devices. You specify the country rating system to use with the RegionRatings parameter. Valid values for the TVShowsRating parameter are: AllowAll: All television shows are allowed, regardless of their rating. DontAllow: No televisions shows are allowed, regardless of their rating. $null (blank): The setting isn't configured. This is the default value."), ValueMap{"AllowAll","DontAllow", "None"}, Values{"AllowAll","DontAllow", "None"}] String TVShowsRating;
    [Write, Description("The TargetGroups parameter specifies the security groups that this rule applies to. This parameter uses the GUID value of the group. To find this GUID value, run the command Get-Group | Format-Table Name,GUID. You can specify multiple groups separated by commas.")] TargetGroups;
    [Write, Description("The UserAccountControlStatus parameter specifies how User Account Control messages are presented on devices. Valid values for this parameter are: $null (blank): The setting isn't configured. This is the default value. AlwaysNotify NeverNotify NotifyAppChanges NotifyAppChangesDoNotDimdesktop"), ValueMap{"AlwaysNotify","NeverNotify", "NotifyAppChanges", "NotifyAppChangesDoNotDimdesktop", "None"}, Values{"AlwaysNotify","NeverNotify", "NotifyAppChanges", "NotifyAppChangesDoNotDimdesktop", "None"}] String UserAccountControlStatus;
    [Write, Description("The WLANEnabled parameter specifies whether Wi-Fi is enabled devices. Valid values for this parameter are: $true: Wi-Fi is enabled. $false: Wi-Fi is disabled. $null (blank): The setting isn't configured. This is the default value.")] Boolean WLANEnabled;
    [Write, Description("The WorkFoldersSyncUrl parameter specifies the URL that's used to synchronize company data on devices. Valid input for this parameter a URL. For example, https://workfolders.contoso.com.")] String WorkFoldersSyncUrl;
    [Write, Description("Specify if this rule should exist or not."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Required, Description("Credentials of the Office365 Global Admin"), EmbeddedInstance("MSFT_Credential")] String GlobalAdminAccount;
};
